### ISSUE TITLE
Failed prop type: The prop `styles` is marked as required in `DayPicker`, but its value is `undefined`

### ISSUE THREAD

**Issue by asveloper** [airbnb/react-dates#1011]
I am getting this error for DayPickerSingleDateController

React: 16.2.0
React Dates: 16.2.1

**Comment by ljharb** [comment]
Are you using the "initialize" entry point, as mentioned in the docs?

**Comment by asveloper** [comment]
@ljharb yes we are initializing it, even after that getting this error

**Comment by ljharb** [comment]
Can you provide the code you're using to render the DayPickerSingleDateController?

**Comment by asveloper** [comment]
<DayPickerSingleDateController
              date={dueDateLabel || moment()}
              onDateChange={date => this.changeDate(date)} // PropTypes.func.isRequired
              withPortal={false}
              numberOfMonths={1}
            />

**Comment by ljharb** [comment]
Can you share the entire file?

**Comment by asveloper** [comment]
import 'react-dates/initialize';
import React, { Component } from 'react';
import autoBind from 'react-autobind';
import Random from '@mobylogix/node-random';
import {_} from 'underscore';
import { PulseLoader } from 'react-spinners';
import moment from 'moment';
import { DateRangePicker, SingleDatePicker, DayPickerSingleDateController } from 'react-dates';
import { RIEInput, RIETextArea } from 'riek';
import Select from 'react-select';

import ThemedStyleSheet from 'react-with-styles/lib/ThemedStyleSheet';
import aphroditeInterface from 'react-with-styles-interface-aphrodite';
import DefaultTheme from 'react-dates/lib/theme/DefaultTheme';
import 'react-select/dist/react-select.css';

import {
  Close,
  AddCircleOutline,
  ExpandLess,
  ExpandMore,
  Settings,
  Clear ,
  DateRange,
} from 'material-ui-icons';

import {
  List,
  ListItem,
  ListItemIcon,
  ListItemText,
  ListSubheader,
  ListItemSecondaryAction,
  IconButton,
  Dialog,
  DialogContent,
  DialogTitle,
  DialogActions,
  Avatar,
  TextField,
  Checkbox,
  Tabs,
  Tab,
  Switch
} from 'material-ui';

import { FormControlLabel, FormGroup } from 'material-ui/Form';

import MyTextField from '../../../components/forms/TextField';
import MyButton from '../../../components/forms/MyButton';
import Status from '../../utils/Status';
import SocketKeys from '../../../utils/SocketKeys';

ThemedStyleSheet.registerInterface(aphroditeInterface);
ThemedStyleSheet.registerTheme({
  reactDates: {
    ...DefaultTheme.reactDates,
    color: {
      ...DefaultTheme.reactDates.color,
      highlighted: {
        backgroundColor: '#82E0AA',
        backgroundColor_active: '#6bc128',
        backgroundColor_hover: '#58D68D',
        color: '#186A3B',
        color_active: '#186A3B',
        color_hover: '#186A3B',
      },
    },
  },
});

export default class General extends Component {
  constructor(props) {
    super(props);

    this.state = {
      open: props.open ? props.open : false,
      disabled: false,
      dueDateLabel: moment(),
      mileStoneDueDate: null,
      showMileStone: false,
      mileStones: [],
      mileUpdate: false,
    };

    autoBind(this);
  }

  componentDidMount() {
    this.setValues(this.props);
  }

  componentWillReceiveProps(props) {
    this.setValues(props);
  }

  setValues(props) {
    if (props && props.open) {
      this.setState({ open: props.open });
    }

    if (props && props.project) {
      this.setState(props.project);
      this.setState({
        project: props.project,
        isPrivate: props.project.isPrivate,
        dueDateLabel: moment(props.project.dueDate) || moment(),
      });
    }

    if (props && props.company) {
      this.setState({company: props.company})
    }
  }


  forceRender() {
    this.forceUpdate();
  }

  setStateValue(key, value) {
    this.setState({ [key]: value });
  }

  onChangeValue(e, stateName) {
    if (e) {
      this.setState({ [stateName]: e.target.value });
    }
  }

  onBtnClick() {
    const { projectModalType, company, team } = this.props;
    const {project} = this.state;
    this.setState({disabled: true});

    let values;
      switch (projectModalType) {
        case 'createProject': {
          values = {
            _id: Random.id(),
            title: this.state.title,
            description: this.state.description,
            notes: this.state.notes,
            isPrivate: this.state.isPrivate,
            companyId: company._id,
            dueDate: this.state.dueDateLabel,
            direction: this.state.direction,
          };
          break;
        }
        case 'updateProject': {
          values = {
            _id: project._id,
            title: this.state.title,
            description: this.state.description,
            isPrivate: this.state.isPrivate,
            companyId: company._id,
            notes: this.state.notes,
            dueDate: this.state.dueDateLabel,
            direction: this.state.direction,
          };
          break;
        }
      }

      if(!project) {
        this.createProject(values);
      } else {
        this.updateProject(values);
      }
  }

  createProject(data) {
    const { socket, notify,closeModal, currentUser, setProject } = this.props;
    const { company } = this.state;

    if (!data.title) {
      notify('Name required', 'error');
      return;
    }

    if (!company) {
      notify('Company required', 'error');
      return;
    }

    data['createdBy'] = currentUser.userId;

    socket.emit(SocketKeys.CREATE_PROJECT, data);
    socket.on(SocketKeys.CREATE_PROJECT, ({success, data, message}) => {
      if (success) {
        notify(message);
        setProject(data);
      } else {
        notify(message, 'error');
      }
    });
  }

  updateProject(data) {
    const { socket, notify, closeModal, setProject } = this.props;
    const { projects, project, company } = this.state;

    if (!company) {
      notify('Company required', 'error');
      return;
    }

    if (!data.title) {
      data['title'] = project.title;
    }

    socket.emit(SocketKeys.UPDATE_PROJECT, data);
    socket.once(SocketKeys.UPDATE_PROJECT, ({ success, data, message }) => {
      if (success) {
        notify(message);
        setProject(data);
      } else {
        notify(message, 'error');
      }
    });
  }

  changeDate(dueDateLabel) {
    this.setState({dueDateLabel});
  }


  render() {
    const { projectModalType, closeModal} = this.props;
    const {
      open,
      title,
      description,
      isPrivate,
      dueDateLabel,
      project
    } = this.state;

    if (!project && projectModalType == 'updateProject') {
      return null;
    }

    return (
      <div className="new-project-container">
        <div className="project-fileds-main">
          <MyTextField
            id="title"
            onChangeValue={(e, id) => this.onChangeValue(e, id)}
            fullWidth={true}
            className="bottomMargin"
            required={true}
            defaultValue={project ? project.title : ''}
          />
          <MyTextField
            id="description"
            onChangeValue={(e, id) => this.onChangeValue(e, id)}
            fullWidth={true}
            className="bottomMargin"
            defaultValue={project ? project.description : ''}
          />
          <MyTextField
            id="direction"
            onChangeValue={(e, id) => this.onChangeValue(e, id)}
            fullWidth={true}
            className="bottomMargin"
            defaultValue={project ? project.direction : ''}
          />
          <MyTextField
            id="notes"
            onChangeValue={(e, id) => this.onChangeValue(e, id)}
            fullWidth={true}
            multiline={true}
            rows={4}
            className="bottomMargin"
            defaultValue={project ? project.notes : ''}
          />

          <div className="new-project-privacy-btn bottomMargin">
            <FormControlLabel
              label="Private"
              control={
                <Switch
                  checked={isPrivate ? isPrivate : false}
                  onChange={(event, checked) => this.setStateValue('isPrivate', checked)}
                />
              }
            />
          </div>
          <div className="react-dates-picker">
            <h4>Due Date</h4>
            {/* <DayPickerSingleDateController
              date={dueDateLabel || moment()}
              onDateChange={date => this.changeDate(date)} // PropTypes.func.isRequired
              withPortal={false}
              numberOfMonths={1}
            /> */}
          </div>

          <div className="new-project-action bottomMargin">
            <MyButton
              label={project ? 'Update Project' : 'Create Project'}
              onClick={() => this.onBtnClick()}
            />
          </div>
        </div>
      </div>
    );
  }
}
