### ISSUE TITLE
Out of the box usage is confusing

### ISSUE THREAD

**Issue by Kizmar** [airbnb/react-dates#1019]
_Using version 16.2.1 with React 16.2.0_

So I have a working React app using Semantic-UI, but I need a date picker. After reading through the implementation documentation, I'm unable to get this working.

I started with the following in my `app.tsx`:
```
import 'react-dates/initialize';
import 'react-dates/lib/css/_datepicker.css';
```
...and the following in the component I wanted to test this in:
```
import { DateRangePicker } from 'react-dates';
...
<Form.Field>
	<label>Seasonal start/stop</label>
	<DateRangePicker
		startDate={this.state.seasonalStart} // momentPropTypes.momentObj or null,
		startDateId="seasonalStart" // PropTypes.string.isRequired,
		endDate={this.state.seasonalEnd} // momentPropTypes.momentObj or null,
		endDateId="seasonalEnd" // PropTypes.string.isRequired,
		onDatesChange={({ startDate, endDate }) => this.handleDateRangeChange} // PropTypes.func.isRequired,
		focusedInput={this.focusedInput} // PropTypes.oneOf([START_DATE, END_DATE]) or null,
		onFocusChange={focusedInput => this.focusedInput = focusedInput} // PropTypes.func.isRequired,
	/>
</Form.Field>
```
This resulted in the following error:
> TypeError: Cannot read property 'theme' of undefined
> create
> C:/.../node_modules/react-with-styles/lib/ThemedStyleSheet.js:33

Next I moved the `import 'react-dates/initialize';` line from `app.tsx` into the component I was using to test. The result of this was no error, but all I get is two text boxes with the arrow between them. The calendar doesn't pop up.

So at this point I thought maybe I needed a default theme set (throwing things at the wall). So I tried adding this in the test component:
```
import ThemedStyleSheet from 'react-with-styles/lib/ThemedStyleSheet';
import DefaultTheme from 'react-dates/lib/theme/DefaultTheme';
ThemedStyleSheet.registerTheme(DefaultTheme);
```
That resulted in the following error:
> Failed prop type: The prop `styles` is marked as required in `DateRangePicker`, but its value is `undefined`.

At this point I'm not sure where to go. I don't see documentation on this `styles` property of `DateRangePicker` and I'm not sure what to set it to for default styles.

**Comment by majapw** [comment]
@Kizmar Thanks for posting your issue! So the `initialize` script should take care of both theme registration and interface registration so likely that won't solve the issue.

You mentioned:
> Next I moved the import 'react-dates/initialize'; line from app.tsx into the component I was using to test. The result of this was no error, but all I get is two text boxes with the arrow between them. The calendar doesn't pop up.

If the two textboxes are styled, then that's a good place to start from. I *think* that the issue is you `onFocusChange` method. Right now, it is:
```
onFocusChange={focusedInput => this.focusedInput = focusedInput} // PropTypes.func.isRequired,
```

However, because you're not calling `this.setState` this doesn't trigger a rerender. If you change this method to be:
```
onFocusChange={focusedInput => this.setState({ focusedInput })}
```

does that solve the problem?

**Comment by Kizmar** [comment]
@majapw I haven't had much time to work on this yet, but making that change did get the calendar to show. I have some other things that need to be fixed that are probably poor implementation on my part. Thanks!
