### ISSUE TITLE
UMD version?

### ISSUE THREAD

**Issue by jpsierens** [airbnb/react-dates#104]
I'm currently using react with requirejs. I'd really like to use this component but I have no idea the amount of work it would take to move this from CommonJS to AMD... Is there a UMD version of this project?

**Comment by ljharb** [comment]
No, we do not have a UMD build.

Is your build process not set up to generically amdify CommonJS modules?

**Comment by jpsierens** [comment]
Hmm, I have honestly never done that. Any documentation you could point me to for amdifying CommonJS modules?

**Comment by ljharb** [comment]
I don't use AMD, but some googling yields me https://github.com/domenic/amd-wrap , and https://www.npmjs.com/package/amdify

**Comment by jpsierens** [comment]
Thanks!
