### ISSUE TITLE
16.3.3: NPM/react-dates/lib/css/_datepicker.css is empty

### ISSUE THREAD

**Issue by finom** [airbnb/react-dates#1044]
Subj.

**Comment by majapw** [comment]
Okay I am going to add a prepublish check for this because this has
happened accidentally multiple times. Will fix later this evening!

**Comment by majapw** [comment]
16.3.4 should be out and include a css file and stuff ==> https://unpkg.com/react-dates@16.3.4/lib/css/_datepicker.css. This means we can go back to careting things. Sorry for the breakage.

Will follow up with a check for its presence. :)
