### ISSUE TITLE
Styles of close Icon weird

### ISSUE THREAD

**Issue by nigimaxx** [airbnb/react-dates#1056]
Hey there,
 
I have a style problem with your very cool Package.

![screen shot 2018-02-28 at 11 42 32](https://user-images.githubusercontent.com/13940953/36783520-927cd78c-1c7c-11e8-9c41-76a539751474.png)

The background of the default clear date icon in the `SingleDatePicker` is not round, because height and width aren't matching.

This is how I use the SingleDatePicker

```jsx
  <SingleDatePicker
      date={date}
      onDateChange={date => onDate(date)}
      focused={focused}
      onFocusChange={({ focused }) => onFocus(focused)}
      showClearDate={true}
      reopenPickerOnClearDate={true}
      placeholder="Datum"
      block={true}
    />
```

I believe the problem is this line in `/src/components/SingleDatePickerInput.jsx`, but I'm not really sure. Maybe the problem is my implementation

```jsx
 const closeIcon = customCloseIcon || (
    <CloseButton
      {...css(
        styles.SingleDatePickerInput_clearDate_svg,
        styles.SingleDatePickerInput_clearDate_svg__small, // <-- X
      )}
    />
  );
```
I am grateful for any tips and suggestions.

**Comment by majapw** [comment]
Thanks!
