### ISSUE TITLE
Is there any plans for react native support?

### ISSUE THREAD

**Issue by raharida** [airbnb/react-dates#1064]
Is there any plans in the coming days to support react native or releasing react native compatible library?

**Comment by ljharb** [comment]
Without react-primitives (which eliminates non flexbox browsers), it’d have to be a separate library.

**Comment by majapw** [comment]
@raharida we do not, at this time, have any plans to move in that direction unfortunately. As @ljharb mentioned, it would require porting over to `react-primitives` or something similar which we're not quite ready to do.

**Comment by bceppi** [comment]
Hi, thank you for this great library! No plans yet for React Native?
