### ISSUE TITLE
How do I know which date has been selected in DateRangePicker?

### ISSUE THREAD

**Issue by wzup** [airbnb/react-dates#1071]
`onDatesChange` receives an object:
```
{
  "startDate": "2018-03-05T10:00:00.000Z",
  "endDate": "2018-03-07T10:00:00.000Z"
}
```
How do I know from this which one has triggered `onDatesChange`, startDate of endDate?

**Comment by wzup** [comment]
OK, found, `focusedInput`

> you can control which input is focused as well as calendar visibility (the calendar is only visible if focusedInput is defined) with the focusedInput and onFocusChange props

**Comment by pavanmehta91** [comment]
Care to close the issue @wzup
