### ISSUE TITLE
DateRangePicker, locale, redux

### ISSUE THREAD

**Issue by JoaoPauloCMarra** [airbnb/react-dates#1077]
I've created a form with redux-form and the locale is a redux definition.

After update the locale from redux, the calendar(picker) get updated(moment.locale(x)) only on weekdays, not the Month name.

Am I doing anything wrong or we need a fix?

![captura de tela 2018-03-16 as 15 38 20](https://user-images.githubusercontent.com/976151/37538677-19c6a474-2930-11e8-9e93-6a987b29a770.png)
![captura de tela 2018-03-16 as 15 38 09](https://user-images.githubusercontent.com/976151/37538678-1a5fc186-2930-11e8-8218-1bc0da4ce451.png)
![captura de tela 2018-03-16 as 15 37 56](https://user-images.githubusercontent.com/976151/37538679-1a8a2cfa-2930-11e8-83ed-ddfbf9664d76.png)

**Comment by wijdench** [comment]
Hi, i have the same issue by using i18next language in the render component.
moment.locale(i18n.language);
Only the month name is always in english.

**Comment by wijdench** [comment]
Hi,
Is there any updates in this issue.

thanks for your help.

**Comment by pwfcurry** [comment]
https://github.com/airbnb/react-dates/issues/1099 might help.

**Comment by ljharb** [comment]
The locale shouldn’t be set in render; it needs to be set prior to rendering.

**Comment by HakanSungur** [comment]
How can we set the locale before creating it first? How do I set the locale before creation to 18n.language?
