### ISSUE TITLE
Custom function for weekDayFormat

### ISSUE THREAD

**Issue by c0derabbit** [airbnb/react-dates#1084]
Hi there – awesome library!
There's one thing I'm missing though, could you please allow passing a function to `weekDayFormat`?
I would like to show the weekday header as `M T W T F S S`, which does not seem to be a valid date format (makes sense, as Sat & Sun are displayed identically).
Something like:
```js
weekDayFormat: PropTypes.oneOfType([PropTypes.string, PropTypes.func])
```

I'm happy to submit a PR with a solution if this is something you would support.

**Comment by ljharb** [comment]
Also Tuesday and Thursday.

Can you elaborate on why you think it would be an acceptable user experience to have Tuesday/Thursday and Saturday/Sunday show duplicate headings? Typically this is considered a bad practice which is why Thursday is commonly referred to with "R" as a single letter.

**Comment by c0derabbit** [comment]
Ah, yes, Tuesday and Thursday as well. 🙈
The header would just be there to indicate where the week starts, it's quite minor visually as well. I have no other explanation tbh, and agree that ux-wise it's better to have 2 letters.

I do have another use case for customising though, e.g. in Hungarian locale I have the day names all lower case, but I would want them uppercase, no matter the language. I realise I could do this with pure css, but then again, why not format it.

In any case, I'd like to be able to format it with a custom function, just as I am with `displayFormat`.

**Comment by majapw** [comment]
We had a PR for this.... did it get merged? Let me poke around.

**Comment by c0derabbit** [comment]
@majapw thanks!
https://github.com/airbnb/react-dates/pull/650 is similar and was merged, but that only allows passing a string (e.g. of `dd`, `ddd` and `dddd`), not a function.

**Comment by jack-sf** [comment]
Can you reopen it? It's still a needed feature for me. Or did you manage to do it in some other way?
