### ISSUE TITLE
Export OutsideClickHandler

### ISSUE THREAD

**Issue by PerfectPixel** [airbnb/react-dates#1088]
`OutsideClickHandler` comes in handy if you implement your own input with a `DayPickerRangeController` or `DayPickerSingleDateController`. Unfortunately, it is not exported in the `index.js`, making a deep import necessary.

Would you be so kind to export it with the main? Pretty please 😃

**Comment by majapw** [comment]
Hi @PerfectPixel, sure, we can add that to the export (also would be happy to accept a PR that does that).

You can also deep import it rn by doing
```
import OutsideClickHandler from 'react-dates/lib/components/OutsideClickHandler';`
```

**Comment by PerfectPixel** [comment]
I created a pull request, thanks 👍
