### ISSUE TITLE
DayPickerRangeController does not work properly with orientation verticalScrollable

### ISSUE THREAD

**Issue by Sebruck** [airbnb/react-dates#1092]
When using the orientation verticalScrollable on a DayPickerRangeController, it's not possible so select a date range once the `navNext` button was clicked.

*Steps to reproduce*
* set numberOnMonths 3
* set orientation "verticalScrollable"
* click on the navNext button once
* on the months 4-6 it's not possible to select a date range

**Comment by imprashast** [comment]
Do you mean something like this: https://github.com/airbnb/react-dates/issues/1100

**Comment by tuantr10** [comment]
I think I have a similar issue. 
With the same Steps to reproduce as @Sebruck wrote up there, I can see that the state of startDate and endDate changed, but the highlighting color is not painted (for startDate, endDate and range)

My version is 16.7.0

**Comment by stjanis** [comment]
having the same issue as @Sebruck and @tuantr10. has anyone found solution / reason why this happens?

**Comment by imprashast** [comment]
Oh I have this issue too. Some screenshots:

<img width="354" alt="screen shot 2018-09-10 at 12 56 07" src="https://user-images.githubusercontent.com/21952706/45293750-57eff480-b4f9-11e8-93a2-95e8a1609cb5.png">

<img width="353" alt="screen shot 2018-09-10 at 12 55 33" src="https://user-images.githubusercontent.com/21952706/45293758-5cb4a880-b4f9-11e8-8bd1-cce68020b51e.png">

Can anyone explain how to fix it?
@ljharb @majapw
