### ISSUE TITLE
Add price to date

### ISSUE THREAD

**Issue by The-Code-Monkey** [airbnb/react-dates#1098]
I am trying to add dates using renderDayContent but it doesnt seem to be returning anything.

looks like a repo issue to me but i might be wrong.

this is my function that im calling

```jsx
renderPrices(day, event) {
    const conDate = day.format('YYYY') + "-" + day.format('MM') + "-" + day.format('DD');

    dateArray.forEach(function(item, i) {
      if (item.date === conDate ) {
        console.log(item)
        return (
          <p>{day.format('DD')} &pound;{item.price}</p>
        )
      } else {
        return (
          <p>{day.format('DD')}</p>
        )
      }
    })
```

and this is the data that its getting.

```jsx
const dateArray = [
    {
      "date" : "2018-04-04",
      "price": "999"
    },
    {
      "date" : "2018-05-04",
      "price": "123"
    }
  ]
```

but this returns nothing to the calendar, even though it hits the console log above the return nothing is returned.

**Comment by ljharb** [comment]
forEach return values are ignored. You might want .find?

**Comment by The-Code-Monkey** [comment]
@ljharb this is what i ended up doing.

`renderPrices(day, event) {
    const conDate = day.format('YYYY') + '-' + day.format('MM') + '-' + day.format('DD');

    if (testDatePrices[0][this.state.airport] === undefined || testDatePrices[0][this.state.airport][0][this.state.boardType] === undefined || testDatePrices[0][this.state.airport][0][this.state.boardType][0][conDate] === undefined) {
      return (
        <p>{day.format('DD')}</p>
      )
    } else {
      return (
        testDatePrices[0][this.state.airport][0][this.state.boardType][0][conDate] ? <p>{day.format('DD')} &pound;{testDatePrices[0][this.state.airport][0][this.state.boardType][0][conDate]}</p> : <p>{day.format('DD')}</p>
      );
    }
  }`

for the function this is using dummy data at the moment without an api so it will be cleaned up

`const testDatePrices = [
  {
    "manchester, uk": [
      {
        "fullBoard": [
          {
            "2018-04-04": "35",
            "2018-05-10": "40"
          }
        ],
        "halfBoard": [
          {
            "2018-04-04": "999",
          }
        ]
      }
    ]
  }
]`

and then the data

**Comment by ljharb** [comment]
Great, seems like this is answered :-)
