### ISSUE TITLE
Range Picker incorrectly highlights 1st April when hovering over an end date of 31st March

### ISSUE THREAD

**Issue by timReynolds** [airbnb/react-dates#110]
When using the date range picker if you select any start date and then hover over the 31st March then the 1st April will also be highlighted. 

This behaviour can be seen on any year, but isn't seen for any other month. 

I've tested this on the public React story board were the behaviour can also be seen. 

It has no functional impact that I could tell. 

![image](https://cloud.githubusercontent.com/assets/168870/19242453/1cf10a2e-8f0b-11e6-8aaa-ccbf3ea9aac3.png)

**Comment by timReynolds** [comment]
This issue is caused by UTC offset, after some investigation isSameDay is returning true as day has an offset of one. 

Output from logic outlined below;

day **2017-04-01T00:00:00+01:00**
startDate 2017-03-15T00:00:00Z
hoverDate 2017-03-31T00:00:00Z
!!startDate && !endDate && (day.isBetween(startDate, hoverDate) false
**isSameDay(hoverDate, day)) true**
**isForwardRange true**

**Comment by timReynolds** [comment]
@ljharb these aren't the only issue I've seen because of UTC offsets which I assume, but am not convinced by, are actually caused by the addition of DST. Calculating isOutsideRange has similar issues across DST from memory. 

I started to look into this in more depth but didn't have enough knowledge about the functionality that would be affected. If this is DST related would setting dates to have time stamps of noon not be a simple solution? Most of the issues I've seen is causes by having a date with DST calculated against one without.

**Comment by majapw** [comment]
What is confusing to me... is that all of these days (`hoverDate`, `startDate`, `day`) should be calculated with the same utc offset, since they're all ultimately coming from the `getCalendarMonthWeeks` method. The March 31st/April 1st crossover is not a DST date in any year (in any country as far as I can tell) so why is the UTC offset changing across this border? 

We can change the time stamp to noon, but I am still confused.

**Comment by alexanbj** [comment]
@majapw See my comment in https://github.com/airbnb/react-dates/issues/111#issuecomment-252827168. I think that is what causes this problem.

**Comment by timReynolds** [comment]
@majapw I agree this isn't a cross over for DST but I couldn't work out what else would cause the issue. 

I've had the same thoughts as @alexanbj about not setting the UTC offset, which feels like it would solve many of these issues. But I believe adding UTC offsets fixes at least one other issue.

**Comment by majapw** [comment]
@alexanbj @timReynolds I think the setting our dates to noon across the board would probably fix all of the issues we're seeing. Can you see if https://github.com/airbnb/react-dates/pull/114#issuecomment-253070238 works for you?

**Comment by alexanbj** [comment]
@majapw #114 fixed #111 for me 😄

**Comment by majapw** [comment]
Awesome! So this bug should also be fixed by #114. I'm going to close it but feel free to reopen if you still see the issue.
