### ISSUE TITLE
Issue with last day of month after end of Norwegian DST

### ISSUE THREAD

**Issue by alexanbj** [airbnb/react-dates#111]
I detected an issue today with the SingleDatePicker and the upcoming end of the Norwegian DST.
In Norway, DST ends on the last Sunday in October, meaning this year it will be 30th of October.

There's an issue with react-dates and the last day of October, the 31st, ie after the DST has changed.

Here's an example using moment and setting the date directly to the 31st:
```javascript
import moment from 'moment';
moment.locale('nb');
const d = moment('2016-10-31');
console.log(d.toJSON());
// Correct timezone offset: 2016-10-30T23:00:00.000Z 
```

However, when selecting October 31st in the SimpleDatePicker I get this:
```
// 2016-10-30T22:00:00.000Z
```
This is the wrong offset for the 31st (compare to moment code above). If I select any date in November I get the correct offset of T23 (as expected). Up to and including the 30th the offset is also correct (T22).

I've forked this repo and reduced the Storybook stories down to a single story that demonstrates this problem: https://github.com/alexanbj/react-dates/tree/dst_error

<img width="553" alt="react-dates-issue" src="https://cloud.githubusercontent.com/assets/81577/19245997/63810156-8f24-11e6-848c-5796f6bb23fc.png">

**Comment by ljharb** [comment]
Is this perhaps the same issue as #110?

**Comment by alexanbj** [comment]
@ljharb after digging a bit further it seems to be related somehow.

I've done some further investigation and I think I found the problem. Have a look at the first few lines of [getCalendarMonthsWeeks.js](https://github.com/airbnb/react-dates/blob/master/src/utils/getCalendarMonthWeeks.js):
```javascript
export default function getCalendarMonthWeeks(month, enableOutsideDays) {
  // set utc offset to get correct dates in future (when timezone changes)
  const baseDate = month.clone().utcOffset(month.utcOffset());
  ...
```

It explicitly sets the UTC offset of the baseDate equal to the offset of the `month` param.
The baseDate is then used as a basis for building arrays of the days in the months.

The issue here is that the UTC offset can change mid-month, as is the case here in my original issue. This is even more evident in March 2017, where there are 5 more days left in the month after the switch to DST. All of these get the wrong offset.


The code comment says that setting the UTC offset is for getting the correct future days. I could be missing something, but if I simply skipped setting the offset, everything worked correctly for me, including the days left in months after a DST switch. All the tests are running green as well.

As a bonus, this also seems to fix the problem in #110 (before removing the UTC offset, in the SingleDatePicker, if I selected March 31st 2017, April 1st was highlighted as well).

**Comment by majapw** [comment]
Hi @alexanbj, Not using UTC breaks things in Australia and in Brazil where DST is at midnight, so it might work for you but it's not universal. You end up getting two of one date in October in those places. However, I think https://github.com/airbnb/react-dates/pull/114 should fix both problems. Can you see if that branch works for you?

**Comment by alexanbj** [comment]
@majapw: Sure! I'll take a look tomorrow at work

**Comment by alexanbj** [comment]
@majapw ok, couldn't wait til morning:

```
date: : ["2016-10-31T11:00:00.000Z"]
date: : ["2016-10-30T11:00:00.000Z"]
date: : ["2016-10-29T10:00:00.000Z"]
```
Since the DST change is at 2 AM here, it is correct that both the 30th and the 31st change their offset when the times are set to noon.

Yup, it looks like #114 fixes this problem 😄 👍

**Comment by majapw** [comment]
Sweet! Thank you for checking!
