### ISSUE TITLE
isDayBlocked -rendering issue

### ISSUE THREAD

**Issue by bumpah** [airbnb/react-dates#1110]
<img width="236" alt="screen shot 2018-04-09 at 12 09 42" src="https://user-images.githubusercontent.com/17970806/38489409-fc302cba-3bee-11e8-8fbb-bc20abf78c48.png">
<img width="410" alt="screen shot 2018-04-09 at 12 09 48" src="https://user-images.githubusercontent.com/17970806/38489410-fc4b7196-3bee-11e8-8b72-ac5cf1a9c67d.png">

In this example April 9th seems greyed out. Either way user is still able to select the date and like other picture of console shows, `isDayBlocked` function returns `false`.

import's
```
import 'react-dates/initialize' // <---- put this at the very top of your js file

import ThemedStyleSheet from 'react-with-styles/lib/ThemedStyleSheet'
import aphroditeInterface from 'react-with-styles-interface-aphrodite'
import DefaultTheme from 'react-dates/lib/theme/DefaultTheme'

ThemedStyleSheet.registerInterface(aphroditeInterface)
ThemedStyleSheet.registerTheme({
  reactDates: {
    ...DefaultTheme.reactDates,
    color: {
      ...DefaultTheme.reactDates.color,
      backgroundColor: '#333',
    },
  },
})
```

**Comment by ljharb** [comment]
You only need the initialize endpoint if you’re not registering your own theme and interface; try removing that line?

**Comment by bumpah** [comment]
Same occurs, except when theme was registered grayed out 9th day would still became active color `green-blue` when clicked. After removing theme registering lines active color won't appear so it stays grayed. `dayIsBlocked` -function still return `false` for 9th day and Dates calendar makes update when day is clicked.

Also noticed quiet odd behaviour, if switch month onwards to let's say August and then switch back to April, 9th day is colored as available `white`. Then changing `startDate` works as expected, but after changing `endDate` problem re-occurs (9th day goes grayed out, and still clickable tho'). Seems like on initial render available dates works as expected.
