### ISSUE TITLE
bug(SingleDatePicker): Uncaught TypeError "onOutsideClick is not a function"

### ISSUE THREAD

**Issue by ricardobrandao** [airbnb/react-dates#1114]
I believe that this error only happens on the SingleDatePicker control. Furthermore, it seems to me that  this bug was introduced in [this PR](https://github.com/airbnb/react-dates/pull/643).

In order to reproduce just check [this example page](http://airbnb.io/react-dates/?selectedKind=SingleDatePicker%20%28SDP%29&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel), open the developer tools and click on the calendar.

**Comment by majapw** [comment]
You're totally right! I put up a quick patch in https://github.com/airbnb/react-dates/pull/1115

**Comment by ricardobrandao** [comment]
Hi Maja,

That was fast! 😃Thanks for the quick action.

Keep up the good work!
