### ISSUE TITLE
Make navigation arrows configurable

### ISSUE THREAD

**Issue by smdern** [airbnb/react-dates#112]
It'd be nice if we could pass in an element in place of the current svg arrows.

**Comment by ljharb** [comment]
what element did you have in mind?

**Comment by smdern** [comment]
It'd be nice to override the `.svg`s for close, next/prev and even the separator arrow for `DateRangePicker`.

https://github.com/airbnb/react-dates/blob/7d2e0d498e1e1b0eb1dce8486c8b0523e622e323/src/components/DayPicker.jsx#L299

It'd be nice if maybe if this was something like `{isVertical ? this.props.verticalNavPrev : this.props.horizontalNavPrev}` then we can pass a node in and the current chevron/arrows are the defaults

**Comment by smdern** [comment]
`<DateRangePicker verticalNavPrev={<SomeOtherSvg />} />` or `<DateRangePicker verticalNavPrev={<span>PREV</span>} />

**Comment by majapw** [comment]
We're probably going to need this at Airbnb soon as well 👍

**Comment by SecurityInsanity** [comment]
Sorry @majapw I didn't see you self assigned this before making the PR on it :disappointed: Hopefully I didn't make you scratch too much :stuck_out_tongue:

**Comment by majapw** [comment]
hurrdurr! No problem! I've been on vacation so it was actually nice to come back and see a PR. :D Thank you!
