### ISSUE TITLE
Where can I find a simple demo ?

### ISSUE THREAD

**Issue by frank994** [airbnb/react-dates#1134]
I installed the dependencies.
And copied the code of DateRangePickerWrapper.jsx
But it didn't work,
I'm a new fish ,Hope someone who can send a link of react-dates simple demo.
Thanks ,guys.

**Comment by AleksandrDorofeev** [comment]
Hi! When run code, you have any errors in console?

**Comment by majapw** [comment]
Hi @frank994 I'd check out https://github.com/majapw/react-dates-demo for a simple datepicker in action, specifically https://github.com/majapw/react-dates-demo/blob/master/src/App.js.
