### ISSUE TITLE
Set Current Date for Placeholder 

### ISSUE THREAD

**Issue by Zara603** [airbnb/react-dates#1140]
Is there any way to set the placeholder value to current date?
thanks

**Comment by ljharb** [comment]
In which component?

**Comment by Zara603** [comment]
SingleDatePicker

**Comment by ljharb** [comment]
Since it takes a `placeholder` prop (https://github.com/airbnb/react-dates/blob/master/src/components/SingleDatePicker.jsx#L51), you could pass in a formatted string from `moment()`?

**Comment by Zara603** [comment]
yes I noticed that, I was hoping there's a initialDay or something, I'm too lazy. thanks anyway.
