### ISSUE TITLE
DateRangePicker not opening Calendar widget despite adding all the required props

### ISSUE THREAD

**Issue by Sumanth290** [airbnb/react-dates#1146]
<code>
import React from "react";
import { connect } from "react-redux";
import {setTextFilter,sortByAmount,sortBydate,setStartDate,setEndDate} from "../actions/filters";
import { DateRangePicker } from "react-dates";
import 'react-dates/initialize';
import 'react-dates/lib/css/_datepicker.css';

class ExpenseListFilters extends React.Component{

    state = {
        startDate : this.props.filters.startDate,
        endDate : this.props.filters.endDate,
        calendarFocused : null
    }
    
    handleSortFilterChange = (e) => {
        (e.target.value && e.target.value === "amount") ? this.props.dispatch(sortByAmount()) : this.props.dispatch(sortBydate())
    };

    handleDateChange = ({startDate,endDate}) => {
        this.setState(() => ({ startDate,endDate }));
        this.props.dispatch(setStartDate(startDate));
        this.props.dispatch(setEndDate(endDate));
    };

    handleFocusChange = ({focused}) => {
        this.setState(() => ({ calendarFocused: focused}));
    };
    
    render(){
        return (
            <div>
                <div>
                    <input type="text" value={this.props.filters.text} onChange={(e) => {
                        this.props.dispatch(setTextFilter(e.target.value));
                    }}/>
                    <span><input type="radio" name="sortFilter" onChange={this.handleSortFilterChange} value="date" checked={
                        this.props.filters.sortBy === "date"
                    }/>Date</span>
                    <span><input type="radio" name="sortFilter" onChange={this.handleSortFilterChange} value="amount" checked={
                        this.props.filters.sortBy === "amount"
                    }/>Amount</span>
                    <DateRangePicker
                        startDate={this.state.startDate}
                        startDateId="filterStartDate"
                        endDate={this.state.endDate}
                        endDateId="filterEndDate"
                        onDatesChange={this.handleDateChange} 
                        focusedInput={this.state.calendarFocused}
                        onFocusChange={this.handleFocusChange}
                        onClose={() => {
                            console.log("Closed");
                        }}
                        // isOutsideRange={() => ( false )}
                        // numberOfMonths={1}
                    />
                </div>
                <div>
                    {/* <span><input type="radio" name="sortFilter" onChange={this.handleSortFilterChange} value="date" checked={
                        this.props.filters.sortBy === "date"
                    }/>Date</span>
                    <span><input type="radio" name="sortFilter" onChange={this.handleSortFilterChange} value="amount" checked={
                        this.props.filters.sortBy === "amount"
                    }/>Amount</span> */}
                </div>
                <div>
                    {/* <DateRangePicker
                        startDate={this.props.filters.startDate} 
                        startDateId="filterStartDate"
                        endDate={this.props.filters.endDate} 
                        endDateId="filterEndDate"
                        onDatesChange={this.handleDateChange} 
                        focusedInput={this.state.calendarFocused}
                        onFocusChange={this.handleFocusChange}
                        isOutsideRange={() => ( false )}
                        numberOfMonths={1}
                    /> */}
                </div>
            </div>
        );
    }
};
export default connect((state) => ({filters : state.filters}))(ExpenseListFilters);

</code>
Now the DateRangePicker is not opening the CalendarWidget but the startDate and endDate are being set successfully.

Versions used:
"moment": "^2.22.1",
"react-addons-shallow-compare": "^15.6.2",
"react-dates": "^16.6.1"

![calendar not launched](https://user-images.githubusercontent.com/37887978/39369967-4761eb98-4a03-11e8-9d65-0085a871fd31.PNG)

**Comment by Sumanth290** [comment]
changed this to fix :
<code>
handleFocusChange = ({focused}) => {
    this.setState(() => ({ calendarFocused: focused}));
};
</code>

<code>
handleFocusChange = (focused) => {
    this.setState(() => ({ calendarFocused: focused}));
};
</code>

**Comment by ucheuzor** [comment]
Please has anyone seen solution to this? Am stuck here. Calendar picker not popping up

**Comment by ucheuzor** [comment]
> changed this to fix :
> ` handleFocusChange = ({focused}) => { this.setState(() => ({ calendarFocused: focused})); }; `
> 
> ` handleFocusChange = (focused) => { this.setState(() => ({ calendarFocused: focused})); }; `

Thanks so much. This solved it for me. I was literally dying. Couldn't figure out where the problem is. This solved it

**Comment by ThandolwenkosiSibanda** [comment]
Thank you so much for that solution worked for me too
