### ISSUE TITLE
Browser Tab Crashing  after onFocusChange

### ISSUE THREAD

**Issue by pavanmehta91** [airbnb/react-dates#1151]
```
            <DateRangePicker
              startDateId="startDate"
              endDateId="endDate"
              onFocusChange={ (focusedInput) => { this.setState({focusedInput}); console.log('focusedInput',focusedInput); }}
              orientation="vertical"
              onDatesChange={({date1, date2}) => { console.log(date1, date2); }}
              startDate={this.state.startDate}
              focusedInput={this.state.focusedInput}
              endDate={this.state.endDate}
            />
```
Here's my implementation of DateRangePicker. Everytime I click on either start or endDate I end up with http://prntscr.com/jccewh this.
What am I doing wrong?

**Comment by pavanmehta91** [comment]
endDate and startDate are both set as null initially

**Comment by ljharb** [comment]
Did you figure it out?

**Comment by pavanmehta91** [comment]
Nope. It only happens in that specific project. It already had an earlier version of react dates too. I tried it inside a newly created project from CRA and it works fine
