### ISSUE TITLE
CustomizableCalendarDay meant to be exported?

### ISSUE THREAD

**Issue by MaxGabriel** [airbnb/react-dates#1153]
I'm working on updating the typescript definition file for react-dates, which were last updated for 16.0.0. Since then it looks like `CustomizableCalendarDay` was added (#894), but I don't see it exported in the generated `lib/index.js` file. Is this intentional?

**Comment by ljharb** [comment]
Yes, it’s intentional. Both because it’s not intended for casual use, and because deep imports are the better way to import things :-)
