### ISSUE TITLE
got 'react-with-direction' peer dependencies warning

### ISSUE THREAD

**Issue by liuwuhaoo** [airbnb/react-dates#1156]
Thanks for any help. I got a peer dep waring
`warning "react-dates > react-with-styles@3.2.0" has unmet peer dependency "react-with-direction@^1.1.0".` 

it seems that react-dates depend on react-with-styles and react-with-styles has a peer dependencies statement about react-with-direction.
my question is react-with-direction should installed by user(me) or react-dates?

**Comment by ljharb** [comment]
react-dates should have it listed as a peer dep, and also as a dep.

In the meantime, you can fix it by adding it as a dep yourself.

**Comment by ljharb** [comment]
Hmm, actually, react-with-styles already specifies react-with-direction as both a dep and a peer dep.

@liuwuhaoo what version of npm did you use to install?

**Comment by liuwuhaoo** [comment]
@ljharb 
![image](https://user-images.githubusercontent.com/19514172/39611486-95d243a4-4f8a-11e8-850d-84965e7b63e2.png)

**Comment by ljharb** [comment]
@liuwuhaoo yarn has some bugs with peer deps; if `npm ls` works, and yarn doesn't, then yarn is the one that's broken.

**Comment by govizlora** [comment]
Why is `react-with-direction` listed as a peer dependency of `react-dates`? Is it the case described here https://nodejs.org/es/blog/npm/peer-dependencies/ ?

**Comment by ljharb** [comment]
@govizlora anything that's a singleton should be a peer dep.
