### ISSUE TITLE
Display date always says the hour is 12 despite the moment object being otherwise

### ISSUE THREAD

**Issue by gwevans** [airbnb/react-dates#1163]
Displaying the time is a must for me, so I have set ```displayFormat={'YYYY-MM-DD HH:mm'}```. I have altered the onDatesChange callback to prevent the time from resetting back to 12:00 when the user selects a new date.

Everything works properly for the minutes, but not for the hour. Whenever the user changes the hour, the updated time is saved in the moment object, but the display time still reads 12 (possibly because of the code in /src/utils/toMomentObject.js? I'm not 100% sure).

Here is the workflow I am trying to achieve.
![capture](https://user-images.githubusercontent.com/24689009/39826121-872f60b6-5368-11e8-9577-74c2f533016e.PNG)

And here is the code:
```
<DateRangePicker
                    startDate={this.state.startDate}
                    startDateId="start_date_id"
                    endDate={this.state.endDate}
                    endDateId="end_date_id"
                    onDatesChange={({ startDate, endDate }) => {
                        if (startDate && this.state.startDate) {
                            startDate.hours(this.state.startDate.hours());
                            startDate.minutes(this.state.startDate.minutes());
                        }
                        this.setState({ startDate, endDate });
                    }}
                    displayFormat={'YYYY-MM-DD HH:mm'}
                    focusedInput={this.state.focusedInput}
                    onFocusChange={focusedInput => this.setState({ focusedInput })}
/>
```

Please don't point me at other date+time packages because I have done extensive research with 10+ packages over the course of this week. This is the package we have arrived at assuming this hour issue can be figured out.

**Comment by ljharb** [comment]
I think that https://github.com/airbnb/react-dates/blob/master/src/utils/toMomentObject.js is definitely the reason this happens, but this is a date picker - displaying the time isn’t a use case we support.

There’s been a few other issues requesting a time picker, but the general consensus is that it should be both a separate package and also a separate component.

**Comment by gwevans** [comment]
@ljharb Thanks for the reply.
