### ISSUE TITLE
Range Controller - Selected dates not unpainted when they are off-screen

### ISSUE THREAD

**Issue by Adam-Pendleton** [airbnb/react-dates#1170]
Hi, I'm using DayPickerRangeController from version 12.1.2.
It sometimes fails to "unpaint" selected days when they aren't visible on the calendar. When I toggle back to them, they remain painted even when other selected or hovered days are correctly painted.
![datepicker-issue](https://user-images.githubusercontent.com/2238075/40087289-8663f9e0-5867-11e8-8d6e-a933db590238.gif)
I'm using Redux with custom input boxes and have the selected start and end dates stored in the redux store. onDatesChange sends an action to update the start and end dates. It would seem strange to me if this was what was the issue, because the painting/unpainting works perfectly if the selected days are visible.

**Comment by ljharb** [comment]
v12 is pretty old (we're on v16); if you upgrade to v16, do you see the same bug?

**Comment by majapw** [comment]
I think that we resolved this issue in https://github.com/airbnb/react-dates/pull/575 (v12.2.0) so you're only off by a minor! I would recommend upgrading at the very least to v12.7.1, but honestly probably through to v16 for the latest and greatest fixes and improvements. :) 

Let us know if upgrading fixes your issue!

**Comment by Adam-Pendleton** [comment]
Yes, it looks like the updates have fixed the issue. Thanks, everyone, for your hard work!
