### ISSUE TITLE
Change color of the start date placeholder

### ISSUE THREAD

**Issue by elliottyson** [airbnb/react-dates#1176]
Hi!
I am using `showClearDates` but I do not know how to change the color of the grey placeholder "Start Date". Can someone help me maybe giving me the CSS class / id?
Many thanks in advance,
Elliot

**Comment by mukuljainx** [comment]
In DateRangePicker you can pass for start date input `startDateId` and then can edit CSS accordingly.

**Comment by elliottyson** [comment]
Thanks, what do you mean by pass `startDateId`?

**Comment by elliottyson** [comment]
Ok but if I use `startDateId` it works if I want to change let's say the color of the **date** selected but what I am looking for is to change the color of the **placeholder** when dates are cleared with `showClearDates`

**Comment by elliottyson** [comment]
I tried `startDatePlaceholderTextId` and `startDatePlaceholderId` but it does not work

**Comment by majapw** [comment]
The inputs are real inputs and thus, you change the placeholder color, I
believe you need to use a pseudoselector.

https://developer.mozilla.org/en-US/docs/Web/CSS/::placeholder should help!
:)

I think you'd be able to use something like `.DateInput_input::placeholder`
or `#startDateInputId::placeholder`.

If you're using Aphrodite, there's a theme variable associated with the
placeholder color that you can change.

**Comment by elliottyson** [comment]
Many thanks @majapw , working!

**Comment by hieupvd00585** [comment]
thank you bro
