### ISSUE TITLE
Installing react-dates package throws warning

### ISSUE THREAD

**Issue by ramyashanmugasundaram** [airbnb/react-dates#1202]
While installing react-dates package, it throws the below warning. I am using version 16.6.1 and I could see it happens in latest release too (16.7.0)

**npm WARN deprecated array.prototype.flatten@1.2.1: This method has been renamed to "flat" - please use array.prototype.flat instead**

> react-with-styles-interface uses array.prototype.flatten package and here is an issue raised by me.

**https://github.com/airbnb/react-with-styles-interface-css/issues/18**

It would be great if you update the react-with-styles-interface package here as well and release it once it solved from their side. This would help us to get rid of the warnings.

**Comment by ljharb** [comment]
This isn't *throwing* anything, it's just a harmless console log on `npm install`. Warnings like these can often be ignored.

We can certainly make the update, but it's not an actual problem.

Closing in favor of https://github.com/airbnb/react-with-styles-interface-css/issues/18.
