### ISSUE TITLE
DateRangePicker: How to configure displaying current and previous months

### ISSUE THREAD

**Issue by amimas** [airbnb/react-dates#1235]
Hello,

I just started using this library. My requirement involves with past dates only. So, I was able to configure the component to disable selecting future dates.

This is great, but when I click on the Calendar, it automatically loads current month and the next month. Since I already disabled all future dates from being selected, I think it'd be useful for my users to see current month + previous month by default.

I'm not really sure how to configure the `DateRangePicker` component for that. The closest I came across was to use `numberOfMonths={1}` but that's not exactly what I want because it's basically limiting the Calendar to display 1 months at a time.

Is there anything in the current implementation of this component that will allow me to configure what I described above? Maybe I missed something in the doc.

**Comment by ljharb** [comment]
The initialVisibleMonth prop seems useful

**Comment by amimas** [comment]
thanks... I'll try that out.

**Comment by TamikoT** [comment]
@amimas `initialVisibleMonth={() => moment().subtract(1, 'month')}` should work as a `param` for `<DateRangePicker`

**Comment by majapw** [comment]
@TamikoT is right! That should open it up to the expected month. :)

**Comment by amimas** [comment]
@TamikoT Thanks a lot for the snippet. It worked like a charm!!
