### ISSUE TITLE
adding hover range?

### ISSUE THREAD

**Issue by maxlibin** [airbnb/react-dates#1237]
How do you add a range highlight and when hover future dates it highlighted the range?

<img width="349" alt="screen shot 2018-06-27 at 7 18 40 pm" src="https://user-images.githubusercontent.com/1277038/41970872-ece6122c-7a3e-11e8-885a-4e574c5d10e4.png">

**Comment by maxlibin** [comment]
ok should be by default if you set null for endDate.

**Comment by alangrn** [comment]
Can you please provide a more detailed example. I have the same issue.

**Comment by maxlibin** [comment]
I am doing something like this on my handler
```
handleOnDateChange = ({startDate, endDate}) => {
    const {startDate: currentStartDate, endDate: currentEndDate} = this.state;

    const hasStartDateChanged = this.hasDateChanged(currentStartDate, startDate);
    const hasEndDateChanged = this.hasDateChanged(currentEndDate, endDate);

    if (hasStartDateChanged) {
      endDate = null; // set end date to null for highlighting the focused range.
    }

    this.setState({
      startDate,
      startDateInput: startDate && startDate.isValid() ? startDate.format(INPUT_DATE_FORMAT) : "",
      endDate,
      endDateInput: endDate && endDate.isValid() ? endDate.format(INPUT_DATE_FORMAT) : "",
      focusedInput: hasEndDateChanged ? "startDate" : "endDate",
    });
  }
```

**Comment by Kevinio04** [comment]
Sorry if I am missing something really obvious here but I cannot get this to work using the suggestions here. For me setting endDate to null does not produce this behavior and none of the examples in the storybook show this behavior so it seems it is not the default. 

My onDatesChange function is almost identical to @maxlibin with the exception I am not setting startDateInput and endDateInput in my state but this does not produce the intended behavior.

Any help would be much appreciated
