### ISSUE TITLE
tether-element is always rendered

### ISSUE THREAD

**Issue by ingro** [airbnb/react-dates#125]
Hello! I updated to the last version (3.3.2) but found a bug with the implementation of react-tether:
it seems that `<TetherComponent>` is always rendered, and since it is absolutely positioned it blocks the interation with the underlying elements of the page.

**Comment by tvanro** [comment]
Encountered the same bug and (temporary) fixed it with adding some CSS.
```
// set z-index higher than .tether-element
.DateRangePicker__picker, .SingleDatePicker__picker {
	z-index: 51;
	pointer-events: all;
}
// make .tether-element non-reactive
.tether-element {
	z-index: 50;
	pointer-events: none;
}
```
You can also get it working setting the z-index but we needed this to display react-dates inside a popup.
```
// set z-index higher than .tether-element
.DateRangePicker__picker, .SingleDatePicker__picker {
	pointer-events: all;
}
// make .tether-element non-reactive
.tether-element {
	pointer-events: none;
}
```

**Comment by ingro** [comment]
Thanks @tvanro , I tried what you suggested but unless I did something wrong that doesn't help with the interation of elements under `<TetherComponent>`

**Comment by zeroasterisk** [comment]
I am also seeing this.  It would be easy to resolve by not rendering, or giving it a `display:none` style when not open.

![ss](https://puu.sh/rNiU2/d4ef14e676.png)

**Comment by majapw** [comment]
Should be fixed in #131! :) Will do a quick patch release. 

Thanks for flagging this! I added an example to the storybook as well that should help us catch this kind of thing earlier next time.

**Comment by ingro** [comment]
Thanks for the quick fix! :)

**Comment by SecurityInsanity** [comment]
@majapw it seems this fix wasn't applied for the single date picket So I've opened #133 . Any chance we could do a quick review + patch release for those of us using the single date picker? :smile:

**Comment by majapw** [comment]
Eek you're totes right. I'll get on that tonight. :)
