### ISSUE TITLE
Warning: Failed prop type: withStyles(SingleDatePicker): unknown props found: renderMonthElement

### ISSUE THREAD

**Issue by ardaplun** [airbnb/react-dates#1251]
Warning: Failed prop type: withStyles(SingleDatePicker): unknown props found: renderMonthElement is occured when trying to customized navigation with year selector.

**Comment by ljharb** [comment]
Can you provide your code?

**Comment by ljharb** [comment]
That props isn't unknown in v17, so I'm not sure why it would be giving you an error :-/

**Comment by ardaplun** [comment]
Oke I found the problem, just need to re-start the npm. Thanks
