### ISSUE TITLE
no dates

### ISSUE THREAD

**Issue by Yar-R** [airbnb/react-dates#1255]
as you can see I do not get any dates checked
this is my code

```
               <DateRangePicker
                    startDate={null}
                    startDateId="date_start"
                    startDatePlaceholderText="С"
                    endDate={null}
                    endDateId="date_end"
                    endDatePlaceholderText="По"
                    onDatesChange={(v: any) => this.onDateChange(v)}
                    onFocusChange={focusedInput => this.setState({focus: focusedInput})}
                    focusedInput={this.state.focus}
                    block={true}
                    reopenPickerOnClearDates={true}
                    showClearDates={true}
                />
```
It is very basic so I can't get what is the problem. 
I've tried to disable all my stylesheets/ other components

I am new to this community, so maybe this is my bad.

![image](https://user-images.githubusercontent.com/23475811/42474538-922f051e-83d0-11e8-9d94-6284fa8f1b2f.png)

**Comment by majapw** [comment]
Hi @Yar-R, the problem is that your `startDate` and `endDate` are always set to `null`. You need those values to update based on whatever happened in your `onDateChange` method.

**Comment by Yar-R** [comment]
@majapw , thanks a lot. I've got frustrated with "or null" in docs.
It works, thanks again.

**Comment by Yar-R** [comment]
I am triyng to get default values work. But if i set as  startDate={moment('2018-01-02')}
I get this if I try to open the picker.

Am I missing something again?

![image](https://user-images.githubusercontent.com/23475811/42512349-10d99b72-845d-11e8-9597-133238fccda0.png)
