### ISSUE TITLE
SingleDatePicker's calendar not rerendering selected date properly

### ISSUE THREAD

**Issue by kmai00** [airbnb/react-dates#1257]
Hi,

I'm looking at the example of the [SingleDatePicker ](http://airbnb.io/react-dates/?selectedKind=SDP%20-%20Input%20Props&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) and I notice when I type in a date that is in the past such as 06/23/2010, the calendar doesn't rerender. It stays in the currently opened month.

Steps to reproduce:
1) Click on text box and type change the year to 2015.
2) Hit enter and click out of focus
3) Click back in and the calendar is still on June 2018 (in my case)

I been having trouble on my side trying to get the calendar to "refocus" even though I set the onFocusChange function to set the "focused" prop to true...

Soo....does anyone have any idea what's happening?

**Comment by kmai00** [comment]
The date is valid. 

I am using DayPickerDateController in my app, are past dates disabled for that component as well?

**Comment by kmai00** [comment]
I think I know what my problem is...

So in my code I'm using DayPickerSingleDateController and I am passing new dates to it but because it is always displayed...the state updates but the calendar doesn't rerender..meaning it doesn't just to the month after it receive this new props...

Is there a way to force it go to the new selected month?

**Comment by majapw** [comment]
Ahh, this is a known issue, and it's on my to-do list but hasn't yet been tackled. I think most of the legwork has been done to allow for this behavior, it just hasn't quite happened yet. :)

**Comment by majapw** [comment]
I'm going to close this in favor of #1320 given that it has a very succinct description of the issue. :)
