### ISSUE TITLE
Charset windows-1255 not supported

### ISSUE THREAD

**Issue by sag1v** [airbnb/react-dates#1264]
Hi, I have a customer that is implementing a widget of mine using `react-dates`.
This customer set the charset attribute on his page to `charset=windows-1255` (hebrew),  i set the moment locale to 'he-il'.
This causes the `dateRangePicker` to display gibberish instead of Hebrew,  other parts of my widget are displaying correctly.

![image](https://user-images.githubusercontent.com/9153149/42820390-b84f7e18-89de-11e8-8ac5-2d9abecc3770.png)

When using `charset=utf-8` on the page everything rendered as expected.

Any idea where is it coming from?

**Comment by ljharb** [comment]
I wouldn’t expect to see any charset but utf-8; which supports Hebrew fine.

**Comment by sag1v** [comment]
@ljharb I agree, yet sometimes our wudgets "lives" on someone elses page. We want to support this charset, but i'm having troubles finding the source for this behavior.
It would be great if you could point me to the right direction (if you know) so i can figure out what are my options here.

**Comment by ljharb** [comment]
I would assume that it’s an issue with moment itself - since moment and not react-dates supplies month names.

**Comment by sag1v** [comment]
Yeah that what i thought 
The only thing i can think of is that theres a file holding the names and it got saved as utf-8 or somethink similar to this.

**Comment by sag1v** [comment]
Ok I think i can confirm that the locale file for the names and titles is indeed in `utf-8`.

![image](https://user-images.githubusercontent.com/9153149/42827530-485003e2-89ef-11e8-8155-a49ebd564c48.png)

@ljharb  Thanks for your time.
