### ISSUE TITLE
InvalidCharacterError: Failed to execute 'createElement' on 'Document': The tag name provided ('/static/media/arrow-right.3e83082a.svg') is not a valid name.

### ISSUE THREAD

**Issue by Stathismi** [airbnb/react-dates#1278]
when i try to run the DateRangePickerWrapper i get this error, has somebody else faced the same error? thanks

**Comment by ljharb** [comment]
Do you mean the example? are you talking about in our storybook, or in your own site? In which browser?

**Comment by Stathismi** [comment]
managed to solve it (i think) (at least compiles now) by doing:

  import React from "react";
  const RightArrow = props =>
<svg focusable="false" viewBox="0 0 1000 1000"><path d="M694.4 242.4l249.1 249.1c11 11 11 21 0 32L694.4 772.7c-5 5-10 7-16 7s-11-2-16-7c-11-11-11-21 0-32l210.1-210.1H67.1c-13 0-23-10-23-23s10-23 23-23h805.4L662.4 274.5c-21-21.1 11-53.1 32-32.1z"/></svg>
  export default RightArrow;

on the RightArrow.jsx


i took the example as you have it on "DateRangePickerWrapper" and put it on a new page on my site. 

However, what it only displays is the start and end date without the actual calendar even when i press on them. Does it have to do with the "focused" or "focusedInput" values? because the focused is what makes the calendar to show on the "SingleDatePicker" but on the range it is the focusedInput, if am not mistaken? and i have seen the comment on README saying: " the calendar is only visible if focusedInput is defined" . so even after initialising focusedInput the calendar does not appear

**Comment by Stathismi** [comment]
thats the only thing i get.
<img width="1187" alt="screen shot 2018-07-22 at 21 40 32" src="https://user-images.githubusercontent.com/36051231/43049913-e6427ede-8df7-11e8-9f29-e7e0b8ba7b38.png">

**Comment by Stathismi** [comment]
<img width="751" alt="screen shot 2018-07-22 at 21 42 44" src="https://user-images.githubusercontent.com/36051231/43049933-339f3802-8df8-11e8-8d87-71de10466772.png">

thats how i solved it, it looks like i cannot post the <svg> here so took a screenshot

**Comment by Stathismi** [comment]
@ljharb just to add , in order to make the "DateRangePickerWrapper" compile i copied your src files needed to make "DateRangePickerWrapper" compile, to my src file

**Comment by fatihsari** [comment]
@Stathismi Thank you
I've fixed this problem with inline SVG imports.
