### ISSUE TITLE
z-index and float 

### ISSUE THREAD

**Issue by ofirk12** [airbnb/react-dates#129]
Hi i have 2 question the first is where i need to put z-index that i will see the calendar  because now its  in back.
other question is that i see "end date -> start date" and this is the opposite .. how can i change it to "start date -> end date"
 thanks for the help

**Comment by tvanro** [comment]
I also had the issue with the z-index and fixed it in this way: https://github.com/airbnb/react-dates/issues/125#issuecomment-254180155

**Comment by ofirk12** [comment]
Thanks @tvanro now i need only to change the direction

**Comment by majapw** [comment]
Can you show a screenshot of what you're seeing? I'm not really sure what you mean by the z-index issue.

Are you trying to do something like this?
![screen shot 2016-10-18 at 2 23 49 pm](https://cloud.githubusercontent.com/assets/1383861/19496891/85b2d5ea-953e-11e6-9c9a-aee862f437a2.png)

If so, the storybook has this example, and you can find the corresponding code in https://github.com/airbnb/react-dates/blob/master/stories/DateRangePicker.js in the "anchored right" story.

```

**Comment by ofirk12** [comment]
@majapw  i fixed it see up the message of tvanro  , the problem was that i saw the calendar behind all the div and cant saw him

**Comment by tvanro** [comment]
@majapw this issue will occur when you try to use react-dates on an element that is using a z-index (a popup for example).

**Comment by vijilvpillai** [comment]
I am also facing the same issue with single datepicker portal. I adjusted the z-index of portal. Now calendar is coming out in a bootstrap modal but selection of dates is not working properly. The datepicker is getting closed  when I am selecting the dates.
Anyone can help please. I am stuck with issue for days

**Comment by zopper-savez** [comment]
> I am also facing the same issue with single datepicker portal. I adjusted the z-index of portal. Now calendar is coming out in a bootstrap modal but selection of dates is not working properly. The datepicker is getting closed when I am selecting the dates.
> Anyone can help please. I am stuck with issue for days

ME TOO!
