### ISSUE TITLE
List of unsupported browsers?

### ISSUE THREAD

**Issue by vsc-github** [airbnb/react-dates#1290]
Using this amazing date-picker in a lot of my projects. I was wondering what is the browser support.
Is there a list of browsers where this component wouldn't work? Or minimum versions that we actually support?

Apologies if this is a repeat question, but couldn't find it in the documentation. Thanks in advance.

**Comment by ljharb** [comment]
It should work in any browser supported by React itself.

**Comment by vsc-github** [comment]
Couldn't have asked for a better answer. Thanks.
