### ISSUE TITLE
Arrow buttons broken on Firefox

### ISSUE THREAD

**Issue by ha1ogen** [airbnb/react-dates#1303]
On Firefox I can't change calendar month, clicking on the arrows does nothing. Anyone else seeing this bug?

I'm on ^17.1.1

**Comment by majapw** [comment]
Eek, I think I can reproduce this. I will investigate today.

**Comment by majapw** [comment]
@ha1ogen can you share your Firefox version and which picker you are using? I can't seem to reproduce in FF61.
