### ISSUE TITLE
Render prop for confirm or cancel buttons on the bottom of the calendar

### ISSUE THREAD

**Issue by SoccerGee** [airbnb/react-dates#1318]
I would like to open a pull request for adding a conditionally rendering render prop.  The render prop would add confirm or cancel buttons similar to the info block on bottom (http://airbnb.io/react-dates/?selectedKind=DRP%20-%20Calendar%20Props&selectedStory=with%20info%20panel%20default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel).

I want to get some feedback if people were interested in that.  See mock up attached.
![image](https://user-images.githubusercontent.com/2251310/44359498-16ce6c80-a486-11e8-945e-9b0ee9e16084.png)

**Comment by majapw** [comment]
Hi @SoccerGee, I think that this is currently possible with the `renderCalendarInfo` prop (because you can render whatever you want in that area). Can you clarify a bit more what you are proposing?

**Comment by SoccerGee** [comment]
I'm assuming that this is might both require a "question" and "feature request" label.

**Comment by SoccerGee** [comment]
Okay, did you see the mockup?  

That is a custom mock up that we have made.  For clarity, Can we pass our own components to the `renderCalendarInfo` prop?

**Comment by SoccerGee** [comment]
@majapw Essentially, we want to pass a component that renders two buttons with some event handlers.

**Comment by majapw** [comment]
@SoccerGee `renderCalendarInfo` is a functional prop that you can return any node from! :) You can style it however you normally style things and add whatever content you want (see https://github.com/airbnb/react-dates/blob/master/stories/DateRangePicker_calendar.js#L152-L159 for a code example). It's in fact what powers airbnb's apply feature that's very similar to what you're describing:
<img width="686" alt="screen shot 2018-08-20 at 11 42 49 am" src="https://user-images.githubusercontent.com/1383861/44359958-3194e700-a46e-11e8-8cf4-24f1c5847212.png">

**Comment by SoccerGee** [comment]
BOOM!  Thank you!

**Comment by ghostropic** [comment]
I'm trying to get this to work but unable to pass the `onClick` out of `renderCalendarInfo`.

parent component: 
`const ChangeDate = ({ subscription, setSubscriptionDate, subscriptionDate }) => {...`

```
const handleSubmit = (date) => {
  console.log('not firing')
 }

<DayPickerSingleDateController
          date={date}
          focused
          enableOutsideDays
          numberOfMonths={1}
          onDateChange={onDateChange}
          onFocusChange={onFocusChange}
          renderCalendarInfo={() => (
            <Button primary label="Submit" type="long" onclick={handleSubmit} />
          )}
        />
```

I have another button working fine in the same parent component:

```
const handleShipNow = (e) => {
  console.log('firing!)
}

<Button primary label={isSending ? 'working...' : 'Ship Order Now'} type="long" onClick={handleShipNow} disabled={isSending} />
```

Maybe something obvious here I'm messing up?

**Comment by ljharb** [comment]
onclick versus onClick?
