### ISSUE TITLE
[feature request] Prop for day of week format

### ISSUE THREAD

**Issue by daltones** [airbnb/react-dates#132]
Currently month headers have the format `dd` hardcoded for week days (that resolves to “Su Mo Tu We Th Fr Sa” in English).

In my case, the default translation for pt-BR shipped in Moment.js resolves to “Dom 2ª 3ª 4ª 5ª 6ª Sáb”, very unusual here. A better format would be `ddd`.

I guess even in English or other languages, one could like to set `ddd` (or even `dddd` for full names). So a prop like `weekDayFormat` for components would be nice.

**Comment by majapw** [comment]
This should be addressed in v12.6.0
