### ISSUE TITLE
Don't render DayPickerSingleDateController when collapsible panels

### ISSUE THREAD

**Issue by edguerrade** [airbnb/react-dates#1332]
When I have 'N' calendars, each one on a collapsible accordion bootstrap panel (react-bootstrap), if it's hidden first time when it renders, it doesn't appear again. Here is the example code https://codesandbox.io/s/6j10z2m8vn

**Comment by edguerrade** [comment]
This issue related with #46

**Comment by klejejs** [comment]
Same happening with version 21.8.0.
