### ISSUE TITLE
Updating README?

### ISSUE THREAD

**Issue by dumblole** [airbnb/react-dates#1337]
I came across this issue when trying to figure out styling without going in too deep.

https://github.com/airbnb/react-dates/issues/758#issuecomment-336670523

I suggest updating the README to match the current CSS variables, since it is outdated and the ones referenced here don't work anymore:

https://github.com/airbnb/react-dates#overriding-styles

I could make a pr if necessary.

**Comment by majapw** [comment]
Sounds great! We'd be happy to accept a PR in this vein. :)

**Comment by ljharb** [comment]
Closed in #1341/#1344.
