### ISSUE TITLE
don't allow to select date range in between blocked dates ? so is this possible.any suggestions please???????????????? 

### ISSUE THREAD

**Issue by hemanth-sp** [airbnb/react-dates#1338]
See still i can able to select range, so which file is causing this issues?

![screenshot from 2018-09-04 13-17-40](https://user-images.githubusercontent.com/24698571/45017388-1ec10b80-b045-11e8-9927-93c36d3c51a4.png)

**Comment by dumblole** [comment]
I understand you may be frustrated, but next time please don't spam so many question marks.

I don't fully understand your question but could this help you? https://github.com/airbnb/react-dates/issues/971

**Comment by hemanth-sp** [comment]
yea, actually i am using this reac dates (wrapper) library in angular, this wrapper complied in node models (js and jsx files) it is very very difficult to override(even no support in web to override node modules)
