### ISSUE TITLE
New to react and need help implementing the Month selector and year selector functionality

### ISSUE THREAD

**Issue by swaritkohli** [airbnb/react-dates#1368]
I'm relatively new to react as well as GitHub, and need some assistance using the year selection functionality on react-dates.
I have used react-dates on a dummy project I made following a course on Udemy, and dd not need that functionality. I've followed up on #25 and #1106 but I wasn't really able to grasp the implementation part.
I'm an intern and the current project I'm a part of, requires that functionality to be added. Could someone please walk me through the use of react-dates in my basic application, say, a form, from importing, to passing the props, to rendering captions and all. Any help would be appreciated. I'm not sure if I should have posted this as an Issue, so if that was not supposed to be done, please excuse me, and kindly move this to wherever this question should be. I'm sorry if this shouldn't have happened.

I have attached the screenshot of how it currently looks to me.

Thanks in advance!
![issue](https://user-images.githubusercontent.com/43463811/45864645-454aaa80-bd98-11e8-9b12-bd4034e9d06b.JPG)

**Comment by Henriklimseth** [comment]
Did you solve this? I'm having the same issue.

**Comment by Henriklimseth** [comment]
@swaritkohli Thank you so much, this solved it for me as well!
