### ISSUE TITLE
Select single date on dateRangePicker

### ISSUE THREAD

**Issue by giacomo-m** [airbnb/react-dates#1369]
Hi, is there a way for selecting a single day in dateRangePicker component? I see on Airbnb website that it is possible by clicking two times on the same day.

![airbnb_-_2018-09-21_15 37 49](https://user-images.githubusercontent.com/15344086/45884478-54d7ec80-bdb4-11e8-9f38-33582b73fce9.png)

Thanks.
Giacomo

**Comment by stjanis** [comment]
you should use SingleDatePicker (SDP)

http://airbnb.io/react-dates/?selectedKind=SingleDatePicker%20%28SDP%29&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by giacomo-m** [comment]
Thanks for your reply @stjanis, but i need both daterange and singledate functions at the same time.
Is that possible?

**Comment by majapw** [comment]
Hi @giacomo-m, you can pass in `minimumNights={0}`. It's set to 1 by default but is customizable.

**Comment by giacomo-m** [comment]
Thanks @majapw. It works fine!

**Comment by IbrahimOwner2020** [comment]
Thanks @majapw. just tried your solution and It worked fine!
