### ISSUE TITLE
DayPickerSingleDateController error: Cannot read property '<date>' of undefined

### ISSUE THREAD

**Issue by stjanis** [airbnb/react-dates#1373]
Might be related to other issue e.g. [#1342](https://github.com/airbnb/react-dates/issues/1342)

When `DayPickerSingleDateController` is used with `orientation="verticalScrollable"`, then clicking on next months button, scrolling to second next month and selecting any day results in above error (e.g. if last month before next months' button is December, then error occurs on February). Error occurs only on specifically +2 month and not on other months. Though selected day styles are missing on following months.

Haven't observed the same issue on `DayPickerRangeController` with `orientation="verticalScrollable"`.

I'm using react 16.2 and react-dates 18.1. Tested on Chrome Version 68.0 on Mac OS.

note: last click in below GIF before error is on on April 1st

![singledatepicker_next_2_months_bug](https://user-images.githubusercontent.com/18189347/45941930-a95faf80-bfe0-11e8-8993-794a65073e32.gif)

**Comment by majapw** [comment]
This likely means that the `DayPickerSingleDateController` isn't properly adding those months to its `state.visibleDays` object (the mapping of month => day => modifiers). Taking a look, you can see that the `DayPickerRangeController` has an `onMultiplyScrollableMonths` method that was lost on the `DayPickerSingleController`. Adding that class method and passing it to the `DayPicker` as a prop would solve the problem!
