### ISSUE TITLE
Auto-focusing startDate

### ISSUE THREAD

**Issue by Architektor** [airbnb/react-dates#138]
I don't know why this is happening, but `startDate` input always gets autofocused when i mount `DateRangePicker`. This is really annoying, i see `onFocusChange(START_DATE)` firing when i open dialog box containing `DateRangePicker`. Default `focusedInput` value is guaranteed `null`.

**Comment by Architektor** [comment]
Right now i'm dealing with it by supressing that first onFocusChange(START_DATE) thing manually.

**Comment by majapw** [comment]
That's really bizarre and might be related to https://github.com/airbnb/react-dates/issues/120. Can you share your set-up?

**Comment by l3wi** [comment]
@Architektor I'm facing the same issue. Could you please share your code for this.

**Comment by Architektor** [comment]
@l3wi sure
`  handleDatePickerClose = () => {
    const inlineDialog = document.getElementById('date-picker');
    inlineDialog.open = false;
    // temp fix to react-dates auto-opening
    // https://github.com/airbnb/react-dates/issues/138
    this.props.unsetFocusedInput();
  }
`

**Comment by majapw** [comment]
Hi @Architektor, can you check if v4.1.1 fixed this issue? 

The relevant PR is here - https://github.com/airbnb/react-dates/pull/212
