### ISSUE TITLE
Selecting past dates from the input field is not working

### ISSUE THREAD

**Issue by Henriklimseth** [airbnb/react-dates#1383]
I'm using react-dates with the prop `isOutsideRange={() => false}`. This enables me to select days in the past from the calendar by clicking on them, but not by typing in the input field.
I.e. typing "09/01/2018" does not update the calendars state.

The issue can be observed in your [Storybook](http://airbnb.io/react-dates/?selectedKind=SDP%20-%20Day%20Props&selectedStory=allows%20all%20days%2C%20including%20past%20days&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) when choosing "allow all days, including past days" under SDP - Day Props: After typing a past date in the input field the calendar does not close, and the date is not highlighted.

Is there something I'm missing, or a different prop that needs to passed to allow for typing past dates in the input field?

**Comment by Henriklimseth** [comment]
I see now that the latest commit is addressing this exact issue, so I'm guessing this will be closed by your next release!

**Comment by majapw** [comment]
Oh sweet. I'm so glad when we've already fixed a problem. :P I'll do a quick patch release.

**Comment by austenpayan** [comment]
+1 would love to get this patch!

**Comment by majapw** [comment]
v18.1.1 is out! I must have gotten distracted 😬Thank you for your patience!

**Comment by austenpayan** [comment]
@majapw Thanks!
