### ISSUE TITLE
readOnly demo does not work

### ISSUE THREAD

**Issue by merrifieldbrian** [airbnb/react-dates#1385]
the demo for readOnly still allows users to edit the date range.

**Comment by majapw** [comment]
I am unable to edit the range by typing in the input. What browser are you using?

**Comment by merrifieldbrian** [comment]
Chrome
Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by majapw** [comment]
Can you provide a gif? I'm on the same version and am unable to reproduce.

**Comment by merrifieldbrian** [comment]
![react-dates-ro](https://user-images.githubusercontent.com/3357891/46381544-9477c180-c65b-11e8-8f46-f0f98722b5c8.gif)

**Comment by rafaalvfe** [comment]
Same issue in my project, readOnly is not working properly in SingleDatePicker.
I tried in two different browsers:
- Chrome Version 69.0.3497.100 (Official Build) (64-bit)
- Safari Version 12.0 (14606.1.36.1.9)

**Comment by majapw** [comment]
I think there may be confusion about what `readOnly` means. We're treating it as you cannot type in a date, but not that you cannot change it via the calendar. If you want to prevent the user from changing the value, I would use the `disabled` prop. You could also simply not update the `focusedInput` prop to accomplish the same thing.

**Comment by rafaalvfe** [comment]
@majapw Yes, I was confused, that's why I deleted mi comment, would be a nice idea to add more documentation about it, I couldn't find any, I inferred it later.

**Comment by majapw** [comment]
Not a bad idea! :)

**Comment by chiubaka** [comment]
This property name is pretty confusing!!
