### ISSUE TITLE
Support a way to use your components without "Tether"

### ISSUE THREAD

**Issue by yaycmyk** [airbnb/react-dates#139]
Sometimes you just want to render a date picker in-place...

**Comment by majapw** [comment]
Can you describe what problems the tethering is causing for you exactly? The idea was to replicate the previous behavior but with the enhanced responsiveness that comes with tethering. If it broke behavior for you, it'd be good to know how.

**Comment by yaycmyk** [comment]
If you are rendering a picker component inside another that is portalled in a way similar to the Yether component, it's difficult to do event detection via bubbling, etc.

**Comment by ljharb** [comment]
React components are supposed to be self-contained - I wouldn't think you'd want to rely on events bubbling out of a React component anyways.

Your outside click detection would be most robust if it used the [`contains`](https://developer.mozilla.org/en-US/docs/Web/API/Node/contains) API, on the ref for the datepicker, to see if it's an inside click - that way it wouldn't matter how the HTML was structured.

**Comment by yaycmyk** [comment]
@ljharb I do in fact use that method, however if one of the inner children does not actually render inside the tree like `Tether` does, then `contains` is useless.

**Comment by yaycmyk** [comment]
Trust me, I've done the research on this and developed my own way of dealing with it for the time being. However, it would be better to simply offer a method of using the component without the tether. For example, sometimes form designs do not need the input field to actually be visible and the date picker lives by itself, adjusting a hidden input.

**Comment by ljharb** [comment]
I'm in complete agreement that there should be a way to use it without tethering :-) i just don't think the use case should be "event bubbling".

**Comment by yaycmyk** [comment]
> For example, sometimes form designs do not need the input field to actually be visible and the date picker lives by itself, adjusting a hidden input.

There you go. In that situation, you'd want to render in-place since it technically doesn't have anything specific to "tether" to.

**Comment by thomasthesecond** [comment]
Another case that I can describe is one that I'm currently experiencing, and that is using the DateRangePicker component inside of another Tether component. In the mobile view of our app, our filter controls (which includes the date picker) render in a pop-over/modal style panel, which is tethered. In this case, I think it would be nice to have the option.

**Comment by majapw** [comment]
Oh yeah, I am in fact running into this now when rendering the datepicker in a modal and it is gross. I was wondering if maybe being able to indicate the DOM element the tether attaches itself to might be sufficient? I really don't want to lose the responsiveness associated with the tether, but I *think* that maybe allowing the tether parent to be something other than the body might help (also with z-index issues).

**Comment by yaycmyk** [comment]
That doesn't help if you want the picker to take up space and affect the
layout of surrounding content.

**Comment by majapw** [comment]
To be fair, the implementation before the tether did not do that either, but I guess you were able to do it more easily in that case with CSS overrides on the DateRangePicker__picker class. I think for that usecase, I was imagining that people would use the DayPicker directly (because do you even want inputs in that situation?)

**Comment by yaycmyk** [comment]
That's what we ended up doing... It works well enough, just felt like a
hack to me to delve into your module tree.

**Comment by majapw** [comment]
Yeah so the tether was a failed experiment. It has been ripped out as of v4.0.0

**Comment by yaycmyk** [comment]
Thanks for your time and effort here. Much appreciated 👍

**Comment by neekey** [comment]
Hi @majapw 

> To be fair, the implementation before the tether did not do that either, but I guess you were able to do it more easily in that case with CSS overrides on the DateRangePicker__picker class. I think for that usecase, I was imagining that people would use the DayPicker directly (because do you even want inputs in that situation?)

I think I kind of runing into the same situation that I just want to use the datePicker directly, and just want to get rid of the two inputs (not sure if they are the "Tether" you were talking about, so I post a screenshot here to make it clear):

![image](https://cloud.githubusercontent.com/assets/499870/21168627/b94933f2-c209-11e6-9f9f-0a8dbbe15418.png)

The reason I can't just use the DayPicker directly is that I need the functionality of picking date range.

My case is like:

![image](https://cloud.githubusercontent.com/assets/499870/21168653/fd6337a4-c209-11e6-9d10-c3c1542e7cbc.png)

I get a date range dropdown, and when the "custom range" is clicked, I want to show the dateRangePicker:

![image](https://cloud.githubusercontent.com/assets/499870/21168672/2147e098-c20a-11e6-89b5-b23130087e71.png)

..

I'm using 4.1.1, but I can't find a way to use the dateRangePicker alone without the "Tether".

**Comment by majapw** [comment]
@neekey I don't quite know what you mean by tether. The tether we're talking about on this issue is a specific dependency that modified the DOM structure of the component and allowed for easy responsiveness. It has been removed totally (and so your question doesn't make very much sense to me) and replaced with something simpler.

It seems like what you actually mean is that you want to have all the logic set up for you but not use the built in inputs associated with the `DateRangePicker`. I'd recommend taking this conversation over to https://github.com/airbnb/react-dates/issues/204#issuecomment-267121036

**Comment by neekey** [comment]
@majapw Thanks for clarifying the situation haha...my mistake. Will move to that issue
