### ISSUE TITLE
react-dates as a button

### ISSUE THREAD

**Issue by wijdench** [airbnb/react-dates#1396]
Hi,

I'm using your react dates compo and it's perfect fo my web application. I want to modify the style of the compo like it is used un your app: a clickable button, once we click, it will open the calendar.

Thanks.

**Comment by LMulvey** [comment]
This is definitely something that you can do in your own implementation. It really depends which component you intend on using. If you were wanting to use the DateRangePicker with the inputs and DayRangePickerController, this example shows you how to achieve what you want:

**Storybook:** http://airbnb.io/react-dates/?selectedKind=DateRangePicker%20%28DRP%29&selectedStory=hidden%20with%20display%3A%20none

```
class TestWrapper extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      showDatePicker: false,
    };
  }

  render() {
    const { showDatePicker } = this.state;
    const display = showDatePicker ? 'block' : 'none';
    return (
      <div>
        <button
          type="button"
          onClick={() => this.setState({ showDatePicker: !showDatePicker })}
        >
          Show me!
        </button>

        <div style={{ display }}>
          <DateRangePickerWrapper />
        </div>
      </div>
    );
  }
}
```
(from https://github.com/airbnb/react-dates/blob/master/stories/DateRangePicker.js)

**Comment by majapw** [comment]
Hi @wijdench! You can use the `renderCalendarInfo` prop to render arbitrary content below the calendar. See https://github.com/airbnb/react-dates/blob/master/stories/DateRangePicker_calendar.js#L152-L159 for more info (and the corresponding story in the storybook).

(Thanks for the help @LMulvey!)

**Comment by wijdench** [comment]
Hi @majapw, 

Thanks for your feedback, this is really helpful.
