### ISSUE TITLE
Missing dependency `react-addons-shallow-compare`

### ISSUE THREAD

**Issue by ryexley** [airbnb/react-dates#14]
Tried pulling this into a project today and I'm getting a build error:

`Error: Cannot resolve module 'react-addons-shallow-compare'`

Looks like that dependency is used in several of the components, but it's listed as one of the `devDependencies` in `package.json`...seems like that needs to be moved to one of the `dependencies` so it can be installed for use in production. Am I missing something?

**Comment by ljharb** [comment]
Since react things are singletons, it'd need to be a peer dependency + dev dependency. Thanks for the report!

**Comment by ljharb** [comment]
Ah, actually it's already a peerDependency - run `npm ls` and you'll see all the missing peer dependencies that this project requires.

**Comment by ljharb** [comment]
I've updated the readme with an installation command that will grab all the peer deps for you.

**Comment by coreylight** [comment]
Is there a way to use the traditional npm install process instead of the custom command? It doesn't seem to line up with other packages out there that just rely on npm install/postinstall etc. I don't have a specific alternative (sorry) but the current process doesn't exactly work 100% with yarn. Thanks for the lib.

**Comment by jpollard-cs** [comment]
@coreylight yarn already has this covered for you 😄 https://yarnpkg.com/en/docs/cli/add#toc-yarn-add-peer-p

**Comment by coreylight** [comment]
So I did this:
`⚡ yarn add react-dates
yarn add v0.15.1
warning hud@0.1.0: Dependency "events" listed in "dependencies" is the name of a built-in module
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning Unmet peer dependency "react-addons-shallow-compare@>=0.14".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 8 new dependencies.
├─ array-includes@3.0.2
├─ classnames@2.2.5
├─ react-dates@3.6.0
├─ react-moment-proptypes@1.2.0
│  └─ moment@2.15.2
├─ react-portal@2.2.1
├─ react-tether@0.5.2
└─ tether@1.3.7
✨  Done in 10.33s.`

Then when I fired up my webpack build again I got this:
`ERROR in ./~/react-dates/lib/components/DayPicker.js
Module not found: Error: Cannot resolve module 'react-addons-shallow-compare' in /Users/corey/Documents/iopipe/hud/node_modules/react-dates/lib/components
 @ ./~/react-dates/lib/components/DayPicker.js 698:18-57

ERROR in ./~/react-dates/lib/components/CalendarMonthGrid.js
Module not found: Error: Cannot resolve module 'react-addons-shallow-compare' in /Users/corey/Documents/iopipe/hud/node_modules/react-dates/lib/components
 @ ./~/react-dates/lib/components/CalendarMonthGrid.js 372:18-57

ERROR in ./~/react-dates/lib/components/CalendarDay.js
Module not found: Error: Cannot resolve module 'react-addons-shallow-compare' in /Users/corey/Documents/iopipe/hud/node_modules/react-dates/lib/components
 @ ./~/react-dates/lib/components/CalendarDay.js 354:18-57
Child html-webpack-plugin for "index.html":`

Am I missing something?

**Comment by jpollard-cs** [comment]
try `yarn add react-dates -P`

**Comment by coreylight** [comment]
Seems to cause the same issue. 

Removed `react-addons-shallow-compare` and also `react-dates`
Then ran this:
```
⚡ yarn add react-dates -P
yarn add v0.15.1
warning hud@0.1.0: Dependency "events" listed in "dependencies" is the name of a built-in module
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning Unmet peer dependency "react-addons-shallow-compare@>=0.14".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 8 new dependencies.
├─ array-includes@3.0.2
├─ classnames@2.2.5
├─ moment@2.15.2
├─ react-dates@3.6.0
├─ react-moment-proptypes@1.2.0
├─ react-portal@2.2.1
├─ react-tether@0.5.2
└─ tether@1.3.7
✨  Done in 8.59s.
```
So, same thing?

**Comment by ljharb** [comment]
For the record, if something works with npm but not with yarn, it's a yarn bug - please file it on their repo.

@coreylight the reason for the fancy install command is because npm doesn't offer an easy way to guarantee you have the right peer deps in your package.json. `yarn add -P` may indeed offer that, but the command provided should work just fine with npm, after which you can regenerate your yarn.lock file.

**Comment by coreylight** [comment]
It seems as if you just duplicate all the peerdeps into the dependencies in the package.json, it will work great for npm 3+ users. npm 2 users can just run `npm dedupe` if they want?

**Comment by ljharb** [comment]
npm 2 automatically installs peer deps, but doesn't put them in package.json - which is an error. Peer deps of deps should always be explicitly listed in package.json, which this command achieves in npm 2 and 3+.

**Comment by jpollard-cs** [comment]
@coreylight yeah not working for me either - maybe I misread the docs. I would just follow @ljharb's suggestion for now (install via NPM). Also if you're on a PC I put together a PowerShell command (to help with the peer dependencies install) that's in the comments of this PR here: https://github.com/airbnb/react-dates/pull/107
