### ISSUE TITLE
Support Custom Styling For Today's Date

### ISSUE THREAD

**Issue by willisplummer** [airbnb/react-dates#1423]
I've been looking for a way to implement a custom style on today's date (e.g. a different background color) in the date picker but there doesn't seem to be one.

It would be great if there were an easy way to apply a class to a specific date so that it could be styled differently. Or maybe there are already is a solution and I'm just not seeing it?

Thanks!

**Comment by majapw** [comment]
Hi @willisplummer, if you're using css stylesheets, you should be able to override style's for today's date by overriding styles for the classname `.CalendarDay__today`. 

There are no default styles, but the class does still get applied: https://github.com/airbnb/react-dates/blob/master/src/components/CalendarDay.jsx#L340
