### ISSUE TITLE
Storybook broken after babel 7 update

### ISSUE THREAD

**Issue by pedroabreu** [airbnb/react-dates#1429]
After update to babel 7 (#1417), storybook is now broken locally

> info @storybook/react v3.4.11
> info
> info => Loading custom .babelrc
> info => Loading custom addons config.
> info => Loading custom webpack config (extending mode).
> webpack built 38abdf82fad419c08734 in 5358ms
> Hash: 38abdf82fad419c08734
> Version: webpack 3.12.0
> Time: 5358ms
>                        Asset       Size  Chunks                    Chunk Names
>     static/manager.bundle.js     2.8 MB       0  [emitted]  [big]  manager
>     static/preview.bundle.js     509 kB       1  [emitted]  [big]  preview
> static/manager.bundle.js.map    3.42 MB       0  [emitted]         manager
> static/preview.bundle.js.map     605 kB       1  [emitted]         preview
>                   index.html    1.21 kB          [emitted]
>                  iframe.html  769 bytes          [emitted]
>  [133] ./node_modules/@storybook/react/dist/server/config/polyfills.js 113 bytes {0} {1} [built]
>  [152] ./node_modules/@storybook/react/node_modules/core-js/fn/array/iterator.js 107 bytes {0} {1} [built]
>  [160] ./node_modules/airbnb-js-shims/index.js 40 bytes {0} {1} [built]
>  [287] ./node_modules/@storybook/ui/dist/index.js 2.43 kB {0} [built]
>  [388] multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./.storybook/addons.js ./node_modules/@storybook/core/dist/client/manager/index.js 52 bytes {0} [built]
>  [389] ./.storybook/addons.js 1.23 kB {0} [built] [failed] [1 error]
>  [390] ./node_modules/@storybook/core/dist/client/manager/index.js 423 bytes {0} [built]
>  [746] ./node_modules/@storybook/core/dist/client/manager/provider.js 3.35 kB {0} [built]
>  [760] multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./node_modules/webpack-hot-middleware/client.js?reload=true ./.storybook/config.js 64 bytes {1} [built]
>  [761] ./node_modules/@storybook/react/dist/server/config/globals.js 105 bytes {1} [built]
>  [762] ./node_modules/webpack-hot-middleware/client.js?reload=true 7.77 kB {1} [built]
>  [763] ./node_modules/querystring-es3/index.js 127 bytes {1} [built]
>  [766] ./node_modules/strip-ansi/index.js 161 bytes {1} [built]
>  [773] ./node_modules/webpack-hot-middleware/process-update.js 4.37 kB {1} [built]
>  [774] ./.storybook/config.js 1.23 kB {1} [built] [failed] [1 error]
>     + 760 hidden modules
> 
> ERROR in ./.storybook/addons.js
> Module build failed: Error: Cannot find module 'babel-core'
>     at Function.Module._resolveFilename (module.js:547:15)
>     at Function.Module._load (module.js:474:25)
>     at Module.require (module.js:596:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/Users/pedroabreu/Documents/react-dates/node_modules/@storybook/react/node_modules/babel-loader/lib/index.js:3:13)
>     at Module._compile (module.js:652:30)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
>     at Function.Module._load (module.js:497:3)
>     at Module.require (module.js:596:17)
>     at require (internal/module.js:11:18)
>     at loadLoader (/Users/pedroabreu/Documents/react-dates/node_modules/loader-runner/lib/loadLoader.js:13:17)
>     at iteratePitchingLoaders (/Users/pedroabreu/Documents/react-dates/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
>     at runLoaders (/Users/pedroabreu/Documents/react-dates/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
>     at NormalModule.doBuild (/Users/pedroabreu/Documents/react-dates/node_modules/@storybook/core/node_modules/webpack/lib/NormalModule.js:182:3)
>  @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./.storybook/addons.js ./node_modules/@storybook/core/dist/client/manager/index.js
> 

Issue is that `babel-core` doesn't exist anymore. Since it seems a bit redundant to add it just because of storybook, perhaps the simplest solution would be to revert this merge

**Comment by ljharb** [comment]
Thanks, will fix.
