### ISSUE TITLE
change arrow between startdate to enddate

### ISSUE THREAD

**Issue by ofirk12** [airbnb/react-dates#143]
hello , how can i change the arrow from right(->) to left (<-)?

**Comment by majapw** [comment]
Uh, there's no way to do that currently. Given that logic currently prevents the end date from coming before the start date, that might be kind of weird. Can you explain your usecase?

**Comment by ofirk12** [comment]
yes i write the website in Hebrew  so its start from the right to left .. therefore i need to change the arrow ... you can say me where is the source of it ? and what i need to change ?

**Comment by herecydev** [comment]
Looks like it's located [here](https://github.com/airbnb/react-dates/blob/master/src/components/DateRangePickerInput.jsx#L5), used [here](https://github.com/airbnb/react-dates/blob/master/src/components/DateRangePickerInput.jsx#L137) and you can probably just swap it out for the `arrow-left` located [here](https://github.com/airbnb/react-dates/tree/master/src/svg).

**Comment by Pixelatex** [comment]
I'd also like to second this idea. You can change the arrows in the calendar itself, but not the arrow between the input fields.. This isn't really consistent. Could you please add this functionality?

**Comment by majapw** [comment]
Fixed in https://github.com/airbnb/react-dates/pull/277

**Comment by tinshade** [comment]
Adding something like
`customArrowIcon={<i className="fas fa-arrow-right"/>}`
in your DatePicker component works.
