### ISSUE TITLE
Is there any documentation on using Radium inline styles for styling our react components? 

### ISSUE THREAD

**Issue by israelluciano** [airbnb/react-dates#1435]
We inline style prop in react in our application. How would I go about creating an interface to react-with-styles so I can keep building my app with inline style and incorporate react-dates?

**Comment by ljharb** [comment]
The best approach would indeed be to find or create an interface - either for radium specifically, or for inline styles generically. You can look at https://github.com/airbnb/react-with-styles which lists a few that should help with creating one.

Once you do, we’d love to add it to the react-with-styles readme!

I’m going to close this for now; we’d be happy to answer any questions you have during the process on the react-with-styles repo :-)
