### ISSUE TITLE
npm install error for v12.7.0

### ISSUE THREAD

**Issue by thinkian** [airbnb/react-dates#1439]
Am not able to install a `12.x` version of `react-dates` later than `12.2.4`. There are some important [fixes](https://github.com/airbnb/react-dates/blob/master/CHANGELOG.md#1260) that were pushed in `12.6.0` related to visible months based on dates changing that I need to use in my application and I am not ready for the major [breaking](https://github.com/airbnb/react-dates/blob/master/CHANGELOG.md#1300) style updates that were made in `13.0.0`.

```
npm ERR! node v6.14.3
npm ERR! npm  v3.10.10
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: react-dates@12.7.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 18.1.0, 12.2.4
```

The npm registry shows that is has the [12.7.0](https://www.npmjs.com/package/react-dates/v/12.7.0) package but I don't seem able to install it. Any insight would be helpful. Thank you.

**Comment by ljharb** [comment]
That it only lists those two versions as valid suggests you’re using a private registry that’s not up to date.

**Comment by thinkian** [comment]
@ljharb You are very correct. My bad. Thank you!
