### ISSUE TITLE
How do we make the year selectable on SingleDatePicker

### ISSUE THREAD

**Issue by moecantplay** [airbnb/react-dates#1450]
So I've been going through the issues, and i can't seem to find a good summarised version of how to make the SingleDatePicker able to select past dates and a selectable year (perhaps a dropdown or something). If someone is kind and patient enough to show me how it'd be so helpful, thanks..

**Comment by ljharb** [comment]
#25 is the request for picking a year; #1106 implements it. Hopefully that helps.
