### ISSUE TITLE
Warning: Failed prop type on SingleDatePicker

### ISSUE THREAD

**Issue by tuanluu-agilityio** [airbnb/react-dates#1454]
Hello,

I got issue `Warning: Failed prop type on SingleDatePicker` when using `SingleDatePicker` on `react-dates`:
<img width="772" alt="screen shot 2018-11-07 at 11 00 47 am" src="https://user-images.githubusercontent.com/24542782/48110021-7a458a80-e27c-11e8-932e-81654f7aafda.png">

Here my code:

```
import 'react-dates/initialize'
import { SingleDatePicker } from 'react-dates'

// Styles
import 'react-dates/lib/css/_datepicker.css'
import '../../../assets/styles/custom_datepicker.css'

<SingleDatePicker
          isOutsideRange={
            isEnableDateRange
              ? day => handleGetOutsideRangeDates(day)
              : this.handleGetDefaultOutSideRange
          }
          date={calendarDate ? moment(calendarDate) : calendarDate}
          onDateChange={date => handleGetPeriod(id, date)}
          focused={this.state.focused}
          onFocusChange={({ focused }) => this.setState({ focused })}
          id={id}
          inputIconPosition={ICON_AFTER_POSITION}
          placeholder={placeholder}
          displayFormat={`DD/MM/YYYY`}
          numberOfMonths={1}
          showDefaultInputIcon={false}
          customInputIcon={
            <LinkIcon {...calendarIconStyles} disabled={disabled} />
          }
          disabled={disabled}
          daySize={22}
          monthFormat={'MMM, YYYY'}
          firstDayOfWeek={1}
          readOnly={readOnly}
        />
```
These errors happen on both `react-dates` `v16.7.0` and `v18.2.1`.
I have research on issues but can't find solution for it. Anyone can help me?

Thanks,

**Comment by ljharb** [comment]
Do you perhaps have a build process that’s inserting “self” and “source” props, perhaps something related to hot reloading?

**Comment by tuanluu-agilityio** [comment]
> Do you perhaps have a build process that’s inserting “self” and “source” props, perhaps something related to hot reloading?

@ljharb I don't have any special config on it. Currently I'm using `react-dates` with `preact`. Do you have any another suggestion to fix these warnings?

**Comment by ljharb** [comment]
It’s possible that preact is doing it - this is react-dates, not preact-dates. You may want to file it on preact.

**Comment by tuanluu-agilityio** [comment]
got it @ljharb . Thanks for the advice 👌

**Comment by ljharb** [comment]
Closing, in favor of https://github.com/developit/preact/issues/762
