### ISSUE TITLE
New Warning with last version 18.2.1

### ISSUE THREAD

**Issue by timhecker** [airbnb/react-dates#1455]
When I use your last DateRangePicker, I see in console this:
`DateRangePicker has a method called shouldComponentUpdate(). shouldComponentUpdate should not be used when extending React.PureComponent. Please extend React.Component if shouldComponentUpdate is used.` - `react-dom.development.js:506`

on every kind of interaction. I'm using last version of React and React-dom (16.6.1)

**Comment by majapw** [comment]
Ah I'm pretty sure this is due to the change I shipped yesterday. I will amend the babel transform to conditionally insert the `shouldComponentUpdate`. Thanks for letting me know! v18.2.0 should be fine.

**Comment by LeHaine** [comment]
This is also happening with SingleDatePicker as well.

**Comment by Dodie324** [comment]
Any updates on this?

**Comment by majapw** [comment]
Just put a fix up! :) I'll merge and republish once I verify it and tests pass.

**Comment by majapw** [comment]
Doing a release now!

**Comment by majapw** [comment]
18.2.2 is out!

**Comment by timhecker** [comment]
Thanks!
