### ISSUE TITLE
which property need to set to enable swipe in mobile or one arrow button top and another arrow button below the calendar??

### ISSUE THREAD

**Issue by hemanth-sp** [airbnb/react-dates#1461]
http://airbnb.io/react-dates/?selectedKind=SDP%20-%20Calendar%20Props&selectedStory=vertical%20with%20full%20screen%20portal&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel for this one

**Comment by hemanth-sp** [comment]
i am using in angular i cant able to override most of your code

**Comment by majapw** [comment]
I think unfortunately we can't support your usecase at this point. Sorry!

**Comment by hemanth-sp** [comment]
no problem
