### ISSUE TITLE
Incompatibility with RTL in react-with-styles-interface-aphrodite

### ISSUE THREAD

**Issue by yzimet** [airbnb/react-dates#1470]
The `react-with-styles-interface-aphrodite` interface has its own RTL layout support (docs: https://github.com/airbnb/react-with-styles-interface-aphrodite#built-in-rtl-support)

We'd like react-dates' RTL implementation to work harmoniously with this interface. To do this, we could:
1. add `/* noflip */` to the relevant directional styles in react-dates, and
2. use the contextual `css` method from react-with-styles

cc: @majapw 

for reference, the current workaround is to "disable" react-with-style's RTL support:
```
<DirectionProvider direction={DIRECTIONS.LTR}>
  <div dir={direction}>
    <DayPickerRangeController
      {...props}
      isRTL={direction === DIRECTIONS.RTL}
    />
  </div>
</DirectionProvider>
```

**Comment by majapw** [comment]
This has been fixed by #1482/#1492 in v18.3.1 of `react-dates`
