### ISSUE TITLE
Overlay does not open with Firefox on Android

### ISSUE THREAD

**Issue by davincho** [airbnb/react-dates#148]
It seams that the plugin does not work with Firefox on Android. On http://airbnb.io/react-dates no date overlay appears if I tab on `State date` or `End date`.
You can easily simulate this behavior if you open http://airbnb.io/react-dates in Firefox (in my case v48), turn on `Responsive view` with `Ctrl+Shift+M` and enable `Simulate touch events`.

**Comment by majapw** [comment]
Ooh, that's not good and could explain a lot of data for us. D: I will dig into this.

**Comment by davincho** [comment]
@majapw I tracked this bug down and found the problem: https://github.com/airbnb/react-dates/blob/master/src/components/DateInput.jsx#L124
It seems that disabled input fields cannot trigger events in Firefox with `Simulate touch events` on. Demonstration: http://www.webpackbin.com/41VTyxNgz

**Comment by majapw** [comment]
Makes sense. I thought that I had a click handler above the input itself (on the surrounding div) to deal with this particular scenario (although it may have disappeared at some point in the grind).

As it is, if we can find a way to hide the keyboard and cursor on mobile devices consistently, I'm happy to replace the `disabled` property with that as that was mainly what I was trying to address.

**Comment by davincho** [comment]
The same error occurs on Windows 10 with current Firefox version (49). I try to find a solution and will submit a PR asap.

**Comment by davincho** [comment]
@majapw What's about registering an onClick handler on `DateInput__display-text` ?

```jsx
<div
  className={cx('DateInput', {
    'DateInput--with-caret': showCaret && focused,
    'DateInput--disabled': disabled,
  })}
>
  <label className="DateInput__label" htmlFor={id}>
    {placeholder}
  </label>

  <input
    className="DateInput__input"
   ....
  />

  <div
    className={cx('DateInput__display-text', {
      'DateInput__display-text--has-input': !!value,
      'DateInput__display-text--focused': focused,
      'DateInput__display-text--disabled': disabled,
    })}
    onClick={onFocus}
  >
    {value || placeholder}
  </div>
</div>
```

**Comment by majapw** [comment]
Hey @davincho, can you check if this is still an issue after https://github.com/airbnb/react-dates/pull/174 has been merged in?

**Comment by davincho** [comment]
Looks like the issue has been resolved! (checked on Linux with most recent Firefox with 'Simulate touch events' enabled and on Firefox for Android). Thanks!
