### ISSUE TITLE
isdayblocked dates not working properly 

### ISSUE THREAD

**Issue by hemanth-sp** [airbnb/react-dates#1483]
![img_20181206_132235](https://user-images.githubusercontent.com/24698571/49569632-7c256b00-f95a-11e8-9091-f14f693a20c6.jpg)

i passed 17th and 19th to blocked but it is blocking other dates 16th,20th, in photo. i think it is utc issues

**Comment by ljharb** [comment]
Did you figure it out? Others will want to benefit in the future.

**Comment by hemanth-sp** [comment]
yes that time utc issues  [like](https://stackoverflow.com/questions/53646145/remove-duplicates-from-array-in-moment-js#53646298) check akrion answer
