### ISSUE TITLE
[Feature Request] Use name instead of Id

### ISSUE THREAD

**Issue by sag1v** [airbnb/react-dates#1488]
Hi, When using `DateRangePicker` for example, these props are mandatory: 
`startDateId` , `endDateId`.

This won't allow us to use multiple `DateRangePicker`s as duplicate id's are not valid.
For example, a `DateRangePicker` rendered in the header of the page + another one in a popup / modal. both targeting the same endpoint and need the same `name` fields.

So, what we actually need for the form is the `name` and not the `id`, duplicate names are ok AFAIK. 
Is there any internal use or modules that dependent on the `id` in `react-dates`?
Can we change this approach?

**Comment by ljharb** [comment]
This is needed for accessibility - for/ID-linking labels to inputs is required (as well as nesting) to achieve full device coverage.

The form _name_ is different, and that should be separately configurable.

**Comment by sag1v** [comment]
OK, makes sense. Thanks.
