### ISSUE TITLE
My Calendar doesn't show up, why?

### ISSUE THREAD

**Issue by Steffi3rd** [airbnb/react-dates#1491]
Hi,

I'm just trying to use `react-dates` and it seems the calendar doesn't show up whereas the console.log is displayed.

When I click on StartDate, I only have a console.log, not the calendar. I cannot choose a date.

Someone knows why?

Thanks

 
<img width="434" alt="capture d ecran 2018-12-12 a 14 47 45" src="https://user-images.githubusercontent.com/814410/49873932-66fa8180-fe1d-11e8-99ce-f0c9d6f4e475.png">

<img width="808" alt="capture d ecran 2018-12-12 a 14 47 12" src="https://user-images.githubusercontent.com/814410/49873940-6c57cc00-fe1d-11e8-92d9-a1eeb76c3a05.png">

<img width="1049" alt="capture d ecran 2018-12-12 a 14 48 32" src="https://user-images.githubusercontent.com/814410/49873921-619d3700-fe1d-11e8-8f76-63757cca2545.png">

**Comment by majapw** [comment]
Hi @Steffi3rd, calendar visibility is controlled by the `focusedInput` prop. When it is `null`, the calendar is always hidden, as it is in your case. This is why we recommend using a `state` variable to control the `focusedInput` value and then updating that state variable with the `onFocusChange` prop. You can see an example of a functional wrapper around the `DateRangePicker` in https://github.com/airbnb/react-dates/blob/master/examples/DateRangePickerWrapper.jsx.
