### ISSUE TITLE
Always have an error : Failed prop type: Invalid prop `modifiers` of type `Object` supplied to `withStyles(CalendarDay)`, expected instance of `Set`.

### ISSUE THREAD

**Issue by Steffi3rd** [airbnb/react-dates#1493]
Hi, 

The minimum REQUIRED setup seems to not work well... What I missed?

The thing is the calendar seems working but I always have an error in console. I don't know why. 
It's the same thing with `DateRangerPicker`, `SingleDatePicker`...

Help please

```
class DatePicker extends React.PureComponent {
  constructor(props) {
    super(props);
    this.state = {
      focused: null,
      date: moment(),
    };
  }

  render() {
    return (
      <SingleDatePicker
        date={this.state.date} // momentPropTypes.momentObj or null
        onDateChange={date => this.setState({ date })} // PropTypes.func.isRequired
        focused={this.state.focused} // PropTypes.bool
        onFocusChange={({ focused }) => this.setState({ focused })} // PropTypes.func.isRequired
      />
    );
  }
}
```

<img width="801" alt="capture d ecran 2018-12-13 a 10 51 31" src="https://user-images.githubusercontent.com/814410/49930540-1c344480-fec5-11e8-9918-79ac8bcac6fe.png">

**Comment by majapw** [comment]
Can you share what version of react-dates you are using?

**Comment by kapor190** [comment]
Same here. Version of react-dates: 18.4.0.

**Comment by marcos0x** [comment]
I have this error: Failed prop type: Invalid prop `modifiers.2019-03-01` of type `Set` supplied to `CalendarMonth`, expected instance of `Set`.

**Comment by ljharb** [comment]
@marcos0x are you polyfilling `Set`, and can you ensure that you're doing that before any other code (including `react-dates`) is loaded?

**Comment by marcos0x** [comment]
@ljharb Yes, I used "airbnb-js-shims"

**Comment by ljharb** [comment]
and can you confirm that you're importing that before *any* other code? and that you're not also using `babel-polyfill` which conflicts?

**Comment by marcos0x** [comment]
@ljharb yes, a import in first line in index.js before of all imports

**Comment by ljharb** [comment]
and can you confirm that you’re also not using babel-polyfill in any way, which conflicts?

**Comment by ljharb** [comment]
k - it can sneak in if you’re using any babel settings besides babel-present-airbnb.

Your propType error strongly implies that the global `Set` isn’t the same one that was available when the instanceof propType was created (which uses the global `Set`). Since it’s unlikely that that’d be caused by anything but a non-first-run polyfill, then assuming you’re using the global Set as well, I’m not sure how to debug further :-/

**Comment by Tam** [comment]
I'm also getting `Warning: Failed prop type: Invalid prop 'modifiers' of type 'Object' supplied to 'withStyles(CalendarDay)', expected instance of 'Set'.` and `Warning: Failed prop type: Invalid prop 'modifiers' of type 'Object' supplied to 'CalendarDay', expected instance of 'Set'.`

Working my way up the stacktrace, it appears that the default `modifiers` prop on the compiled `CalendarMonth` in `lib/` is set to an empty object:
```js
var defaultProps = {
  month: (0, _moment["default"])(),
  // ...
  modifiers: {},
  // ...
  verticalBorderSpacing: undefined
};
```
I don't know if that's causing the issue or not. 

I'm not polyfilling Set in any way, checking `typeof Set === "function"` and using Firefox's `toSource()` returns `function Set() { [native code] }`.

**Comment by dfonidata** [comment]
Any news about this problem? I'm having these errors too.

**Comment by dfonidata** [comment]
Found a solution that worked for me.

https://github.com/airbnb/react-dates/issues/1198#issuecomment-419154768
