### ISSUE TITLE
Why do we need to click arrow down key before the calendar shows up?

### ISSUE THREAD

**Issue by janjanarnaldo** [airbnb/react-dates#1495]
I tried to copy this wrapper https://github.com/airbnb/react-dates/blob/master/examples/SingleDatePickerWrapper.jsx to my app but I noticed that upon on focus, there's no calendar, it only displays when I click on arrow down button.

This is the initial interface
![image](https://user-images.githubusercontent.com/13392638/50125700-fb913380-02a4-11e9-9184-7a61f1ff34d6.png)

And then displays after arrow down
![image](https://user-images.githubusercontent.com/13392638/50125710-0946b900-02a5-11e9-91a3-128321f0f0dc.png)

I learned that arrow key will work because of this paragraph hidden inside the component
![image](https://user-images.githubusercontent.com/13392638/50125750-28dde180-02a5-11e9-8c79-efab3d7aff4c.png)

**Comment by janjanarnaldo** [comment]
hope you can be of any help @ljharb @majapw thanks

**Comment by majapw** [comment]
Hi @janjanarnaldo, what is your `onFocusChange` callback look like? How are you maintaining focus state? It kind of looks like that's not being properly managed.

**Comment by janjanarnaldo** [comment]
HI @majapw it is focusing if you check the component's state.

![image](https://user-images.githubusercontent.com/13392638/50132286-59337900-02c1-11e9-98c4-3139b525ca79.png)

**Comment by majapw** [comment]
Is the DayPickerRangeController rendering in the DOM?

**Comment by janjanarnaldo** [comment]
tried 2 ways of callbacks
`onFocusChange = ({ focused }) => this.setState({ focused })` and

onFocusChange({ focused }) {
  this.setState({ focused });
} // were onFocusChange is bound to .this at constructor.

**Comment by janjanarnaldo** [comment]
No @majapw but I can see SingleDatePickerInputController

**Comment by majapw** [comment]
And what version of `react-dates` are you using?

**Comment by janjanarnaldo** [comment]
18.3.1 @majapw

**Comment by janjanarnaldo** [comment]
also, after clicking arrow down which shows the calendar, the `DayPickerSingleDateController` as you mentioned is already mounted @majapw

**Comment by majapw** [comment]
Can you share your entire props configuration?

**Comment by janjanarnaldo** [comment]
sure I'll put the entire component instead

`import React, { Component } from 'react';
import 'react-dates/initialize';
import 'react-dates/lib/css/_datepicker.css';

import moment from 'moment';

import { SingleDatePicker } from 'react-dates';

class DateSelector extends Component {
  static defaultProps = {
    // example props for the demo
    autoFocus: false,
    initialDate: null,

    // input related props
    id: 'date',
    placeholder: 'Date',
    disabled: false,
    required: false,
    screenReaderInputMessage: '',
    showClearDate: false,
    showDefaultInputIcon: false,
    customInputIcon: null,
    block: false,
    small: false,
    regular: false,
    verticalSpacing: undefined,
    keepFocusOnInput: false,

    // calendar presentation and interaction related props
    renderMonthText: null,
    // orientation: HORIZONTAL_ORIENTATION,
    // anchorDirection: 'right',
    horizontalMargin: 0,
    withPortal: false,
    withFullScreenPortal: false,
    // initialVisibleMonth: null,
    numberOfMonths: 1,
    keepOpenOnDateSelect: true,
    reopenPickerOnClearDate: false,
    isRTL: false,
    hideKeyboardShortcutsPanel: true,

    // navigation related props
    navPrev: null,
    navNext: null,
    onPrevMonthClick() {},
    onNextMonthClick() {},
    onClose() {},

    // day presentation and interaction related props
    // renderCalendarDay: undefined,
    // renderDayContents: null,
    enableOutsideDays: false,
    isDayBlocked: () => false,
    // isOutsideRange: day => !isInclusivelyAfterDay(day, moment()),0
    isDayHighlighted: () => {},

    // internationalization props
    monthFormat: 'MMMM YYYY',
    displayFormat: () => moment.localeData().longDateFormat('L'),
  }

  constructor(props) {
    super(props);
    this.state = {
      focused: props.autoFocus,
      date: props.initialDate,
    };
  }

  onDateChange = date => this.setState({ date })

  onFocusChange = ({ focused }) => this.setState({ focused })

  render() {
    const { focused, date } = this.state;

    const { autoFocus, initialDate, ...props } = this.props;

    return (
      <div className="DateSelector">
        <SingleDatePicker
          {...props}
          id="date_input"
          date={date}
          focused={focused}
          onDateChange={this.onDateChange}
          onFocusChange={this.onFocusChange}
        />
      </div>
    );
  }
}

export default DateSelector;
`

**Comment by janjanarnaldo** [comment]
Ugh the issue is just because of styling where overflow is hidden. What a nice cut right there, it looks so much like a bug. Thanks for accommodating though @majapw will close now.

**Comment by majapw** [comment]
Glad you figured it out!

**Comment by elmargasimov** [comment]
@majapw I am experiencing a similar issue, but the fix by using appendToBody gives me the following error:

```
Uncaught Invariant Violation: Portal.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.
```

Versions:
    "react": "^16.8.6",
    "react-dates": "^20.1.0",
    "react-dom": "^16.8.6",
    "react-with-direction": "^1.3.0",

**Comment by elmargasimov** [comment]
> @majapw I am experiencing a similar issue, but the fix by using appendToBody gives me the following error:
> 
> ```
> Uncaught Invariant Violation: Portal.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.
> ```
> Versions:
> "react": "^16.8.6",
> "react-dates": "^20.1.0",
> "react-dom": "^16.8.6",
> "react-with-direction": "^1.3.0",

@majapw Just bumping this up. Would you be able to give me some more direction into this issue?
