### ISSUE TITLE
How to uninstall is missing in docs

### ISSUE THREAD

**Issue by kushalmahajan** [airbnb/react-dates#1498]
Please specify the criteria for removing the package and all it's dependencies as well. 

Yarn remove doesn't works.

**Comment by ljharb** [comment]
That should be sufficient; for every package, npm uninstall (and yarn remove) should work.

If it doesn’t, you’ll have to elaborate more on what’s not working, and it might be something you need to file on yarn.

**Comment by jakesyl** [comment]
I think he's referring to the peer dependencies.

**Comment by ljharb** [comment]
That has to be done manually; that’s not something that’s typically documented. Separately, it might not be safe to remove peer deps, because other things might be using them - so a human always has to make that choice.

I think this is answered.
