### ISSUE TITLE
your documentation is terrible

### ISSUE THREAD

**Issue by harrythedev** [airbnb/react-dates#150]
can you please fix it?

**Comment by jpollard-cs** [comment]
![image](https://cloud.githubusercontent.com/assets/16087487/19784584/476d9cc0-9c64-11e6-9c14-fe8d8e6ddec3.png)

**Comment by ljharb** [comment]
@harrythedev negative comments are not helpful. #107 is one PR that's attempting to improve the documentation.

If you'd like to make a PR, that'd be great! If you can make a request politely by filing an issue, great! Otherwise, please keep your comments to yourself.
