### ISSUE TITLE
IE11 select date does not work

### ISSUE THREAD

**Issue by jonathanhotono** [airbnb/react-dates#1516]
**react-dates version**
e.g. react-dates@18.4.1

**Describe the bug**
Open in IE11: http://airbnb.io/react-dates/?selectedKind=DateRangePicker%20%28DRP%29&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

Select the start date & end date and it won't work.

Tried to look on the console and unfortunately no error message being displayed..

**Comment by marcos0x** [comment]
@ljharb @majapw I urgently need it to work in IE11!

**Comment by ljharb** [comment]
@marcos0x a PR to fix the bug, with a test, would be most appreciated, and will help accelerate the process :-)

**Comment by marcos0x** [comment]
@majapw has @ljharb said, a PR please! :)

**Comment by ljharb** [comment]
@marcos0x you misunderstood; i'm suggesting that if you need it, *you* can submit a PR. Both my and @majapw's time is very limited.

**Comment by marcos0x** [comment]
@ljharb @majapw https://github.com/airbnb/react-dates/pull/1524

**Comment by mccambridge** [comment]
Thank you! I've been spending hours on this bug

**Comment by pratap003** [comment]
I'm facing the same issue.

**Comment by majapw** [comment]
This should be fixed in v19.0.3, releasing now
