### ISSUE TITLE
Upgrading from v11.0.1: Method for adding classes, not overriding?

### ISSUE THREAD

**Issue by jobokai** [airbnb/react-dates#1517]
### Problem
In updating from version 11.0.1 to v18.4.1 I've noticed that our use of DayPicker no longer passes modifiers into cssClasses. We used the modifiers to add classes to indicate open, close, published, abnormal statuses to certain dates and used css psuedo elements to render notifications of these statuses. We passed modifiers to the DayPicker, but it looks like in the push for using withStyles (https://github.com/airbnb/react-dates/commit/e2c391d1eb878f48ad82d2a8c829b69d2e49e89f#diff-bfcddc5b7aece6519bd248744069628bL102) the code that added the custom modifier classes was removed.
### DayPicker
```
<DayPicker
hideKeyboardShortcutsPanel={true}
modifiers={modifiers}
numberOfMonths={1}
onDayClick={(day) =>
this.setState({ navigateTo: '/rd/menu/' + this.props.locationId + "/" + day.format('YYYY-MM-DD') })
}
onNextMonthClick={() => this.updateVisibleMonth(1)}
onPrevMonthClick={() => this.updateVisibleMonth(-1)} />
```
![image](https://user-images.githubusercontent.com/13200689/51755302-52501100-208c-11e9-8809-ac9f0a1cddf8.png)

### Modifiers

```buildModifiers() {
    // build modifiers for the month being displayed.
    let modifiers = {};

    for (let i = 1; i <= this.state.visibleMonth.daysInMonth(); i++) {
      const date = this.state.visibleMonth.clone().date(i);
      const day = this.getDay(date);
      let dayModifiers = null;

      if (!day) {
        continue;
      }

      dayModifiers = new Set([]);

      if (moment().isSame(date, 'day')) {
        dayModifiers.add('today');
      }
      dayModifiers.add(day.IsOpen ? 'open' : 'closed');
      if (day.IsPublished) {
        dayModifiers.add('published');
      }
      if (day.IsAbnormal) {
        dayModifiers.add('abnormal');
      }
      if (day.NeedsAttention) {
        dayModifiers.add('unpublished');
      }
      if (!day.IsPublished && !day.NeedsAttention) {
        dayModifiers.add('blocked-out-of-range');
      }

      modifiers[date.format('YYYY-MM-DD')] = dayModifiers;
    }
    return { [this.state.visibleMonth.format('YYYY-MM')]: modifiers };
  }
```
The above code would return a set of dates within the month with the modifiers.
![image](https://user-images.githubusercontent.com/13200689/51755666-4284fc80-208d-11e9-9ed7-d7084eb56687.png)

### Question
Is there a method that I should use instead of the modifiers, I'm not wanting to override the existing css or anything and that was the only information I could find in the documentation.

**Comment by ljharb** [comment]
That's a big jump - I'd suggest upgrading one major at a time, reading the changelog each time to understand the breaking changes.

**Comment by jobokai** [comment]
It looks like this issue is fairly similar to what I'm encountering: https://github.com/airbnb/react-dates/issues/1017

**Comment by jobokai** [comment]
I've changed things to use the renderDayContents method to render a div with the classes that used to be added via modifiers so I would have more control over the CalendarDay rendering. This seems to take care of everything.
