### ISSUE TITLE
How to assign the stardate/enddate to rangepicker?

### ISSUE THREAD

**Issue by sche0025** [airbnb/react-dates#1518]
Hi there:

I was trying to retrieve the stardate & enddate from the database and put it on rangepicker: 
![image](https://user-images.githubusercontent.com/35447735/51798948-c5b17880-226e-11e9-89a9-33fc94e2c009.png)
The dates above were also generated by react-date, 
However, this will trigger :
![image](https://user-images.githubusercontent.com/35447735/51798953-f7c2da80-226e-11e9-905b-0a471588a3f3.png)
So, could someone tell me how to fix it? thx !

**Comment by sche0025** [comment]
Hi, thank you for your reply:
![image](https://user-images.githubusercontent.com/35447735/51813299-a4ea3100-2309-11e9-9754-b1710e25826b.png)
this is the date in string format, what I want to do is to convert it into moment object, and assign this value to datepicker, so could you tell me how I can convert string to moment object?

**Comment by ljharb** [comment]
For that, see the moment docs: http://momentjs.com/

**Comment by sche0025** [comment]
@ljharb Thank you so much

**Comment by ljharb** [comment]
Closing since this seems answered; happy to reopen if not.
