### ISSUE TITLE
DayPickerSingleDateController - How to disable dates in the past

### ISSUE THREAD

**Issue by jamesrichards** [airbnb/react-dates#1519]
**react-dates version**
react-dates@18.4.1

**Describe the bug**
I'm using the DayPickerSingleDateController component and by default dates in the past are not disabled. [But on the storybook examples previous dates are disabled.](http://airbnb.io/react-dates/?selectedKind=DayPickerSingleDateController&selectedStory=single%20month&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) 

I've scoured through the props used on the storybook example in my dev tools and I can't see what props are causing the component to have dates in the past disabled.

**Source code (including props configuration)**
[Here's a clean example on CodeSandbox](https://codesandbox.io/s/mzo1k0j459?module=%2FDatePicker.js)

**Desktop (please complete the following information):**
 - OS: OSX High S
 - Browser: Chrome 
 - Version: 71.0.3578.98 

**Is the issue reproducible in Storybook?**
No, it seems to work how I'd want it to.

Thanks in advance for any support on this one. I'm sure its a small thing and probably something I've overlooked. 🙏🏻

**Comment by npenalopez** [comment]
same problem here, have you solved this issue @jamesrichards ?

**Comment by jamesrichards** [comment]
@npenalopez Afraid not, I've sort of parked this feature of the work I'm doing in hopes someone, or a maintainer can point me in the right direction. I'm not even sure if it's a bug, or just a lack of required prop.

Any help would be appreciated 😬

**Comment by jamesrichards** [comment]
Bump. @majapw Hope you don't mind the direct mention. Would you be willing to shed some light on this one please? Not sure if this is a bug, or intentional behaviour. If it's the latter, what props should I be providing in order to disable dates in the past?

Thank you

**Comment by ljharb** [comment]
This prop: https://github.com/airbnb/react-dates/blob/master/src/components/DayPickerSingleDateController.jsx#L43 should let you define whether past dates are allowed or not, i think?

**Comment by jamesrichards** [comment]
Excellent, thanks for sharing this. I didn't realise you had to explicitly specify this prop for the SingleDateController. Works as expected now.

Thank you

**Comment by AyabongaQwabi** [comment]
You guys are very vague, what is this prop?
if you mean this one then I don't understand. Outside which range?
is there a prop to specify the range?

isOutsideRange: () => false

**Comment by ljharb** [comment]
Outside the range of dates you consider valid for your date picker. The prop is named “isOutsideRange”, and is a function.
