### ISSUE TITLE
SingleDatePicker auto closes on hover on today when withPortal={true}

### ISSUE THREAD

**Issue by nijona** [airbnb/react-dates#1520]
**react-dates version**
react-dates@18.4.1

**Describe the bug**
SingleDatePicker auto closes on hover on today when withPortal={true}
onDateChange doesn't get called

**Source code (including props configuration)**
```
import React from 'react';
import { SingleDatePicker } from 'react-dates'
import 'react-dates/lib/css/_datepicker.css';

class Test extends React.Component {
  constructor() {
    super();
    
    this.state = {
      date: null,
      focused: false
    };
  }
  render() {
    console.log(this.state)
    return (
       <SingleDatePicker
        id="date_input"
        withPortal
        autoFocus
        numberOfMonths={1}        
        date={this.state.date} 
        onDateChange={date => { 
            console.log('date changes')
            return this.setState({ date })
         }}
        focused={this.state.focused}
        onFocusChange={({ focused }) => {
            console.log('onFocusChange changes')
            return this.setState({ focused })
         }} />
    )
    
  }
}

export default Test;
```

**Is the issue reproducible in Storybook?**
yes
[http://airbnb.io/react-dates/?selectedKind=SDP%20-%20Calendar%20Props&selectedStory=horizontal%20with%20portal&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel](url)

**Additional context**
[https://stackblitz.com/edit/react-5z8pun?file=Hello.js](url)

**Comment by danedavid** [comment]
Can I work on this issue?

**Comment by danedavid** [comment]
@ljharb Looks like this issue has been fixed, maybe unknowingly, in https://github.com/airbnb/react-dates/pull/1533. The issue no longer persists.

**Comment by ljharb** [comment]
Whoops, thanks for catching that!

Fixed in #1533.

**Comment by Sravan501** [comment]
With in modal SingleDatePicker auto closes on hover on today when withPortal={true}

**Comment by mmarkelov** [comment]
@ghost could you provide some representation. Just checked [storybook](https://airbnb.io/react-dates/?path=/story/sdp-calendar-props--horizontal-with-portal) and it's ok
