### ISSUE TITLE
SingleDatePicker auto closes on clicking anywhere when appendToBody={true}

### ISSUE THREAD

**Issue by alvaro-cuesta** [airbnb/react-dates#1522]
**react-dates version**
react-dates@18.4.1 (18.4.0 is fine)

**Describe the bug**
When `SingleDatePicker` has `appendToBody={true}`, clicking anywhere (including a date) closes the calendar (and no date is selected).

If you click any of the day names ("Mo", "Tu", etc.) the calendar works as expected from then on.

**Source code (including props configuration)**

```jsx
const Datepicker = props => {
  const {
    date,
    id,
    placeholder,
    isDisabled,
    isFocused,
    onDateChange,
    onFocusChange,
  } = props
  return (
    <SingleDatePicker
      date={date}
      onDateChange={onDateChange}
      focused={isFocused}
      onFocusChange={onFocusChange}
      id={id}
      placeholder={placeholder}
      disabled={isDisabled}
      numberOfMonths={1}
      verticalSpacing={11}
      hideKeyboardShortcutsPanel
      customInputIcon={<Icon name="calendar" />}
      navPrev={<Icon name="arrow-left" />}
      navNext={<Icon name="arrow-right" />}
      inputIconPosition="after"
      isOutsideRange={() => false}
      appendToBody={true}
    />
  )
}
```

Parent component handlers:

```jsx
<Datepicker
  date={values.date}  // set from `setFieldValue`
  onFocusChange={({ focused }) => {
    if (!focused) {
      setFieldTouched('date', true, true)
    }

    setDatePickerFocused(focused)
  }}
  onDateChange={date => {
    setFieldValue('date', date, true)
  }}
  id="event_date"
  isFocused={datePickerFocused} // set from `setDatePickerFocused`
  isDisabled={false}
/>
```

**Desktop:**
 - OS: Mac OS Mojave Version 10.14 (18A391)
 - Browser: Chrome Version 71.0.3578.98 (Official Build) (64-bit)

But happens anywhere I tried.

**Is the issue reproducible in Storybook?**

Yes

https://airbnb.io/react-dates/?selectedKind=SDP%20-%20Calendar%20Props&selectedStory=appended%20to%20body&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Additional context**

Happens since v18.4.1.

**Comment by majapw** [comment]
@monokrome @TaeKimJR can you take a look at this? It looks like it is related to y'all's tabbing change.
