### ISSUE TITLE
DateRangePicker selecting dates not working in IE11

### ISSUE THREAD

**Issue by devans-k4** [airbnb/react-dates#1534]
react-dates@18.3.1

When trying to pick a start and end date in the DRP those dates do not populate  in the start and end date fields. It seems to just revert back to nothing ever being selected and I'm not getting any sort of error. I've also noticed that this same problem is happening when I try in Storybook.

<DateRangePicker
          startDate = {this.calcDate('startDate', user)}
          startDateId = "startDateId"
          endDate = {this.calcDate('endDate', user)}
          endDateId = "endDateId"
          onDatesChange = {({startDate, endDate}) => this.onChangeDates(startDate, endDate)}
          focusedInput = {focusedInput}
          onFocusChange = {focusedInput => this.setState({ focusedInput })}
          displayFormat = "MMM D YYYY"
          noBorder = {true}
          showDefaultInputIcon = {true}
          isOutsideRange = {() => false}
         numberOfMonths = {1}
/>

calcDate(dateType, user) {
        if(this.state[dateType]){
            return new moment(this.state[dateType])
        }
        if(user.away && user.statusDates[dateType]){
            if (dateType === 'startDate') {
                this.setState({
                    startDate: new moment(user.statusDates[dateType])
                });
            } else {
                this.setState({
                    endDate: new moment(user.statusDates[dateType])
                });
            }
            return new moment(user.statusDates[dateType]);
        }
        if(dateType === 'startDate'){
            this.setState({
                startDate: new moment()
            });
            return new moment();
        }
        return null;
    }

This works fine in Chrome and Safari just having problems in IE11

Storybook url also not working in IE11
https://airbnb.io/react-dates/?selectedKind=DateRangePicker%20%28DRP%29&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by devans-k4** [comment]
This is actually happening be clicking anywhere inside the date picker component. It just closes the calendar window.

**Comment by majapw** [comment]
This should be fixed in v19.0.3.

**Comment by Laawe** [comment]
@majapw when that will happen? I've got version ^20.0.0 and having the same scenario (don't know if bug or something)
