### ISSUE TITLE
Custom Arrow Icon does not work if small={true}

### ISSUE THREAD

**Issue by tlaak** [airbnb/react-dates#1537]
**react-dates version**
e.g. react-dates@19.0.1

**Describe the bug**
The `customArrowIcon` property is ignored when property `small` is set to `true`

**Source code (including props configuration)**
```
<DateRangePicker
  startDate={this.state.startDate}
  startDateId="your_unique_start_date_id"
  endDate={this.state.endDate}
  endDateId="your_unique_end_date_id"
  onDatesChange={({ startDate, endDate }) => this.setState({ startDate, endDate })}
  focusedInput={this.state.focusedInput}
  onFocusChange={focusedInput => this.setState({ focusedInput })}
  small={true}
  customArrowIcon={<span>I will not appear</span>}
/>
```

**Comment by ljharb** [comment]
This seems to be very intentional: https://github.com/airbnb/react-dates/blob/master/src/components/DateRangePickerInput.jsx#L176

I might expect `customArrowIcon` to be disallowed when `small` is `true`, however, to enforce that.
