### ISSUE TITLE
Buttons in SDP is in wrong place

### ISSUE THREAD

**Issue by ReTWi** [airbnb/react-dates#1554]
**react-dates version**
"react-dates": "^19.0.3",

**Describe the bug**
[Buttons](https://i.imgur.com/oNEbysf.png) is not in correct place.

**Source code (including props configuration)**
   
```
   <SingleDatePicker
        orientation='vertical'
        date={moment.utc()}
        onDateChange={date => {}}
        focused={true}
        onFocusChange={() => {}}
        id='banDatePicker'
      />
```

**Screenshots/Gifs**
https://i.imgur.com/oNEbysf.png

**Desktop**
 - OS: Windows
 - BrowserChrome
 - Version 72.0.3626.109

**Is the issue reproducible in Storybook?**
Nope

**Comment by jamstooks** [comment]
@ReTWi - any luck resolving this?

I'm seeing the navigation buttons wrapping too: https://codesandbox.io/s/delicate-voice-pe1qy

**Comment by ReTWi** [comment]
@jamstooks i use now react-datepicker, so idn

**Comment by mmarkelov** [comment]
@jamstooks i suppose something wrong with computing styles, cause i can't find this lines:
```css
html {
  box-sizing: border-box;
}

* {
  box-sizing: inherit;
}
```
Here is working sandbox:
[![Edit epic-lewin-q4wiz](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/epic-lewin-q4wiz?fontsize=14)
I'll take a look what can be wrong with it

**Comment by jamstooks** [comment]
Thanks, @mmarkelov! That looks like it. I missed:

> Note: This component assumes `box-sizing: border-box` is set globally in your page's CSS.

in [the docs](https://github.com/airbnb/react-dates#initialize).
