### ISSUE TITLE
startDate UI is broken if startDate time is not 12:00:00

### ISSUE THREAD

**Issue by thecotne** [airbnb/react-dates#1599]
startDate UI is broken even on airbnb.com (works correctly in examples at http://airbnb.io/react-dates/)

this is because of this stuff  https://github.com/airbnb/react-dates/pull/310

<img width="974" alt="Screenshot 2019-03-27 13 23 19" src="https://user-images.githubusercontent.com/1606993/55064611-b8104780-5093-11e9-9e31-947192e7ca88.png">

**Comment by iluhakhurtin** [comment]
Faced the same issue. Having updated from version 12.2.2 to the latest 20.1.0 found that my start date is not highlighted, but end date works well. I found that the latest version that used to work well is 19.0.3. Version 19.0.4 has a change that does not highlight a start date. Also I found out that start date cell in the date picker does not have class .CalendarDay__selected that is why it is not highlighted. However, it has class .CalendarDay__selected_start so if you want to use a version higher 19.0.3 add the class in a root.css or another css file you have:

.CalendarDay__selected_start,
.CalendarDay__selected_end {
    background: #00a699 !important;
    border: 1px double #00a699 !important;
    color: #fff;
}

**Comment by thecotne** [comment]
I have hardcoded 12:00:00 on startDates and it works for now

But it's a shame airbnb did not notice how this library and airbnb.com itself is broken...

**Comment by thecotne** [comment]
any updates on this?

**Comment by thecotne** [comment]
this is still an issue on airbnb itself...

**Comment by lencioni** [comment]
Fixed by #1710
