### ISSUE TITLE
Add class at hovered end date

### ISSUE THREAD

**Issue by RobertBierbauer** [airbnb/react-dates#1603]
After defining a start date, while choosing an end date, I would find it useful if there would be set a class at the currently hovered (but not selected) end date. Currently after the selection of an end date there is set a class `CalendarDay__selected_end` which can be targeted using CSS, but on hover only the class `CalendarDay__hovered_span` is set but no `CalendarDay__hovered_end`.

I am using the `<DateRangePicker/>` and Version 20.1.0

**Comment by krissalvador27** [comment]
@RobertBierbauer would `CalendarDay__selected_end:hover` work for you?

**Comment by RobertBierbauer** [comment]
@krissalvador27 no, actually that's my problem. `CalendarDay__selected_end` is only set after the end date has been selected, but not when hovering with the mouse while choosing the end date. In this case only `CalendarDay__hovered_span` is set, which is also set on all days between the start date and the currently hovered end date, and therefore can't be used in my case.

**Comment by krissalvador27** [comment]
Ah I see! Would doing `CalendarDay__hovered_span:hover` work? It would target the potential end date that you're hovering on and shouldn't affect the other CalendarDay__hovered_span's inbetween that hovered date and the start date.

**Comment by RobertBierbauer** [comment]
Thank you, that works pretty well. I guess, I couldn't see the forest for the trees :)
I will close this issue
