### ISSUE TITLE
Can't customize font family

### ISSUE THREAD

**Issue by yuribett** [airbnb/react-dates#1604]
I've been using react-dates and material-ui, so no css files.

The problem is I cannot replace the font family, it is getting Times as default from my computer.

The approach I am using to override the styles is:
https://github.com/airbnb/react-dates#theming

But I don't see fontFamily in the defaults here: https://github.com/airbnb/react-dates/blob/master/src/theme/DefaultTheme.js

How can I customize them?

**Comment by guiaramos** [comment]
@yuribett did you get the solution for this issue?
