### ISSUE TITLE
Jest tests failing with error TypeError _moment.default.localeData is not a function

### ISSUE THREAD

**Issue by mkelley33** [airbnb/react-dates#1612]
**react-dates version**
e.g. react-dates@18.3.1

**Describe the bug**
I've set up a jest test to render my component that is using a react-dates datepicker, and I've 
imported `'react-dates/initialize'`, but my test fails with the error:

`TypeError: _moment.default.localeData is not a function`

**Source code (including props configuration)**
```
<DateRangePicker
  startDate={this.state.startDate}
  startDateId="your_unique_start_date_id"
  endDate={this.state.endDate}
  endDateId="your_unique_end_date_id"
  onDatesChange={({ startDate, endDate }) => this.setState({ startDate, endDate })}
  focusedInput={this.state.focusedInput}
  onFocusChange={focusedInput => this.setState({ focusedInput })}
/>
```
If you have custom methods that you are passing into a `react-dates` component, e.g. `onDatesChange`, `onFocusChange`, `renderMonth`, `isDayBlocked`, etc., please include the source for those as well.

**Screenshots/Gifs**
If applicable, add screenshots or gifs to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS 10.13.6
 - Browser [e.g. chrome, safari] Chrome 
 - Version [e.g. 22] 72.0.3626.121 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Is the issue reproducible in Storybook?**
The issue is not reproducible in storybook.  This only happens in test.

**Additional context**

**Comment by ljharb** [comment]
Have you perhaps mocked out moment in your jest config?

**Comment by aviyadeveloper** [comment]
> Have you perhaps mocked out moment in your jest config?

I have the same issue and indeed a mocked out version of moment running with the test. How should I solve that? @ljharb

**Comment by ljharb** [comment]
@aviyadeveloper no; because your mocked default export doesn’t do `Object.assign(func, moment)`, it won’t.

**Comment by YM-KA** [comment]
Hi @ljharb ! I am having the exact same problem. Can you please elaborate on your answer? 
Simply adding <code>Object.assign(func, moment)</code> inside the default export does not do the trick. Maybe I am just stupid? 😉

**Comment by ljharb** [comment]
@YM-KA what does your mock look like?

**Comment by YM-KA** [comment]
Hi @ljharb ! I managed to get it to work. My mock looked like this:

```
const moment = require.requireActual('moment')
export default (timestamp = 0) => {
  return moment(timestamp)
}
```
I changed it into
```
const moment = require.requireActual('moment')
const myMoment = (timestamp = 0) => {
  return moment(timestamp)
}
Object.assign(myMoment, moment)
export default myMoment
```
😃

**Comment by ljharb** [comment]
Closing, but will be happy to reopen if @mkelley33 can reply with clarification.
