### ISSUE TITLE
Update Readme with type of func required for initialVisibleMonth

### ISSUE THREAD

**Issue by EdwardGoomba** [airbnb/react-dates#1619]
Readme examples provide proptypes for initialVisible month as PropTypes.func with no indication as to what type of function is being expected.

Please update with an example: ie: `initialVisibleMonth={()=>moment()}`

**Comment by rawpixel-vincent** [comment]
Yes that would be nice, I noticed that in the example wrapper the propTypes is MomentObject, but when you pass a momentObject you got an error `...is not a function`..

**Comment by AlokTakshak** [comment]
@ljharb 
#1652
