### ISSUE TITLE
reopenPickerOnClearDates - Signature TypeScript doesn't match actual props 

### ISSUE THREAD

**Issue by nzamarreno** [airbnb/react-dates#1629]
Hello, I use `react-dates@20.1.0` and I notice the following issue:

The TypeScript signature of the `SingleDatePicker` component contains a `reopenPickerOnClearDates` props but the actual component has `reopenPickerOnClearDate` (without `s`).

Below my actual code:
```javascript
<SingleDatePicker
    date={this.date}
    onDateChange={this.handleDateChange}
    focused={this.focused}
    onFocusChange={this.handleFocusChange}
    id="Date"
    showClearDate
    reopenPickerOnClearDates
 />
```

Thanks for your help ;)

**Comment by ljharb** [comment]
This repo has no type definitions; please file an issue in DefinitelyTyped instead.
