### ISSUE TITLE
How to prevent triggering renderCalendarInfo on mouseover/mouseout of day?

### ISSUE THREAD

**Issue by xavier-ga** [airbnb/react-dates#1630]
I am using DayPickerRangeController and passing renderCalendarInfo to show more buttons/info.

I found that renderCalendarInfo is triggering on mouseover and mouseout over a day in the calendar. Is there a way to prevent this?

**Comment by xavier-ga** [comment]
@majapw Could you please help me?

**Comment by pedroapfilho** [comment]
+1

**Comment by pedroapfilho** [comment]
#1359 #
