### ISSUE TITLE
props minDate and maxDate to block navigation doesn´t work on SingleDatePicker

### ISSUE THREAD

**Issue by darcusfenix** [airbnb/react-dates#1632]
react-dates@20.1.0

I´m adding a minDate and maxDate to block the navigation on SingleDatePicker but it doesn´t work. 

Anybody knows how can i block the navigation with the same range of isOutsideRange using SingleDatePicker

**Comment by s-stefanov** [comment]
I have the same problem. #1331 is implemented only for DayPickerRangeController.
Also looks like we are not the only one asking https://github.com/airbnb/react-dates/issues/692#issuecomment-500952408

**Comment by GHMT** [comment]
Why is this closed when it is not in a release? I can see the commit in master, but not in the latest v21.8.0.

**Comment by ljharb** [comment]
Issues are pretty much always closed everywhere on GitHub when the fix lands, unrelated to whether it’s released.

**Comment by MadeleineLeadbetter** [comment]
Hi, my team would really love to be able to use this feature in our current work.  Is there an estimated time on when it will be included in a release?

**Comment by churchill1973** [comment]
> Hi, my team would really love to be able to use this feature in our current work. Is there an estimated time on when it will be included in a release?

I'am not sure for this componenet, but for DateRangePickerWrapper  this worked `isOutsideRange= {() => false}`

**Comment by federicogomez-estudiocactus** [comment]
@ljharb Hello, are you guys planning on creating another release that includes this props? We're using this package but we find ourselves in the need to have a min date for the single date picker component, I've tried forking/patching and copying code but so far I haven't been able to make it work

**Comment by RodrigoTomeES** [comment]
Hi, @ljharb could you release this change? please, the last release It's from 3 years ago 😅

I made this like a workaround. In your package.json:

```json
{
  "scripts": {
    "instal": "cd ./node_modules/react-dates && npm install && npm run build && cd ../../../"
  }
  "dependencies": {
    "react-dates": "git+https://github.com/react-dates/react-dates.git#b7bad38dcff024d374ee98f972b55b3de9e61289",
  }
}
```
