### ISSUE TITLE
How to translate this damn calendar into Russian

### ISSUE THREAD

**Issue by sxavi** [airbnb/react-dates#1636]
как перевести этот календарь на русский язык, потратил уже кучу времени и все в пустую, неужели нельзя создать пропсы куда бы я передавал массив с названиями дней недели и месяцами

**Comment by ljharb** [comment]
from google translate:
> how to translate this calendar into Russian, has already spent a lot of time and everything is empty, is it really impossible to create props where I would pass an array with the names of the days of the week and months

Duplicate of #327, i think?

**Comment by saschb2b** [comment]
Setting it via `moment.locale()` doesn't work every time. For me just importing the wanted language was enough. For Russian `import 'moment/locale/ru';`

**Comment by ozil07** [comment]
Ты лучший друг!!!!!!

**Comment by ozil07** [comment]
> Setting it via `moment.locale()` doesn't work every time. For me just importing the wanted language was enough. For Russian `import 'moment/locale/ru';`

Ты лучший друг!!!!!!

**Comment by mr-devboy** [comment]
> Setting it via `moment.locale()` doesn't work every time. For me just importing the wanted language was enough. For Russian `import 'moment/locale/ru';`

Thank you

**Comment by ghost** [comment]
> Setting it via `moment.locale()` doesn't work every time. For me just importing the wanted language was enough. For Russian `import 'moment/locale/ru';`

THANK YOU BOSS

**Comment by Fuur** [comment]
> Setting it via `moment.locale()` doesn't work every time. For me just importing the wanted language was enough. For Russian `import 'moment/locale/ru';`

Thank you very much 🫶🏼
