### ISSUE TITLE
Install dependencies, correct version number

### ISSUE THREAD

**Issue by Cr0cky** [airbnb/react-dates#1646]
Exactly where and how do run this code?

`(
  export PKG=react-dates;
  npm info "$PKG" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g; s/ *//g' | xargs npm install --save "$PKG"
)`

I tried in my command prompt, but that is obviously not the right place.

**Comment by ljharb** [comment]
That is indeed the right place, but that command doesn’t work on windows.

You can use `npx install-peerdeps react-dates` on npm 5+ as well, on any platform.

**Comment by reZach** [comment]
Thanks @ljharb - can this comment be placed on the readme so it's easier for others?
