### ISSUE TITLE
Your docs are useless

### ISSUE THREAD

**Issue by alansutherland** [airbnb/react-dates#1647]
I can't get this running at all, the styles are not imported, seriously need to make your readme better

this is what I see, clearly no css imported

<img width="361" alt="Screenshot 2019-05-22 at 13 02 12" src="https://user-images.githubusercontent.com/4670058/58146616-dd839100-7c91-11e9-8ae9-a2da6bcc3a25.png">

tried:

```import 'react-dates/initialize';
import { DateRangePicker } from 'react-dates';
import 'react-dates/lib/css/_datepicker.css';

<DateRangePicker
                startDate={this.state.startDate} // momentPropTypes.momentObj or null,
                startDateId="your_unique_start_date_id" // PropTypes.string.isRequired,
                endDate={this.state.endDate} // momentPropTypes.momentObj or null,
                endDateId="your_unique_end_date_id" // PropTypes.string.isRequired,
                onDatesChange={({ startDate, endDate }) => this.setState({ startDate, endDate })} // PropTypes.func.isRequired,
                focusedInput={this.state.focusedInput} // PropTypes.oneOf([START_DATE, END_DATE]) or null,
                onFocusChange={focusedInput => this.setState({ focusedInput })} // PropTypes.func.isRequired,
              />```

**Comment by alansutherland** [comment]
I have to add using yarn since my project already uses it extensively and running the npm commands suggested seriously mess up my project, so I used:

`yarn add react-dates -P`

**Comment by ljharb** [comment]
This issue title is hostile and unproductive.

Using yarn - a decidedly non-default choice - means you have chosen to take on the burden of knowing that you can’t ever run npm commands without manually translating them to yarn commands. Glad you figured that one out.

Regarding the styles, please see https://github.com/airbnb/react-dates#initialize.

**Comment by alansutherland** [comment]
@ljharb Yes sorry my title was unproductive, that was due to frustration

yarn is not "a decidedly non-default choice" it's a very common choice. 

I have followed your docs and included initialize, it doesn't help

**Comment by ljharb** [comment]
It’s far less than 50% usage, and either way it doesn’t ship with node; npm is the default until it doesn’t ship with node, so everything else incurs the obligation i mentioned.

If you can provide more concrete repro steps, including code, we can certainly try to look into it.
