### ISSUE TITLE
Replace 'react-addons-shallow-compare' with first party implementation

### ISSUE THREAD

**Issue by WillSelway** [airbnb/react-dates#1671]
Instead of waiting for react 18/dropping support for older react versions to fix the issue with 'react-addons-shallow-compare', could it be replaced by a first party implementation based of the original package instead?

The implementation is actually pretty small -

```
function shallowCompare(instance, nextProps, nextState) {
	return (
		!shallowEqual(instance.props, nextProps) ||
		!shallowEqual(instance.state, nextState)
	);
}

function shallowEqual(objA, objB) {
	if (is(objA, objB)) {
		return true;
	}

	if (typeof objA !== 'object' || objA === null || typeof objB !== 'object' || objB === null) {
		return false;
	}

	var keysA = Object.keys(objA);
	var keysB = Object.keys(objB);

	if (keysA.length !== keysB.length) {
		return false;
	}

	for (var i = 0; i < keysA.length; i++) {
		if (!hasOwnProperty.call(objB, keysA[i]) || !is(objA[keysA[i]], objB[keysA[i]])) {
			return false;
		}
	}

	return true;
}

function is(x, y) {
	if (x === y) {
		// Steps 1-5, 7-10
		// Steps 6.b-6.e: +0 != -0
		// Added the nonzero y check to make Flow happy, but it is redundant
		return x !== 0 || y !== 0 || 1 / x === 1 / y;
	} else {
		// Step 6.a: NaN == NaN
		return x !== x && y !== y;
	}
}
```

The real issue with 'react-addons-shallow-compare' is its outdated dependency pointing to and old version of 'fbjs' which in turn points to a very old version of 'core-js' that NPM/yarn print vulnerability warnings for.

I am happy to submit a PR to do this but wanted to check with the authors first in case there is some reason I am missing to not do this.

**Comment by ljharb** [comment]
It already exists in enzyme, fwiw, but i'm not sure if the peer deps would make that practical.

Is there no chance `react-addons-shallow-compare` could be updated instead, to not use fbjs?

**Comment by WillSelway** [comment]
https://github.com/airbnb/react-dates/issues/438

This issue thread says its apparently been unsupported since 2017, so it looks like bad news on that front.

**Comment by ljharb** [comment]
I've extracted enzyme's implementation to https://npmjs.com/enzyme-shallow-equal, and updated react-dates to use it.

**Comment by WillSelway** [comment]
Thank you very much 🙏
