### ISSUE TITLE
DateRangePicker Error in IE11: "Object.keys: argument is not an Object "

### ISSUE THREAD

**Issue by juan400** [airbnb/react-dates#1675]
**react-dates version**
e.g. react-dates@20.2.0

**Describe the bug**
I'm building a app with React.Js, I'd created a new component with a date picker on it and in IE it is crashing. At first try I got an error that I could skip using arbnb-shims (before this I tried with a polifill without luck). Now I'm stuck and with non clue how to solve the issue, I'm getting an error that said "Object.keys: argument is not an Object"

![image](https://user-images.githubusercontent.com/6495795/59067918-d6a77180-8880-11e9-804a-f6441834c502.png)

**Source code (including props configuration)**
![image](https://user-images.githubusercontent.com/6495795/59067839-9ba53e00-8880-11e9-9aaf-799732a9416e.png)

```
<DateRangePicker
                    orientation={"horizontal"}
                    anchorDirection={"left"}
                    isDayBlocked={day => {
                        const monthYearDate = moment(day).format("MMYYYY");
                        return !availableMonths.some((monthYear: string) => monthYear === monthYearDate);
                    }}
                    small={true}
                    numberOfMonths={1}
                    daySize={35}
                    startDate={this.state.startDate}
                    startDateId="startDate"
                    endDate={this.state.endDate}
                    endDateId="endDate"
                    focusedInput={this.state.focusedInput}
                    onFocusChange={this.onFocusChange}
                    onDatesChange={this.onDatesChange}
                    readOnly={!!isMobile.any()}
                    showClearDates={true}
                    required={true}
                    displayFormat={"MM/DD/YYYY"}
                    initialVisibleMonth={(): moment.Moment => (availableMonths[0] ? moment(availableMonths[0], "MMYYYY") : undefined)}
                />

**Desktop (please complete the following information):**
 - OS: [e.g. Win10]
 - Browser [e.g. IE11]

**Comment by ljharb** [comment]
Certainly you need to use `airbnb-browser-shims` or the equivalent. What version of babel are you using?

**Comment by juan400** [comment]
Hi Jordan,
![image](https://user-images.githubusercontent.com/6495795/59110267-bb824380-890c-11e9-8f22-f306ded2341e.png)

**Comment by juan400** [comment]
Jordan, 
I found what I missed to add on my component

import 'airbnb-js-shims/target/es2015';
import 'airbnb-browser-shims/browser-only';

Thanks and sorry to bothering you with a mistake on my side.
