### ISSUE TITLE
SingleDatePicker doesn't work for touch devices in Microsoft Edge

### ISSUE THREAD

**Issue by ViktoriyaSavkina** [airbnb/react-dates#169]
Try to view http://airbnb.io/react-dates in Edge. Clicking on input field doesn't do anything, datepicker view doesn't show up

**Comment by ViktoriyaSavkina** [comment]
@majapw is there a reason to disable date input for touch devices? I tried removing disabled attribute in dev tools and everything works fine. Would you guys accept a PR to remove disabled attribute for touch devices?

**Comment by moonboots** [comment]
I'm able to reproduce on the SingeDatePicker and DatePickerInput (when clicking on "Start Date" or "End Date", DayPicker still works). @majapw, do we still need special handling for touch devices. It looks like we used to check `isTouchDevice` to conditionally `React.initializeTouchEvents(true)`, but it looks [that method was removed](https://github.com/facebook/react/issues/2468).

**Comment by ViktoriyaSavkina** [comment]
@moonboots thanks for looking into this! submitted PR to remove the check https://github.com/airbnb/react-dates/pull/174
