### ISSUE TITLE
SingleDatePicker rerendering due to state.dayPickerContainerStyles

### ISSUE THREAD

**Issue by aaronbabaron** [airbnb/react-dates#1699]
**react-dates version**
20.2.4

**Describe the bug**

I'm trying to make rendering/rerendering of two separate singledatepickers faster, but it seems like dayPickerContainerStyles on the state is causing it to rerender regardless of what's going on.

![Screen Shot 2019-06-20 at 1 06 44 PM](https://user-images.githubusercontent.com/15972357/59878114-52fb8380-935c-11e9-9f0f-dae408721c22.png)

```
          <SingleDatePicker
            customInputIcon={
              <SomeIcon />
            }
            inputIconPosition="after"
            date={date}
            focused={this.state.isEndDateFocused}
            id="some_end_date_id"
            onDateChange={(date: Moment | null) => {
              //something here
            }}
            onFocusChange={this.setFocus.bind(this, 'END')}
            placeholder="End Date"
          />
```

**Comment by mmarkelov** [comment]
@aaronbabaron there is one possible not the best updating of state, that I see:
https://github.com/airbnb/react-dates/blob/121fc443631efaea3e2dbee80a5695c0666599ea/src/components/SingleDatePicker.jsx#L305-L309
This function run on resize event and when focused is changing. So my thoughts not to run setState in this function when **dayPickerContainerStyles** is empty. I can do PR, maybe it will help
