### ISSUE TITLE
DayPickerRangeController not working as expected

### ISSUE THREAD

**Issue by aibrahim3546** [airbnb/react-dates#1700]
**react-dates version**
"react-dates": "^20.2.4"

**Describe the bug**
DayPickerRangeController only showing one calendar and the date cannot be selected

**Source code (including props configuration)**
Here is the source code
```
import React from 'react';
import { Link } from 'react-router-dom';
import 'react-dates/initialize';
import 'react-dates/lib/css/_datepicker.css';
import { DayPickerRangeController } from 'react-dates';


class HomePage extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      startDate: null,
      endDate: null,
      focusedInput: 'startDate',
    };
  }

  handleDateChange = () => {
    console.log('do something here');
  }

  render() {
    return (
      <div>
        <DayPickerRangeController
          startDate={this.state.startDate}
          endDate={this.state.endDate}
          onDatesChange={({ startDate, endDate }) =>
            this.handleDateChange(startDate, endDate)
          }
          focusedInput={this.state.focusedInput}
          onFocusChange={focusedInput =>
            this.setState({ focusedInput: focusedInput || 'startDate' })
          }
        />
      </div>
    );
  }
}

export default HomePage;
```

**Screenshots/Gifs**
![Screenshot 2019-06-21 at 5 39 05 PM](https://user-images.githubusercontent.com/31366174/59914238-8e757b00-944c-11e9-9b40-bafab15f781e.png)

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser chrome
 - Version latest version

**Is the issue reproducible in Storybook?**
this issue is not reproducible in storybook.
https://airbnb.io/react-dates/?path=/story/daypickerrangecontroller--default

**Comment by mmarkelov** [comment]
@aibrahim3546 this is working as expected - you should add **numberOfMonths** property to 2 for displaying two calendars, also there is no problem with **onDatesChange** 
[![Edit sleepy-hellman-dvypu](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sleepy-hellman-dvypu?fontsize=14)

**Comment by aibrahim3546** [comment]
Hey @mmarkelov thanks for the solution it works perfectly. Look like I have been missing the `numberOfMonths` props and I also forget to `setState` for the `startDate` and `endDate`
