### ISSUE TITLE
RangePicker: start date of the range not colored correctly

### ISSUE THREAD

**Issue by ktrungha** [airbnb/react-dates#1703]
I have a date range picker with default range.
When the picker is first opened, the start date of the range is not colored correctly.
Only the end date of the range has the darker color.

The start date is colored correctly if I manually pick the range after the picker opens.

I am not using css to style this picker. I use theming.

In the photo, you can see that the 24th day is not colored correctly.

![SelectedStart](https://user-images.githubusercontent.com/6115540/59986365-c0f7c180-9660-11e9-99d2-12e235b9d83f.png)

**Comment by mmarkelov** [comment]
@ktrungha your code will be helpful

**Comment by teagueash** [comment]
This issue has been the default behavior for a while now. Just look at their storybook example:
[http://airbnb.io/react-dates/?path=/story/drp-input-props--default](url)

Source code here: [https://github.com/airbnb/react-dates/blob/master/examples/DateRangePickerWrapper.jsx](url)

**Comment by ktrungha** [comment]
I look at the html element. It looks like the css class 'selected' is applied to the end date but not the start date. That's why the end date is colored  with the darker color but not the start data.

**Comment by ktrungha** [comment]
Looks like this is a bug reported here https://github.com/airbnb/react-dates/issues/1599

**Comment by lencioni** [comment]
Fixed by #1710
