### ISSUE TITLE
How can I re-render/re-fresh the calendar ?!!

### ISSUE THREAD

**Issue by smrsan76** [airbnb/react-dates#1716]
**react-dates version**
react-dates@^20.2.5

**Describe the bug**
I want to find a way to re-render it after each time of manipulation. It could just re-render the calendar after clicking on "go to next/prev month" buttons!

**Source code (including props configuration)**
```jsx
import React, { Component } from "react";
import { DayPicker } from "react-dates";
import JMoment from "moment-jalaali";
//...

class App extends Component {
  state = {
    isShamsi: false
  };

  toggleShamsi = () => {
    const { isShamsi } = this.state;
    this.setState({ isShamsi: !isShamsi });
    /****** The Problem is Here ******/
    /****** It doesn't Re-Render Completely ******/
  };

  renderDayContents = moment => {
    const { isShamsi } = this.state;
    if (!isShamsi) return moment.format("D");
    return JMoment(moment).format("jD");
  };

  renderMonthText = moment => {
    const { isShamsi } = this.state;
    if (!isShamsi) return moment.format("MMMM YYYY");
    return JMoment(moment).format("jMMMM jYYYY");
  };

  render() {
    const { isShamsi } = this.state;

    return (
      <>
        <span>Use Shamsi:</span>
        <input type="checkbox"
               defaultChecked={isShamsi}
               value={isShamsi}
               onClick={this.toggleShamsi}
        />
        <br />
        <br />
        <DayPicker
          isRTL
          firstDayOfWeek={6}
          numberOfMonths={1}
          renderDayContents={this.renderDayContents}
          renderMonthText={this.renderMonthText}
        />
      </>
    );
  }
}

export default App;
```

**Screenshots/Gifs**
![Peek 2019-06-29 16-23](https://user-images.githubusercontent.com/18097850/60383758-6b6d4b80-9a8a-11e9-84a2-78d990805d64.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu v18.04
 - Browser: Chrome, Firefox (all of them)
 - Version: all

**Is the issue reproducible in Storybook?**
No, because there is no such an example like this one.

**Additional context**
I want a method to re-render/re-fresh the calendar whenever I want.

**Comment by mmarkelov** [comment]
@smrsan76 you can pass **isFocused** prop, that depend on **isShamsi** state value:
```javascript
...
<DayPicker
            firstDayOfWeek={6}
            numberOfMonths={1}
            renderDayContents={this.renderDayContents}
            renderMonthText={this.renderMonthText}
            isFocused={isShamsi}
/>
...
```

**Comment by smrsan76** [comment]
@mmaday Thank you ...
But it doesn't makes any sense to put the calendar type into the `isFocused` property.
Therefore, It won't work ... (I've tested it)

**Comment by mmarkelov** [comment]
@smrsan76 here is sandbox:
[![Edit jolly-neumann-rdf3t](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jolly-neumann-rdf3t?fontsize=14)
Main idea to start rerendering on changing **isFocused** prop

**Comment by smrsan76** [comment]
@mmarkelov Yeah... That works very well!!!
But another issue is still exists #755 👎
If there was a good solution for that, I would start using `react-dates` in my Persian project.
