### ISSUE TITLE
Enable past dates

### ISSUE THREAD

**Issue by curiousPup** [airbnb/react-dates#1719]
How do i enable past dates to be selected?

**Comment by davidyeiser** [comment]
Passing this prop should do it:
```
isOutsideRange: () => false
```

**Comment by ljharb** [comment]
Duplicate of #1124, #1519, #1392, #1117, #1073, #985, #801, #718, #714, etc.

**Comment by danishfareed** [comment]
This worked perfectly for me:
isOutsideRange={(day) => moment(day).isBefore(moment())}
