### ISSUE TITLE
Uncaught TypeError: Cannot read property 'createLTR' of undefined

### ISSUE THREAD

**Issue by rustyb** [airbnb/react-dates#1726]
Hi There - been battling with this for hours unsuccessfully.  I keep getting the error Uncaught TypeError: Cannot read property 'createLTR' of undefined when I load the `DateRangePicker` component:

<img width="711" alt="Screenshot 2019-07-11 at 18 44 12" src="https://user-images.githubusercontent.com/53086/61069121-e8de7780-a40b-11e9-8c28-bf859ec01656.png">

Not using webpack as in the examples but browserify to bundle up the app.js seperately to the dependencies, might this be causing the problem?

```
gulp.task('vendorScripts', function () {
  // Ensure package is updated.
  readPackage();
  var vb = browserify({
    debug: true,
    require: pkg.dependencies ? Object.keys(pkg.dependencies) : []
  });
  return vb.bundle()
    .on('error', gutil.log.bind(gutil, 'Browserify Error'))
    .pipe(source('vendor.js'))
    .pipe(buffer())
    .pipe(sourcemaps.init({loadMaps: true}))
    .pipe(sourcemaps.write('./'))
    .pipe(gulp.dest('.tmp/assets/scripts/'))
    .pipe(reload({stream: true}));
});
```

Versions of the various packages:

```
"react": "16.8.6",
"react-dates": "^20.2.5",
"react-dom": "16.8.6",
"browserify": "^16.2.2",
```

**Comment by ljharb** [comment]
Try https://github.com/airbnb/react-dates#initialize

**Comment by rustyb** [comment]
Meant to mention that in the component loading the `DateRangePicker` I already have the following at the top of the file:

```
import 'react-dates/initialize';
import {DateRangePicker} from 'react-dates';
import 'react-dates/lib/css/_datepicker.css';
```
No matter where I add the `import 'react-dates/initialize';` it seems to have no effect.

**Comment by rustyb** [comment]
So coming back to this I found how to overcome this issue for anyone who encounters the same issue.

During my build I split the "app" code (bundle.js) from the dependencies (vendor.js). Doing so seems to interfere with the initialise function.

The **workaround** is to remove both `react-dates` and `react-with-styles` from the vendor.js and add them to the bundle.js and 💥 goes the issue.

**Comment by ljharb** [comment]
The splitting should be fine as long as the module cache spans split bundles.

**Comment by reZach** [comment]
This is still a issue in December. Has this not gotten fixed yet in the master branch? I am not doing anything with a bundle as @rustyb describes - so I am stuck how to fix this.

**Comment by noorReza** [comment]
I have also come across this problem. It has been solved by putting following imports at the top of the page (top of other imports):

```
import 'react-dates/initialize';
import 'react-dates/lib/css/_datepicker.css';
```

@rustyb Your problem was you were not importing them at first (before importing DateRangePicker)

**Comment by ni8mr** [comment]
I have also come across this problem. It has been solved by putting following imports at the top of the page (top of other imports):

import 'react-dates/initialize';
import 'react-dates/lib/css/_datepicker.css';

@rustyb  Your problem was you were not importing them at first (before importing DateRangePicker)
