### ISSUE TITLE
Picker won't go after Jan 2020

### ISSUE THREAD

**Issue by pinguinjkeke** [airbnb/react-dates#1728]
**react-dates version**
20.2.0

**Describe the bug**
When I try to go past January 2020 it starts to render Jan 2020 2 times and render all next months under it.

**Source code (including props configuration)**
```
class MyComponent extends PureComponent {
dateRange = {
    start: moment().subtract(2, 'years'),
    end: moment()
      .add(1, 'year')
      .endOf('year'),
  };
  isDayBlocked = (day: moment.Moment) => {
    return (
      day.isBefore(this.dateRange.start) || day.isAfter(this.dateRange.end)
    );
  };
  render() {
    return (
      <DateRangePicker
        startDate={this.state.startDate}
        startDateId="your_unique_start_date_id"
        endDate={this.state.endDate}
        isDayBlocked={this.isDayBlocked}
        isOutsideRange={this.isDayBlocked}
        endDateId="your_unique_end_date_id"
        onDatesChange={({ startDate, endDate }) => this.setState({ startDate, endDate })}
        focusedInput={this.state.focusedInput}
        onFocusChange={focusedInput => this.setState({ focusedInput })}
      />
}
```

**Screenshots/Gifs**
If applicable, add screenshots or gifs to help explain your problem.
<img width="682" alt="Screenshot 2019-07-18 at 14 08 18" src="https://user-images.githubusercontent.com/10704892/61449462-0f4d6700-a966-11e9-8c2d-b2ebc68dea4e.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS/Windows
 - Browser [e.g. chrome, safari] Chrome, FF
 - Version [e.g. 22] latest

**Is the issue reproducible in Storybook?**
No

**Comment by mmarkelov** [comment]
@pinguinjkeke it seems to be ok for me:
[![Edit async-bash-gd43j](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/async-bash-gd43j?fontsize=14)

**Comment by pinguinjkeke** [comment]
@mmarkelov what can I do with it? Where should I look?

**Comment by mmarkelov** [comment]
@pinguinjkeke, sorry here is working sandbox:
 [![Edit ecstatic-snowflake-yz1ln](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ecstatic-snowflake-yz1ln?fontsize=14)
![demo](http://dl3.joxi.net/drive/2019/07/22/0026/1598/1717822/22/28715ddb8e.jpg)

**Comment by pinguinjkeke** [comment]
The issue was in incorrectly imported `padStart` polyfill. It's working now.
Thank you @mmarkelov, I'm closing the issue.
