### ISSUE TITLE
Data-visible false duplication

### ISSUE THREAD

**Issue by ehtonay** [airbnb/react-dates#1740]
**react-dates version**
e.g. react-dates@18.3.1

**Describe the bug**
Non-urgent. I apologize if this is a dumb question.

In Jest snapshots, I am seeing three instances of the same month (eg. "September 2019"). Two of these three are data-visible: false, the other is data-visible: true. When inspecting the live version in browser, I don't see any trace of these data-visible: false months.

Is there a reason for this duplication? Is this something that is likely caused by the implementation? Thank you in advance for you help.

**Screenshots/Gifs**
![Screen Shot 2019-08-01 at 1 35 48 PM](https://user-images.githubusercontent.com/33971189/62311177-a552b880-b461-11e9-8bea-a9e8297ef29e.png)

**Comment by ehtonay** [comment]
**Follow-up:** I did some further digging into the docs, and notice that `isVisible` is passed into the `renderMonthElement` callback. I tried adding a `if (!isVisible) return;` statement to the callback we supply, and it fixed the issue. Is this fix advisable?

**Comment by ehtonay** [comment]
Can anyone help with this please?

**Comment by ljharb** [comment]
That depends on your snapshot tool; I don't endorse or recommend snapshot tests (they're brittle), but you could use enzyme's `.debug()` to see what's there?

**Comment by ehtonay** [comment]
True about the snapshot tests, but my particular concern is why `DatePickerRangeController` seems to render elements with [data-visible="false"] at all. I presume it's for spacing/navigation?

**Comment by ljharb** [comment]
It's done [here](https://github.com/airbnb/react-dates/blob/5f1964b38c5d020b40a0caf897e6612179ada9c9/src/components/CalendarMonth.jsx#L190) - i believe because we render 3 months at a time, so we can smoothly move forward and back, but only the middle one is visible.

**Comment by ehtonay** [comment]
Thanks so much!! Just wanted to confirm. Sorry to bug ya.
