### ISSUE TITLE
currentMonth state is only reset once and never updated after that

### ISSUE THREAD

**Issue by ViktoriyaSavkina** [airbnb/react-dates#175]
`currentMonth` state field along with `hasSetInitialVisibleMonth` flag are initialized in the constructor of the DatePicker component.
After `componentWillReceiveProps` is ran first, `hasSetInitialVisibleMonth` is set to true which causes the `currentMonth` field to never update, making it impossible to open datepicker with dates on different months.
https://github.com/airbnb/react-dates/blob/master/src/components/DayPicker.jsx#L100

**Comment by majapw** [comment]
This is intentional behavior. Can you describe the usecase you need to change the month more than once for?

**Comment by timhwang21** [comment]
Hi,

Based on this discussion, it sounds like it is intended for the calendar to always open on the same month, regardless of the currently selected values. Is that correct?

I noticed on Storybook, changing the month, selecting dates, closing the calendar, and reopening the calendar opens the picker based on the `startDate` selected.

On the other hand, in use the calendar seems to always open based on today's date, regardless of what value is selected, even after reducing the component down to the most minimal set of props possible.

I was wondering if I was missing something? If this is a bug, do you know where I could start looking to determine why my calendar is always opening based on today's date?

Thank you!

**Comment by novartema** [comment]
Looks like it was fixed in new versions. I got same behavior in 7+ version. I installed 8.2.0 version and it works good.
