### ISSUE TITLE
autoFocusEndDate seems to not work for DayPickerRangeController

### ISSUE THREAD

**Issue by yqbk** [airbnb/react-dates#1755]
**react-dates version**
react-dates@^20.2.0

**Describe the bug**
When I try to use `autoFocusEndDate` prop in the `DayPickerRangeController` component I receive error message:
_Warning: Failed prop type: DayPickerRangeController: unknown props found: autoFocusEndDate_

**Source code (including props configuration)**
```
    <DayPickerRangeController
      autoFocusEndDate
      onPrevMonthClick={handlePrevMonthClick}
      startDate={calendarStartDate}
      endDate={calendarEndDate}
      hideKeyboardShortcutsPanel
      transitionDuration={0}
      navNext={<Chevron />}
      navPrev={<Chevron />}
      numberOfMonths={2}
      minimumNights={0}
      noBorder
      {...{
        initialVisibleMonth,
        isOutsideRange,
        onDatesChange,
        onFocusChange,
        focusedInput,
      }}
    />
```

**Is the issue reproducible in Storybook?**
http://airbnb.io/react-dates/?path=/story/daypickerrangecontroller--default - props description

**Comment by mmarkelov** [comment]
@yqbk There is on inputs for [DayPickerRangeController](https://github.com/airbnb/react-dates#daypickerrangecontroller), so there is no **autoFocusEndDate**  prop

**Comment by lianju** [comment]
Is it possible to autofocus the enddate input when using DayPickerRangeController?
