### ISSUE TITLE
Date is changed on SingleDatePicker when picker is opened again

### ISSUE THREAD

**Issue by terohotti** [airbnb/react-dates#1795]
**react-dates@21.1.0**

Can be reproduced in: https://airbnb.io/react-dates/?path=/story/singledatepicker-sdp--default

Select SingleDatePicker -> Default
Pick a date -> Click on date field to open picker again -> Date on input field is changed to the last day of the week

![image](https://user-images.githubusercontent.com/4482090/65321869-0408f880-dbae-11e9-829d-3ed990d1cb1a.png)

**Comment by mmarkelov** [comment]
@terohotti will be fixed by #1796
