### ISSUE TITLE
DRP: Start date being unintentionally set to the last value of current week when focusing it a second time

### ISSUE THREAD

**Issue by antjernberg** [airbnb/react-dates#1808]
**react-dates version**
react-dates@21.1.0

**Describe the bug**
If you've chosen a start- and end-date. The start date will automatically change to the last day of the previously selected week when you focus on the start date field a second time

Reproduction steps: 
1. Choose a start date which is not at the end of a row (not the last day of a week in other words).
2. Choose an end date.
3. Focus the start date field by clicking it. 
4. Blur the field by pressing outside the calendar component

The value is now set to the last day of the week that was previously selected. 
Please see the gif

**Source code (including props configuration)**
This bug is found in any setup of the component that I've tried, also in the publically available storybook here: 
https://airbnb.io/react-dates/?path=/story/daterangepicker-drp--default
(Use the same prop setup as the storybook basic example)

**Screenshots/Gifs**
In the gif, 27th of september is initially selected. It is the changed to the 28th of september without any user input when you focus the input element a second time
https://gyazo.com/07e8fa227d0ff9d12c436c6365f73dd2

**Desktop:**
 - OS: macOS
 - Browser: Chrome
 - Version: 77.0.3865.90

**Is the issue reproducible in Storybook?**
Yes. 
https://airbnb.io/react-dates/?path=/story/daterangepicker-drp--default

**Comment by mmarkelov** [comment]
Duplicate of #1807 #1804 #1800 #1799 #1795

**Comment by antjernberg** [comment]
Alright, didnt see those. 
Thank you! : )
