### ISSUE TITLE
DRP: drop down not closing when (forward) tabbing out of focus

### ISSUE THREAD

**Issue by antjernberg** [airbnb/react-dates#1809]
**react-dates version**
react-dates@21.1.0

**Describe the bug**
I believe the calendar should close when you move the focus outside of the components within the calendar component. This is when happens when you back-tab, but not when you forward tab. Meaning, if you forward tab to another element which also uses some keyboard interaction and absolute positioned dropdowns, you could end up in an awkward position.

Problem: switching focus away from calendar using Tab does not close the Calendar dropdown. 

**Source code (including props configuration)**
This bug is found in any setup of the component that I've tried, also in the publicly available storybook here:
https://airbnb.io/react-dates/?path=/story/daterangepicker-drp--default
(Use the same prop setup as the storybook basic example)

**Screenshots/Gifs**
In the gif, you can see me tabbing to select the calendar. After tabbing through all the elements and focusing on *other* elements on the site, the dropdown remains open.
https://gyazo.com/fb17ed0af5d125c7566c0352a0cf6c28

Backwards tabbing works correctly however. It closes the dropdown when currently focusing the first element and pressing shift-tab.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome 
 - Version: 77.0.3865.90

**Is the issue reproducible in Storybook?**
Yes.
https://airbnb.io/react-dates/?path=/story/daterangepicker-drp--default

**Comment by mmarkelov** [comment]
@antjernberg yeah that's true. I made PR about two month ago. And this fix issues like this. But I'm not sure that it will be merged(
