### ISSUE TITLE
Object doesn't support property or method 'from' - For React Calendar when open with IE

### ISSUE THREAD

**Issue by sarwan39** [airbnb/react-dates#1810]
Hi Team,

In Chrome, its working perfectly in SPO Modern page. When i try to open the page in IE any version issue remains same with Object doesn't support property or method 'from' - react-calendar

<img width="819" alt="Modern page calendar webpart in IE" src="https://user-images.githubusercontent.com/55893419/65794570-6b86f100-e136-11e9-9103-75b78bdd9883.PNG">

**Comment by ljharb** [comment]
Although it should be noted in the readme, this package requires https://npmjs.com/airbnb-browser-shims or the equivalent.

**Comment by sarwan39** [comment]
I couldnt understand that. do you have any steps which i may need to execute to get the things working it in the SPO ?

**Comment by sarwan39** [comment]
npm i airbnb-browser-shims 

I have executed again with this steps and then executed Gulp Build and other steps and the issues remains same as it is.

Do you have any recommendation to make it work for IE ?

**Comment by ljharb** [comment]
@sarwan39 you can't solely install it, you have to require/import it before all other app code - it's in the readme of airbnb-browser-shims.
