### ISSUE TITLE
Object doesn't support property or method 'from' - For React Calendar when open with IE 

### ISSUE THREAD

**Issue by sarwan39** [airbnb/react-dates#1812]
npm i airbnb-browser-shims

I have executed again with this steps and then executed Gulp Build and other steps and the issues remains same as it is.

Do you have any recommendation to make it work for IE ?

In Chrome, its working perfectly in SPO Modern page. When i try to open the page in IE any version issue remains same with Object doesn't support property or method 'from' - react-calendar
<img width="819" alt="Modern page calendar webpart in IE" src="https://user-images.githubusercontent.com/55893419/65796950-fc140000-e13b-11e9-8ab9-9803d812d7b2.PNG">

**Comment by ljharb** [comment]
There's no need to file a new issue; let's keep discussing in #1810.
