### ISSUE TITLE
Both Single / Range Pickers change date to first day of the week on focus

### ISSUE THREAD

**Issue by cloud-walker** [airbnb/react-dates#1815]
**react-dates version**
react-dates@21.1 only

**Describe the bug**
When focusing the input of SingleDatePicker and RangeDatePicker the focused input change the date to the nearest "first day of the week"

**Source code (including props configuration)**
https://codesandbox.io/embed/react-bw80u

**Desktop (please complete the following information):**
 - OS: MacOS, Windows 10
 - Browser Chrome
 - Version latest

**Comment by mmarkelov** [comment]
Duplicate of #1808 #1807 #1804 #1800 #1799 #1795
