### ISSUE TITLE
Date input jumps to nearest Saturday on focus

### ISSUE THREAD

**Issue by jchang-tracker** [airbnb/react-dates#1816]
I encountered this locally with react-dates@21.1.0, but the same thing happens when looking at the [official Storybook demo](https://airbnb.io/react-dates/?path=/story/singledatepicker-sdp--default). I'm not sure if this is a bug or a feature that I've missed the documentation for.

Essentially, after picking a non-Saturday date in SingleDatePicker (e.g., Nov 1, 2019), the input is correctly set. Clicking on the input a second time changes it to Nov 2, 2019. The jump in date appears to always be the nearest upcoming Saturday. If I then click out of the input, then the date will be altered.

If this is a default feature, how do I disable it?

**Comment by mitko993** [comment]
I can confirm the same issue occurs for me as well.

react-dates@21.0.0 and newer

I am using a `DateRangePicker`. When i open the calendar, focus on the start date or end date, the start date changes to whatever is the last date in the current row or the row above.
Example:
  - if `firstDayOfWeek={0}` (week starts on Sunday) then the start day will change to Saturday as this is the last day in the week.
 - if `firstDayOfWeek={1}` then the start day will change to Sunday and so on...

One more thing i noticed. In the `render()` method i am passing the correct date (the one i selected), but then in the `componentDidUpdate(prevProps)` the previous props are set to a new date (the last date from the row).

I am using redux to store the selected dates and i can't see any action being dispatched to change the dates.

**Comment by mmarkelov** [comment]
Can you check the latest version **v21.2.0** I suppose it should be fixed?

**Comment by mitko993** [comment]
I can't replicate the issue anymore

**Comment by jchang-tracker** [comment]
Tried with v21.2.0, and it looks to be fixed. Thank you!
