### ISSUE TITLE
firstDayOfWeek={1} results in wrong month being shown initially

### ISSUE THREAD

**Issue by ThiefMaster** [airbnb/react-dates#1819]
**react-dates version**
e.g. react-dates@21.1.0

**Describe the bug**
When setting `firstDayOfWeek={1}` with `date={moment('2019-10-01')}` (or just omitting it as of today), I see September instead of October.

**Source code (including props configuration)**
```jsx
<DayPickerSingleDateController
  date={moment('2019-10-01')}
  // as soon as I set fDOW, I get september instead of october displayed
  firstDayOfWeek={1}
  focused
/>
```

`moment.locale() === 'en'` in case it matters

**Screenshots/Gifs**
![image](https://user-images.githubusercontent.com/179599/65950749-fb7eb080-e43e-11e9-9642-83d3b325a9e0.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Firefox
 - Version: 70.0b10

**Is the issue reproducible in Storybook?**
CodeSandbox: https://codesandbox.io/s/react-dates-ublwb

**Comment by mic4ael** [comment]
I tried to debug this but the only thing I found out is that `DayPicker` which is used inside `DayPickerSingleDateController` receives incorrect `moment` object as `initialVisibleMonth` prop.

From `DayPickerSingleDateController.jsx`

```javascript
<DayPicker
   ...
   initialVisibleMonth={() => currentMonth}
   ...
/>
```

The only suspicious thing here is that `_d` property of `currentMonth` is off by 3 days (Sun Sep 29 2019).

**Comment by mic4ael** [comment]
Oh I think I finally found the root case of this issue. But this has been fixed in one of the recent commits https://github.com/airbnb/react-dates/commit/5e569b52870fdeb6d511cdf253736e2f3288ec91

**Comment by mic4ael** [comment]
Updating to `21.2.0` should fix the issue.

**Comment by ThiefMaster** [comment]
Indeed it did!
