### ISSUE TITLE
initialVisibleMonth doesn't work if we specify `focusedInput: START_DATE` in the initial state

### ISSUE THREAD

**Issue by Louis-Simon22** [airbnb/react-dates#1820]
react-dates@21.1.0

```
constructor(props) {
    super(props);
    this.state = {
        focusedInput: START_DATE,
        periodSelectionType: "day",
    };
}


<DayPickerRangeController
    onDatesChange={({ startDate, endDate }) =>
        this.props.onDatesChange(moment(startDate), moment(endDate).endOf('day'))}
    onFocusChange={(focusedInput) => this.onFocusChange(focusedInput)}
    focusedInput={this.state.focusedInput}
    initialVisibleMonth={() => moment().add(10, 'months') }
/>
```
It works if we specify `focusedInput: "startDate"`

See the [codesandbox ](https://codesandbox.io/embed/react-dates-demo-kf01k)

Windows 10
Chrome 76.0.3809.132

**Comment by mmarkelov** [comment]
@Louis-Simon22 package does not export `START_DATE` constant, so it is `undefined`.  But under hood `START_DATE` is equal to `startDate`. So it is work if you specify `focusedInput: "startDate"`

**Comment by ljharb** [comment]
a PR to expose that constant would be ideal; otherwise we could change the string value at any time.

**Comment by Louis-Simon22** [comment]
Something like adding
`export { START_DATE } from './constants';`
to react-dates/src/index.js ?
Any other constants that would be worth exporting? All of them?

**Comment by ljharb** [comment]
Yep! Let’s only export the ones that have use cases; we can export more later.

**Comment by TheSharpieOne** [comment]
Worth noting that #53 exposed these in `react-dates/constants`: `import { START_DATE } from 'react-dates/constants';`
