### ISSUE TITLE
How I can hide rangeDatePicker input [StartDate, EndDate]

### ISSUE THREAD

**Issue by ahmedraza11** [airbnb/react-dates#1833]
I am using DateRangePicker and want to hide default startDate and endDate inputs from UI so I can trigger it by clicking on custom Input.
![image](https://user-images.githubusercontent.com/16984365/66411690-94986300-ea0d-11e9-9477-d0ff3d46f9a3.png)

**Comment by ahmedraza11** [comment]
I simpled disabled these fields from custom css.

**Comment by betCG** [comment]
> I simply disabled these fields from custom css.

Hi! how did you do that? I'm kinda new doing this.
