### ISSUE TITLE
verticalSpacing prop is missing from the documentation

### ISSUE THREAD

**Issue by daviddelusenet** [airbnb/react-dates#1852]
**react-dates version**
e.g. react-dates@18.3.1

**Describe the bug**
The `verticalSpacing` prop isn't present in the current documentation but it is in the Storybook examples: https://airbnb.io/react-dates/?path=/story/sdp-calendar-props--with-custom-vertical-spacing

**Comment by ianjmacintosh** [comment]
Does the documentation live in this repo? Heck if I can find it.

I'm presuming the ask here isn't to remove `verticalSpacing` from the Storybook examples.

**Comment by ljharb** [comment]
The documentation is the storybook and the readme.

**Comment by ianjmacintosh** [comment]
> The documentation is the storybook and the readme.

Got it. I was looking at https://airbnb.io/projects/react-dates/
