### ISSUE TITLE
Unable to select dates in months different from what initialVisibleMonth returns

### ISSUE THREAD

**Issue by ingro** [airbnb/react-dates#186]
After updating to 4.0.1 I noticed a strange behaviour:
it's impossible to choose a date outside the initial month(s) returned from `initialVisibleMonth`, as the datepicker gets re-rendered as soon as you hover over a day, bringing you back to initial month!

You can check that here: http://airbnb.io/react-dates/?selectedKind=SingleDatePicker&selectedStory=with%20month%20specified%20on%20open&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel

**Comment by Jonathanx5** [comment]
Me too !!!!, how to downgrade ?

**Comment by ingro** [comment]
Just go back to 4.0.0, the bug was introduced in 4.0.1.

**Comment by ViktoriyaSavkina** [comment]
PR to fix the issue https://github.com/airbnb/react-dates/pull/189

**Comment by majapw** [comment]
Fixed in v4.0.2. We're going to think more deeply on how to address @ViktoriyaSavkina's usecase. :)

**Comment by ingro** [comment]
Thanks for the fast fix! :)

**Comment by Jonathanx5** [comment]
Fast fix ! So cool, thanks !!!! 😀
