### ISSUE TITLE
No way to set a "title" attribute on input fields

### ISSUE THREAD

**Issue by vastolf** [airbnb/react-dates#1861]
**Update:** this now has a PR with full Tests & Storybook Documentation: https://github.com/airbnb/react-dates/pull/1862

---

In many browsers, when you hover over an input field, text that looks similar to alt text appears (see the "Search" text in the tooltip below the search field):

![Screen Shot 2019-11-13 at 10 03 52 AM](https://user-images.githubusercontent.com/2312432/68781186-052e3300-05fd-11ea-895c-582a0d0aa86a.png)
https://www.w3.org/WAI/tutorials/forms/labels/#using-the-title-attribute

On images this is the `alt` attribute. On input fields, it is the `title` attribute. Currently there is no way to set a `title` attribute on the Start or End date fields. 

By default in Chrome, the text in the tooltip defaults to "Please fill out this field" if nothing is set & the field is required. When implementing the Date Range Picker for a client, they requested we set custom text for this; I had to tell them this was not currently possible.

Adding this issue here as I am thinking of drafting a PR for this, but would like to get some outside input, especially from an accessibility perspective. I've not been able to find a ton of information about the accessibility concerns regarding this, but will leave the following resource to get the conversation started:

https://stackoverflow.com/questions/56947455/specifying-both-aria-label-and-title

**Comment by astolfivincent** [comment]
I have started a PR for this. It still needs Tests & Documentation:

https://github.com/airbnb/react-dates/pull/1862

@majapw would love to get some input from you on this, as I'm sure you've got a bit more accessibility experience :)

**Comment by astolfivincent** [comment]
@majapw and @ljharb this now has a PR with full Tests & Storybook Documentation
