### ISSUE TITLE
Removal of componentWillReceiveProps

### ISSUE THREAD

**Issue by WillSelway** [airbnb/react-dates#1864]
**react-dates version**
react-dates@21.3.2

**Describe the bug**
An warning gets printed to the console when any date picker is loaded.

**Source code (including props configuration)**
Load a date picker with any configuration

Would the library maintainers please consider creating a fork that drops older React support so we can get rid of this error earlier 🙏 

Additionally, How have you prevented the error from occurring on airbnb.co.uk or is it using an older version of react-dates/react?

Similar to https://github.com/airbnb/react-dates/issues/1850, https://github.com/airbnb/react-dates/issues/1805 & https://github.com/airbnb/react-dates/issues/1748

**Comment by ljharb** [comment]
The error only occurs in development, i assume it’s just ignored.

**Comment by WillSelway** [comment]
Ah of course it does I should of checked first

**Comment by nakita-strangeways** [comment]
This error started showing up recently for the first time on our tests too
![Screen Shot 2020-04-21 at 4 49 44 PM](https://user-images.githubusercontent.com/40547453/79926938-102e9000-83f3-11ea-8014-6e51773b4156.png)
Is this still a non-issue?
