### ISSUE TITLE
Several prop types missing(TypeScript)

### ISSUE THREAD

**Issue by paulopretoEI** [airbnb/react-dates#1866]
Several prop types missing from  the documentation
I just did the initial config for the `react-dates` -> `DateRangePicker` and after the `npm install --save @types/react-dates`

And started the configuration of the `DateRangePicker` but when I put both  `minDate`and `maxDate` prop, it gives me the follwing error `Property 'minDate' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<DateRangePickerShape, any, any>> & Readonly<DateRangePickerShape> & Readonly<{ children?: ReactNode; }>'.ts(2769)`. 

**My code**
```
import React, { Component } from 'react'
import 'react-dates/initialize';
import { DateRangePicker, DateRangePickerShape } from 'react-dates';
import styles from './RangePicker.less'

export interface RangePickerProps extends DateRangePickerShape {
}

const RangePicker: React.FC<RangePickerProps> = (props) => {
    return (
        <>
            <DateRangePicker {...props} />
        </>
    )

}

export default RangePicker;
```

**Methods**
```
    handleDateChange = ({ startDate, endDate }) =>
        this.setState({ startDate, endDate });

    handleFocusChange = focusedInput => this.setState({ focusedInput });
```
**dependencies**
I'm using `"@types/react-dates": "^17.1.5","react-dates": "^21.5.0",`

**Comment by ljharb** [comment]
We don't maintain those types, they're part of DefinitelyTyped. Also, the major and minor versions of a `@types` package have to match the version of the real package, or else the types will be wrong.

In other words, if you're using v21.5 of react-dates, you'd need to use a v21.5 of `@types/react-dates` - and if it doesn't exist, then there's no types available.

**Comment by paulopretoEI** [comment]
So how can I `extend` all the props types from the react-dates?

**Comment by ljharb** [comment]
You can make a pull request to https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-dates/ and DT will autopublish a new version.
