### ISSUE TITLE
Invalid font-weight style for regular option

### ISSUE THREAD

**Issue by tuanalumi** [airbnb/react-dates#1868]
When `regular` option is true, style for `DateInput_input__regular` has `font-weight: auto`. 

But `auto` is an invalid value for `font-weight` in Chrome (I have not checked other browsers). The value should be `unset`.

**Comment by ljharb** [comment]
This appears to be the line: https://github.com/airbnb/react-dates/blob/9501a98b729825358f4c698a59bad40a5cf45c41/src/components/DateInput.jsx#L338 added in #957.
