### ISSUE TITLE
DatePickerSingleDate focus issue when tabing, tab-index is set to -1 for all available dates

### ISSUE THREAD

**Issue by marianhorlescu** [airbnb/react-dates#1870]
I am using React-Dates 12.6.0 , and i can see that tabbing on the SingleDatePicker is not focusing on first available date, it is just jump from the controllers button into the shortcuts panel,  inspecting the component i can see that all the days buttons have data-index="-1" so i guess the first one available should have data-index: 0, any idea ?

**Comment by erin-doyle** [comment]
I believe this has been fixed.  Please try updating to the latest version and if this is still an issue please reopen this.
