### ISSUE TITLE
Cannot resolve module 'react/lib/CSSPropertyOperations'

### ISSUE THREAD

**Issue by jsmankoo** [airbnb/react-dates#188]
Module not found: Error: Cannot resolve module 'react/lib/CSSPropertyOperations' in /home/jsmankoo/Cluep/WebServer-Internal-v2/node_modules/react-dates/node_modules/react-portal/build
@ ./~/react-dates/~/react-portal/build/portal.js 17:29-71

The latest update for react broke this I believe. react@15.4.0

**Comment by ljharb** [comment]
It should be fixed in v4.0.1 - which version of react-dates are you using?

**Comment by jsmankoo** [comment]
well my package.json was set to "^3.6.0" when i ran npm update and thats when it broke.

**Comment by ljharb** [comment]
That won't update to v4, because of the `^`. You'll have to rerun the install script in our readme to update to v4.0.1 (check the changelog for the breaking changes)
