### ISSUE TITLE
onClose returns incorrect endDate if it's been entered manually in the input

### ISSUE THREAD

**Issue by AragondPL** [airbnb/react-dates#1892]
If dates are not choosed from calendar but entered manually in inputs onClose handler returns null or previous date in endDate. It is visible in storybook https://airbnb.io/react-dates/?path=/story/drp-calendar-props--with-onclose-handler

**Comment by VitaliyGaliy** [comment]
still the same issue

**Comment by VitaliyGaliy** [comment]
any updates?
