### ISSUE TITLE
Is it possible to set the endDate with the same startDate on DateRangePicker?

### ISSUE THREAD

**Issue by KuroNoDev** [airbnb/react-dates#1901]
Sample scenario: we want our users to have the option to view the data of a specific day.

**Comment by mmarkelov** [comment]
@KuroNoDev you can use **minimumNights** prop. Like so:
```javascript
<DateRangePicker minimumNights={0} {...otherProps}  />
```

**Comment by KuroNoDev** [comment]
Thanks! https://github.com/airbnb/react-dates/issues/24
