### ISSUE TITLE
Weekday headers render issue

### ISSUE THREAD

**Issue by FabioFleitas** [airbnb/react-dates#191]
For some reason Saturday in the weekday headers renders below Sunday. See screenshots. I'm on version `3.6.0`
<img width="904" alt="screen shot 2016-11-18 at 2 21 19 pm" src="https://cloud.githubusercontent.com/assets/2321202/20448753/65099120-ad9a-11e6-87e2-f186f49697f6.png">

**Comment by FabioFleitas** [comment]
I use `import 'react-dates/css/styles.scss';`. Is there another CSS I could use?

**Comment by FabioFleitas** [comment]
@ljharb It seems that if `numberOfMonths > 2` then this render issue occurs. Checkout the screenshots.
![screen shot 2016-11-18 at 2 55 20 pm](https://cloud.githubusercontent.com/assets/2321202/20449600/4970da04-ad9f-11e6-8b08-05064eb4fd2f.png)
![screen shot 2016-11-18 at 2 55 32 pm](https://cloud.githubusercontent.com/assets/2321202/20449602/498dd1fe-ad9f-11e6-83b8-6b2dd50996ca.png)
![screen shot 2016-11-18 at 2 56 23 pm](https://cloud.githubusercontent.com/assets/2321202/20449601/498ce9ec-ad9f-11e6-89f5-191eaf193ace.png)

**Comment by majapw** [comment]
Oh yeah, this is a thing that I haven't gotten around to fixing but have noticed before. D: It is due to a rounding error I believe --- https://github.com/airbnb/react-dates/blob/master/src/components/DayPicker.jsx#L312

**Comment by FabioFleitas** [comment]
@majapw Interesting. I can see why `3` may have a rounding error, but why would `4`?

**Comment by majapw** [comment]
Yeah. D: There's def a possibility my initial instinct was wrong. I will investigate some more.

**Comment by FabioFleitas** [comment]
@majapw Let me know how I can be helpful

**Comment by majapw** [comment]
Should be fixed in v4.3.0! Thanks for reporting @FabioFleitas

**Comment by FabioFleitas** [comment]
Awesome! Thanks @majapw
