### ISSUE TITLE
Question: How to change currently viewed month range for DateRangePicker?

### ISSUE THREAD

**Issue by lainermeister** [airbnb/react-dates#1923]
Like many other users, I am trying to add a Year dropdown to my DateRangePicker. However, I am not sure which prop I can set to update the currently viewed dates. 

In the example below, I want to use the dropdown I created to update the month that is being shown to February 2018.

![Screen Shot 2020-02-06 at 6 51 49 PM](https://user-images.githubusercontent.com/26628913/73988804-d1b82780-4911-11ea-9a2a-69a1c2b78a7f.png)

Appreciate your help in advance!

**Comment by mmarkelov** [comment]
@lainermeister I suppose **renderMonthElement** prop is what you need.
```javascript
        <DayPickerRangeController
          ...
          renderMonthElement={({ month, onMonthSelect, onYearSelect }) => (
            // your custom caption
          )}
        />
```

https://airbnb.io/react-dates/?path=/story/daypickersingledatecontroller--single-month-custom-caption

**Comment by lainermeister** [comment]
@mmarkelov Thanks for getting back to me. I used renderMonthElement to change the tops of the calendars to display the drop down via custom captions. However, I’m not sure how I can change the actual calendar view’s month?

**Comment by mmarkelov** [comment]
@lainermeister sorry I just can't understand what exactly do you want. :( Do you want to change end date to February  2018 in your example?

**Comment by lainermeister** [comment]
@mmarkelov Yes, I want the actual calendar dates in the two calendars to change to correspond to Feb 2018 and Mar 2018 when I select 2018 in the dropdown.

**Comment by mmarkelov** [comment]
@lainermeister may be this help?
[![Edit ecstatic-snowflake-yz1ln](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ecstatic-snowflake-yz1ln?fontsize=14&hidenavigation=1&theme=dark)

**Comment by lainermeister** [comment]
That's awesome, thank you so much!
