### ISSUE TITLE
Blocked Dates changes not resetting modifiers correctly

### ISSUE THREAD

**Issue by missbruni** [airbnb/react-dates#1926]
I have a DateRangePicker at the moment with blocked dates. 

- Once the start date is selected, I check for the first blocked date from the start date and unblock it using isDayBlocked. (We do that because the user should be able to select the first blocked/unavailable date as a checkout date) - So we basically check startDate and unblock the first blocked day using isDayBlocked. 

my isDayBlocked I am doing something like:
```
const isDayBlocked = (day: Moment): boolean => {
    if (startDate && !endDate && day.isSame(moment(getFirstUnavailableDate())) { return false; }
    ....extra logic to disable all unavailable dates.
}
```
![Animated GIF-downsized_large](https://user-images.githubusercontent.com/12257311/74345501-19bdcb00-4da6-11ea-97a3-6bb33de4cd38.gif)

So when I click the startDate, my first unavailable date visually seems unblocked but I am unable to select the date, and the modifiers are not reset properly. 

Modifiers show:
1) Blocked: `{"blocked", "blocked-calendar"} `
2) After selecting a startDate and returning false on isBlockedDay: `{} // empty :( shouldn't it be valid ?`
3) After hovering: `{"hovered"}  //missing valid and hovered span`
4) Can't select

The actual modifiers I believe, after unblocking it should have been:

1) Blocked: `{"blocked", "blocked-calendar"} `
2) After returning false on isBlockedDay: `{"valid"}`
3) After hovering: `{"valid", "hovered", "hovered-span"}` 
4) After selecting `{"valid", "selected-end", "hovered"}`

**Comment by mmarkelov** [comment]
@missbruni could you provide small representation?

**Comment by missbruni** [comment]
Don't rmb but it was solved at the time. I think it might have been css.
