### ISSUE TITLE
Inline datepicker ?

### ISSUE THREAD

**Issue by vladi160** [airbnb/react-dates#193]
Hi, is this datepicker can be inline ?

**Comment by majapw** [comment]
Yeah, I mean, I would just throw it in an `inline` styled wrapper div. Then you should be able to easily align it horizontally in whatever form you need. 

This is what it used to look like on airbnb.com. Does that answer your Q?
<img width="1097" alt="screen shot 2016-11-21 at 6 41 49 pm" src="https://cloud.githubusercontent.com/assets/1383861/20505341/346c5174-b01a-11e6-8854-042a704ed60d.png">

**Comment by vladi160** [comment]
I mean when the calendar stay always no matter for click and it is part of the design, like show always in its own container somewhere in the site like this: 
![11111111111111111111111111111111](https://cloud.githubusercontent.com/assets/20115474/20542081/bb154534-b108-11e6-871c-3815cd6bf2d4.jpg)

**Comment by altayaydemir** [comment]
@vladi160 you can try https://github.com/Adphorus/react-date-range.

**Comment by majapw** [comment]
If you want to use `react-dates`, you can also do one of two things. I just exposed `DayPickerRangeController` which is a component that takes in a start date and end date, along with a `onDatesChange` callback and does all the fancy day callbacks and styling for you. However, it also expects a `focusedInput` prop so you would have to figure out some way to indicate that to the component (and some rules on how that changes). If you want to roll your own everything, you can just use the `DayPicker` component which is a vanilla calendar out of the box and takes in event handlers for the days as well as modifiers for the styling. You can see an example of how to use it in the source code for the `DayPickerRangeController`. 

I think the takeaway is that there are def options, but you are free to explore other packages as well, of course. :)

**Comment by Kestanous** [comment]
Sorry to bump a closed issue but it would be really nice to be able to tell the SingleDatePicker to inline with one bool prop. Any chance this could become a feature request? 

Of the other projects I have looked at none come with all the features I need but this one, inline being the only exception.

**Comment by majapw** [comment]
@Kestanous it hasn't been a priority recently, but it is def on the radar to expose a component similar to the `DayPickerRangeController` for the `SingleDatePicker`.
