### ISSUE TITLE
Export isBeforeDay/isAfterDay

### ISSUE THREAD

**Issue by herecydev** [airbnb/react-dates#1943]
Both `isBeforeDay` and `isAfterDay` are quite useful utlities but are not included [in index.js exports](https://github.com/airbnb/react-dates/blob/master/src/index.js#L14-L15). Is there a reason behind this? If not, would you accept a PR to export those?

**Comment by ljharb** [comment]
They're already exposed - `react-dates/lib/utils/isBeforeDay`, etc. There's no real need imo to add to the already too-massive manifest export in the "main".

Everything reachable is part of the public API.

**Comment by paras-shah-synechron** [comment]
import isBeforeDay from "react-dates/lib/utils/isBeforeDay";
import isAfterDay from "react-dates/lib/utils/isAfterDay";
