### ISSUE TITLE
Can we add reset button to clear selected dates?

### ISSUE THREAD

**Issue by yu-coder** [airbnb/react-dates#1951]

**Comment by ljharb** [comment]
Form reset buttons are a horrific antipattern; typically if you want to clear a form, you should refresh the page; it's far too easy to accidentally erase a ton of effort by clicking a reset button.

What's the use case for a button to clear the date field, as opposed to clicking in it and deleting its contents?

**Comment by yu-coder** [comment]
Yes, when refreshing the page it looks like selected dates are being cleared. That makes sense.
But for example, if we use this component to **_filter some results by date range_** the selected dates shouldn't be cleared even we refresh the page.
And in this case, it would be better if we have **Reset** button in the component.

**Comment by ljharb** [comment]
The tradeoff to me seems to be between "the difficulty of having to click in the field and press backspace/delete" and "the difficulty caused by accidentally clicking Reset when you didn't mean to". The damage of the latter seems far too great to be worth the minor convenience of the former.
