### ISSUE TITLE
onDatesChange returns null

### ISSUE THREAD

**Issue by M1ck0** [airbnb/react-dates#1953]
This is code that I implemented

```html
<DayPickerRangeController
                startDate={startDate}
                startDateId="startDateId"
                endDate={endDate}
                endDateId="endDateId"
                onDatesChange={(date) => console.log(date)}
                focusedInput={focus}
                onFocusChange={(focus) => console.log(focus)}
              />
```

But onDatesChange returns null

```
{startDate: null, endDate: null}
```

here are my hooks

```javascript
const [dateRange, setDateRange] = useState({
    startDate: null,
    endDate: null,
  });
  const [focus, setFocus] = useState(null);

const { startDate, endDate } = dateRange;
```

Any ideas why?

These are my imports

```javascript
import 'react-dates/initialize';
import { DayPickerRangeController } from 'react-dates';
```

**Comment by mmarkelov** [comment]
@M1ck0 According to docs https://github.com/airbnb/react-dates#daypickerrangecontroller
`The user will only be able to select a date if focusedInput is provided.`
So your **focus** should be **startDate**

**Comment by M1ck0** [comment]
If you think this
```html
focusedInput={startDate}
```
It is not working.. Already tried that

**Comment by mmarkelov** [comment]
@M1ck0 it should be: `focusedInput='startDate'`
You code will be:
```js
const [dateRange, setDateRange] = React.useState({
    startDate: null,
    endDate: null
  });

  const [focus, setFocus] = React.useState("startDate");

  const { startDate, endDate } = dateRange;

  return (
    <div className="App">
      <DayPickerRangeController
        startDate={startDate}
        endDate={endDate}
        onDatesChange={date => setDateRange(date)}
        focusedInput={focus}
        onFocusChange={focus => setFocus(focus)}
      />
    </div>
  );
```

**Comment by M1ck0** [comment]
It works (sort of). It does what it should but now I can't change date.
Any ideas?

**Comment by M1ck0** [comment]
If you want to change date set focus to 'startDate'

```javascript
setFocus('startDate')
```

**Comment by Jeniffen** [comment]
I was running into a similar issue. The previous solution worked for me - just with a _minor_ adjustment

`  
const [dateRange, setDateRange] = React.useState({
    startDate: null,
    endDate: null,
  });

  const [focus, setFocus] = React.useState("startDate");
  const { startDate, endDate } = dateRange;

  return (
    <DayPickerRangeController
      startDate={startDate}
      endDate={endDate}
      onDatesChange={(date) => setDateRange(date)}
      focusedInput={focus}
      onFocusChange={(focus) => setFocus(focus || "startDate")}
    />
  );
`
