### ISSUE TITLE
storybook is broken

### ISSUE THREAD

**Issue by BartJanvanAssen** [airbnb/react-dates#1956]
the demo storybook http://airbnb.io/react-dates seems to be resolving to a 404 page

![image](https://user-images.githubusercontent.com/4742816/77737612-a0ed9800-700e-11ea-9ee5-a9e9e9075157.png)

**Comment by ljharb** [comment]
Thanks; the gh-pages branch was accidentally deleted by a contributor, and altho i restored it, it seems like it hasn’t redeployed.

I believe whichever of @lencioni @majapw @backwardok @nkinser has admin access will have to fix the gh-pages settings to ensure its redeployed properly.

**Comment by lencioni** [comment]
Thanks for flagging! It should be working again now.
