### ISSUE TITLE
Benefit of isBeforeDay(date, date) over Moment.isBefore(date, 'day')?

### ISSUE THREAD

**Issue by DBjelovuk** [airbnb/react-dates#1973]
Curious of the reason for the utils `isBeforeDay`, `isAfterDay`, etc. Are they different in some way? Or were they just introduced before the API existed in Moment? Thanks.

**Comment by ljharb** [comment]
No, isBefore was added in [2013](https://github.com/moment/moment/blob/develop/CHANGELOG.md#200-see-changelog).

As you can see though, https://github.com/moment/moment/blob/40b52a0333f2620f1c3fc3bdad7dc71b5941c13f/src/lib/moment/compare.js#L18-L29 is not the same as https://github.com/airbnb/react-dates/blob/master/src/utils/isBeforeDay.js - the latter is the logic we needed, so we implemented it as a util.

**Comment by DBjelovuk** [comment]
Aside from being static and with a different implementation, do they not produce the same result? Looks like they would to me after grocking a bit, but maybe I'm mistaken.

**Comment by ljharb** [comment]
I can't speak to the history. If they have the same behavior *now* - for every locale and every possible date/time - then we could conceivable refactor our impl to just call into moment's impl. That seems like a lot of work to prove, though.

**Comment by DBjelovuk** [comment]
Fair enough, I'll chalk it up as an in-theory sort of thing, but with potential edge case blind spots. Thanks for the insight.
