### ISSUE TITLE
how to create month picker ? 

### ISSUE THREAD

**Issue by rikinshah23** [airbnb/react-dates#1980]
Hello,

I am looking to get month picker as shown on this link. 
https://tombatossals.github.io/react-dates/?selectedKind=MonthPicker&selectedStory=with%20custom%20month%20size&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel

Could anyone guide on basic example for this pls? 
Thanks

**Comment by mmarkelov** [comment]
@rikinshah23 it will be pretty hard to do this. As start point you can check #241

**Comment by ljharb** [comment]
react-dates doesn't have a month picker; you're linking to a fork.
