### ISSUE TITLE
Styling question to override inline styling

### ISSUE THREAD

**Issue by rikinshah23** [airbnb/react-dates#1981]
I want to make styling changes to react-dates, DateRangePicker.

I want to be able to give paddingBottom and on right as highlighted.

If I see in dev tools it shows me style is given inline so I cannot even override this change

![image](https://user-images.githubusercontent.com/26806597/80168057-3002b700-859f-11ea-9858-b179b1b52940.png)

![image](https://user-images.githubusercontent.com/26806597/80168043-28dba900-859f-11ea-854e-d647db2ee801.png)

some guidance is helpful..

**Comment by mmarkelov** [comment]
@rikinshah23 you can add it with your styles:
```css
.DayPicker {
  padding-bottom: 30px
}
```
