### ISSUE TITLE
renderMonthText prop makes the calendar invisible

### ISSUE THREAD

**Issue by meness** [airbnb/react-dates#1993]
**react-dates version**
react-dates@21.8.0

**Describe the bug**
I need the Jalali calendar instead of Gregorian, so based on docs and examples, I came up with the following configuration.

The calendar works perfectly without `renderMonthText` prop. `renderMonthText` prop makes the calendar view invisible as you see on the preview below.

**Source code (including props configuration)**
```jsx
<DayPickerSingleDateController
  isRTL
  renderMonthText={(month) =>
    momentJalaali(month).format('jMMMM jYYYY')
  }
  renderDayContents={(day) => momentJalaali(day).format('jD')}
/>
```

**Screenshots/Gifs**
![screen-capture](https://user-images.githubusercontent.com/7955356/81927452-e6831600-95f8-11ea-9a27-bfcddaa1f3c4.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome
 - Version 81.0.4044.138

**Is the issue reproducible in Storybook?**
https://codesandbox.io/s/purple-glade-wb9rx?file=/src/App.js

**Additional context**
I saw this behavior before with `DateRangePicker`. In that case, `renderMonthText` prop makes calendars invisible too.

**Comment by mmarkelov** [comment]
@meness youp, seems like a bug. And I suppose it came from here:
https://github.com/airbnb/react-dates/blob/480b9902d69e64e62a2ef5c2d3b5fc3adef94444/src/components/DayPicker.jsx#L342-L346
Cause comparing two functions will be always return false, it will break UI, I can take a look and try to fix it

**Comment by mmarkelov** [comment]
@meness as workaround it should work with **renderMonthElement**
```js
<DayPickerSingleDateController
  isRTL
  renderMonthElement={(month) =>
    momentJalaali(month).format('jMMMM jYYYY')
  }
  renderDayContents={(day) => momentJalaali(day).format('jD')}
/>
```

**Comment by mlp73** [comment]
+1 same issue here. Using the workaround in the meantime

**Comment by meness** [comment]
@mmarkelov & @ljharb The issue still exists.

```jsx
renderMonthText={(month) =>
              DateUtils.formatDateBasedOnLocale(
                month,
                i18n.locale,
                'MMMM YYYY',
                'jMMMM jYYYY'
              )
            }
```

**Comment by mmarkelov** [comment]
@meness it was not published yet

**Comment by mohsensaremi** [comment]
I have created a fork to fix this.
`calendarSystem` prop added to`DateRangePicker` and`SingleDatePicker` components for supporting JALALI calendar system.

You can see a working range picker here:

https://mohsensaremi.github.io/react-dates/?path=/story/daterangepicker-drp--non-english-locale-persian
