### ISSUE TITLE
SingleDatePicker error when date props is set to null

### ISSUE THREAD

**Issue by martin2day** [airbnb/react-dates#1994]
For **SingleDatePicker** when the date props is set to null, language isn't taken into account anymore and set to default in english.
               
```
 <SingleDatePicker
                    date={null}
                    onDateChange={date => this.singlesDateChanges(date)}
                    focused={this.state.focused}
                    onFocusChange={({ focused }) => this.setState({ focused })}
                    id={this.props.id}
                    displayFormat={this.state.dateFormat}
/>
```

**Comment by mmarkelov** [comment]
@martin2day could you provide small repro with [codesandbox](https://codesandbox.io/) for example?

**Comment by martin2day** [comment]
The codesandbox help me to identifie the problems. 🦆
The error came from me. 
Sorry for the inconvenience, i'm closing this issue.
