### ISSUE TITLE
MaxLength = 10 attribute on the input field makes it impossible to enter dates in a custom format

### ISSUE THREAD

**Issue by matthiasfeist** [airbnb/react-dates#200]
https://github.com/airbnb/react-dates/blob/master/src/components/DateInput.jsx#L123

In this file there is a hardcoded value of 10 for the maxlength attribute of the input field. This is very inconvinient when using a custom date format like the `ll` format of momentjs (try entering `16 Sept, 2016`)

**Comment by ljharb** [comment]
It seems like the only options here are a) remove it, b) allow it to be passed on, c) generate dates in all 12 months in the selected format, and use the longest one's length as the maxLength.

**Comment by matthiasfeist** [comment]
I'd vote for a) or b) 😃

**Comment by majapw** [comment]
Probably we should just remove it. It's a relic of a less customizable time.

**Comment by majapw** [comment]
Should be fixed in v4.3.0! :)
