### ISSUE TITLE
Accessibility on CalendarDay

### ISSUE THREAD

**Issue by Angelfire** [airbnb/react-dates#201]
I'm using _SingleDatePicker_ and my browser want to explode by: (more than 11000 warnings related to that)

```
index.js:108 CalendarDay You have a click handler on a non-interactive element but no `tabIndex` DOM property. The element will not be navigable or interactive by keyboard users. http://www.w3.org/TR/wai-aria-practices/#focus_tabindexwarn @ index.js:108
index.js:108 CalendarDay You have a click handler on a non-interactive element but no `role` DOM property. It will be unclear what this element is supposed to do to a screen-reader user. http://www.w3.org/TR/wai-aria/roles#role_definitions
```

**Comment by majapw** [comment]
I'm surprised that these are being logged. I wonder if this is due to an upgrade for our linting tools. D: I will... address that because that's really gross.

**Comment by erin-doyle** [comment]
This is still an issue.  I believe the logging is coming from the [react-a11y](https://github.com/reactjs/react-a11y) plugin not react-dates, but these findings are indeed from the react-dates source code.

**Comment by majapw** [comment]
So the actual issue of `onClick` being noninteractive divs will be solved by https://github.com/airbnb/react-dates/pull/301 and is more explicitly outlined by https://github.com/airbnb/react-dates/issues/28 as an issue.

The problem of `react-a11y` logging this to the console seems like a configuration issue with the parent app using `react-a11y`. I'm going to close this issue in favor of #28.
