### ISSUE TITLE
TypeError: moment.default is not a function

### ISSUE THREAD

**Issue by taiphamv** [airbnb/react-dates#2027]
**react-dates version**
react-dates@21.8.0
**react version**
react@16.9.0

**Describe the bug**
I use react to build theme wordpress. When I use `react-dates` component. The error display as attachment image.
![Moment-Error](https://user-images.githubusercontent.com/11961973/87809363-7b1e2480-c885-11ea-8bb3-3bc922f6090d.PNG)

My webpack config is:
```
const defaults = require("@wordpress/scripts/config/webpack.config");
const path = require("path");
module.exports = {
  ...defaults,
  externals: {
    react: "React",
    "react-dom": "ReactDOM",
  },
  node: {
    fs: "empty",
    module: "empty",
  },
  resolve: {
    modules: ["node_modules"],
  },
  module: {
    ...defaults.module,
    rules: [
      ...defaults.module.rules,
      {
        use: "babel-loader",
        exclude: /node_modules/,
        test: /\.js$/,
      },
      {
        test: /\.css$/i,
        use: ["style-loader", "css-loader"],
      },
  },
};
```
Can you give me advice for webpack config or something for it?

**Comment by ljharb** [comment]
Did you figure out your issue?

Typically this is a babel configuration error.

**Comment by taiphamv** [comment]
Thank you very much @ljharb. This issue related babel configuration. I resolved this issue.
