### ISSUE TITLE
Q/A: Adjusting the size of date range picker ?

### ISSUE THREAD

**Issue by cemremengu** [airbnb/react-dates#203]
Is it possible to make date range picker smaller than the default size or make it fluid without fiddling with the scss ?

**Comment by majapw** [comment]
Hi @cemremengu, what specifically are you trying to adjust? Like the individual `CalendarDay` squares?

**Comment by majapw** [comment]
This exists now!

**Comment by cemremengu** [comment]
@majapw I was watching from shadows due to my work load. :eyes:  Thank you for your hard work!
