### ISSUE TITLE
Can't navigate more then 3 months ahead

### ISSUE THREAD

**Issue by alexanderwassbjer** [airbnb/react-dates#2034]
I have a problem. I use the airbnb react-dates date picker and I want to be able to navigate 12 months from current date. All the demos and also my date picker can only navigate 3 months from current date with the nextMonth button.

Anyone have a clue what's going on?

**Comment by mmarkelov** [comment]
@alexanderwassbjer could you provide some code example? Looked through [default example](http://airbnb.io/react-dates/?path=/story/daterangepicker-drp--default) -seems to be ok

**Comment by mmarkelov** [comment]
@alexanderwassbjer looks strange. Cause I'm able to do it
<img width="641" alt="Снимок экрана 2020-08-20 в 20 15 15" src="https://user-images.githubusercontent.com/22371328/90803828-02960200-e322-11ea-8350-a69e2e65d4f4.png">

**Comment by alexanderwassbjer** [comment]
@mmarkelov 
It works perfect in chrome but not in safari both macOS safari and iOS safari.
Do you have a clue why it dosen't work in safari?
I think it should work in safari like it does in chrome.

Thanks!

**Comment by alexanderwassbjer** [comment]
Any status on this?

**Comment by mmarkelov** [comment]
@alexanderwassbjer still can't reproduce it. Do you try to navigate to next month with your keyboard?

**Comment by petercherm** [comment]
I can confirm the issue, we are having that issue on iOS14, both on iPad and iPhone. It's not possible to navigate beyond December 2020.

**Comment by JimmyGray** [comment]
I'm having the same issue on iOS14. I temporarily fixed it by setting transitionDuration={0}. Hope this helps! @alexanderwassbjer

**Comment by constantin-barbu** [comment]
Also experiencing this issue. @JimmyGray 's solution works until it gets fixed, thank you!

**Comment by plamenh** [comment]
Not only ahead, but backwards as well. @JimmyGray ‘s temp fix works.

**Comment by alexanderwassbjer** [comment]
@mmarkelov 
Can you reproduce it now? When 4 more people experience the same bug and also that is only appears on iOS 14 on safari.

**Comment by mmarkelov** [comment]
@alexanderwassbjer I can reproduce it only for mobile browsers. It's ok for desktop safari.

**Comment by BlairOu** [comment]
> I'm having the same issue on iOS14. I temporarily fixed it by setting transitionDuration={0}. Hope this helps! @alexanderwassbjer

It will lose the animating If use **transitionDuration={0}** , this is not a good way for me
