### ISSUE TITLE
Localization does not work if start date is given

### ISSUE THREAD

**Issue by sumeyradavran** [airbnb/react-dates#2035]
If I give a start date value, localization does not work. You can see an example in https://codesandbox.io/s/react-dates-class-it4v7?file=/src/index.js

If I set start date as null, everything works.

`import React from "react";
import ReactDOM from "react-dom";
import moment from "moment";
import "moment/min/locales.min";
import "react-dates/initialize";
import "react-dates/lib/css/_datepicker.css";
import { DateRangePicker } from "react-dates";

import "./styles.css";

class App extends React.Component {
  dateRange = {
    start: moment().subtract(2, "years"),
    end: moment().add(1, "year").endOf("year")
  };

  state = {
    startDate: moment(),
    endDate: null,
    focusedInput: null,
    lang: "en"
  };

  handleChange = (event) => {
    this.setState({ lang: event.target.value });
  };

  render() {
    const { lang, focusedInput } = this.state;

    moment.locale(lang);

    return (
      <div className="App">
        <div>
          <select value={lang} onChange={this.handleChange}>
            <option value="tr">Tr</option>
            <option value="en">En</option>
            <option value="de">De</option>
            <option value="ru">Ru</option>
          </select>
        </div>
        <DateRangePicker
          startDate={this.state.startDate}
          startDateId="your_unique_start_date_id"
          endDate={this.state.endDate}
          endDateId="your_unique_end_date_id"
          onDatesChange={({ startDate, endDate }) => {
            this.setState({ startDate, endDate });
          }}
          focusedInput={focusedInput}
          onFocusChange={(focusedInput) => this.setState({ focusedInput })}
        />
      </div>
    );
  }
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
`

**Comment by gggiiia** [comment]
this was closed, did you firgured out the problem?

**Comment by mindaugasnakrosis** [comment]
@sumeyradavran How did you solve this? I have the same problem.

**Comment by sumeyradavran** [comment]
@mindaugasnakrosis can you please take a look at https://codesandbox.io/s/react-dates-9xcsl?file=/src/DateRangeSelector.js the idea is to call moment with locale.

**Comment by HakanSungur** [comment]
I have the same problem in the new version, what can I do?

**Comment by HakanSungur** [comment]
```
const defaultDateRange = {
  startDate: moment().add(7, "days"),
  endDate: moment().add(11, "days"),
};
```
```
const defaultDateRange = {
  startDate: null,
  endDate: null,
};
``` 
It is solved when you give a null value. But I don't want to give null value.
