### ISSUE TITLE
Moment 2.26.0 breaks the typing of dates in any component

### ISSUE THREAD

**Issue by pramodsum** [airbnb/react-dates#2036]
**react-dates version**
react-dates@21.8.0

**Describe the bug**
Moment 2.26.0 breaks the typing of dates in any component in `react-dates`

**Source code (including props configuration)**
1. Set dependency to "moment": "2.26.0" or higher and pass in a date into the DayPicker
2. Compile code with typescript@3.3.3

**Screenshots/Gifs**
```
error TS2741: Property 'isoWeeksInISOWeekYear' is missing in type 'import("/root/code/js/packages/bricks-storybook/node_modules/moment/moment").Moment' but required in type 'moment.Moment'
```

**Desktop (please complete the following information):**
 - OS: Catalina 10.15.6
 - Browser Chrome
 - Version 84.0.4147.135

**Smartphone (please complete the following information):**
N/A

**Is the issue reproducible in Storybook?**
No

**Additional context**
There were similar issues with other packages that consume `moment` such as https://github.com/ant-design/ant-design/issues/24377

**Comment by ljharb** [comment]
Sounds like this is an issue with the moment.js DefinitelyTyped package?

**Comment by TC-mSundaram** [comment]
To me it seems like the opposite - that the typings for react-dates is out of date with Moment

**Comment by ljharb** [comment]
@TC-mSundaram react-dates has no types, so either way it's an issue with DefinitelyTyped.

**Comment by TC-mSundaram** [comment]
@ljharb Ah ok, sorry. And thank you!
