### ISSUE TITLE
How to set the end date using onDatesChange prop for DateRangePicker?

### ISSUE THREAD

**Issue by sindhuanamal** [airbnb/react-dates#2040]
Hi, i am new to using react-dates.

i am trying to set the end date when user clicks on a date on calendar.

currently my code is as below, which sets the start date and end date. end date is 4 weeks from todays date. (schedule now how can i determine the end date when user clicks on calendar.

    function handleDateChange = (dates: { startDate: moment.Moment | null }){
         const { startDate: newStartDate } = dates;

         if (newStartDate) {
             const newEndDate = moment(newStartDate)
                 .add(4, 'weeks')
                .subtract(1, 'day');
             setStartDate(newStartDate);
             setEndDate(newEndDate);
          }
      }
    }
    <DateRangePicker
          onDatesChange={handleDateChange}
        />

how can i set the end date or retrieve end date in handleDateChange method. could someone help me with this. thanks.

**Comment by mmarkelov** [comment]
@sindhuanamal hello!
**end date** is passed inside **onDatesChange** method as **endDate**:
```js
const { startDate: newStartDate, endDate } = dates;
```

**Comment by sindhuanamal** [comment]
thanks. how does the daterangepicker component detect start and end dates. just for knowing it in more detail.

**Comment by mmarkelov** [comment]
@sindhuanamal you can check this method:
https://github.com/airbnb/react-dates/blob/5b29610dba5a00c0e61ac6c84ea58f0991690d4f/src/components/DayPickerRangeController.jsx#L586-L673

**Comment by sindhuanamal** [comment]
thanks a lot.
