### ISSUE TITLE
Remove dependency on MomentJS

### ISSUE THREAD

**Issue by vipul0092** [airbnb/react-dates#2043]
MomentJS has announced that it a legacy project in maintenance mode. Not dead, but it is indeed done.
https://momentjs.com/docs/#/-project-status/

Would it make sense to remove the dependency on moment from this library? Especially now that Moment is a deprecated library, has a huge size and is not tree-shakeable.
The Momentjs team has recommended some libraries which can be used in its place.

**Comment by mmarkelov** [comment]
@vipul0092 you can check #208 and #1294

**Comment by tonyhb** [comment]
Also https://github.com/airbnb/react-dates/pull/1947.

This has been stonewalled as the maintainer is saying that temporal is close and this is unnecessary.  It's been this reason for over 2 years now.

**Comment by ljharb** [comment]
Duplicate of #208 and others.
