### ISSUE TITLE
Official support for Moment has (finally) been discontinued

### ISSUE THREAD

**Issue by davea38** [airbnb/react-dates#2044]
I'd love to use this library, but moment is too heavy. Finally it's been officially discontinued... could I please request you change to date-fns?!

[Moment repo](https://github.com/moment/moment/)

**Comment by ljharb** [comment]
This is a duplicate of #208, in which it's explained that we'll be on moment until Temporal is stage 3, at which point we'll migrate to that.

**Comment by davea38** [comment]
Thanks for the clarification 👍
