### ISSUE TITLE
Not enough control in `renderMonthElement` method `onMonthSelect`

### ISSUE THREAD

**Issue by drzhbe** [airbnb/react-dates#2045]
**react-dates version**
react-dates@21.8.0

**Describe the bug**
The only way to allow users to change a month and a year separately is through `renderMonthElement`.
This API exposes `onMonthSelect` and `onYearSelect` functions. [It works fine](http://airbnb.io/react-dates/?path=/story/daypickersingledatecontroller--single-month-custom-caption) if you use `<select>` controls for both a month and a year.
I want to have arrows for both a year selection and a month selection. In this case, when a month changes between January and December, I want the year to also change.
The current API doesn't allow it – I've tried calling both `onMonthSelect` and `onYearSelect`, but only the last one is applied.

**Source code (including props configuration)**
```js
<DayPickerSingleDateControllerWrapper
  onOutsideClick={action('DayPickerSingleDateController::onOutsideClick')}
  onPrevMonthClick={action('DayPickerSingleDateController::onPrevMonthClick')}
  onNextMonthClick={action('DayPickerSingleDateController::onNextMonthClick')}
  numberOfMonths={1}
  renderMonthElement={({ month, onMonthSelect, onYearSelect }) => (
    <div style={{
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      marginTop: -10,
    }}>
      <div>
        <button onClick={() => {
          onYearSelect(month, month.year() - 1);
        }}>
          ←
        </button>
        <span>{month.year()}</span>
        <button onClick={() => {
          onYearSelect(month, month.year() + 1);
        }}>
          →
        </button>
      </div>
      <div>
        <button onClick={() => {
          const newMonthVal = moment(month).subtract(1, 'month').month();
          // Switch from January to December should subtract a year.
          if (newMonthVal === 11) {
            onYearSelect(month, month.year() - 1);
          }
          onMonthSelect(month, newMonthVal);
        }}>
          ←
        </button>
        <span>{month.format('MMM')}</span>
        <button onClick={() => {
          const newMonthVal = moment(month).add(1, 'month').month();
          // Switch from December to January should add a year.
          if (newMonthVal === 0) {
            onYearSelect(month, month.year() + 1);
          }
          onMonthSelect(month, newMonthVal);
        }}>
          →
        </button>
      </div>
    </div>
  )}
/>
```

**Screenshots/Gifs**
![month-of-next-year](https://user-images.githubusercontent.com/1445539/93549953-c4860f80-f9ad-11ea-9c3e-93069a82a2b0.gif)

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.6
 - Browser Chrome
 - Version 85.0.4183.102 (Official Build) (64-bit)

**Is the issue reproducible in Storybook?**
The story for the case doesn't exist yet.

**Comment by Lyrics1** [comment]
> Why close this question, have you solved it? , I also encountered this problem

**Comment by drzhbe** [comment]
I've tried fixing the API, but it turned out to be more complicated in the current architecture.
So I went with a dropdown for the month selection on my side :)

**Comment by jesiolowski-wsb** [comment]
hello, I have a veeery similar issue .
I have a dropdown with values consisting of current month + 11 months in advance (read: values reaching to 'next year'). From  usability perspective, there is no point in having a separate dropdown for 'year' with 2 values, and it seems that current implementation doesn't allow switching from dec 2022 to jan 2023 using `onYearSelect` and `onMonthSelect` both at once. 

Is there any possibility to handle this use case using react-dates? any method I'm not aware of?

**Comment by vsarthak21** [comment]
Please reopen this
