### ISSUE TITLE
Not an issue but don't know where to ask

### ISSUE THREAD

**Issue by TomaIvanovTomov** [airbnb/react-dates#2049]
Excuse me for my question! It might be something simple but didn't find answer around google.
How can I add react package in simple javascript? I wan't to use the react-dates package but don't understand how and can I use it in plain javascript project. 
Thank you!

**Comment by ljharb** [comment]
To use basically anything these days, you need to npm install it, and use a module bundler to deliver it to the web. There’s a number of tutorials for this floating around. Good luck!
