### ISSUE TITLE
[IOS 14] When I click the arrow to move for he next month, it only move to the next 3 months! and not after that!

### ISSUE THREAD

**Issue by HadeerFawzy** [airbnb/react-dates#2050]
**react-dates version**
e.g. react-dates@18.3.1

**Describe the bug**

**Source code (including props configuration)**
```jsx
<DateRangePicker
  startDate={this.state.startDate}
  startDateId="your_unique_start_date_id"
  endDate={this.state.endDate}
  endDateId="your_unique_end_date_id"
  onDatesChange={({ startDate, endDate }) => this.setState({ startDate, endDate })}
  focusedInput={this.state.focusedInput}
  onFocusChange={focusedInput => this.setState({ focusedInput })}
/>
```

**Comment by mmarkelov** [comment]
@HadeerFawzy just made PR that should fix it. You can use `transitionDuration={0}` for a while

**Comment by matejstrasek** [comment]
Thanks,` transitionDuration={0} ` works. Would be great to get the fix merged soon though.

**Comment by HadeerFawzy** [comment]
Yes I need this to get merged ASAP

**Comment by duran91** [comment]
This issue is closed and apparently resolved but our team recently experienced the same bug inside a wkwebview. The transitionDuration={0} patched the issue

**Comment by ljharb** [comment]
@duran91 the PR is merged, but the fix has not yet been released.
