### ISSUE TITLE
What props should I use to create a tooltip?

### ISSUE THREAD

**Issue by goongoguma** [airbnb/react-dates#2052]
Thank you for this amazing library. I love it.

I have a question: What callback props should I use to create a tooltip?

I want to show tooltip when user hovers a dates on the calendar. According to this [issue](https://github.com/airbnb/react-dates/issues/94), renderDay props is recommended to create it but looks like this is not available current version.

**Comment by Yair-Ohana** [comment]
Any update?
same issue here ..

**Comment by AdeolaFaraday** [comment]
`<DateRangePicker
                            startDate={'start date here'}
                            startDateId="your_unique_start_date_id"
                            endDate={'end date here}
                            renderDayContents={(day) => {
                                return (
                                    <Tooltip
                                        title={`tool tip title`}
                                    >
                                        <div
                                            className="searchDay"
                                            onMouseEnter={() =>
                                                console.log({ day })
                                            }
                                        >
                                            {moment(day).format('D')}
                                        </div>
                                    </Tooltip>
                                );
                            }} />`
                            
                 // you can use the renderDayContents to render the html of the day, for example you can wrap it in a tootlip
                 
                 i hope this helps someone
