### ISSUE TITLE
SyntaxError: Unexpected token 'export' when using SingleDatePicker

### ISSUE THREAD

**Issue by adoratour** [airbnb/react-dates#2053]
![issue](https://user-images.githubusercontent.com/65339923/96671937-3b3b7180-138d-11eb-8959-67f5107f3a8f.PNG)
Hi, I got this issue when using SingleDatePicker, but DateRangPicker still Work

**Comment by ljharb** [comment]
If you're using the `esm` dir, you need to be using a bundler like webpack or rollup that understands ESM import/export syntax.

Separately, never use `file://`, many things are broken in browsers with that. Only ever use a proper http/https server.

**Comment by adoratour** [comment]
Hi, i am using webpack bundle, but can u please guide me about this line " Separately, never use file://, many things are broken in browsers with that. Only ever use a proper http/https server.?" can u please guide me directly, please?

**Comment by ljharb** [comment]
I'm saying, don't test things by loading an HTML file using the `file:` protocol. Use a local webserver, and access it in the browser via `http:` or `https:`. Typically, your bundler can provide this with some kind of dev server.
