### ISSUE TITLE
renderDayContents passing Years in negative 

### ISSUE THREAD

**Issue by iamRamkumar** [airbnb/react-dates#2054]
we are using both DateRangePicker and SingleDatePicker in our app. In **SingleDatePicker** **renderDayContents** passing year in **negative** (Date Sat Mar 31 -2021 12:00:00 GMT+0553 (India Standard Time)) on Mozilla firefox but in google chrome we are getting expected value (Wed Mar 31 2021 12:00:00 GMT+0530 (India Standard Time)) .

**current behaviour:** 
![image](https://user-images.githubusercontent.com/25427547/96881232-ac694a80-149b-11eb-98f9-2318215fca55.png)

**expected behaviour:** 

![image](https://user-images.githubusercontent.com/25427547/96881756-34e7eb00-149c-11eb-9049-cba5d20c2e5a.png)

**Mozilla Firefox version:** 72.0.2 (64-bit)
**Chrome version:** 86.0.4240.75 (Official Build) (64-bit)

**@types/react-dates version:** "^17.1.5"
**react-dates**: "^20.2.5"
**moment**: "^2.24.0"
**react-moment-proptypes**: "^1.6.0"

**Comment by mmarkelov** [comment]
@iamRamkumar could you provide small representation with [codesandbox](https://codesandbox.io/) for example?

**Comment by iamRamkumar** [comment]
> @iamRamkumar could you provide small representation with [codesandbox](https://codesandbox.io/) for example?

@mmarkelov please refer the below: https://codesandbox.io/s/bold-firefly-bn0jb?file=/pages/index.js

**Comment by iamRamkumar** [comment]
It seems due to we are passing date in `DD-MMM-YYYY` format to prop `initialVisibleMonth` which led to the issue. 

`initialVisibleMonth={() => moment(disableDateBefore)}`

where `disableDateBefore = "15-Feb-2021"`

issue resolved with below code:

`initialVisibleMonth={() => moment(
            moment(disableDateBefore, 'DD-MMM-YYYY')
              .format(),
          )}`
