### ISSUE TITLE
Feature Request: Support unselecting a selected date by clicking on it

### ISSUE THREAD

**Issue by joaopsrleal** [airbnb/react-dates#2061]
**react-dates version**
react-dates@15.5.3

**Describe the bug**
This is mostly a feature request. When using the single date picker, it is not possible to unselect a currently selected date by clicking on the already-selected date. This FR was initially [filed in AMP's repo](https://github.com/ampproject/amphtml/issues/25609). [AMP uses the `DayPickerSingleDateController`](https://github.com/ampproject/amphtml/blob/b6313e372fdd1298928e2417dcc616b03288e051/extensions/amp-date-picker/0.1/single-date-picker.js#L33) for building the single date component. 

We would like to support the use-case of unselecting a date by clicking it again. However, instead of building this on our side, we thought it would be a good idea to fully support it on the `react-dates` side since that would be more sustainable and would potentially benefit others.

I've already explored a possible solution for this (see my comments in the [original FR](https://github.com/ampproject/amphtml/issues/25609)). I'd be happy to contribute with a PR for this.

**Is the issue reproducible in Storybook?**
Select a date on the [demo DayPickerSingleDateController](http://airbnb.io/react-dates/?path=/story/daypickersingledatecontroller--default) and then clicking that same date again. The date is not unselected on the second click.

**Comment by joaopsrleal** [comment]
As I mentioned in the issue's description, I'm happy to tackle this. Let me know what you think :)

**Comment by ljharb** [comment]
Thanks, a PR sounds great.

**Comment by joaopsrleal** [comment]
Perfect. If possible, could you please assign me to the issue then?

**Comment by ljharb** [comment]
Sure, done, altho that’s not usually needed.

**Comment by joaopsrleal** [comment]
Ah good to know, thanks for the heads up.

**Comment by joaopsrleal** [comment]
Hey @ljharb I've finally had some time to prepare a PR for this issue (https://github.com/airbnb/react-dates/pull/2066). What should I do to get it reviewed? Would you be the right person to do it?

**Comment by ljharb** [comment]
thanks! atm I'm the only person paying much attention; i'll take a look as soon as i have time.

**Comment by dijodaiju7** [comment]
I'm Interested in this issue. Can you please assign it to me? @ljharb

**Comment by joaopsrleal** [comment]
Hey @dijodaiju7, there's a PR in review for this. It's linked in a comment above (this is the PR: #2066). Thanks for showing interest :)
