### ISSUE TITLE
Question: How do I change the shape of the selected/hovered calendar days from square to round?

### ISSUE THREAD

**Issue by jdiaz-xactly** [airbnb/react-dates#2062]
I'm trying to change the selected and hovered calendar days from square to round but it seems that since the date is directly in a `td` element it isn't possible do without the whole calendar day becoming round, which doesn't work for spanned selections (see screen shot). It seems that to make this work correctly the date would need to be in a `div` within the `td`. Any thoughts or suggestions on how to make this work?

<img width="137" alt="Screen Shot 2020-11-05 at 7 54 10 AM" src="https://user-images.githubusercontent.com/57644757/98257475-f55ddc00-1f3c-11eb-8676-4e52041f725c.png">

**Comment by ljharb** [comment]
CalendarDay takes a `renderDayContents` prop that may be helpful.

**Comment by jdiaz-xactly** [comment]
this is exactly what I need, thanks!
