### ISSUE TITLE
Can't install with react 17.0.1

### ISSUE THREAD

**Issue by bobbyZ94** [airbnb/react-dates#2067]
**react-dates version**
react-dates@21.08.0

**Describe the bug**
Can't install with react 17:

PS C:\Users\Robert\Projects\WebdevProjects\ReactCourse\exp-app> npm i react-dates
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: exp-app@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14 || ^15.5.4 || ^16.1.1" from react-dates@21.8.0
npm ERR! node_modules/react-dates
npm ERR!   react-dates@"^21.5.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

**Desktop:**
 - OS: Windows
- React: 17.0.1

**Seems to work with:**
npm i --legacy-peer-deps react-dates

though there are new warnings: 
0.chunk.js:35261 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

0.chunk.js:35261 Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

**Comment by ljharb** [comment]
That's because this package isn't compatible with react 17 yet.
