### ISSUE TITLE
startDatePlaceholderText & endDatePlaceholderText not updating after props update

### ISSUE THREAD

**Issue by lamashree** [airbnb/react-dates#2075]
I am using DateRangePicker in Child component. start date and end date getting as a props. After getting the props I can see the placeholder text for start date and end date are perfect. onDatesChange the placeholder update successfully with new dates which I have selected. But if I changed the dates in parent component, we are getting the updated dates as props, but placeholders are not updated. Can you please look into this.

**Comment by ljharb** [comment]
Duplicate of #2074.
