### ISSUE TITLE
bump lodash to 4.17.20

### ISSUE THREAD

**Issue by dodedom** [airbnb/react-dates#2080]
this application's usage of lodash:4.1.1 results in the following vulnerability(s):
(CVSS9.8: critical) https://snyk.io/vuln/SNYK-JS-LODASH-590103

suggested upgrade to 4.17.20

**Comment by ljharb** [comment]
1. the vulnerability is, like most CVEs, a false positive. Prototype pollution is only an issue when unserializing unsanitized/uintrusted user data, and that's not how we're using lodash. Thus, you can safely ignore this warning.
1. semver ranges mean that you'll already by default use the latest version of lodash, and `npm update` will update it. So, this package's usage of lodash *in no way* impedes anyone from avoiding the vulnerability warning.

Duplicate of #1737. Duplicate of #1838. Duplicate of #1839.
