### ISSUE TITLE
SassError: This function isn't allowed in plain CSS.

### ISSUE THREAD

**Issue by denny7** [airbnb/react-dates#2081]
**react-dates version**
react-dates@21.8.0

**Describe the bug**
Get 

> SassError: This function isn't allowed in plain CSS.
>   
> 152 │   color: darken(#cacccd,10%);
>    
>   node_modules/react-dates/lib/css/_datepicker.css 152:10  @import
>   src/assets/sass/app.scss 21:9                            root stylesheet

when trying to import css. I'm using next.js 10.0.0. In previos versions of next.js I didn't have this problem.

**Comment by ljharb** [comment]
Fixed by #2058. See also, #1513.

it will be in the next release (no planned date yet)

**Comment by austinhinderer** [comment]
@ljharb Any chance a release is coming soon? I'm encountering this issue and would love to get this fix.

**Comment by ljharb** [comment]
Unfortunately it’s not really practical for me to cut a release while i lack admin privileges on the repo; I’m in the process of sorting that out and unfortunately the release is waiting on it.

**Comment by austinhinderer** [comment]
Is this something that you believe will occur in days, weeks, or months?

**Comment by ljharb** [comment]
I honestly have no idea. It could be days, it could be much longer.

**Comment by austinhinderer** [comment]
Through some back channels, I poked AirBnB. There is no internal owner for this package at the moment, so they are trying to come to a decision on ownership. For now, I just internalized the CSS to my app and will re-assess if an update is released.

**Comment by m-nathani** [comment]
> internalized the CSS

Hey boss.. i am facing the same issue.. what do you mean by the `internalized the CSS` ?
