### ISSUE TITLE
Can I select only past dates?

### ISSUE THREAD

**Issue by Valentin1918** [airbnb/react-dates#209]
By using `isOutsideRange={() => false}` I enabled all past dates. Now I need something like `isInsideRange={() => true}` to disable all future dates. Does it exist some built in method to disable future dates? 
If not, can somebody advise, how can I use isDayBlocked method to block all future dates?
Thanks.

**Comment by Valentin1918** [comment]
isOutsideRange={day => !isInclusivelyBeforeDay(day, moment())}

**Comment by winterblack** [comment]
I get `Uncaught ReferenceError: isInclusivelyBeforeDay is not defined`

**Comment by ljharb** [comment]
@winterblack like anything else, you need to import that function to be able to use it. `import { isInclusivelyBeforeDay } from 'react-dates';` should suffice.

**Comment by mrmuhammadali** [comment]
how can I enable dates of last 30 days?

**Comment by majapw** [comment]
Hi @mrmuhammadali, if you want to enable only the last thirty days, you could use isOutsideRange as follows:

```
isOutsideRange={(day) => day.isBefore(moment()) && day.isAfter(moment().subtract(1, 'month))}
```

I'd recommend setting `initialVisibleMonth` to `moment().subtract(1, 'month')` in that case as well. There are some optimizations you could do (caching `moment()` for instance), but that's the general gist.

**Comment by mrmuhammadali** [comment]
Hi @majapw, I tried your code but it enables every other date except for last 30 days. :(

**Comment by majapw** [comment]
Then just flip the boolean?

**Comment by mrmuhammadali** [comment]
Hi @majapw, I tried this but it is enabling all dates.
`isOutsideRange={(day) => !day.isBefore(moment()) && !day.isAfter(moment().subtract(1, 'month'))}`

**Comment by mrmuhammadali** [comment]
I tried this: `isOutsideRange={(day) => day.isAfter(moment()) || day.isBefore(moment().subtract(30, 'days'))}` and it worked like a charm.
Thanks 👍

**Comment by awitherow** [comment]
just wanted to contribute to this thread as it helped me... I am using the following code to limit selection to the last 30 days, and exclude the future as well... if you see a problem or way I could upgrade it, lemme know 👍

```javascript
isOutsideRange={day =>
    !day.isAfter(moment().subtract(1, "month")) ||
    !isInclusivelyBeforeDay(day, moment())
}
```

**Comment by kinsomicrote** [comment]
Is there a way to disabled specific dates? Say I have a series of dates which can be apart by a few days (20, 24, 30), how do I go about disabling them in the datepicker?

**Comment by SumanDontha16** [comment]
Is there a way to disable the current date like(today)? Does it exist some built in method to disable
