### ISSUE TITLE
Focused element is off by one when selecting start date

### ISSUE THREAD

**Issue by multiwebinc** [airbnb/react-dates#2090]
**react-dates version** 21.8.0

**Describe the bug**
When selecting a start date, the end date that gets focused for keyboard navigation is off by one day.

**Source code (including props configuration)**
https://codesandbox.io/s/react-dates-date-range-picker-forked-oyxpn?file=/src/date-picker.jsx
Select a start date and then move your mouse over any of the dates after the one selected (at least 2 days later). The element that has focus is the date 2 days after the first selected date, which you can see there is a black outline around it.

**Screenshots/Gifs**
![image](https://user-images.githubusercontent.com/901732/107834422-bcaf7900-6d5b-11eb-8e2e-b73ebf4faa56.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version: 88.0.4324.150

**Is the issue reproducible in Storybook?**
No

**Comment by multiwebinc** [comment]
It appears react-dates expects the dates to be at noon for some reason, so setting the dates like this solved the issue:

```js
<DateRangePicker
  startDate={inDate ? moment(inDate + " 12:00") : null}
  endDate={outDate ? moment(outDate + " 12:00") : null}
  // ...
/>
```

**Comment by ljharb** [comment]
We had to pick some time, and midnight doesn’t exist in every timezone ¯\_(ツ)_/¯

**Comment by multiwebinc** [comment]
@ljharb That's interesting. Thanks for the comment.
