### ISSUE TITLE
Add option to show full last week, overlapping next month, for UX

### ISSUE THREAD

**Issue by caub** [airbnb/react-dates#2108]
It's much easier to pick days on a week base
If the week ends Friday 30th, currently you have to go look far away to find next day

I propose we add an option to display the full weeks (first and last of each month)
![2021-04-28-220633_595x317_scrot](https://user-images.githubusercontent.com/3134574/116466238-88cdf500-a86e-11eb-82a8-59a5b2f0245d.png)

**Comment by nkinser** [comment]
There's already a prop [enableOutsideDays](https://github.com/airbnb/react-dates/blob/master/src/components/DayPickerRangeController.jsx#L73) that handles this. 
https://airbnb.io/react-dates/?path=/story/drp-calendar-props--with-outside-days-enabled

**Comment by caub** [comment]
Oh thanks! didn't find it yesterday
