### ISSUE TITLE
Maybe bring back modifiers on DateRangePicker

### ISSUE THREAD

**Issue by ChristerGustavsson** [airbnb/react-dates#211]
I've seen that modifiers prop has been removed from DateRangePicker and now only exists on DayPicker. I was wondering if the prop could be brought back so it's easier to extend with custom classes and so on.

I wanted to use modifiers to add a "today" class but maybe that's a generic enough feature that it could be added by default instead? I dunno and leave that decision up to you guys.

**Comment by majapw** [comment]
The modifiers prop has never been on the `DateRangePicker`. Having a `today` modifier seems really reasonable though and I would definitely be open to adding that. I probs won't have bandwidth until after Friday, but would def approve a PR that did this.

**Comment by ChristerGustavsson** [comment]
I see now that you're correct about modifiers not being a prop on DateRangePicker. I should've looked further into the commit https://github.com/airbnb/react-dates/commit/1984a74cd6d33628efaefb437b67ac3b9d568412 than just the commit message.

But nevertheless, I've created a small PR with only adding the today modifier without any styling because I wasn't sure how the process goes for that.
