### ISSUE TITLE
How can i build React Dates with Vitejs

### ISSUE THREAD

**Issue by datpt11** [airbnb/react-dates#2114]
----------- when dev -----------
when dev everything is fine
![image](https://user-images.githubusercontent.com/48908789/117392195-c6d8b200-af1b-11eb-93bc-43f19423f544.png)
----------- when build -----------
![image](https://user-images.githubusercontent.com/48908789/117392112-9a249a80-af1b-11eb-94c5-574ae64a12d4.png)

-----------dependencies-----------
"react": "^17.0.0",
"react-dates": "^21.8.0",

**Comment by ljharb** [comment]
react-dates is a CJS module, so you’d have to bundle it (not script type=“module”). If it’s not working with Vite, please file a bug there.
