### ISSUE TITLE
MomentJS is now deprecated: Any plans to migrate?

### ISSUE THREAD

**Issue by LucyMac** [airbnb/react-dates#2125]
Hello, as you likely know [MomentJS have announced](https://momentjs.com/docs/#/-project-status/) they will no longer be developing the library, and are encouraging the use of alternatives such as Day.JS, date-fns etc. 

Any plans to migrate `react-dates` away from Moment?

**Comment by ljharb** [comment]
It is not deprecated, in fact; the announcement doesn’t use that term.

Temporal recently got stage 3. Once there’s a production-ready polyfill (none exists yet) then every date library you mentioned, including moment, is immediately obsolete, and react-dates will migrate to it.

In the meantime, it would be wasted effort to migrate off of moment - which remains the de facto standard regardless of what it’s maintainers announce.

**Comment by LucyMac** [comment]
Thanks, I didn't know about Temporal

An overview for those interested: [javascript-temporal-api-introduction](https://www.sitepoint.com/javascript-temporal-api-introduction/)

**Comment by anshubaldeep** [comment]
What would you say now? Is it still not a good time to migrate, 2 years later?

**Comment by ljharb** [comment]
Temporal is stage 3, but it's still making normative changes every 2 months. When that settles down, *then* a sufficiently backwards-compatible polyfill can be created (none yet exists), and *then* we can migrate react-dates to it.
