### ISSUE TITLE
Need single date calendar grid without borders

### ISSUE THREAD

**Issue by puneetgupta1** [airbnb/react-dates#2135]
I am new to react-dates and trying to find a way to create a calendar without borders in the grid. Can you please help me styling this using DayPickerSingleDateController?

**Comment by puneetgupta1** [comment]
<img width="219" alt="PNG image 3" src="https://user-images.githubusercontent.com/26937476/126734154-c45ad4b6-8bf4-408d-a22e-b64d972b92c9.png">

**Comment by puneetgupta1** [comment]
I need a calendar with above screenshot.

**Comment by opqpop** [comment]
bump, did you ever figure this out? also would like this!

**Comment by benkindt** [comment]
You use noBorder-prop for the outside calendar border.

The fastest way to remove the border around the days is via css.
Try something like:
```
td.CalendarDay {
    border: 0px;
}
```

**Comment by ljharb** [comment]
Seems answered.
