### ISSUE TITLE
when building with esbuild there is a runtime error. 

### ISSUE THREAD

**Issue by huvber** [airbnb/react-dates#2138]
**react-dates version**
e.g. react-dates@18.3.1

**Describe the bug**
I'm trying to build an application with `esbuild` that has react-dates as dependency but I come out with a runtime error related to a dep of the library. I also notice that in order to build I need to add `@babel/runtime` as dep. 

I create a test project to reproduce it.

**Source code (including props configuration)**

src/index.tsx
```javascript
import { useState } from 'react';
import { render } from 'react-dom';
import 'react-dates/initialize';
import { DateRangePicker, FocusedInputShape } from 'react-dates';
import moment, { Moment } from 'moment';

const App = () => {
  const [startDate, setStartDate] = useState<Moment>(moment());
  const [endDate, setEndDate] = useState<Moment>(moment());
  const [focus, setFocus] = useState<FocusedInputShape | null>(null);
  return (
    <section>
      <header>
        <DateRangePicker
          startDate={startDate}
          startDateId="start-date"
          endDate={endDate}
          endDateId="end-date"
          onDatesChange={({ startDate, endDate }) => {
            if (startDate) setStartDate(startDate);
            if (endDate) setEndDate(endDate);
          }}
          focusedInput={focus}
          onFocusChange={(focusedInput) => setFocus(focusedInput)}
        />
        <h2>This is a test</h2>
      </header>
      <main></main>
    </section>
  );
};

render(<App />, document.querySelector('main'));
```

esbuild.config.js
```javascript
const { pnpPlugin } = require('@yarnpkg/esbuild-plugin-pnp');
const esbuild = require('esbuild');

esbuild.build({
  entryPoints: {
    index: 'src/index.tsx',
    'index.html': 'src/index.html',
  },
  assetNames: '[name]',
  inject: ['./react-shim.js'],
  bundle: true,
  outdir: 'build',
  loader: {
    '.html': 'file',
  },
  plugins: [pnpPlugin()],
});
```

tsconfig.json
```json
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "jsx": "react-jsx",
    "lib": ["esnext", "dom"],
    "moduleResolution": "node",
    "noImplicitAny": false,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "outDir": "build/",
    "preserveConstEnums": true,
    "resolveJsonModule": true,
    "removeComments": false,
    "skipLibCheck": true,
    "sourceMap": true,
    "strictNullChecks": true,
    "target": "esnext",
    "forceConsistentCasingInFileNames": false
  },
  "include": ["src"]
}
```

react-shim.js
```javascript
import * as React from 'react';
export { React };
```

package.json
```json
{
  "name": "test-react-dates",
  "sideEffects": false,
  "main": "build/index.js",
  "files": [
    "build"
  ],
  "scripts": {
    "build": "rm -rf build && yarn node esbuild.config.js"
  },
  "devDependencies": {
    "@babel/runtime": "^7.14.8",
    "@types/react": "^17.0.13",
    "@types/react-dates": "^17.1.5",
    "@types/react-dom": "^17",
    "@yarnpkg/esbuild-plugin-pnp": "^1.0.0-rc.13",
    "esbuild": "^0.12.16"
  },
  "dependencies": {
    "moment": "^2.29.1",
    "react": "^17.0.2",
    "react-dates": "^21.8.0",
    "react-dom": "^17.0.2"
  }
}
```

**Screenshots/Gifs**
<img width="844" alt="image" src="https://user-images.githubusercontent.com/5032333/126964180-120806f9-83b6-42ea-8d1a-a4d623544988.png">

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS]
 - Browser [e.g. firefox, chrome]

**Comment by ljharb** [comment]
This seems like something you’d need to file on esbuild.

**Comment by huvber** [comment]
I don't think so because actually seems that react-dates is only build in commonjs or umd and not in esm so esbuild can't use the module system and need to add the umd that actually using `require` not allowed in the browser. Probably others building system replace that. Would be nice to have the esm build of react-dates in order to use it properly.

**Comment by ljharb** [comment]
The vast majority of npm is CJS and will be so forever; a bundler that can’t handle that well isn’t particularly good at it’s only job.

If there’s an issue with building the library with esbuild but not with webpack or browserify (the de facto standards), then it’s a problem with esbuild. Can you reproduce it with another bundler?

**Comment by huvber** [comment]
I understand what do you say but the fact that the library doesn't support the import as a module (in ESM) is not a matter of the bundler. In my opinion is a missing thing of the library. This won't be useful just for esbuild but also for webpack, rollup and others when they will deal with the tree shacking or if they want to bundle in ESM (to allow other to use it as a module). I don't really know if commonJS will be that forever but browsers and bundler are moving to support complete ESM so as a library maintainers I will at least consider it.

**Comment by huvber** [comment]
> If there’s an issue with building the library with esbuild but not with webpack or browserify (the de facto standards), then it’s a problem with esbuild. Can you reproduce it with another bundler?

If you try to build as a module in webpack or rollup and use it in a browser probably you would have the same problem if doesn't use babel but just a bundler.

**Comment by ljharb** [comment]
The library does support it - in node, and in every bundler except esbuild, it seems like.

I can guarantee you react-dates works, and has worked for years, in node, webpack, browserify, and even rollup.

**Comment by huvber** [comment]
I never said is not working, we are using it from a long time and it's working. What I'm saying that doesn't support the module feature and so the tree shacking and bundle it in ESM won't  behave correctly. I don't think would be difficult to make it work and there would be a lot of benefit to have that.

**Comment by ljharb** [comment]
I’m a bit confused; the title of the issue claims a runtime error.

It is an incredibly large bit of work to add node-native ESM, and it is a breaking change, and the value is quite tiny - deep imports make treeshaking unnecessary (and do a better job of keeping the bundle small than treeshaking possibly can)

However, react-dates/esm already exists.

**Comment by huvber** [comment]
I didn't know about that because I think it isn't mentioned in the documentation. Thanks a lot to share that with me I will try to use aliasing to see if works.
