### ISSUE TITLE
PrevMonth & NextMonth don't work correctly after upgrade to 4.1.1

### ISSUE THREAD

**Issue by yangaobo** [airbnb/react-dates#214]
After recently the updated to `4.1.1` from `4.1.0`, the `PrevMonth` & `NextMonth` arrows in `DayPicker` don't work as expected. Tested in Chrome (54.0.2840.98 64-bit) & Safari.

The `NextMonth` doesn't work at all (month won't change), whereas `PrevMonth` will cause 2 months overlay at first click and then stop working as well, like below.
<img width="324" alt="screen shot 2016-12-15 at 4 51 34 pm" src="https://cloud.githubusercontent.com/assets/5113450/21217446/36123efa-c2e7-11e6-9d4b-377517809318.png">

- However, in Chrome, if `click` (i guess because of the `focus` effect) within the days area first, they can work correctly.
- In Safari, even after `click` a day, the `Prev` & `Next` can only work once and initial month will never appear again (the element is still in DOM, but `data-visible` won't be set to true), for example, start with `Dec`, u can at most go next to `Jan` and then `Prev` will lead directly to `Nov`, vice versa.

Any known changes in 4.1.1 will cause above situation?

**Comment by majapw** [comment]
Yikes! This is true in the storybook, but doesn't seem to affect the DRP/SDP. I will investigate ASAP.

It seems likely to be related to https://github.com/airbnb/react-dates/pull/196.

**Comment by majapw** [comment]
Got a PR up! 👍 Thanks for flagging!

**Comment by majapw** [comment]
Okay, should be fixed in v4.1.2! :)
