### ISSUE TITLE
Cannot set horizontalMargin on SingleDatePicker component

### ISSUE THREAD

**Issue by aviskarkc10** [airbnb/react-dates#2162]
**react-dates version**
react-dates@21.8.1

**Describe the bug**
Looks like `horizontalMargin` was never passed to the component and thus can't be set. The value will always be `0`.

https://github.com/airbnb/react-dates/blob/master/src/components/SingleDatePicker.jsx#L595

Was this designed like this or is it a missing prop?

**Source code (including props configuration)**
```
<SingleDatePicker
 // This value never makes it to the component
  horizontalMargin={10}
/>
```

**Screenshots/Gifs**
-

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version: 96.0.4664.45

**Is the issue reproducible in Storybook?**
-

**Additional context**
-

**Comment by ljharb** [comment]
It seems like `horizontalMargin` is used here: https://github.com/airbnb/react-dates/blob/adec1c86590f1f86a4cd2537c6b780cdc35dd812/src/components/SingleDatePicker.jsx#L352

which is used here: https://github.com/airbnb/react-dates/blob/adec1c86590f1f86a4cd2537c6b780cdc35dd812/src/components/SingleDatePicker.jsx#L158-L166
