### ISSUE TITLE
Package version

### ISSUE THREAD

**Issue by ovidiu-travelperk** [airbnb/react-dates#2166]
Hello, why is the package version not being updated / published?  It's been stuck to 21.8.0 since almost 2 years now, even tho PRs are still merged that fix a lost of issues.
From what I can see, using npm I can only get the latest published version - which I believe is the one from 2020

**Comment by ljharb** [comment]
Because there hasn’t been a release since then.

It will be updated when there is one, and there is never a schedule for releases, although i hope to do one very soon.

**Comment by ovidiu-travelperk** [comment]
understood
no I reckon there is no way to get any code version newer than that using npm?

**Comment by ljharb** [comment]
Nope, since github doesn't have built files, since github is for development, not consumption.
