### ISSUE TITLE
react-with-styles@5.0.0 isn't compatible

### ISSUE THREAD

**Issue by caub** [airbnb/react-dates#2170]
https://codesandbox.io/s/react-datepickers-o9fbh?file=/src/Datepicker.js

If you update to react-with-styles@^4 it works

**Comment by ljharb** [comment]
Yes, this is by design, and the peer deps declarations cover this.

**Comment by caub** [comment]
ah ok thanks, react-with-styles is meant to work with a future react-dates version I guess

**Comment by ljharb** [comment]
No, react-with-styles doesn’t make changes based on how it will work with dependents; it’s the other way around. We’ll have to make changes in the future if we want to be compatible with v5+ of react-with-styles.
