### ISSUE TITLE
Poor performance with a few hundred blocked dates

### ISSUE THREAD

**Issue by milanpanin** [airbnb/react-dates#2171]
As the title says, the behavior of **react-dates** is very bad with a large number (~500) of blocked dates. 
 
Code of whole application is here: https://github.com/milanpanin/react-dates/blob/master/src/App.js
Also, app is live here: https://react-dates-test.netlify.app/ and here you can see how slow the application actually works 😕

```js
  // [disableNext3, disableBetween, disableNext6Between] - represent arrays with all together about 500 dates
  const isBlocked = (day) => ([disableNext3, disableBetween, disableNext6Between].flat()).some(date => day.isSame(date, 'day'));

  return ( 
    <div className="App">
        <DateRangePicker
          startDateId="startDate"
          endDateId="endDate"
          startDate={startDate}
          endDate={endDate}
          onDatesChange={({ startDate, endDate }) => { setStartDate( startDate ), setEndDate( endDate )}}
          focusedInput={focusedInput}
          onFocusChange={(focusedInput) => { setSocusedInput( focusedInput )}}
          isDayBlocked={isBlocked}
        />
        ...
```
I also tried to implement a spinner on each render, but without success. Is there any solution to my problem?

**Comment by ljharb** [comment]
That seems like the poor performance is on `isBlocked`, not react-dates? Have you tried doing the `.flat()` outside the `isBlocked` function, so you don't have to repeat it every time the predicate is called?

**Comment by milanpanin** [comment]
The same thing came to my mind but there was no significant improvement when I applied that change. What I think could be a good solution is to implement a spinner on every render that happens, but I haven't succeeded with that yet.

Do you have any suggestions?

**Comment by ljharb** [comment]
I wonder if you could instead implement your `isBlocked` kind of like this pseudocode:
```
const blockedDates = new Set(dates.map(x => gimmeYearMonthInUTC(x));
const isBlocked = (x) => blockedDates.has(gimmeYearMonthInUTC(x));
```

**Comment by milanpanin** [comment]
That's the solution! Thank you so much for your time! 
For all those who find themselves in the same problem as me, here is a sample code of how I do it...
```js
  let blockedDates = new Set([arr1, arr2, arr3].flat());
  const isBlocked = (day) => blockedDates.has(moment(day).format('YYYY-MM-DD'));
```
