### ISSUE TITLE
Misleading to place this package under airbnb

### ISSUE THREAD

**Issue by erikt9** [airbnb/react-dates#2174]
https://github.com/airbnb/react-dates/issues/2105#issuecomment-993864942

>ljharb commented on Dec 14, 2021
> @JRebella yes, it's still being maintained. Unfortunately the passage of time does not help provide me with much time for unpaid work.
> 
> Specifically, this project can't support React 17 until its tests pass on React 17, and that's blocked on enzyme, primarily. (which i'm also the only maintainer of).

I think a lot of people choose this package because they see it under airbnb and believe the company is dedicating resources to maintaining and improving it.  If there is only a single unpaid maintainer of this package, it seems misleading to place it under airbnb. Clear knowledge of this fact will allow people to make an informed decision about whether to use this package vs. other calendars.

**Comment by ljharb** [comment]
Thanks for your thoughts.

The reality is that one should never, ever, see a company-owned project and assume the company is dedicating resources to maintaining and improving it. A note on one project doesn't change that that's something everyone just has to know.
