### ISSUE TITLE
Question: Is it possible to edit the left panel of DateRangePicker

### ISSUE THREAD

**Issue by Breigner01** [airbnb/react-dates#2180]
So, I want to implement DateRangePicker on my website, the only issue is that the left panel (circled in red) doesn't have the presets that I need:
![image](https://user-images.githubusercontent.com/55832366/152357005-bb3916c9-2812-4377-8ac8-9f82148ada66.png)
So my question is, can I somehow edit it through props?
If so, how can I do it?
I didn't seem to find how to do it.

Thanks in advance

**Comment by ljharb** [comment]
That panel isn't part of react-dates. Can you confirm which library you're using?

**Comment by Breigner01** [comment]
Oh, I just realized I posted this on the wrong repo.
I'm really sorry, it's the react-date-range package.
Closing this issue.
