### ISSUE TITLE
isOutsideRange day always start at noon. What if I want midnignt?

### ISSUE THREAD

**Issue by nitish-arora** [airbnb/react-dates#2185]
**react-dates version**
e.g. react-dates@21.8.0

**Describe the bug**
I want to disable the future dates so  I used (day.isAfter(moment()) || day.isBefore(moment().subtract(4, 'M'))).
But it disables the current date till 12pm. Which i don't want.

**Comment by ljharb** [comment]
Midnight doesn’t exist in every timezone on every day, so noon is the only safe choice. This is a date picker, not a time picker, so the time should be irrelevant.

**Comment by sergei-shneider** [comment]
> Midnight doesn’t exist in every timezone on every day, so noon is the only safe choice. This is a date picker, not a time picker, so the time should be irrelevant.

How can it not be relevant? The date is not selectable until noon.

**Comment by ljharb** [comment]
Maybe I'm not understanding the problem. You're saying that the current time determines whether a day is selectable?

If so, that's because you're using `moment()`, which includes a time, instead of using `moment().startOf('day')`. Try that?

**Comment by nitish-arora** [comment]
Yes actually I used additional thing day.isAfter(moment(), ‘days’)
something like that. It started working.

**Comment by ljharb** [comment]
Glad you figured it out.
