### ISSUE TITLE
react-dates@21.8.0 requires a peer of react@^0.14 || ^15.5.4 || ^16.1.1 but none is installed. You must install peer dependencies yourself.

### ISSUE THREAD

**Issue by isanjaymaurya** [airbnb/react-dates#2193]
react-dates@21.8.0 requires a peer of react@^0.14 || ^15.5.4 || ^16.1.1 but none is installed. You must install peer dependencies yourself.

pls update the dependency

**Comment by ljharb** [comment]
Duplicate of #2105.
