### ISSUE TITLE
DateRangePicker stops working when rendering more than 1 picker from an array

### ISSUE THREAD

**Issue by svphan1** [airbnb/react-dates#2200]
**Describe the bug**
I have a row of inputs that includes a <DateRangePicker> and an add button that adds more rows. One DateRangePicker by itself works just fine, but when I add more DateRangePickers in, then clicking on any of the pickers does not work. I noticed that if I click and hold on the startDate, then I see the date ranges pop up for all rows overlapping each other. How can I fix this and properly handle multiple DateRangePicker in an array? I do need to handle updating each individual picker correctly with the onDatesChange method. Any feedback on that? NOTE: this app is old and uses version 15.5.3. Could be causing issues. 

**Source code (including props configuration)**
```
this.state.shops.map((shop, index)) => {
<div>
   <input/>
   <input/>
   <DateRangePicker
     startDate={this.state.startDate}
     endDate={this.state.endDate}
     onDatesChange={({ startDate, endDate }) => this.setState({ startDate, endDate })}
     focusedInput={this.state.focusedInput}
     onFocusChange={focusedInput => this.setState({ focusedInput })}
   />
</div>
}
```

**Screenshots/Gifs**

<img width="605" alt="Screen Shot 2022-06-15 at 12 35 49 PM" src="https://user-images.githubusercontent.com/36240410/173901088-abf754ba-65c1-4d7c-bd80-4b96b2360c4b.png">

**Comment by ljharb** [comment]
It’s because you’re reusing the same state for them all. They each need their own if you want them to behave separately.

**Comment by svphan1** [comment]
> It’s because you’re reusing the same state for them all. They each need their own if you want them to behave separately.
@ljharb 
I'm having trouble using index with this native onDatesChange method. Can you help me with how you would go about that with this component?

**Comment by svphan1** [comment]
@ljharb I'm having trouble using index to handle that with this native onDatesChange method since the only argument it takes is args: {startDate; endData}. Can you help me with how you would go about that with this component?

**Comment by ljharb** [comment]
I'd probably use the shop ID, since that's deterministic and unrelated to ordering.
