### ISSUE TITLE
How to reflect changes made to constants.js in production?

### ISSUE THREAD

**Issue by MattHeslington** [airbnb/react-dates#2203]
Hello,

Fantastic library, thank you.

I have made a single change to the node_modules/lib/constants.js file to style the calendar more to my theme:

`var DAY_SIZE = 50;`

This works fine locally, and the calendar reflects the change. However, when I deploy to Vercel, the calendar reverts to its default settings. I also changed node_modules/esm/contants.js and node_modules/src/constants.js too for good measure, but still default styling in the live environment. I realise I've missed something really obvious, if someone could point it out for me I'd be extremely gratious. 

Cheers, Matt

**Comment by ljharb** [comment]
npm-installed packages can't generally be edited like that - vercel probably installs them fresh itself.

node_modules is a black box and you're not supposed to be making changes in there. Anything the library doesn't support customizing via the API, isn't customizable.

**Comment by MattHeslington** [comment]
Found I can just use the daySize param instead - it's not documented for DayPickerRangeController but does work.

**Comment by ljharb** [comment]
@MattHeslington great! if it's there, it should be documented; care to make a PR doing so?

**Comment by MattHeslington** [comment]
> @MattHeslington great! if it's there, it should be documented; care to make a PR doing so?

Sure
