### ISSUE TITLE
Month in full format for all calendars

### ISSUE THREAD

**Issue by CoolHasan** [airbnb/react-dates#2217]
If you search for how to show months in all calendars(when you set months={2}) in long full format ("January", not "Jan") this poor documented lib has "monthDisplayFormat" prop.
For this problem in this poor library I wasted 5 hours to find how to show months in normal full format. So just add monthDisplayFormat= "MMMM yyyy" in <DateRange ..... />

**Comment by ljharb** [comment]
It's hard to find something actionable amidst the insults. Happy to reopen if you can make what you want clear, respectfully.
