### ISSUE TITLE
Upgrading to react 17 caused: TypeError: Cannot read properties of undefined (reading 'createLTR')

### ISSUE THREAD

**Issue by A-Kasaaian** [airbnb/react-dates#2218]
**react-dates version**
react-dates@21.8.0

**Describe the bug**
I'm facing following error:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'createLTR')
    at makeCreateFn (withStyles.js:154:1)
    at WithStyles.getProps (withStyles.js:236:1)
    at WithStyles.render (withStyles.js:292:1)
    at finishClassComponent (react-dom.development.js:17485:1)
    at updateClassComponent (react-dom.development.js:17435:1)
    at beginWork (react-dom.development.js:19073:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
```
I'm seeing it after upgrading to React 17. It was working very well with React 16.
I have read [this issue](https://github.com/react-dates/react-dates/issues/1726) and  [this one](https://github.com/react-dates/react-dates/issues/2111) nothing worked for me. I also tried all the solutions I found on stackoverflow.

"react": "^17.0.2"
"react-dates": "^21.8.0"

**Source code (including props configuration)**

```
// App.tsx

import 'react-dates/initialize';
import 'react-dates/lib/css/_datepicker.css';

// Range-date-picker.tsx

import { DateRangePicker } from 'react-dates';
...
<DateRangePicker
                startDate={startDate}
                minimumNights={0}
                startDateId='date-range-start'
                endDateId='date-range-end'
                endDate={endDate}
                onDatesChange={handleDateChange}
                focusedInput={focusedInput}
                displayFormat={'L'}
                renderCalendarInfo={renderInfo}
                disabled={disabled}
            />
```

**Comment by ljharb** [comment]
react-dates does not support react 17 yet. if you run `npm ls`, you'll see that your dep graph is invalid, which means you can't expect anything to work.

**Comment by A-Kasaaian** [comment]
As you are not supporting this project and there is no release out since Jan 2020, why don't you archive the project and let others know it's left alone. I had the same issue with React-VR which later changed to React-360 and then they archived it. It totally make sense to people. I think, the sooner it happens the better reaction you get.

**Comment by ljharb** [comment]
Of course I’m supporting this project.
