### ISSUE TITLE
Q/A : onClick events fired by the Datepicker

### ISSUE THREAD

**Issue by TanguyLe** [airbnb/react-dates#223]
First, thanks to all the contributors for the great work on this library, it's an amazing Datepicker !

I'm on a project with ag-grid trying to get the datepicker into a custom filter from this grid. 
However, ag-grid is closing its filters listening to onClick events on document, and've consequently been trying to prevent onClicks from bubbling out of the datepicker. 
(To prevent my whole filter from closing at any datepicker-related click)

But either I get the internal functionalities like prev/next Month to stop working (by a missplaced stopPropagation()), either an event is fired up to body. I'm starting to wonder if there is solution to achieve this from the outside of the component as the prev/next seems to rely on events getting to the top of the DOM.

Any clever thought on this would be appreciated !

**Comment by ljharb** [comment]
@TanguyLe `<div onClick={(e) => { e.stopPropagation(); }}><Datepicker /></div>`?

**Comment by TanguyLe** [comment]
@ljharb My bad, I was using the previous version with tether (which made those concerns harder to handle), the updates are making this much easier. Thanks for letting me realize that !
