### ISSUE TITLE
Question: Is there a predefined way to change the months' language?

### ISSUE THREAD

**Issue by pablodclavijo** [airbnb/react-dates#2233]
That's pretty much all. I have an app in spanish and I need to change the names of the months on the dropdown select element from DateRangePicker. 
Is it possible? like a prop or something that I need to pass to it? If not, where is it reading the months from, so I could manually translate them. Thank you

**Comment by Maksim-Skvortsov** [comment]
You need to change moment's locale. Here's documentation https://github.com/react-dates/react-dates#localization
