### ISSUE TITLE
Three interesting questions about border-radius in cells, years and holidays

### ISSUE THREAD

**Issue by aleporyadin** [airbnb/react-dates#2239]
Hi all,
I have three problems how to implement the following things:
1) When I use react-dates, I need to change the border style in cells, by default we have grey border and on hover the background too, but I want to change the border radius and background colour on hover. 
For example we have a default date selection range:

<img width="581" alt="image" src="https://github.com/react-dates/react-dates/assets/57897989/4880293a-ab34-473f-86bd-9a34dbc40930">

And I want to do something like this (when hovering we have a purple coloured border, when selecting a cell the background changes to purple and when going to select a range, the dates should have a purple coloured border):

<img width="641" alt="image" src="https://github.com/react-dates/react-dates/assets/57897989/8a6e1230-ca72-4293-97ca-7e85f0580d32">

2) How I can create year picker near month names like it:

<img width="339" alt="Знімок екрана 2023-08-28 о 12 36 14" src="https://github.com/react-dates/react-dates/assets/57897989/4d11efbd-20a2-45e4-a931-84799442febb">

3) And about holiday, how we can made popup window to show holiday namem like it:

<img width="750" alt="image" src="https://github.com/react-dates/react-dates/assets/57897989/250f4444-c93a-462a-8d70-eafafe69dc27">

(When hover we see public holiday name)

**Can you tell me which css classes need to be overridden or how it can be added?**

**Comment by lariane-guerra** [comment]
@aleporyadin did you find a way?
