### ISSUE TITLE
Doesn't work after following simple installation instructions and examples

### ISSUE THREAD

**Issue by tannerlinsley** [airbnb/react-dates#225]
Hey guys, obviously the component works, since we've all seen it in action in the demos, but so far I haven't been able to get the component to do anything but render the input box with some text. 

Once rendered, the box does nothing.  No hover states, no reactions to clicking, hovering, or focusing.  The date selection box is there, but never shows.  

To replicate: 
- Make a new create-react-app project (https://github.com/facebookincubator/create-react-app#getting-started)
- Follow `react-dates` readme exactly as shown on your readme
- Attempt to use the component eg. 
```javascript
import { DateRangePicker } from 'react-dates'

<DateRangePicker
  startDate={moment()}
  endDate={moment().add(1, 'week')}
  onDatesChange={(dates) => {console.log(dates)}}
/>

**Comment by majapw** [comment]
Hiyo! Because the `DateRangePicker` is fully controlled, that means focus state AND date value need to be passed in as props and updated through a callback function. Please take a look at https://github.com/airbnb/react-dates/blob/master/examples/DateRangePickerWrapper.jsx to see an example of the barebones the parent of the `DateRangePicker` needs to have to be functional.

**Comment by michael-go** [comment]
I stumbled upon the same issue.
Maybe the `propTypes` of `DateRangePicker` should be updated with with some `isRequired` fields, or at least explain it in the docs

**Comment by wzup** [comment]
Same issue here.

`<DateRangePicker>` doesn't respond to clicks. No date picker is pop-upped. Just date field rendered

![date-picker - google chrome 2017-01-17 11 43 59](https://cloud.githubusercontent.com/assets/3880497/22006983/76de8eb6-dcaa-11e6-8af2-d9a417e365ca.png)

```
render() {
        let now = moment();
        let back3days = now.subtract(3, 'days');
        return (
            <DateRangePicker
                id="dp"
                startDate={now}
                endDate={back3days}
                numberOfMonths={2}
                enabledOutsideDays
                orientation='HORIZONTAL_ORIENTATION'
                focusedInput='START_DATE'
                displayFormat='YYYY-MMM-DD dd'
            />
        )
}
```

**Comment by michael-go** [comment]
@wzup In case you are asking how to make it work (and not just talking about the documentation),
make sure you also provide the `onDatesChange` and `onFocusChange` props like in here: https://github.com/airbnb/react-dates/blob/master/examples/DateRangePickerWrapper.jsx

**Comment by NathanCH** [comment]
@wzup Did you get this working? I followed everything in the wrapper but can't get it to open on click.

I successfully setup the SingleDatePicker.
