### ISSUE TITLE
Programmatically open calendar

### ISSUE THREAD

**Issue by bjsmasth** [airbnb/react-dates#2258]
Hi there, 
is there a way to open calendar on button click rather than clicking on input fields?

 Thanks

**Comment by ljharb** [comment]
You can have the button click cause the input fields to be focused.

**Comment by bjsmasth** [comment]
any examples or documentation link for that ?

**Comment by ljharb** [comment]
https://react-dates.github.io/react-dates/?path=/story/drp-input-props--with-show-calendar-icon is an example of showing a calendar icon that can be clicked on; otherwise you can set the focusedInput prop https://github.com/react-dates/react-dates?tab=readme-ov-file#daterangepicker
