### ISSUE TITLE
Cannot find module "react-addons-shallow-compare"

### ISSUE THREAD

**Issue by YuriTu** [airbnb/react-dates#226]
I use yarn to install 4.2.0.
After that I installed “react-addons-shallow-compare”，but  the problem still exists.

**Comment by ljharb** [comment]
Please make sure you have all the proper [peerDependencies](https://github.com/airbnb/react-dates/blob/master/package.json#L103-L106) installed with the proper versions, and that all of the react dependencies have identical versions.

**Comment by YuriTu** [comment]
The problem is solved.Thanks!

**Comment by arnarthor** [comment]
@ljharb Is there a reason that you are using `react-addons-shallow-compare` instead of PureComponent?

**Comment by ljharb** [comment]
We support back to React 0.13 and 0.14, and that was added in 15.3 iirc.

**Comment by arnarthor** [comment]
That makes perfect sense. I had a PR ready for this since where I work we don't need to think this far back 😄 

Thanks for the quick reply 👍
