### ISSUE TITLE
It doesn't work with Internet Explorer 11?

### ISSUE THREAD

**Issue by igorescobar** [airbnb/react-dates#233]
It seems that this plugin doesn't work with Internet Explorer 11. Edge works fine. 

Any idea on how to fix it?

**Comment by ljharb** [comment]
Can you elaborate on "doesn't work"? It should work down to IE 9, at least.

**Comment by igorescobar** [comment]
@ljharb It doesn't work at all. The component to select the date don't even appear. Do you want to know something specific?

**Comment by ljharb** [comment]
On your site, or on the storybook?

**Comment by igorescobar** [comment]
@ljharb After your comment I decided to check it out. it isn't working on our website but I think that I followed everything mentioned in the README. Do I need to do something more to make it work?

**Comment by igorescobar** [comment]
@ljharb you an check it out here: https://www.hole19golf.com/portugal/club-de-golfe-quinta-do-peru

**Comment by igorescobar** [comment]
Well... I guess no help will come from this.

**Comment by ljharb** [comment]
@igorescobar please have patience, this (and the last two weeks) is holiday time in the US.

**Comment by Valentin1918** [comment]
In IE 11 I have the error which is linked with: "Array.from" -- is indicated, that property "from" is not supported. It seems need to use polyfill: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from

**Comment by ljharb** [comment]
@Valentin1918 could you perhaps point me to a line number? That's something that'd be relatively trivial to fix.

**Comment by Valentin1918** [comment]
It is in lib/components/DayPicker.js line 116

**Comment by ljharb** [comment]
Thanks, all fixed for the next release.

**Comment by igorescobar** [comment]
@ljharb any idea when it will be released?

**Comment by ljharb** [comment]
I can try for today or tomorrow.

**Comment by ljharb** [comment]
v4.3.1 published.

**Comment by Valentin1918** [comment]
Thanks. Also in src/components/DayPicker.jsx (line 241) need to be called calculateDimension but not this.calculateDimension

**Comment by ljharb** [comment]
Thanks, I unpublished 4.3.1 - 4.3.2 will be out later today with that fix.

**Comment by ljharb** [comment]
v4.3.2 has been published.

**Comment by warn4n** [comment]
Has there been an IE11 regression since then? I'm getting multiple errors including Array.from etc on version 11.0.1.

**Comment by ljharb** [comment]
@warn4n Part of v11's breaking changes was that it required `Set` and `Array.from` - you now need to use https://npmjs.com/airbnb-js-shims or the equivalent (you should be doing this regardless in older browsers like IE 11)

**Comment by warn4n** [comment]
@ljharb Great, I'll try that out! Thanks so much for your very quick response!!

**Comment by corohsnk** [comment]
Hello, I import react-dates DateRangePicker in my project and testing in IE9 return error "SCRIPT5007: Unable to get value of the property 'isDayBlocked': object is null or undefined", and file initialize.js has const and IE9 not understand const, I changed const to var.

Any idea on how to fix it?

**Comment by ljharb** [comment]
@corohsnk https://github.com/airbnb/react-dates/blob/master/initialize.js doesn't have `const`, and neither does https://unpkg.com/react-dates@15.0.0/lib/initialize.js - how are you importing it into your project?

**Comment by corohsnk** [comment]
@ljharb I checked in my project, it was with version 13, I updated to the current version (15.0.0) but it still gives error of isDayBlocked: object is null or undefined in IE9

**Comment by ljharb** [comment]
@corohsnk can you file a new issue, and include the stack trace as well as how you're using react-dates? Also, please confirm (in the issue) that you're using airbnb-browser-shims or the equivalent?

**Comment by khsily** [comment]
@corohsnk That is because of "this.props.isDayBlocked" in constructor.
I don't know why but lower versions of ie do not support using this.props in constructor so simply changing "this.props.isDayBlocked" to "props.isDayBlocked" will fix the problem.
