### ISSUE TITLE
masked input / format option 

### ISSUE THREAD

**Issue by DanielRuf** [airbnb/react-dates#237]
In addition to the placeholder (https://github.com/airbnb/react-dates/issues/79) it could be good to have also a masked input / format option as property of type function so users can only input dates into the text field (see https://github.com/airbnb/react-dates/blob/fa163dffe15fbc93b2eea704b31ad6cc9655b314/src/components/DateInput.jsx#L113-L128) instead of any text to prevent empty / invalid inputs.

**Comment by majapw** [comment]
I was thinking about this over the break too. I think this would be a good idea and help a lot with our validation code. I was looking into masked inputs libraries over the holiday but didn't land on one with a particularly high level of support. If you have some ideas of ones to explore, I'll look into it.

@ljharb @lencioni @backwardok thoughts on good libraries to accomplish this?

**Comment by ljharb** [comment]
I'm not convinced that restricting input is a great pattern - I feel like allowing the user to type the wrong thing might give us the opportunity to provide a more helpful error message. Fields that only allow numbers, for example, make a bit more sense, but it's really confusing and annoying when credit card fields prohibit spaces, and phone number fields prohibit dashes.

Open to being convinced tho.

**Comment by lencioni** [comment]
Nielsen Norman Group recommends never using placeholders. https://www.nngroup.com/articles/form-design-placeholders/

They do recommend formatting input as it is typed in some situations (e.g. phone numbers):

> An even better solution is to format the users’ input as they type —like Uber’s website does during account creation. Once you begin typing, the form adds the spaces, parentheses, and hyphens where they normally go, and also ignores additional nonnumeric characters (which acts as a type of helpful constraint, preventing users from adding unnecessary extra parentheses, for example). This helps the user understand what characters they should type, and does the work of reformatting, making it much easier for users to read and double-check their own work.

https://www.nngroup.com/articles/slips/

I also agree with @ljharb that restricting input is not a great pattern. Personally, when I encounter this I often find it more frustrating than useful.

**Comment by lencioni** [comment]
If we want to reformat input after it is typed, it seems like it should be pretty straightforward to do that without bringing in a new dependency (e.g. parse input with moment, update state with desired format of given input).

**Comment by DanielRuf** [comment]
Autoformatting (and possibly autovalidating / shoeing if the given input value is correct) could be a good solution.

My idea was not to fully restrict the input or enforce a specific format but give hints if it is correct and can be parsed or not.

**Comment by backwardok** [comment]
Late to the game on commenting on this, but the cases that @lencioni and @ljharb seem to apply a lot less to dates and more so to things like credit cards and phone numbers. This is especially important for dates because switching the order of what you put for month and date will get you an entirely different value, and that's not true for something like credit cards or phone numbers, where the order will always be the same and can just be masked to fit within a desired visual output. 

Format could be kind of interesting, but that would then require a specific input method and not be able to accept multiple (like it does today)

**Comment by DanielRuf** [comment]
Right. Great to still see some activity by Airbnb devs.
