### ISSUE TITLE
Is focusedInput requred for DateRangePicker

### ISSUE THREAD

**Issue by mir3z** [airbnb/react-dates#238]
I can't find any place in documentation that states `focusedInput` prop is required but when I don't add this prop date picker is not visible after clicking input.

I have to dive into examples to finally see that https://github.com/airbnb/react-dates/blob/master/examples/DateRangePickerWrapper.jsx sets this prop.

**Comment by majapw** [comment]
Good call. We should probably indicate in the README that this is the case (and the examples folder is a great place to look for how to set up your initial code!). Thanks for highlighting this.

**Comment by majapw** [comment]
The README should make this information more clear now.
