### ISSUE TITLE
Allow past dates for DateRangePicker

### ISSUE THREAD

**Issue by mir3z** [airbnb/react-dates#239]
Is it possible to select past dates in DateRangePicker?

**Comment by wzup** [comment]
@mir3z 
Why did you close the issue? Did you solve it? Mind tell others how?

**Comment by ljharb** [comment]
See `isOutsideRange` in the documentation.

**Comment by winterblack** [comment]
What documentation? The github readme doesn't mention anything about isOutsideRanger other than that it expects a function.

**Comment by ljharb** [comment]
@winterblack that's a fair point. The "is" prefix means, by almost universal convention, that it's a predicate, which means it has to return a boolean (`true` or `false`). What it accepts might not be super apparent, but it takes a moment object representing a date, and leaves it to you to determine whether that date is outside the range or not.

PRs improving the documentation are always appreciated!

**Comment by ckeeney** [comment]
I just struggled with this issue for a bit.  I passed in as a prop
```
isOutsideRange={() => {false}}
```
This effectively lets any date be chosen.

**Comment by MarkEhr** [comment]
@ckeeney be aware that this solution is creating a new function each render call thus forcing a re-render of the component even though nothing may have changed.    
If you want to avoid this just create the function as a constant outside your component like:
`const falseFunc = ()=>false;`
and then use the function as the prop
`isOutsideRange={falseFunc}`
This may add too little overhead to be noticeable ( unless you're rendering a ton of this in one view which seems unlikely ), but it's still a good pattern to follow.

**Comment by jrgleason** [comment]
Would be nice to understand the inputs to the function, like how do I say outside range if more than a year in the past.

**Comment by jrgleason** [comment]
Spec tests show a day being passed but how do I make it relative to the start/end without outside vars?

**Comment by narthkings** [comment]
thanks for this, just saved my ass from going through the d.ts file to inspect
