### ISSUE TITLE
Question: Disable future dates?

### ISSUE THREAD

**Issue by NickCain** [airbnb/react-dates#247]
Hi,

I was wondering would it be possible to disable dates in the future on the calendar? 

For example, I have a annual schedule of dates which need to be disabled, is there a way for React Dates to consume this dates and disable the corresponding date.

Thanks in advance.

**Comment by majapw** [comment]
Hi @NickCain, sure! There are two props that could help you with this. If you have an array of blocked dates (which is what it seems like), you could use the `isDayBlocked` prop. This prop is a function that takes in a moment object and returns true or false based on whether you want it to be selectable. So for examples you could do something like this:

**Comment by NickCain** [comment]
Hi @majapw,

Thanks for for your reply.

Yes! this looks like what I wanted to do! Thank you!

**Comment by spiral2k** [comment]
there is an option to not accept the range select if there is blocked day in the range?

**Comment by ybakhshi** [comment]
@NickCain did you implement this? are you using react-datepicker? 
Because currently react-datepicker is using date-fns not moment.  I tried to use the code from @majapw  but it didn't work for me.

Could you please help me here

**Comment by NickCain** [comment]
Hi @ybakhshi ,

It was a long time ago, but from what I remember this did work at the time, however I'm not sure now as there may of been some updates that have made by the lib owner.

I did import moment separately so I would suggest doing this and then the example should work, moment is just used as a helper here to format the dates needed.

**Comment by ybakhshi** [comment]
@NickCain  Thanks for your kind reply . i solved it using the excludeDates ={disableFullyBookedDates()} . 
![image](https://user-images.githubusercontent.com/57077366/78544069-e3c32300-77f9-11ea-8f17-34e2fb0ae148.png)
in case someone needs it

**Comment by NickCain** [comment]
@ybakhshi  - Glad you sorted it, I did suspect something may of changed in react-datepicker. itself.

**Comment by moosefaceee** [comment]
@ybakhshi I'm confused, is this thread not on react-dates?
