### ISSUE TITLE
DateRangePicker: Calendars do not appear on click with ES6 arrow function syntax

### ISSUE THREAD

**Issue by mikesparr** [airbnb/react-dates#252]
I basically recreated the `Wrapper` component in your demos but within context of my projects. The `DateRangePicker` appears but does not respond to click events to display the calendars. I even tried enabling the portal prop to see if it was hidden off screen for some reason but no luck.

I noticed in Chrome dev tools React view that when I click on the picker, the `focusedInput` state originally set as `null` disappears from state completely?  Any suggestions greatly appreciated.

## Versions
 * React: `^15.4.2`
 * React-Dates: `^4.3.2`

## Appears as
<img width="389" alt="screen shot 2017-01-16 at 11 23 23 am" src="https://cloud.githubusercontent.com/assets/5553105/21994949/81c622e2-dbdf-11e6-8928-d5bbe38cf9fb.png">

## Relevant code
~~~
// ...

import moment from 'moment'
import { DateRangePicker } from 'react-dates'
// css compiled with stylus

// ...

class Totals extends Component {
	state = {
		focusedInput: null,
		startDate: null,
		endDate: null
	}

	onDatesChange = ({startDate, endDate}) => this.setState({startDate, endDate})
	onFocusChange = ({focusedInput}) => this.setState({focusedInput})

	render() {
		const { focusedInput, startDate, endDate } = this.state;
		return (
			<div>

			        Date range: <DateRangePicker
			          {...this.props}
			          onDatesChange={this.onDatesChange}
			          onFocusChange={this.onFocusChange}
			          focusedInput={focusedInput}
			          startDate={startDate}
			          endDate={endDate}
			          numberOfMonths={2}
			          withPortal={true}
			        />

// ...
~~~

**Comment by mikesparr** [comment]
I found the issue. The PropTypes restriction on function type does not like the lambdas or arrow functions for the event handlers so I had to change them to JS functions and add constructor to the component.

Perhaps you might consider ES6 syntax support in PropTypes declaration so above code works without needing to explicitly bind `this` to functions, etc. Thanks anyway for a great tool!

**Comment by ljharb** [comment]
Can you elaborate? propTypes run on values, and arrow functions vs non-arrow functions are largely indistinguishable as a value.

**Comment by ljharb** [comment]
I think this is a confusion about the difference between `React.createClass` and class-based components. The former "autobinds" all instance methods for you. The latter follows JavaScript idioms, and absolutely requires you to manually bind your instance methods in the constructor.

In other words, your component is broken - you should be defining `onDatesChange` as an instance method, and doing `this.onDatesChange = this.onDatesChange.bind(this)` in the constructor.

**Comment by mikesparr** [comment]
Ah, I think you're right. It did work after adding constructor, but I was trying to get them to work without and just using arrow functions. It puzzles me why one works but other doesn't, however it works using the constructor and bind approach. Thanks for prompt reply.
