### ISSUE TITLE
{...this.props} causing issue when using Redux

### ISSUE THREAD

**Issue by kunokdev** [airbnb/react-dates#254]
I am using Redux and I have this instance of `DateRangePicker` component:
```
<DateRangePicker
                  {...this.props}
                  onDatesChange={this.props.onDatesChange}
                  onFocusChange={this.props.onFocusChange}
                  focusedInput={S.datePicker_focusedInput}
                  startDate={S.datePicker_startDate}
                  endDate={S.datePicker_endDate}
                  numberOfMonths={1}
                  minimumNights={0}
                  enableOutsideDays
                  isOutsideRange={ day =>
                          (!this.isInclusivelyAfterDay(day, moment())) ||
                          this.isInclusivelyAfterDay(day, moment().add(1, 'years'))
                  }
                />
```

However, I have issue with `{...this.props}` parameter which is displayed in example.

I am unsure which method should I use to fill these missing props because right now `{...this.props}` is owned by redux.

Any example on how to do that?

**Comment by kunokdev** [comment]
Instead it can be just omitted.

**Comment by kunokdev** [comment]
Instead, it can be just omitted.

**Comment by ljharb** [comment]
I'd recommend avoiding spread props, and instead explicitly passing all props that you need.

**Comment by kunokdev** [comment]
@ljharb indeed, I thought it was necessary since it was shown as such in examples, however I omitted it and it works just fine, thanks!
