### ISSUE TITLE
Would love to be able to change the format of the inputs

### ISSUE THREAD

**Issue by jcreamer898** [airbnb/react-dates#26]
I noticed that the input values are always in mm/dd/yyyy format, I think because of https://github.com/airbnb/react-dates/blob/04e2840fe6181dadcb5edd695a0550b46ea9b054/src/components/DateRangePicker.jsx#L395.

It'd be nice to be able to format that date to a custom format.

**Comment by majapw** [comment]
Yeah! This is def a thing that I've kind of started thinking about in the utility classes (namely the `toMomentObject` method takes in a custom format as an optional argument). 

My thought is that the `DateRangePicker` and `SingleDatePicker` would have a `customDateFormat` prop and then we could have `toLocalizedDateString` use that in the render method and `toMomentObject` use that `onStartDateChange` and `onEndDateChange` methods. If it's falsey, then we just fall back to the `L` format. :)

**Comment by jcreamer898** [comment]
Sweet. I can try to PR for it.

**Comment by majapw** [comment]
Sounds great!
