### ISSUE TITLE
Accessibility improvement

### ISSUE THREAD

**Issue by allanpope** [airbnb/react-dates#261]
Hi,

I'm using the date range picker and I would like to include an additional message for screen reader users to inform them of the constraints around what they can type in the inputs.

Would you be open to me submitting a pull request that adds an `aria-describedby` to the DateInput ?

This way you could write an additional message to users, to let them know about minimum nights, the date format they should type in and blocked out dates etc.

**Comment by majapw** [comment]
Oh that would be sweet. I'm also probs gonna put in some time this quarter to devote to a11y work.
