### ISSUE TITLE
DateRangePicker cannot render correctly inside a scrolling container

### ISSUE THREAD

**Issue by isaachinman** [airbnb/react-dates#273]
Because `DateRangePicker__picker` is rendered adjacent to `DateRangePickerInput`, it cannot work correctly inside containers that scroll their overflow - it will either push the edges of the container outwards, or be clipped if you have something like `overflow-y: scroll; overflow-x: hidden;`. I believe I opened a ticket similar to this about five months ago, and it was "fixed" in #83.

@majapw Any update on this? I can provide an example if needed but it's quite simple to reproduce.

**Comment by majapw** [comment]
Hi @isaachinman, I think I don't understand the issue completely and a screenshot or gif would definitely help.

**Comment by isaachinman** [comment]
Hey @majapw. Sorry, on second read through I can see how vague that is. I've gone a different direction (because of this problem) in my own project, but basically the problem is that if a DateRangePicker's parent is less wide than viewport width with some CSS scroll attribute set, the `DateRangePicker__picker` will set itself inside this scroll parent, either as a scrolling child or a clipped child, despite the viewport width itself being enough to accommodate the DateRangePicker positioned absolutely.

This is because the `DateRangePicker__picker` is set adjacent to the root, so it scrolls like "normal" content, despite it not being intended to.

Here's a gif:

![](http://i.imgur.com/ruY6dOJ.gif)

**Comment by BamaBoy** [comment]
This feature was implemented via TetherComponent. I've looked through the commit history. It seems that TetherComponent  [has been removed](https://github.com/airbnb/react-dates/commit/5799674184239888de6700b1cb81b6f88108d1e5). But i think internal replacement wasn't implemented.
I find this feature very useful, so I am using 3.6.0 version.

**Comment by isaachinman** [comment]
Thanks @BamaBoy. Looks like @majapw removed that dep, maybe she can shed some light? I would assume this comes down to absolute vs fixed positioning.

**Comment by willianribeiro** [comment]
I'm having exactly the same issue here. 
Is there any workaround to solve the problem without back the version?

**Comment by isaachinman** [comment]
@willianribeiro I never got a response on this. I ended up making some small structural changes and hacking some tricky CSS to get it working in my own use case. Still no clarification on the removal of TetherComponent. Maybe they've added in back in, this project seems to release rapidly, so do check recent releases.

**Comment by willianribeiro** [comment]
Thanks for the answer @isaachinman (-;

It seems would be a good idea return the TetherComponent. I don't know if it's possible for the react-dates, but to avoid problems like that, components who appear over other components should be positioned fixed and be a Body child (directly). This way many possible problems are eliminated.

**Comment by majapw** [comment]
The TetherComponent, unfortunately, also introduced a large number of problems. The main problem I was using it to fix was to hug the container to the edge of the screen instead of rendering it offscreen, which is now done internally.

You can see a thread here outlining some of the issues we had with using tether - https://github.com/airbnb/react-dates/issues/139

We actually do now use the datepicker in modal content without problems (with it overhanging the edge of our modal), but I think our modal implementation doesn't scroll in a fixed size container, which makes the difference. I do not plan to add back tether.io to this repository, BUT if you really need it, you can put it together yourself with the pieces.

Specifically, `react-dates` exposes both the `DateRangePickerInputController` and `DayPickerRangeController` components which contain all the logic about selecting ranges, displaying dates in a particular format, etc. The `DateRangePicker` is basically just the logic that highlights the inputs and opens the calendar. You could import the inputs/calendar components directly and put together your own logic using `react-tether` instead. Let me know if you'd like me to clarify on that point.

**Comment by isaachinman** [comment]
No, that all makes perfect sense. What is the rationale behind positioning the picker as `absolute` and not `fixed`, though? If those controllers are exposed I think implementation can be very flexible.

**Comment by willianribeiro** [comment]
@isaachinman, I was thinking here.. if it was positioned as fixed it would have problems when scroll it, no?

Like this (sorry for the gif quality):

![fixed_position](https://cloud.githubusercontent.com/assets/3102551/23762355/7d6cee2e-04d4-11e7-9ac0-a73f3d5272e9.gif)

**Comment by isaachinman** [comment]
@willianribeiro Well yes of course, if you aren't doing anything else. You should take a look at `react-tether`, as @majapw mentioned.

But probably the easiest way is just to create your own wrapper component that mounts the calendar controller as a direct child of body, and then position it absolutely without weirdness.

**Comment by willianribeiro** [comment]
Nice guys, thank you so much for your support! :wink:

**Comment by divan** [comment]
> But probably the easiest way is just to create your own wrapper component that mounts the calendar controller as a direct child of body, and then position it absolutely without any weirdness.
Can anyone elaborate on this for non DOM/CSS-ninjas? Working example, maybe? 🙏

I'm currently trying to use react-dates inside MaterialUI Dialog and have the same issue.

**Comment by isaachinman** [comment]
@divan For a specific question like that, you're probably better off posting on StackOverflow. Good luck.

**Comment by revyh** [comment]
Will portals (introduced in react 16) change anything with this issue?

**Comment by isaachinman** [comment]
@revyh It's been awhile since we discussed this issue, but yep - I imagine that'd solve it nicely.

It's also been awhile since I looked through the `react-dates` source, but if I recall correctly, there's some deeply nested stuff going on. Porting `DateRangePicker__picker` as a direct descendent of `body` would solve these positioning issues.

**Comment by joaovieira** [comment]
@majapw been wanting this for a long time and now I *need* it. 

>Specifically, react-dates exposes both the DateRangePickerInputController and DayPickerRangeController components which contain all the logic about selecting ranges, displaying dates in a particular format, etc. The DateRangePicker is basically just the logic that highlights the inputs and opens the calendar. You could import the inputs/calendar components directly and put together your own logic using react-tether instead. Let me know if you'd like me to clarify on that point.

Are you saying we'd need to reimplement/copy all the 600 LOC of `DateRangeInput` logic just to render the parts in a slightly different way (wrap input/day picker in Tether/Popper components)?

**Comment by majapw** [comment]
I'm trying to think of whether the right approach is to have a `withTether` prop, or to have a `TetheredDateRangePicker` or to assume copying of the DRP contents. I feel like you likely wouldn't have to copy everything because you wouldn't necessarily need all the options, but I can understand the consternation. 

@ljharb do you have any thoughts on this?

**Comment by joaovieira** [comment]
@majapw I've forked and have been working on adding an `appendToBody` prop (seen in many other "popup" components - e.g. [AngularJS Material Tooltip](https://github.com/angular/material/blob/master/src/components/tooltip/tooltip.js#L376), [Bootstrap Tooltip](https://getbootstrap.com/docs/4.0/components/tooltips/#options), [vue-popper](https://github.com/RobinCK/vue-popper#props)) that essentially renders the picker in a portal, positions it next to the input and prevents scroll. I'll be opening a PR later today to see your thoughts.

I think Tether/Popper would be ideal, but hard to integrate at this point as it would conflict with the explicit positioning via props in react-dates. The whole benefit of Tether/Popper is to take care of the anchor position + open direction automagically.
