### ISSUE TITLE
cursor position on input

### ISSUE THREAD

**Issue by bsr203** [airbnb/react-dates#276]
I was going to request some way to guide the user on entering the date in input field. A version of this is raised already here https://github.com/airbnb/react-dates/issues/237

But, at the least there should be some kind of feedback to the user that the date input field is editable. Currently, there is no cursor on the input field, and no way to know which field (date/ month, ..) are editing. I initially thought it may be a button / span or not editing supported until I see the last commit and https://github.com/airbnb/react-dates/issues/274

Please bring the cursor position back on input.

**Comment by bsr203** [comment]
looks like the actual input is masked by a div for the display https://github.com/airbnb/react-dates/blob/master/src/components/DateInput.jsx#L133

**Comment by timhwang21** [comment]
Hey, wondering if there's any discussion on this. This has been brought up in a bug report in our usage of this library. Thanks!

**Comment by sjain-mi9** [comment]
Is there a way anyone could find to have the cursor active to just type in the date?

**Comment by liubko** [comment]
@sjain-mi9 the drawback is that `displayFormat` has no effect on a value inside `DateInput__input` =(

**Comment by sjain-mi9** [comment]
@liubko not sure what you mean by displayFormat? I'm able to type in my dates, navigate via input cursor and it reads it well.

**Comment by liubko** [comment]
```
<DateRangePicker
  ...
  displayFormat="DD/MM/YYYY"
  ...
/>
```

@sjain-mi9 when selecting dates in a calendar with a mouse the value in the input will not be formatted according to the `displayFormat` prop. It only formats text inside `DateInput__display-text`

**Comment by ConAntonakos** [comment]
I started writing a PR branch for potential changes. My approach is to remove the `display-text` node and instead merge those class names into the `DateInput__input` node.

Any thoughts, @majapw or anyone else?

Here is an example:
![screen shot 2017-07-06 at 4 53 04 pm](https://user-images.githubusercontent.com/1504302/27932409-ab0d0e50-626b-11e7-900f-5b7bc942e154.png)

**Comment by timhwang21** [comment]
Hey @ConAntonakos! I would like this functionality as well, so if you have a PR I'd really appreciate if you shared it :) If not, I'll probably give this one a try. Thanks!

**Comment by ConAntonakos** [comment]
Hey, @timhwang21! I started something, but never got around to finishing it. I also wanted to hear back from other maintainers/contributors to see if there was a consensus with the solution. Please feel free to give it a try, and I'd love to contribute to it. 😄

**Comment by majapw** [comment]
This is fixed now that we use real inputs (instead of the fake one) as per previous suggestions in this issue. :)

**Comment by ConAntonakos** [comment]
Even though the UI changed a bit, I like the solution. Thanks for address this!
