### ISSUE TITLE
non-english format not working correct

### ISSUE THREAD

**Issue by vklein** [airbnb/react-dates#281]
Hi,

since version v5.2.0 the non-english locale format is not working correct anymore.

<img width="649" alt="bildschirmfoto 2017-02-01 um 16 19 51" src="https://cloud.githubusercontent.com/assets/756939/22512761/4c621080-e89a-11e6-99cb-cf4608412dd8.png">

As you can see in the screenshot the Date Format in the Open SingleDatePicker is correct, but the shown Date in the Input-Field is always in english format. "YYYY-MM-DD". 

I think the problem is that you have to change the Prop you pass to the SingleDatePickerInput from 
dateValue={dateString} to displayValue={dateString} because the prop name changed.

**Comment by majapw** [comment]
You are totes right! I will update that immediately. Thank you for the catch!
