### ISSUE TITLE
Open to selection

### ISSUE THREAD

**Issue by refaelos** [airbnb/react-dates#282]
Hey, great widget!!!

When the DateRangePicker opens, is there a way to open it on a selected range? even if it's in the past?
For now, when I open it just opens to 'today' onwards and if there's a selection in the past it's not shown.

**Comment by allanpope** [comment]
@refaelos I think by default it opens in the current month. 

There is a `initialVisibleMonth()` function which allows you to open the calendar on a certain month. You could check to see if there is a range already selected and if there is, pass the start date month & year to the `initialVisibleMonth()`.

**Comment by refaelos** [comment]
@allanpope thanks 👍

**Comment by refaelos** [comment]
@allanpope I tries using initialVisibleMonth but it doesn't really work. Do you have a working example of this?

**Comment by allanpope** [comment]
@refaelos There is an example of how to open it on a specific month on the [storybook demo](http://airbnb.io/react-dates/?selectedKind=DateRangePicker&selectedStory=with%20month%20specified%20on%20open&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel).

If you inspect the story for it, you'll see the code below. You'll need to pass in a moment date.

``` 
<DateRangePickerWrapper
    initialVisibleMonth={() => moment('04 2017', 'MM YYYY')}
/>
```

**Comment by refaelos** [comment]
@allanpope yeah that's what I did. It didn't work. I'll investigate...

Thanks!

**Comment by majapw** [comment]
Thanks, @allanpope! Can you post your code @refaelos?

**Comment by refaelos** [comment]
Hey @majapw 

Here's my code:

```
<DateRangePicker
            onFocusChange={this.onFocusChange.bind(this)}
            onDatesChange={this.onDatesChange.bind(this)}
            focusedInput={this.state.focusedInput}
            startDate={dates.startDate}
            endDate={dates.endDate}
            anchorDirection={ANCHOR_RIGHT}
            initialVisibleMonth={() => dates.startDate}
            minimumNights={0}
            isOutsideRange={this.isOutsideRange.bind(this)}
          />
```

**Comment by majapw** [comment]
Huh. And the behavior is just that it always opens to the current month? And `dates.startDate` is definitely a moment object?

**Comment by refaelos** [comment]
@majapw startDate is definitely a moment object and it only goes back one month from 'this month'. I tried different startDates (hard coded ones) and same thing happen.

**Comment by majapw** [comment]
@refaelos What version are you on? Are you using v6.0.0?

**Comment by majapw** [comment]
When I run the following locally in my storybook:
```
    <div style={{ float: 'right' }}>
      <DateRangePickerWrapper
        anchorDirection={ANCHOR_RIGHT}
        minimumNights={0}
        initialVisibleMonth={() => moment('01 2017', 'MM YYYY')}
        isOutsideRange={() => false}
      />
    </div>
```
I see:
![screen shot 2017-02-02 at 11 10 03 am](https://cloud.githubusercontent.com/assets/1383861/22564145/3fdad880-e938-11e6-8d54-2427865ee33e.png)

Which is what I'd expect.

**Comment by refaelos** [comment]
Oh .. I'm on v5.2.0 ... I'll try 6.x.

**Comment by refaelos** [comment]
@majapw I think I know why this happens to me ... is `initialVisibleMonth` being considered only when the component initializes ?
If yes, is it possible to update this parameter later?

**Comment by refaelos** [comment]
@majapw any idea?

**Comment by jfama** [comment]
Bumping as this issue is still present as per @davebream's post #951
The initially shown month does not respect the `initialVisibleMonth` prop unless `focusedInput` is not null for DateRangePicker, or unless `focused` is not null for SingleDatePicker.
