### ISSUE TITLE
input icon on SingleDatePicker

### ISSUE THREAD

**Issue by reyhansofian** [airbnb/react-dates#292]
can we add input icon on `SingleDatePicker` component? Just saw that only the `DateRangePicker` have a property to modify input icon

**Comment by majapw** [comment]
This is a good idea. :) We just have not implemented it yet.

**Comment by shockry** [comment]
I was looking into this issue and there is one thing I would like to ask about.

When it comes to the styling of the icon, its class name (`DateRangePickerInput__calendar`) is very tied to the `DateRangePicker`, and it's even in the scss file named `DateRangePickerInput.scss`.

I believe that the same styling would be suitable for the `SingleDatePicker` icon too, so what should we do about that?

**Comment by majapw** [comment]
Closing this in favor of #368
