### ISSUE TITLE
add class to dates

### ISSUE THREAD

**Issue by oldo** [airbnb/react-dates#297]
Hi there,

Another question: I would like to add a class to a particular day cell which would allow me to style that particular day differently to other days.

Is there a function similar to `isDayBlocked()` that I can access that would allow me to do this?

Thanks :-)

**Comment by majapw** [comment]
Hi! Are you using `isDayHighlighted`? That would be my recommendation. The day will still be interactive (unlike with `isDayBlocked` or `isOutsideRange`). You can check it out in action here - http://airbnb.io/react-dates/?selectedKind=DateRangePicker&selectedStory=with%20some%20highlighted%20dates&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel.

**Comment by oldo** [comment]
Hi @majapw 
Yes, I did see this yesterday and I think that it could help.
What I'm trying to achieve is to have two kinds of blocked dates:
* one kind is a blocked date that can not be included within a date range; and
* the other kind just is blocked from checking in on that day, so the start date can not be this date but can be included within a range (exactly the same functionality as `isDayBlocked`).

I'll close this issue as although your answer isn't exactly what I'm looking for, I think that using the `isDayHighlighted` is a good step in the right direction.

Thanks :-)

**Comment by davidmartin** [comment]
Hi, 
I am wondering if it could be possible to highligth more than one day using **different colors** and if so how can I accomplish that?

Thanks.

**Comment by oldo** [comment]
@davidmartin you might have more chance of getting a response if you post to an open issue or open your own issue.

**Comment by davidmartin** [comment]
@oldo Ok, i will open a new issue.

Thanks :)
