### ISSUE TITLE
DateRangePicker/SingleDatePicker should auto-close when user clicks any area other than the open Calendar.

### ISSUE THREAD

**Issue by mayurgupta1991** [airbnb/react-dates#298]
As a user when I click to select date, then Datepicker opens up calendar to select date.

However, if user does click on any other part of HTML body then Datepicker still remains open, until and unless User selects a date.

In this scenario when Datepicker is open and user click on any other part of HTML body, Datepicker should autoclose itself.

**Comment by majapw** [comment]
Hi @mayurgupta1991, I believe this is already the current behavior. Are you not seeing this? Can you send a gif if not?
