### ISSUE TITLE
Add source code from the demo 'http://airbnb.io/react-dates/' to the examples

### ISSUE THREAD

**Issue by crankycookie** [airbnb/react-dates#300]
I've been struggling a bit with the provided documentation and the given two examples. 

I couldn't find any other useful documentation on this and I was hoping that there was a way to open up the code you have in the demo from http://airbnb.io/react-dates/

This would help me out so much and I'm sure it would beef up the examples library as well.

**Comment by majapw** [comment]
Hi @crankycookie, the documentation def needs some love so this makes sense! You can find each of the stories from the demo for the relevant components in https://github.com/airbnb/react-dates/tree/master/stories.

Basically the props there get passed straight down to the example files in https://github.com/airbnb/react-dates/tree/master/examples. 

There are some useful plugins that we should add the the storybook demo so as to just have the source code right there.

**Comment by crankycookie** [comment]
Oh nice, I didn't notice that. This will be helpful!

Thanks!
