### ISSUE TITLE
Bug / regression?: incorrect "invalid" dates when startDate/endDate moment object's time is not 12:00:00

### ISSUE THREAD

**Issue by timhwang21** [airbnb/react-dates#306]
I am using this component together with a TimePicker component. Both are controlled components, so changing the time changes the moments that are currently in the DatePicker.

I upgraded the version of react-dates to major version 5 this week, and noticed a weird interaction when using the DateRangePicker:

* When the time is after `12:00:00`, the date immediately after the start date is marked as out of range.
* When the time is before `12:00:00`, the date immediately before the start date is marked as out of range.

Hopefully the images make this more clear. If you have any questions, please let me know. Thanks!

Case 1: Time before `12:00:00`:
<img width="431" alt="screen shot 2017-02-07 at 4 10 50 pm" src="https://cloud.githubusercontent.com/assets/5831434/22711825/94b4ab9e-ed50-11e6-94ea-b5d6c8cfbf53.png">
<img width="401" alt="screen shot 2017-02-07 at 4 10 56 pm" src="https://cloud.githubusercontent.com/assets/5831434/22711827/94b5c1e6-ed50-11e6-898e-a637e8a31fdf.png">

Case 2: Time after `12:00:00`:
<img width="394" alt="screen shot 2017-02-07 at 4 11 04 pm" src="https://cloud.githubusercontent.com/assets/5831434/22711828/94b5f490-ed50-11e6-8c5b-ebd3ee566fed.png">
<img width="332" alt="screen shot 2017-02-07 at 4 11 08 pm" src="https://cloud.githubusercontent.com/assets/5831434/22711826/94b5888e-ed50-11e6-8c59-93a60c8600b0.png">

**Comment by majapw** [comment]
Huh, I have no idea what would cause this regression. @timhwang21 what version did you upgrade from and are you now on v5.0.0 or v5.2.0?

This is probably coming from the minimum nights calculation I imagine. Can you share your prop values?

**Comment by timhwang21** [comment]
I'll test later today if it's a regression by rolling back the version, didn't have time earlier today

Will also reply with props, I overwrote the blocked dates function but realize I didn't write any minimum nights logic so I'll check that out as well.

Thanks for the quick response!

Tim Hwang
Software Engineer
http://timhwang21.github.io

**Comment by timhwang21** [comment]
Sorry, I actually upgraded from `4.3.2` to `6.0.1`. Problem is still there after rolling back, so it's not a regression. 

I think the only relevant prop I have passed is `isOutsideRange()` which in my situation is a no-op.
