### ISSUE TITLE
Make readonly on the input fields overrideable

### ISSUE THREAD

**Issue by matthiasfeist** [airbnb/react-dates#317]
Here: https://github.com/airbnb/react-dates/blob/master/src/components/DateInput.jsx#L130
We found a little problem with this today. A colleague has a newer Dell laptop with .... a touch screen! And for him the input field does not accept any inputs.
Now I can totally understand why you added this feature but it would be really great if I had an option to disable it somehow or to override this...

Thanks a lot for your awesome component by the way!

**Comment by majapw** [comment]
I think this is fixed now! X_x If `readOnly` is explicitly set to false, then that will override the default `isTouch` fallback --- https://github.com/airbnb/react-dates/blob/master/src/components/DateInput.jsx#L194
