### ISSUE TITLE
Error: Can't convert undefined to object

### ISSUE THREAD

**Issue by RodionNikolaev** [airbnb/react-dates#318]
I'm taking [this example](https://github.com/airbnb/react-dates/blob/master/examples/DateRangePickerWrapper.jsx) and replace constructor initialization like this:

this.state = {
            focusedInput: null,
            **startDate: moment()**,
            **endDate: moment().add(5, "day")**,
        };

When I click to 'EndDate' input I receive  "**TypeError: can't convert undefined to object**"

![default](https://cloud.githubusercontent.com/assets/10497662/22836524/d4cc6ca6-efcd-11e6-95eb-bf7a64e327e5.png)

react-dates@6.0.2
react@15.4.2

**Comment by ljharb** [comment]
Can you provide more of the stack trace?

**Comment by RodionNikolaev** [comment]
Chrome:
![default](https://cloud.githubusercontent.com/assets/10497662/22840819/0ec987ce-efe0-11e6-923c-56723c11c08d.png)

Firefox:
![default](https://cloud.githubusercontent.com/assets/10497662/22840855/3beee80c-efe0-11e6-9f26-22535d9fe6d4.png)

**Comment by majapw** [comment]
@RodionNikolaev do you have any other props passed into your `DateRangePicker`?

**Comment by ljharb** [comment]
This looks like the error is coming from moment's `diff` function.

**Comment by RodionNikolaev** [comment]
@ljharb  I have tried to downgrade momentjs version.  Seems like this error occurs from moment@2.13.0 until current version.

**Comment by ljharb** [comment]
@RodionNikolaev can you make a test case that just uses moment, and not react-dates at all? If so we should file that on moment itself.

**Comment by majapw** [comment]
I can't repro though... shouldn't it happen for us as well?

**Comment by majapw** [comment]
I'm going to close this issue since we can't repo.
