### ISSUE TITLE
How to show selected days in day picker?

### ISSUE THREAD

**Issue by tamoyal** [airbnb/react-dates#320]
It looks like the supported way to select a day in the DayPicker is to define `modifiers` and change the class of the day element. When I say select a day, I mean show the day is selected in the user interface by force (in the event that we are showing edit time, we have a previously set time) or when the user is actually interacting with the DayPicker. This seems slow / inefficient because the date comparison code in the modifiers method needs to be run for each day and it looks like regardless of number of months showing, it renders 90 days (maybe the month before and month after)? So that's 90 comparisons every time a day is tapped, a month is changed, or we forcefully set the selected date and re-render the component to reflect that. Maybe it's just a documentation issue. Is there a better way?

Right now I do something like...
```
  dayClick = (date) => {
    this.setState({selectedDay: date});
  }
...
<DayPicker
  id="date_input"
  numberOfMonths={1}
  onDayClick={this.dayClick}
  modifiers={{selected: (day) => 
    day.isSame(this.state.selectedDay, 'd')}}
/>

```

The SingleDatePicker has a `date` prop for selected date but it doesn't look like the DayPicker does.

**Comment by zefj** [comment]
Struggling with the same issue, it looks as if the DayPicker component wasn't finished. I need an inline calendar without an input field and literally every lib out there is a pop-up datepicker hooked to an input field.

**Comment by majapw** [comment]
Hi @tamoyal, is this issue about the performance or about the `DayPicker` component requiring modifiers?

We're addressing the performance issues slowly (we'll probably be making some large architectural changes soon which will be a bigger one, but now we're hacking away at it) and tracking this problem in https://github.com/airbnb/react-dates/issues/272 primarily.

As for needing an out of the box input-less calendar, @zefj, we have exposed `DayPickerRangeController` (which you can check out [here](http://airbnb.io/react-dates/?selectedKind=DayPickerRangeController&selectedStory=default&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel)) and soon, we'll also expose `DayPickerSingleDateController` as well. :)

**Comment by tamoyal** [comment]
hard to respond intelligently ~2 months later but i think the issue is there should be a callback for when a date is tapped with more stuff passed back

**Comment by majapw** [comment]
So sorry for the delayed response. :'( I definitely just missed some issues when things got crazy at work, and this was one of them, unfortunately. Thanks for responding anyways!

**Comment by alpjor** [comment]
when will we get `DayPickerSingleDateController`?

**Comment by alpjor** [comment]
It looks to me like the modifiers that are currently passed into <DayPicker are getting lost in here: https://github.com/airbnb/react-dates/blob/master/src/components/CalendarMonthGrid.jsx#L223

why would we need to pass modifiers that are scoped to a month name?
