### ISSUE TITLE
How to handle only selecting 1 date on the DateRangePicker

### ISSUE THREAD

**Issue by watsonink** [airbnb/react-dates#321]
We notice something rather strange, we can't select a single date in the DateRangePicker. Should this be something we could handle or is this a bug?

Even the React Storyboard demo doesn't allow you to select a single date.

**Comment by majapw** [comment]
What do you mean? The `DateRangePicker` is designed to select a range, ie two dates. The `SingleDatePicker` allows you to select just one date, if that's what you need. Both seem functional in the demo. Can you post a gif or a screenshot of what you're seeing?

**Comment by RodionNikolaev** [comment]
@majapw, For example, this can be actual for Reports, in most cases we select a date range, but sometimes we need data for one day only, for today or for yesterday.
Like this:
![selection](https://cloud.githubusercontent.com/assets/10497662/22852635/19ac3332-f051-11e6-9fb6-c859f37ac7d1.gif)

Partially we solved this with this code:

```
onDatesChange({startDate, endDate}) {
        if (this.state.startDate.diff(startDate, 'days') == 0 && this.state.endDate.diff(endDate, 'days') == 0) {
            if (this.state.focusedInput == "startDate")
                endDate = startDate;
            else
                startDate = endDate;
        }     
        this.setState({startDate, endDate});
}
```

**Comment by watsonink** [comment]
@majapw: Thanks for the quick comment, I was going to explain what we are trying to do, however, I think @RodionNikolaev just answered.

@RodionNikolae: I will try this out, many thanks.

**Comment by watsonink** [comment]
I am closing this, as of 7.0.0, this feature is now available.
@majapw: thanks for including this feature.

**Comment by ConAntonakos** [comment]
To be specific, just set `minimumNights={0}` in order to achieve the effect of the issue in question.
