### ISSUE TITLE
Why is the opacity of the DateInput field set to 0?

### ISSUE THREAD

**Issue by ecbrodie** [airbnb/react-dates#329]
Perhaps not an issue in the application by definition, but this still feels like the best place to report something that does not make sense to me.

I would like to know more as to why the CSS `opacity` value of the `<input>` for the DateInput is set to `0`? It feels semantically wrong because an opacity of 0 implies full transparency, ie the element is invisible, ie I should not see it on the page. But that is indeed not the case. It is quite visible on the page.

This also does not play well with the Capybara acceptance test framework. By default, their `fill_in` method looks only for `<input>` fields that are visible. Setting the opacity to 0 makes Capybara correctly believe that this field should not be filled in. I had to use a workaround of a `visible: false` option in that DSL to trick Capybara, but I think that this hack should not be necessary.

Thank you for your feedback.

**Comment by ecbrodie** [comment]
Poking due to lack of activity. @ljharb ?

**Comment by majapw** [comment]
Hey @ecbrodie, the inputs are in need of a bit of a refactor. The original
designs we were working with wanted to devalue the inputs in favor of the
calendar interaction. As a result the library doesn't show a cursor in the
inputs, even when you can type. This is something I am looking into fixing,
but unfortunately, has not been high on my priority. I hope to get to it in
the coming weeks (months?).

**Comment by majapw** [comment]
I think this has been addressed now that we are using real life inputs! :)
