### ISSUE TITLE
programmatically clear dates

### ISSUE THREAD

**Issue by oldo** [airbnb/react-dates#330]
I'd like to clear the dates from any of the pickers programmatically. Basically I just want exactly the same functionality as the clear dates button, but to trigger it via code. Is this possible?

**Comment by majapw** [comment]
Just set `date` or `startDate` and `endDate` to null in your containing element. They are props passed into the `SingleDatePicker` or the `DateRangePicker` so you can set them to whatever you want.

**Comment by oldo** [comment]
Too easy! :-D
Thanks :-)

**Comment by edward93** [comment]
When you enter incorrect day manually (typing the date e.g. start date - 01/01/2017 and end date 01/01/2015) It actually doesn't update the state and it remains null. So in this case that incorrect value stays  no matter what at least I couldn't find a solution or workaround for it. Any advise?

**Comment by kishoremvrs** [comment]
i too have the same issue as mentioned by @edward93 

Can there be a solution? or should i just make the input field read only.?

**Comment by Andrevoks** [comment]
same problem like @edward93, guys did you find any solution?

**Comment by baybird** [comment]
Having the same issue.

Object { startDate: null, endDate: null }

componentWillReceiveProps() *********** 

Object { _isAMomentObject: true, _i: Object, _isUTC: false, _pf: Object, _locale: Object, _d: Date 2018-06-29T07:00:00.000Z, _isValid: true }

**Comment by alwsBgood** [comment]
More comments, more chances to find a solution?) Have the same problem, help wanted.

**Comment by lferreira457** [comment]
Had a similar issue with not being able to clear invalid dates/gibberish entered manually by a user.
Managed to check/clear this manually via a promise after date pickers are unfocused:

```
handleFocusChange = ({ focused }) => {
  this.setState({ focused }, () => { this.clearInvalidInput() })
}

clearInvalidInput = (focused) => {
  if (focused || this.props.selected) return
  document.querySelector(`input[id='${this.props.id}']`).value = ''
}
```
it would still be better if we were able to programmatically clear all input values (not just valid dates)

**Comment by thian4** [comment]
having the same issue 

https://github.com/airbnb/react-dates/issues/1548

**Comment by DBjelovuk** [comment]
This should be reopened. The issue is still outstanding as far as I can make out. Setting the date to null doesn't seem to affect the underlying input value.
