### ISSUE TITLE
In README.md: Why do you need to export PKG environment variable?

### ISSUE THREAD

**Issue by Jesus-Gonzalez** [airbnb/react-dates#334]
I think this script is "wrong": It's not critical, but I'd suggest not exporting the PKG envvar. 
```
(
    export PKG=react-dates;
    npm info "$PKG" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g; s/ *//g' | xargs npm install --save "$PKG"
)
```

Change the `export PKG=react-dates` to just `PKG=react-dates`
If I'm correct, setting the variable as `export`, you will indeed export the envvar to other sessions. We do just need the envvar set for the current command.

Thank you,
Jesús

**Comment by ljharb** [comment]
In my testing, the `export` is required for the command to work in some shells, and due to the parens (which invokes a subshell) the var should not be visible afterwards.

Is this something you've tested or noticed in practice, or is this solely a theoretical concern?

**Comment by Jesus-Gonzalez** [comment]
I understand:
It's solely a theoretical concern and I might be completely wrong about it, just curious.

Jesús

**Comment by ljharb** [comment]
Thanks for being vigilant!

In my testing (both originally, and now) this will not result in `PKG` being available outside the parens.
