### ISSUE TITLE
Server Rendering Checksum Error

### ISSUE THREAD

**Issue by robwise** [airbnb/react-dates#335]
When server-rendering we get a checksum error because `DateInput` is using `isTouchDevice` to set the `readOnly` attribute on the input. `isTouchDevice` is always rendering `false` on the server (since `window` isn't defined) regardless of whether the client device is actually a touchDevice. What's worse, this causes checksum errors even if the device is not a touch device anyway:

```
       Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
        (client)  autocomplete="off" readonly="" aria-des
        (server)  autocomplete="off" aria-describedby=""
```

One way to fix this might be to move the device type check to run only after the component mounts and just use a constant value when on the server and on the initial render. Or, alternatively, you could allow the user to specify the value themselves if they so choose and thus figure out their own fix, such as guessing the device type on the server via the request's user agent header (similar to this discussion for media queries in react-responsive: https://github.com/contra/react-responsive/issues/43).

**Comment by ljharb** [comment]
Indeed, moving the `isTouchDevice` check to `componentDidMount` is the proper solution here.

**Comment by robwise** [comment]
@ljharb Should I make a PR?

**Comment by ljharb** [comment]
I'm about to put one up :-) thanks tho!

**Comment by ljharb** [comment]
Fixed, will be in the next release.
