### ISSUE TITLE
Add screenshot to readme

### ISSUE THREAD

**Issue by ljharb** [airbnb/react-dates#34]
Also, add demo URL to "website" field of package.json

**Comment by lencioni** [comment]
Animated GIF?

**Comment by ljharb** [comment]
That would be awesome!

**Comment by lencioni** [comment]
How's this one?

![react-dates-optimized](https://cloud.githubusercontent.com/assets/195534/17918916/e7a79ff2-697d-11e6-95fc-e7521a0eff5f.gif)

**Comment by ljharb** [comment]
LGTM :-)
