### ISSUE TITLE
DateRangePicker won't fire when on clicked, no error in console.

### ISSUE THREAD

**Issue by eldyvoon** [airbnb/react-dates#343]
I tried SingleDatePicker and DayPicker and it worked. But not DateRangePicker. I did see the DateRangePicker being rendered but it doesn't nothing when I click on it. No error at all in my console. Am I missing something?

**Comment by ljharb** [comment]
Can you provide the code you're using?

**Comment by eldyvoon** [comment]
I simply do 

```
import { DateRangePicker } from 'react-dates';

render(){
  return(
    <DateRangePicker />
  )
}
```

I can see this http://imgur.com/GhqlI8X but there's no event attached to it? Clicked on it but nothing happens.

**Comment by ljharb** [comment]
If you check the propType warnings (the shape is [here](https://github.com/airbnb/react-dates/blob/master/src/shapes/DateRangePickerShape.js)) you'll see that there's a number of required properties you'll need to provide.

**Comment by eldyvoon** [comment]
@ljharb I suspect that's the issue but why there's no error in my console? I tried to removed few props from SingleDatePicker I can see the error in my console.

**Comment by ljharb** [comment]
Are you using the production React build? In dev you should use the dev build, which does surface PropType warnings.

You don't have to include the DateRangePickerShape - that's just a list of the props you can/must supply.

**Comment by eldyvoon** [comment]
@ljharb I can see prop error when I did not supply prop for SingleDatePicker but not DateRangePicker. Feel like a bug to me.

**Comment by ljharb** [comment]
It's possible that the required props haven't yet been published. Nonetheless, if you follow the shape I linked, you should be able to get a working picker.

**Comment by eldyvoon** [comment]
How I require the DateRangePickerShape ? `import { DateRangePickerShape } from react-dates`?

**Comment by ljharb** [comment]
You don't import the shape at all - you read it with your eyes, and see what props it says are required and what kind of value they expect, and then you type that prop name in your component and provide a compatible value.

**Comment by pratikborsadiya** [comment]
I am having the same issue here is the code i am using
```
import { DateRangePicker } from 'react-dates';
import 'react-dates/lib/css/_datepicker.css';

<DateRangePicker
	startDateId={'start-date'}
	endDateId={'end-date'}
	onDatesChange={(startDate, endDate)=>{ console.log(startDate, endDate); }}
	onFocusChange={(focusedInput)=>{ console.log(focusedInput); }}
	startDate={moment()}
	endDate={moment()} />
```
DateRange picker is not opening, There are no errors in console too!

**Comment by majapw** [comment]
@pratikborsadiya your `onFocusChange` and `onDatesChange` methods don't actually do anything. If you look at our readme:
```
Here is the minimum REQUIRED setup you need to get the DateRangePicker working:

<DateRangePicker
  startDate={this.state.startDate} // momentPropTypes.momentObj or null,
  endDate={this.state.endDate} // momentPropTypes.momentObj or null,
  onDatesChange={({ startDate, endDate }) => this.setState({ startDate, endDate })} // PropTypes.func.isRequired,
  focusedInput={this.state.focusedInput} // PropTypes.oneOf([START_DATE, END_DATE]) or null,
  onFocusChange={focusedInput => this.setState({ focusedInput })} // PropTypes.func.isRequired,
/>
```

Specifically, the parent components keeps track of whether or not the datepicker is open by updating `this.state.focusedInput`. If `focusedInput` never gets updates, the datepicker will never open.

**Comment by pratikborsadiya** [comment]
@majapw I was following [this](https://github.com/airbnb/react-dates/blob/master/src/shapes/DateRangePickerShape.js) shape as mentioned in above comment by @ljharb and it seems that the file is not up-to-date as it do not state that `focusedInput` is required.
Thanks for the help anyways.

**Comment by majapw** [comment]
The problem with focusedInput is that it can be null (when nothing is
focused), which gave us issues with required proptypes in the past. We do
try to highlight its necessity in the readme tho. I think there's maybe a
comment in the shape as well.

**Comment by ljharb** [comment]
i think we can try it again with `explicitNull` tho

**Comment by majapw** [comment]
I think the original issue here has been addressed.
