### ISSUE TITLE
DateRangePicker Calendar not rendering correctly.

### ISSUE THREAD

**Issue by GGross5213** [airbnb/react-dates#344]
I am having trouble rendering the DateRangePicker Calendar to render properly.

Here is what I have:

![react-dates-screenshot](https://cloud.githubusercontent.com/assets/5498093/23228443/2131d404-f902-11e6-9324-324ba3092a06.png)

My code is:
`                    <DateRangePicker   startDate={startDate}
                                       endDate={endDate}
                                       focusedInput={focusedInput}
                                       onDatesChange={this.onDatesChange}
                                       onFocusChange={this.onFocusChange}
                                       showClearDates={true}
                                       startDatePlaceholderText={"Start Date"}
                                       endDatePlaceholderText={"End Date"}
                                       orientation={HORIZONTAL_ORIENTATION}
                    />`

**Comment by majapw** [comment]
Do you have any universal table styles in place. Likely, there is something overwriting the td widths or the table width (that is my guess). Can you inspect the styles on those elements and show those?

In either case, this is definitely a CSS issue. Your setup look reasonable.

**Comment by GGross5213** [comment]
You are totally right. I do have some global table styles. That fixed it! Thanks!
