### ISSUE TITLE
Failed to setState({ date }) on onDateChange

### ISSUE THREAD

**Issue by SiqiTian-minted** [airbnb/react-dates#346]
Need help, for the following code:

```jsx
import React from 'react';
import { SingleDatePicker } from 'react-dates';

class MyComponent extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      focused: false,
      date: null,
      otherKey1: '',
      otherKey2: 1,
    };
    this.onChangeDate = this.onChangeDate.bind(this);
    this.onChangeDateFocus = this.onChangeDateFocus.bind(this);
  }

  onChangeDate(date) {
    console.log(date);
    this.setState({
      ...this.state,
      date,
    }, () => console.log(this.state));
  }
  onChangeDateFocus({ focused }) {
    this.setState({
      ...this.state,
      focused,
    });
  }

  render() {
    const { date, focused, otherKey1, otherKey2 } = this.state;
    return (
      <SingleDatePicker
        id="my-data-picker"
        date={date}
        focused={focused}
        onDateChange={this.onChangeDate}
        onFocusChange={this.onChangeDateFocus}
      />
    );
  }
}
```
When click on any date, it will trigger `onFocusChange`, but I will get `focused=null`.

More importantly, when click on any date, despite it successfully trigger `onDateChange` with `date=MomentObject{...}`, the `this.setState` fails. My `this.state.date` is always `null`.

Any ideas? Do I need to `require('moment')` for this file?

**Comment by ljharb** [comment]
I doubt it's related, but fwiw you don't need `...this.state,` - React always merges your `setState` argument with the existing state for you. If you remove that line, does the problem still occur?

**Comment by SiqiTian-minted** [comment]
Nope, still `focused`=`null` and `date`=`null`. I wonder if it has anything to do with CSS, since I have it in a modal window.

**Comment by ljharb** [comment]
Can you make a jsfiddle that reproduces the error?

**Comment by SiqiTian-minted** [comment]
anyway, it magically healed it self today, strange. closing

**Comment by mikeLspohn** [comment]
I'm having a similar issue where `date` isn't updating after `onDateChange`. In the function provided to `onDateChange` I'm creating a new state object like so

**Comment by ljharb** [comment]
What is `update` and `$set`?

**Comment by mikeLspohn** [comment]
That's just from react immutability helpers. That part works fine though, we're using it elsewhere. And like I said the console.log of newState is correct.

**Comment by ZengQingFeng1994** [comment]
Here's a problem with the react dates component:
Problem scenarios:
1. The startDate property is disabled and the default value is set;
2. When the onDateChange function is triggered, get the date: {startDates, endDates};
Problems encountered:
{startDates and endDates} are the default values we set at the beginning: startDates. What causes this?Is there any solution?
Here is my code:
onDatesChange = ({ startDate, endDate }: DateRangeType) => {
    console.log('startDate', startDate);
    console.log('endDate', endDate);
    this.setState(
      {
        startDate,
        endDate,
      },
      () => {
        const { onChange } = this.props;
        const { endDate, startDate } = this.state;
        if (endDate && startDate) {
          const end = endDate.format('YYYY-MM-DD');
          const start = startDate.format('YYYY-MM-DD');
          const days = this.mathDays(end, start);
          onChange && onChange({ end, start, days });
        }
      }
    );
  };

**Comment by ZengQingFeng1994** [comment]
@ljharb
Here's a problem with the react dates component:
Problem scenarios:
1. The startDate property is disabled and the default value is set;
2. When the onDateChange function is triggered, get the date: {startDates, endDates};
Problems encountered:
{startDates and endDates} are the default values we set at the beginning: startDates. What causes this?Is there any solution?
Here is my code:
OnDatesChange = ({startDate, endDate}: DateRangeType) => {
The console. The log (' startDate, startDate);
The console. The log (" endDate ", endDate);
Enclosing setState (
{
StartDate,
EndDate,
},
() = > {
Const {onChange} = this.props;
Const {endDate, startDate} = this.state;
If (endDate && startDate) {
Const end = endDate. The format (' MM - DD YYYY - ');
Const start = startDate. The format (' MM - DD YYYY - ');
MathDays (end, start);
OnChange ({end, start, days});
}
}
);
};

**Comment by ljharb** [comment]
@zengqingfeng1994 please file a new issue; this one is 2 years old.
