### ISSUE TITLE
Highlight certain dates

### ISSUE THREAD

**Issue by themre** [airbnb/react-dates#36]
Hi,
Great lib! Currently you have blockedByDefault api, that blocks certain dates. I would like to know, if there could be some API that you could add certain styling on certain dates (e.g. for highlighting, or some other stuff). And perhaps custom tooltip would also be nice. Just like with jQuery UI, where datepicker has method beforeShowDay.

**Comment by ljharb** [comment]
Can you be more specific about your use case? Screenshots of the existing component, edited to show a mockup of what you want, would be particularly helpful.

**Comment by themre** [comment]
Sure! For example we're gathering some data and when new data arrives, we want to highlight that data, so that the user knows. But you can also pick some other date if you'd like. Example is below.
![image](https://cloud.githubusercontent.com/assets/10845050/17883821/15a50dae-6915-11e6-8bc4-0afb1c5a955d.png)

**Comment by Corei13** [comment]
Currently the `<CalendarDay />` component renders `<span className="CalendarDay__day">{day.format('D')}</span>`. A `renderDay` prop can be added to render custom day components. It'll be also useful in use cases like this:
![image](https://cloud.githubusercontent.com/assets/4954380/17901669/415be7b2-6986-11e6-8bd0-f2065c74cb67.png)

**Comment by majapw** [comment]
I am not super sure about overriding the `renderDay` method, mostly because that's something I feel like should be tightly controlled.

However, as for the original selection, I think it'd be reasonable to add something like `isDayHighlighted` similar to the `isDayBlocked` and `isOutsideRange` methods on the top-level to add the `CalendarMonth__day--highlight` class to specific days.

**Comment by themre** [comment]
no, I also wouldn't override renderDay method, perhaps adding more props would be enough (e.g. isDayHihglighted). 
and for adding additional html to day (as @Corei13 pointed), you could add `additionalDayHtml` prop which would render if a function returned anything.
