### ISSUE TITLE
initialVisibleMonth as previous month and this month

### ISSUE THREAD

**Issue by cheeminjun** [airbnb/react-dates#364]
I'm trying to use the DateRangePicker for a dashboard where you select only past dates. Now I've found the way to reverse the outside range via #209 but I also want the initialVisibleMonth to start with the previous month + this month. 

How do I use initialVisibleMonth to do so?

**Comment by majapw** [comment]
Hi @cheeminjun! You would do the following:
```
initialVisibleMonth={() => moment().subtract(1, 'month')}
```
You might also want to cache `moment()` in your constructor or somewhere similar so as to avoid creating a new moment object on every render.

**Comment by cheeminjun** [comment]
Cheers!
