### ISSUE TITLE
How to use in Angular 2

### ISSUE THREAD

**Issue by a-jahanshahlo** [airbnb/react-dates#369]
Hi
Please tell me can i use this package on angular 2+ if YES please tell me how to use?
if NO have any plane for angular 2+?

**Comment by ljharb** [comment]
This is a React component, not an Angular one. Unless Angular 2 can render React components, I don't think this will be possible.

We have no plans to support Angular.

**Comment by a-jahanshahlo** [comment]
Please one more Question?
Can i use this component like javascript library in none React base project?
If Yes how do that?

**Comment by ljharb** [comment]
No - this is a React component, so you can only use it if you are using React (or a similar React-like rendering engine).

**Comment by a-jahanshahlo** [comment]
:( :(
Thank you for permanent replying.

**Comment by eldarsil** [comment]
Hi! Probably this will help [https://github.com/larixsource/angular-react-dates](url)

**Comment by a-jahanshahlo** [comment]
Thank you a lot.
This is exactly i need.

**Comment by hemanth-sp** [comment]
> Hi! Probably this will help https://github.com/larixsource/angular-react-dates

how modify this angular code beacuse i need to add some custom methods and ui?????????????????

**Comment by kuncevic** [comment]
Just use https://ng-bootstrap.github.io/#/components/datepicker/overview by `import {NgbDate, NgbCalendar} from '@ng-bootstrap/ng-bootstrap';`
