### ISSUE TITLE
Date prop type

### ISSUE THREAD

**Issue by SergeyShablenko** [airbnb/react-dates#370]
`date` is set to null by default, but SingleDatePicker throws next error 
Invalid prop `date` of type `object` supplied to `SingleDatePicker`, expected `Moment`
Any suggestions how to fix it?

**Comment by ljharb** [comment]
https://github.com/airbnb/react-dates/blob/master/src/components/SingleDatePicker.jsx#L36-L37 says that it's required.

I'm not sure why it's not actually required by the propType (@majapw) but you need to pass a moment object as `date` in `SingleDatePicker` for it to work.

**Comment by majapw** [comment]
Wait, it's not required because we couldn't get `one of thing or
null.isRequired`. But yes.

**Comment by ljharb** [comment]
We should be able to now, with `or` and `explicitNull` from `airbnb-prop-types` :-)

**Comment by majapw** [comment]
@SergeyShablenko to clarify, are you trying to pass an object other than `null` or a moment object to the `SingleDatePicker`? I am looking at the public storybook and `null` does not seem to throw a proptype warning (this would also throw in our tests I imagine).

In either case, I will work on making the prop explicitly required... but I'm confused about what the actual issue you're running into is.

**Comment by majapw** [comment]
I'm going to assume this is no longer an issue! :)

**Comment by Parthchokshi** [comment]
@majapw I think it has to do with moment constructor getting null as initial value.
https://github.com/airbnb/react-dates/issues/1127#issuecomment-401201659
