### ISSUE TITLE
Custom highlight class

### ISSUE THREAD

**Issue by davidmartin** [airbnb/react-dates#374]
Hi,
I am wondering if it could be possible to highlight more than one day using different colors and if so how can I accomplish that?

Thanks.

**Comment by majapw** [comment]
Hi @davidmartin, there's no real way to do this right now as the only class we apply in this situation is `.CalendarDay__highlighted-calendar`. Can you describe your use case and why that would be necessary?

**Comment by davidmartin** [comment]
Hi @majapw, It would be necessary because I need to mark different holiday dates, such as:

- Blue days:  National holiday
- Yellow days: User's holiday
- Green days: Special Days 

![calendar](https://cloud.githubusercontent.com/assets/11908901/24197305/68037aee-0f01-11e7-9937-a99ea4e94f64.png)

I thought in two different ways to accomplish that:

1. Allow adding a className to the td element related to the day.
2. Allow adding a children component inside the td element related to the day.

**Comment by vepasto** [comment]
@davidmartin you can use `renderDay` function here. 

```
<DayPicker
        ...
	renderDay={this.renderDay}
/>
```  
and the renderDay function would be something like this
```
	renderDay(day) {
                const holidayColor = this.getHolidayColor(day);

		return (
			<div style={{ backgroundColor: holidayColor ? holidayColor : 'white', height: '100%', color: 'black' }}>
				<span>{day.format('D')}</span>
			</div>
		);
	}
```

**Comment by mattias800** [comment]
The typing for renderDay is wrong in the Typescript definitions.

**Comment by ljharb** [comment]
@mattias800 you should file that on the DefinitelyTyped repo; we do not write, maintain, or support TypeScript definitions.

**Comment by kdichev** [comment]
![image](https://user-images.githubusercontent.com/12297753/34390693-a3c7a8f8-eb41-11e7-9200-e21a8043297c.png)

I have managed to go this far as displaying differrent colored ranges. I am using `renderDayContents` but I guess I might want to switch to render day?

**Comment by juanpujol** [comment]
@kdichev did you managed to make this work?

**Comment by kdichev** [comment]
@juanpujol yes, I did manage to do what I have shown on the screenshot but unfortunately I cannot find the project I was working on. Ill try and find it and post it here as soon as possible.

**Comment by nelsoneldoro** [comment]
@juanpujol  you can manage days by `renderDayContents` prop

`renderDayContents?: (day: momentPropTypes.momentObj) => (string | JSX.Element)`

```
<DayPicker
    renderDayContents={(day) => (day.day() % 6 === 5 ? '😻' : day.format('D'))}
/>
```



![image](https://user-images.githubusercontent.com/137902/46686598-212bfd80-cbcf-11e8-8b15-792128332c61.png)

**Comment by juanpujol** [comment]
Thanks @kdichev and @nelsoneldoro

**Comment by davidmartin** [comment]
Thanks !! :+1:

**Comment by kdichev** [comment]
@davidmartin I think we should close this one :)

**Comment by majapw** [comment]
Thanks for helping out, y'all! :)

**Comment by mitko993** [comment]
Hello,

I am using the `renderCalendarDay` prop with `CustomizableCalendarDay`.
How do i add styles for ::after ?
This is what I've tried so far, but nothing works:

const selectedStyles = {
  background: '#590098',
  border: '1px solid #590098',
  color: '#fff',

  after: {...},
  '&:after': {...},
  '::after': {...}
};

**Comment by jufghd** [comment]
> @juanpujol you can manage days by `renderDayContents` prop like as following
> 
> `renderDayContents?: (day: momentPropTypes.momentObj) => (string | JSX.Element)`
> 
> ```
> <DayPicker
>     renderDayContents={(day) => (day.day() % 6 === 5 ? '😻' : day.format('D'))}
> />
> ```
> 
> ![image](https://user-images.githubusercontent.com/137902/46686598-212bfd80-cbcf-11e8-8b15-792128332c61.png)

how to change dates of different blocked dates color??

**Comment by f4ez** [comment]
> ![image](https://user-images.githubusercontent.com/12297753/34390693-a3c7a8f8-eb41-11e7-9200-e21a8043297c.png)
> 
> I have managed to go this far as displaying differrent colored ranges. I am using `renderDayContents` but I guess I might want to switch to render day?

Bro I want this one code :)

**Comment by HenryPineda** [comment]
Hi @majapw I have a question. I am using the DayPickerRangeController I am able to pick end start and the start date. Picking the date range backwards essentially. Starting with the end date and then the start. However. The hightlighting does not working does when picking the dates backwards. Meaning that in the normal behavior whent the start date is selected the later dates up until the end date hightlighted in a green color. Any idea how to achive that highlighting when the dates are being selected backwards. Thanks!
