### ISSUE TITLE
Plunker/JSFiddle/etc. with react-dates?

### ISSUE THREAD

**Issue by rubencodes** [airbnb/react-dates#375]
I'm having some bugs with how this project is interacting with another package, but I'm finding it difficult to reproduce as I can't find a UMD build of react-dates I can simply import. Does anyone have a Plunker/JSFiddle/etc. setup with react-dates? Would be super helpful. Thanks!

**Comment by ljharb** [comment]
Does https://wzrd.in/standalone/react-dates@latest help?

**Comment by rubencodes** [comment]
This is perfect! Thank you!
