### ISSUE TITLE
Improved documentation for `focusedInput` (and in general...)

### ISSUE THREAD

**Issue by ddellacosta** [airbnb/react-dates#386]
My issue is simply that understanding the actual important parts of getting a bare-bones working version of this up is not clear. The [example](https://github.com/airbnb/react-dates/blob/master/examples/DateRangePickerWrapper.jsx) has a lot of incidental complexity and lacks comments describing what is truly important and what is not. The main documentation is also lacking.

After actually reading the code I realized that, basically, you need to define the `onDatesChange` and `onFocusChange` functions (which becomes obvious immediately) and then to actually trigger opening of the calendar sub-widgets, you need to explicitly set `focusedInput` in your props to the input which is focused, using the constants provided. The documentation states:

> The focusedInput prop indicates which of the two inputs is currently focused, if either. You can import the START_DATE and END_DATE constants from react-dates/constants.

This suggests that you don't have to set this; I think it would be more clear if this said something like

> The `focusedInput` prop, when set, triggers display of the `DayPicker` widget, and is associated with the input field which has current focus.  It's likely you want to explicitly set this in your `onFocusChange` handler.  You can import the `START_DATE` and `END_DATE` constants from react-dates/constants.  (Note that the DayPicker widget will call `onDatesChange` when it returns with the date selected, mapped to a given input.)

...or something.  In fact it would probably be more useful to simply state at the beginning of the docs exactly what is truly required and how this stuff fits together, and to simplify (or better document) the example to do the same.

Of course I would be remiss if I did not mention that part of the reason I had trouble was certainly that I was trying to implement this in ClojureScript, my JavaScript is terrible, and the example has enough JS-isms in it that it took me a bit of time to figure it out. But having something that clearly stated/showed the _true_ bare minimum to getting this up and running would probably be helpful for everyone.  See https://github.com/airbnb/react-dates/issues/385 or https://github.com/airbnb/react-dates/issues/343, for example.

I'm happy to offer a PR for this if you want, but didn't want to start there without asking first to avoid wasting time.

**Comment by majapw** [comment]
Hi @ddellacosta, I've def been thinking about this a lot. Our README has a lot of superfluous information, but doesn't really do enough to explain how to use the component out of the box.

Can you take a look at https://github.com/airbnb/react-dates/pull/387 and see if the new version makes more sense to you?

**Comment by ddellacosta** [comment]
@majapw Sorry I'm late to the party here--I just saw the docs you updated and I think it makes a world of difference. Much better!

Thanks a lot for your response and for taking the time to improve the documentation.
