### ISSUE TITLE
remove jQuery from peerDependencies

### ISSUE THREAD

**Issue by maslianok** [airbnb/react-dates#39]
Thanks for the awesome component!

Just one question:
Can we remove jQuery from this component? 

I found that you use it only at [src/components/DayPicker.jsx](https://github.com/airbnb/react-dates/blob/master/src/components/DayPicker.jsx). Am I right? Can we rewrite it with pure javascript?

**Comment by majapw** [comment]
Yeah definitely! We have a PR open here - https://github.com/airbnb/react-dates/pull/16 where we're already working on it. :) We need to test it in IE9 and IE10 first before we merge it in, which we are unfortunately not able to do with storybook, so it's going to take us a bit longer. I'm going to use the airbnb site for testing and hopefully we can get that merged in this weekend!

**Comment by maslianok** [comment]
Oh, my bad. Didn't see that PR.

Maybe let's leave this issue open for now, so anyone else like me can find this information?

**Comment by majapw** [comment]
👍 Definitely! Will close it when we get testing completed and can merge that stuff in!

**Comment by zackify** [comment]
I saw this was merged, can someone push a new release to npm? thanks :)

**Comment by majapw** [comment]
Will do later today!

**Comment by sontek** [comment]
haha, I'm excited about this project.  First thing I ran into was the jquery dependency and you are already fixing it today :)

**Comment by majapw** [comment]
So glad to hear it, @sontek! Feel free to suggest any other improvements as issues and PRs. :) We've just release v2.1.1 without jquery so yaaaay. :) @zackify
