### ISSUE TITLE
Question: how to disable future days/months

### ISSUE THREAD

**Issue by dgsunesen** [airbnb/react-dates#390]
Hi y'all,

I'm working on an app that needs to display some historical data in a graph. I would like to the restrict the user to only be able to choose past days/months. How is this possible here? I see the `isOutsideRange` but I'm not sure if that's the one to use and how to go on about it.

Best regards
Dan

**Comment by majapw** [comment]
Hi @dgsunesen!

You can accomplish this by doing:
```
import { isInclusivelyAfterDay } from 'react-dates';

const today = moment(); // alternatively cache it in the constructor
...

render() {
  return (
    <DateRangePicker
      isOutsideRange={day => isInclusivelyAfterDay(today)}
      ...
    />
  );
}
```

**Comment by dgsunesen** [comment]
Hmm.. Doesn't seem to work?

**Comment by dgsunesen** [comment]
Found the "error"... I had to pass in `day` as the first parameter in `isInclusivelyAfterDay`

**Comment by dgsunesen** [comment]
@majapw - last question. How would i include today as well? Right now it's only days before today. I would like to be able to pick today as well..

**Comment by ConAntonakos** [comment]
After attempting this, I believe `day` and `today` need to be switched?

` isOutsideRange={day => isInclusivelyAfterDay(day, today)}`

**Comment by timhwang21** [comment]
@ConAntonakos Looks right 👍

**Comment by c316** [comment]
To get this to work I had to do

```
isOutsideRange={day => isInclusivelyAfterDay(day, moment().add(1, 'days'))}
```
