### ISSUE TITLE
Is there a way to re-enable blocked dates after they have been blocked off?

### ISSUE THREAD

**Issue by acp31** [airbnb/react-dates#392]
I need to have the first and last day in a date range be able to be selected so I can have multiple bookings on the same day. For example if one person checks out on a Sunday I want to have someone be able to check in that same Sunday because the entire day is not being reserved. I want to have some sort of representation for users that a certain day has only been partially booked.

**Comment by majapw** [comment]
Hello @acp31!

The best bet right now would be to conditionally block dates based on whether or not the start date or the end date is focused.

For instance, for your case, the Sunday in question would not be blocked when `focusedInput` is equal to `START_DATE` but would be blocked when `focusedInput` is equal to `END_DATE`.
