### ISSUE TITLE
Suddenly Calendar won't open

### ISSUE THREAD

**Issue by GGross5213** [airbnb/react-dates#398]
I don't know what happened but I updated everything and now suddenly the react-dates calendar won't open when I click on it.

Edit: 

I can tab through and get it to open. It specifically doesn't open on click
Here is how I am using DateRangePicker:

```                
<DateRangePicker startDate={startDate}
                               endDate={endDate}
                                focusedInput={focusedInput}
                                onDatesChange={this.onDatesChange}
                                onFocusChange={this.onFocusChange}
                                showClearDates={true}
                                startDatePlaceholderText={"Start Date"}
                                endDatePlaceholderText={"End Date"}
                                withPortal={true}
 />
```

**Comment by majapw** [comment]
Can you share from what version you update? That will probably help to narrow down the issue.

**Comment by GGross5213** [comment]
I believe I was using 7.0.1 then updated to 8.2.1

**Comment by GGross5213** [comment]
Okay. I narrowed it down. I am also using the library [materialize-css](https://github.com/Dogfalo/materialize) in my app. They released a new version and that seemed to break react-dates. I am not sure what they did, but I rolled back the materialize-css version. Everything works fine now.
