### ISSUE TITLE
OutsideClickHandler causes error

### ISSUE THREAD

**Issue by dgsunesen** [airbnb/react-dates#403]
Hi,

I'm working on a week picker I'm trying to build using the DayPicker. I would like to import the OutsideClickHandler to make something kind of like the DateRangePicker, where the calendar closes when I click outside.

However, when I try to use the OutsideClickHandler, I keep getting this error:

<img width="971" alt="screen shot 2017-03-26 at 19 45 53" src="https://cloud.githubusercontent.com/assets/1023815/24333702/13295296-125d-11e7-806c-f8301eb0ed4b.png">

My render method looks like this:

```
render() {
    const { state, dispatch } = this.props;
    const { focused, date } = this.state;

    const modifiers = {
      'hovered': day => this.isInWeek(day),
      'selected-start': day => this.isStartDate(day),
      'selected-end': day => this.isEndDate(day),
      'selected-span': day => this.isInBetween(day),
    }

    return (
      <div>
        <OutsideClickHandler onOutsideClick={() => console.log('clicked outside')}>
          <DateRangePickerInputController />
          <DayPicker
            modifiers={modifiers}
            numberOfMonths={2}
            onDayClick={this.onDayClick}
            onDayMouseEnter={this.onDayMouseEnter}
            onDayMouseLeave={this.onDayMouseLeave}
          />
        </OutsideClickHandler>
      </div>
    );
  }
```

Importing the react-dates components like this:

`import { DayPicker, DateRangePickerInputController, OutsideClickHandler } from "react-dates";`

I'm using Typescript as well (not sure if that should have anything to say in this regard).

/Dan

**Comment by ljharb** [comment]
OutsideClickHandler is not exported from index.js. You'd need to import it directly from its file path.

**Comment by dgsunesen** [comment]
oh, I see.. that explains why :) - Thanks @ljharb
