### ISSUE TITLE
warning on focusedInput

### ISSUE THREAD

**Issue by ndao** [airbnb/react-dates#408]
I'm getting a warning when using focusedInput prop. has that been removed in the latest version?

`Warning: Failed prop type: SingleDatePicker: unknown props found: focusedInput`

**Comment by majapw** [comment]
The `SingleDatePicker` never took a `focusedInput`! :) 

It takes a `focused` prop that can either be true or false.

**Comment by ndao** [comment]
oh! There was not a warning before so I was confused. thanks for clarifying!

**Comment by majapw** [comment]
Yup! One of the latest updates added `forbidExtraProps` on each component which helps to highlight typos like this more quickly. :)
