### ISSUE TITLE
Month displayed is not synced with the provided date

### ISSUE THREAD

**Issue by ingro** [airbnb/react-dates#41]
Hello and thanks for this well designed library!
Anyway I found a bug (or maybe it is a design choice?).

If I pass a date as props to `SingleDatePicker` that it outside the current month(s), like this:

```jsx
<SingleDatePicker
    focused
    date={moment().add(70, 'days')}
/>
``` 

The `DayPicker` keep showing the current month(s) without displaying the selected date, and that may confuse the user.

I think that the right behaviour is that if a date is provided then the `DayPicker` should show the month of that date instead the current one.

**Comment by majapw** [comment]
I think you are right! and I think this is a duplicate issue of https://github.com/airbnb/react-dates/issues/17

We've had a lot of discussion there, but I think the best way to do this moving forward is to provide a prop that allows the parent component to set the visible month on opening. If we allow that to be a moment object, it'd be very easy to do as you describe:
```
const date = moment().add(70, 'days');
<SingleDatePicker
  focused
  date={date}
  initialVisibleMonth={date}
/>
```

I'm going to close this issue as a duplicate, but feel free to hop on the conversation over there!

**Comment by ingro** [comment]
Sorry, I didn't notice that there was already an issue opened! I will follow there, thanks for your response!
