### ISSUE TITLE
How to block reserved dates with asynchronous call to get data?

### ISSUE THREAD

**Issue by Swapnilchavan18** [airbnb/react-dates#422]
I want to get reserved dates with asynchronous call and block them with isDayBlocked function, but this does not work. it keeps on rendering lot of times and make reserved date unblocked again. I am not sure how to do this. Can anyone help.

I am using below code, my ls1 object has array of reserved objects.
```jsx
<DateRangePicker startDate={this.state.startDate} endDate={this.state.endDate} onDatesChange={({ startDate, endDate }) => this.setState({ startDate, endDate })} focusedInput={this.state.focusedInput}  onFocusChange={focusedInput => this.setState({ focusedInput })} numberOfMonths={this.state.nomonths} renderDay={this.renderday.bind(this)} isDayBlocked={this.checkcalendar.bind(this)} onNextMonthClick={this.onNextMonthClick.bind(this)}/>

checkcalendar(data){
       var ddate = data._d;
        var day = data._d.getDate();
        this.state.ls1.forEach(function(value, index){
            if(moment(ddate).format('YYYY-MM-DD') ==ls1.rdate){
                return true;
            }
        });
}
```
it keeps rendering a lot and finally blocking does not work as expected.

**Comment by ljharb** [comment]
@Swapnilchavan18 are you aware that `return true` only returns from the forEach function, and not at all from `checkcalendar`? you might want `some` instead of `forEach`. (also, `forEach` and friends is synchronous, not asynchronous)

**Comment by Swapnilchavan18** [comment]
ok thanks for your explanation.
I did it working with below code.

var ddate = day._d;
        var day = day._d.getDate();
        var rescnt = 0,ls1=[];
        if( this.state.ls1!= null){
            rescnt = this.state.ls1.length;
            ls1= this.state.resdata.ls1;
        }
        for(var i=0;i<rescnt;i++){
            var resdate = ls1[i].resdate;
            if(moment(ddate).format('YYYY-MM-DD') == resdate){
                return true;
            }
        }
