### ISSUE TITLE
How can we block DRP with checkin and checkout dates separetely for reserved dates.

### ISSUE THREAD

**Issue by Swapnilchavan18** [airbnb/react-dates#424]
I have check in and checkout dates from asynchronous call, I am blocking dates with isblocked method, now I want to show different blocking for check in and check out, because I need checkout date open 1 day more than checkin blocked dates, How can we apply checkout 1 more day open for bookings.
I am using below code for blocking bookings.
```js
        var ddate = day._d;
        var day = day._d.getDate();
        var rescnt = 0,ls1=[];
        if( this.state.ls1!= null){
            rescnt = this.state.ls1.length;
            ls1= this.state.resdata.ls1;
        }
        for(var i=0;i<rescnt;i++){
            var resdate = ls1[i].resdate;
            if(moment(ddate).format('YYYY-MM-DD') == resdate){
                return true;
            }
        }
```

**Comment by ljharb** [comment]
(please use triple backticks to surround code blocks; they're unreadable otherwise. i've edited your post to include them)

**Comment by majapw** [comment]
Hi @Swapnilchavan18, 
This should be possible presently by just having a different check depending on whether the `focusedInput` is `START_DATE` or `END_DATE`. Basically, I'd do something like:
```
isBlocked(day) {
  const { focusedInput } = this.state;
  if (focusedInput === START_DATE) {
    ...
  } else {
    ...
  }
}

render() {
  return (
    <DateRangePicker
      isDayBlocked={this.isBlocked}
      ...
    />
  );
}
```

In v11.0.0, the `isDayBlocked` function will get rerun when the `focusedInput` changes - https://github.com/airbnb/react-dates/blob/master/src/components/DayPickerRangeController.jsx#L274-L291
