### ISSUE TITLE
Keyboard Accessibility help modal broken when only 1 month is visible

### ISSUE THREAD

**Issue by emmenko** [airbnb/react-dates#427]
Version: `react-dates@10.0.0`

![image](https://cloud.githubusercontent.com/assets/1110551/24788983/f2c18d94-1b70-11e7-9424-e1b94f46c2d8.png)

**Comment by emmenko** [comment]
Also, is there a way to **not show** the `?` button?

**Comment by ConAntonakos** [comment]
I noticed this as well.

![screen shot 2017-04-10 at 3 34 58 pm](https://cloud.githubusercontent.com/assets/1504302/24879121/c5155e9e-1e03-11e7-8c74-912655288dd0.png)

Should we add `overflow: auto` to the `.DayPickerKeyboardShortcuts__panel` class?

**Comment by ConAntonakos** [comment]
Also, there seems to be some clipping for `.DayPickerKeyboardShortcuts__show--bottom-right`?

![screen shot 2017-04-10 at 4 10 55 pm](https://cloud.githubusercontent.com/assets/1504302/24880535/c8c26c44-1e08-11e7-9a01-2b4a605214a5.png)

Ostensibly from this rule: `border-top: 26px solid #fff`. Maybe make it `transparent` instead?

**Comment by majapw** [comment]
Huzzah! Totally not surprised that these things broke (it was a very big PR) and very happy to accept PRs to fix them. 

Quick stop-gap to hide the `?` would be just to hide it in CSS (I think it's `.DayPickerKeyboardShortcuts__show`?), but yeah we should probs fix the panel. :)

**Comment by atkinchris** [comment]
We hastily patched this with `.DayPickerKeyboardShortcuts__panel {  position: fixed; }`. Not perfect, but functional.

**Comment by dburles** [comment]
Can see the behaviour here: http://airbnb.io/react-dates/?selectedKind=DayPickerRangeController&selectedStory=single%20month&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel

**Comment by majapw** [comment]
Ping! Sorry for the delay, but here's a PR - https://github.com/airbnb/react-dates/pull/477

**Comment by emmenko** [comment]
Cool, thanks for addressing this 👍
