### ISSUE TITLE
Modifying the layout

### ISSUE THREAD

**Issue by dhcloud** [airbnb/react-dates#428]
Hi

I was wondering how easy / difficult it is to adjust the layout of the (AirBnb) Datepicker. I've looked through the component code but seems quite a technical challenge unless I'm missing an essential point that does make it easy.

The required change to the layout would be limited to the header and from:

    <    April 2017    >  // present UX to scroll through months / years

to:

    <     2017     >  // be able to click through years - both directions

    <     April     >   // be able to click through months - both directions 

If anyone can show me how to do this I'd be massively grateful.

Many thanks :-)

**Comment by ljharb** [comment]
#25 is for allowing year navigation.

**Comment by majapw** [comment]
Yeah, I think we'd need to basically have a different component to allow month/year navigation in this way. I'm going to close this issue in favor of #25 since it is essentially asking for the same thing.
