### ISSUE TITLE
RTL languages support

### ISSUE THREAD

**Issue by sag1v** [airbnb/react-dates#431]
There inst a native way to make it render right to left? am i missing something in the doc's?

**Comment by ljharb** [comment]
This would be a great thing to support.

**Comment by sag1v** [comment]
i've forked it and added `RTL` support (70% done) still have to change the animations of `prev` and `next`.
also added examples to the storybook.
let me know what you think:
https://github.com/sag1v/react-dates/tree/feature/RTL-support

**Comment by ljharb** [comment]
Some pre-review - initialisms like RTL should always be capitalized; `Rtl` looks like a Java camelCasing algorithm. Also, there's some whitespace that needs consistency, as well as a bunch that needs needs reverting; and it'll need some tests. Looks like a great start though!

**Comment by sag1v** [comment]
> initialisms like RTL should always be capitalized

done. 
any idea on how to handle the animations? 
and i think we may have to handle the height calculation of `transition-container`

**Comment by sag1v** [comment]
i finished most of the core changes. i've created a PR. would love if you can take a look and review it. :)

**Comment by ljharb** [comment]
linking to #454
