### ISSUE TITLE
Is there an option to get range date pickers separately?

### ISSUE THREAD

**Issue by wzup** [airbnb/react-dates#433]
So your default DP is combined like this:

![react storybook - google chrome 2017-04-10 18 23 02](https://cloud.githubusercontent.com/assets/3880497/24857481/11d3b0fc-1e1b-11e7-80bf-0d57a0837c9e.png)

Is there a predefined option to have two date pickers separately, like this? By predefined I mean to get it without much hacking

![1124x977 - google chrome 2017-04-10 18 23 38](https://cloud.githubusercontent.com/assets/3880497/24857515/2e28f1ea-1e1b-11e7-973d-3f794ff5b8b9.png)

**Comment by majapw** [comment]
Hi @wzup, I'm going to leave this information here and close this issue.

There are two options for this behavior if you want to use `react-dates` depending on your needs.

If you want the attached calendar that shows a range and has hovering over the range, you can use css to override the styles of the individual inputs. The default styling has them looking like one input, but you can def override that.

If you want two separate inputs each with their own calendar and with a single date select, I would recommend using two `SingleDatePicker` components.

**Comment by danvn** [comment]
How can you override the styles of the individual inputs to make them look separate in the DRP?
