### ISSUE TITLE
React DOM Unknown Prop Warning on implementation of onClose

### ISSUE THREAD

**Issue by hamisor** [airbnb/react-dates#444]
The current implementation of onClose callback in DataInput.jsx uses onClose props in the input tag. This is not a recognised prop by react DOM or HTML DOM. Please change onClose to data-onClose to avoid react warning. 

Thanks

**Comment by haunguyen90** [comment]
@ljharb Any ideas to fix it ?

**Comment by ljharb** [comment]
Fix is incoming. Caused by #397.
