### ISSUE TITLE
Object.assign is not defined ( at IE )

### ISSUE THREAD

**Issue by 9renpoto** [airbnb/react-dates#445]
`react-dates/lib/utils/getPhrasePropTypes.js` use `Object.assign`, after babel .
Please use https://www.npmjs.com/package/babel-plugin-transform-object-assign

version: `react-dates@10.1.0` 

```js
function getPhrasePropTypes(defaultPhrases) {
  return Object.keys(defaultPhrases).reduce(function (phrases, key) {
    return Object.assign({}, phrases, _defineProperty({}, key, _propTypes2['default'].oneOfType([_propTypes2['default'].string, _propTypes2['default'].func, _propTypes2['default'].node])));
  }, {});
}
```

**Comment by ljharb** [comment]
You are expected to polyfill it in your own app. That babel plugin would mean that we aren't calling the faster, built-in method - we'd instead be shipping a much larger and slower replacement for it.

I recommend https://npmjs.com/object.assign

**Comment by 9renpoto** [comment]
Oops, it is works at IE11 ...
I will continue to investigate a little more.

https://9renpoto.github.io/react-dates-sample/
