### ISSUE TITLE
custom weekday format on week header

### ISSUE THREAD

**Issue by barwis** [airbnb/react-dates#453]
weekday format seems to be hardcoded

`<small>{moment().weekday(i).format('dd')}</small>`

it would be good to be able to set this up in the config

**Comment by palashkaria** [comment]
is this possible with react-dates, in any way?

**Comment by barwis** [comment]
@palashkaria currently the weekday format is hardcoded `('dd')`. Would be great to be able to control it

**Comment by palashkaria** [comment]
I'm doing this using renderCalendarInfo for now, but agreed, it should be configurable.
