### ISSUE TITLE
SingleDatePicker withFullScreenPortal scrolling

### ISSUE THREAD

**Issue by modsoussi** [airbnb/react-dates#456]
I'm using a ```SingleDatePicker``` with ```withFullScreenPortal={true}``` from react-dates@10.1.1 and I'm running into the issue where if I touch on the SDP, the page scrolls all the way to the bottom before SDP is in focus. The SDP is part of a bottom floating bar. Any idea what could be causing this?

**Comment by sag1v** [comment]
@modsoussi  can you create an example of that behavior?

**Comment by majapw** [comment]
@modsoussi A gif would also be very helpful!

**Comment by modsoussi** [comment]
@majapw @sag1v you can see an example of this behavior on https://daycationapp.com/hotels/metcomo-miami. Had to push to production because running low on time. But bottom line is I have two SingleDatePickers, one is rendered withFullScreenPortal on a fixed div when on mobile and the other one is rendered on desktop. Only one is rendered at a time. I'm going to try to recreate the behavior in a standalone project.

**Comment by modsoussi** [comment]
@majapw @sag1v https://daycationapp.com/test/react/dates now has a reproduction of the weird behavior. The code for it is as follows:
```
import {SingleDatePicker as SDP} from 'react-dates';
import moment from 'moment';

export default class extends React.Component {
  constructor(props, context) {
    super(props, context);

    this.state = {
      date: moment(),
      focused: false
    };

    this.onDateChange = this.onDateChange.bind(this);
    this.onFocusChange = this.onFocusChange.bind(this);
  }

  onDateChange(date) {
    this.setState({
      date: date
    });
  }

  onFocusChange(focus){
    this.setState(focus);
  }

  render() {
    return(
      <div style={{backgroundColor: "rgb(200,200,200)", height: '300vh', overflowY: 'scroll'}}>
        <div style={{position: 'fixed',  bottom: '10px', backgroundColor: 'white'}}>
          <SDP
            date={this.state.date}
            focused={this.state.focused}
            onFocusChange={this.onFocusChange}
            onDateChange={this.onDateChange}
            numberOfMonths={1}
            placeholder="mm/dd/yyyy"
            withFullScreenPortal={true}
          />
        </div>
      </div>
    )
  }
}
```

**Comment by modsoussi** [comment]
@majapw @sag1v anything on this?

**Comment by modsoussi** [comment]
Going to close this issue. I worked around the issue by saving scroll state right before the date picker appears and scrolling the background back to that state so when the date picker disappears the scroll state is back where it was.
