### ISSUE TITLE
Shortcuts on singleDatePicker

### ISSUE THREAD

**Issue by liormaynhypr** [airbnb/react-dates#460]
hey,
i'm using singleDatePicker and i would like the shortcuts button to not be displayed.
how can i do that?
is there a prop i'm missing that disables the display of that button?

thanks :)

**Comment by sag1v** [comment]
was about to ask the same, the only condition i found for displaying that is `!isTouch` on the `DayPicker.jsx`:
![kbshortcuts](https://cloud.githubusercontent.com/assets/9153149/25313151/dfe836a0-2831-11e7-915a-fc30e4aa761a.png)
would be nice if we can explicitly configure to hide / show this, for example via a prop `enableKeyboardShortcuts`

**Comment by ljharb** [comment]
Why would you want to hide it? It's for accessibility.

**Comment by liormaynhypr** [comment]
it overflowed and i don't have enough room in the page where the date picker is needed to adjust the sizes..

**Comment by liormaynhypr** [comment]
i fixed it with display none in the meantime but i think it would be nice if it was optional

**Comment by ljharb** [comment]
I think that perhaps what would make the most sense is an option to disable the keyboard shortcuts unconditionally, which would then naturally hide the shortcuts button.

**Comment by sag1v** [comment]
@ljharb what do you mean by 

> an option to disable the keyboard shortcuts unconditionally

**Comment by ljharb** [comment]
Correct. If keyboard shortcuts work, the "?" button should be displayed; if it's not displayed, the shortcuts shouldn't work.

**Comment by sag1v** [comment]
I think the keyboard shortcuts feature should get some second attention. i mean it's a great feature but can't really use it with the issues it has. [461](https://github.com/airbnb/react-dates/issues/461) [462](https://github.com/airbnb/react-dates/issues/462)

**Comment by kbariotis** [comment]
@ljharb specific users may not need accessibility (shortcuts specifically) and throwing to them an extra button will just confuse them more. 

Having an option to disable shortcuts all together sounds good to me since if you don't know that shortcuts exist you wouldn't expect something to happen if you accidentally press a key.

**Comment by sag1v** [comment]
issue [#427](https://github.com/airbnb/react-dates/issues/427) got most of the issues we mentioned the last couple of days regarding the keyboard shortcuts

**Comment by majapw** [comment]
@ljharb I disagree. Keyboard shortcuts should be non-negotiable, but I think it's fine to have an option to hide the menu.

**Comment by sag1v** [comment]
@majapw you mean hiding the button that shows the menu?

**Comment by majapw** [comment]
Yeah. I've added an option for that in https://github.com/airbnb/react-dates/pull/477

**Comment by ljharb** [comment]
@majapw why is it acceptable for keys to secretly trigger behavior without a clear explanation for what they do?

**Comment by majapw** [comment]
The `hideKeyboardShortcutsPanel` prop is available in the latest version.

**Comment by thiemeljiri** [comment]
Why is the button showing up in Firefox but not in Chrome? I even searched the DOM for the button but without success. This really puzzles me. Is that intentional?
