### ISSUE TITLE
Keyboard Shortcuts button on single month overlap with CalendarDay

### ISSUE THREAD

**Issue by sag1v** [airbnb/react-dates#461]
When you use a single month display, the `CalendarDay` is overlapping with the `top-border` of  `KeyboardShortcuts`:

![singlemonthkb](https://cloud.githubusercontent.com/assets/9153149/25313498/6f1967bc-2838-11e7-92a6-86edec8158bb.png)

my suggestion is to change the `border-top` color of `.DayPickerKeyboardShortcuts__show--bottom-right` to `transparent` instead of `#FFF`.
Will result in this:

![singlemonthkbfix](https://cloud.githubusercontent.com/assets/9153149/25313545/2d117656-2839-11e7-943d-f75c5dcf143c.png)

**Comment by majapw** [comment]
This should be fixed now!
