### ISSUE TITLE
How to enable selection of month and year only, and how to set min and max date range for a Single date picker

### ISSUE THREAD

**Issue by jofomah** [airbnb/react-dates#465]
Hey,

I need help with two things:

-  How to set Single Date Picker to select only month and year without selecting date example, when the calendar opens, it shows only months and years without showing dates.

- Is there a way to set min and max date range, e.g if i have a date range picker, i want the start date to be less than or equal to end date while end date is always greater than or equal to start date. is there an in-built feature for that??

**Comment by majapw** [comment]
Hi @jofomah, sorry for the delay in response:

For your first question, are you looking for a month picker, ie https://github.com/airbnb/react-dates/pull/241? We don't currently have that component... and the datepickers, well uh, they're about selecting dates, not months.

For your second question, the start date is already assumed and enforced to be less than the end date. To limit what values those can be, you can use the `isOutsideRange` prop to indicate what dates are not allowed.

**Comment by jofomah** [comment]
@majapw thanks!
