### ISSUE TITLE
Disable keyboard shortcuts panel

### ISSUE THREAD

**Issue by kbariotis** [airbnb/react-dates#466]
Is it possible to disable keyboard shortcuts panel?

**Comment by ljharb** [comment]
Not currently; see #460

**Comment by kbariotis** [comment]
Thank you, let me comment there.

**Comment by padrisimo** [comment]
css cheat:

`button.DayPickerKeyboardShortcuts_buttonReset {
  display:none;
}`

wont disable it functionality but hide the button.

![captura de pantalla 2018-06-01 a las 16 59 09](https://user-images.githubusercontent.com/15703165/40847649-42c722ee-65bd-11e8-91ab-483205d392cd.png)

**Comment by majapw** [comment]
There's also a `hideKeyboardShortcutsPanel` prop that you can set to true.

**Comment by Kibo007** [comment]
Thank you @majapw , strange I could not find this in the documentation
