### ISSUE TITLE
prop-types deprecation warning due to react-portal

### ISSUE THREAD

**Issue by kbariotis** [airbnb/react-dates#467]
prop-types deprecation warning is still there due to the [react-portal](https://github.com/tajo/react-portal) package

https://cloudup.com/cGWN1K_TwPb

I am opening this issue for reference. `react-portal` should be updated once this [PR](https://github.com/tajo/react-portal/pull/144) is merged.

Thank you

**Comment by ljharb** [comment]
Thanks - the reference isn't needed tho; that's a semver-patch update, so it will automatically upgrade when published.

**Comment by feyzo** [comment]
@ljharb It looks like fix for this issue was a minor update `v3.1.0`. Can you bump up the version for `react-portal` please?

https://github.com/tajo/react-portal/releases/tag/v3.1.0

**Comment by ljharb** [comment]
@feyzo no need, `^` automatically covers all non-major updates.

**Comment by feyzo** [comment]
I researched how to upgrade a sub-dependency in `yarn` but couldn't find a decent solution. There are a few issues scattered around on web but none of them helped.

Can you tell me how i can use `react-portal@3.1.0` without installing it as a main dependency?

**Comment by ljharb** [comment]
You'd have to check yarn's documentation; we use npm.
