### ISSUE TITLE
Need help setting initial Date for SingleDatePicker

### ISSUE THREAD

**Issue by dtodo1paco** [airbnb/react-dates#470]
Hi!

I've seen in storybook that setting a "before-today" date for initial date in a SingleDatePicker is possible ([here](http://airbnb.io/react-dates/?selectedKind=SDP%20-%20Day%20Props&selectedStory=allows%20all%20days%2C%20including%20past%20days&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel))

![image](https://cloud.githubusercontent.com/assets/3096057/25419833/4849eb74-2a55-11e7-806c-c492b17fd44e.png)

But I could not find the correct property to set the same behavoir. 
I'm trying this
```
                <SingleDatePicker
                    showClearDate={true}
                    numberOfMonths={3}
                    enableOutsideDays={true}
                    isDayBlocked={() => false }
                    date={this.state.date} // momentPropTypes.momentObj or null
                    onDateChange={date => this.setState({ date })} // PropTypes.func.isRequired
                    focused={this.state.focused} // PropTypes.bool
                    onFocusChange={({ focused }) => this.setState({ focused })} // PropTypes.func.isRequired
                />
```

But the result is not the expected:
![image](https://cloud.githubusercontent.com/assets/3096057/25419838/50e7b6bc-2a55-11e7-8ebc-63189dd7a0dd.png)

I've searched the documentation and try a lot of properties, but as I find a startDate prop in DateRangePicker, there is no equivalent in SingleDatePicker

Can somebody help with this? Maybe I'm missing something obvious. If this is the case, please, let me know.

Thanks

**Comment by majapw** [comment]
I think the `initialVisibleMonth` property might be what you're looking for? It expects a thunk ie (`() => moment()`) that returns a moment object representing the month you want to be first in your visible months.

**Comment by majapw** [comment]
JOKES: I think what you want is the `isOutsideRange` prop. If you look in the stories, https://github.com/airbnb/react-dates/blob/master/stories/SingleDatePicker_day.js#L25 is what you're looking for. You'd want to set `isOutsideRange` to `() => false` for this to work.

**Comment by majapw** [comment]
`isDayBlocked` is more intended for individual one-off days and `isOutsideRange` is intended for limiting the scope of what is selectable at all.
