### ISSUE TITLE
displayFormat not working

### ISSUE THREAD

**Issue by aishwarya-bote** [airbnb/react-dates#471]
I am trying to add displayFormat="MMM DD YYYY" to dateRangePicker but its not working.

**Comment by majapw** [comment]
Hi @aishwarya-bote, can you share your actual code? I tried
```
    <DateRangePicker
      displayFormat="MMM DD YYYY"
    />
```
in the storybook and it just works.

**Comment by aishwarya-bote** [comment]
Here is my code.
![datedisplayformat](https://cloud.githubusercontent.com/assets/20040165/25533755/446dfada-2c4f-11e7-8edb-9d3ad4531202.png)

**Comment by ljharb** [comment]
What is your moment locale? Do you use any moment plugins that might be changing how moment works?

**Comment by majapw** [comment]
@aishwarya-bote Can you also share a screenshot of the kind of behavior you are actually seeing? Like what format does end up being used?

**Comment by aishwarya-bote** [comment]
@ljharb The locale is 'en' and no there are no additional moment plugins.

@majapw The format getting displayed is 'YYYY-MM-DD'.refer the screenshot attached.

![displayformat](https://cloud.githubusercontent.com/assets/20040165/25697778/f277dd6a-30d9-11e7-819a-013c1aa39142.png)

**Comment by majapw** [comment]
What do your css overrides look like? The input element (which is hidden by the default css that comes packaged) always has an ISO (YYYY-MM-DD) format value, but the actual text that gets displayed uses the display format.

**Comment by aishwarya-bote** [comment]
You are right @majapw . the css wrapper '.DateInput__display-text' had its display set to 'none'.As soon as i removed it the correct display format showed up. But now i dont know how to hide the default format of date input box.Currently i can see both the values.See thescreenshot attached.
![bothdisplays](https://cloud.githubusercontent.com/assets/20040165/25733517/888d5d3c-3177-11e7-9fb7-8d86da91da13.png)

Could you maybe help me with this?

**Comment by timrcoulson** [comment]
Bump on this

**Comment by majapw** [comment]
Oh wow, this is old! @timrcoulson are you still seeing this issue? I don't think it is applicable anymore. 

If you are seeing both it is likely that either the CSS is not being loaded properly or that there is an override that is doing weird things. If this is still a problem, can you open a new issue detailing the problems you are seeing?
