### ISSUE TITLE
diplayFormat not work at the first time

### ISSUE THREAD

**Issue by guonanci** [airbnb/react-dates#472]
displayFormat not work when dates controller showed at the first time , but it works normally after I closed it and open again
Current version is 10.1.1

```js
  displayFormat = () => {
    moment.locale('zh_CN')
  }

  isOutsideRange=()=>{
    return false
  }
  render () {
    const {startDate, endDate, focusedInput} = this.state
    const {type, available_items, min_date, max_date } = this.props.filter
    const {hdidx, value} = this.props
    const dateRangePicker = <div>
         <DateRangePicker
          onDatesChange={this.onDatesChange}
          onFocusChange={this.onFocusChange}
          startDate={startDate}
          endDate={endDate}
          focusedInput={focusedInput}
          numberOfMonths={2}
          displayFormat={this.displayFormat}
          keepOpenOnDateSelect={true}
          startDatePlaceholderText={'开始日期'}
          endDatePlaceholderText={'截止日期'}
          isOutsideRange={this.isOutsideRange} />

        <Button bsStyle='orange' onClick={this.onConfirm}>确定</Button>
      </div>
      ...
  }
```

**Comment by ljharb** [comment]
`moment.locale()` is stateful and you need to call it yourself, in componentWillMount or sooner.

I'm pretty sure displayFormat needs to return a format, not "whatever moment.locale()" returns.

**Comment by guonanci** [comment]
@ljharb I tried react mounting lifecycle method, still not work, you can also set displayFormat to sth, maybe you will meet the same problem ?

**Comment by ljharb** [comment]
I'm suggesting that you omit `displayFormat` entirely, and instead ensure that `moment.locale('zh_CN')` has been called prior to `DateRangePicker` rendering - does that help?

**Comment by guonanci** [comment]
@ljharb It helps, thanks a lot, In fact, displayFormat can work normally, but I just wrapped <Overlay>
 with <Popover>, <Popover> with <PopoverFilter>, and <PopoverFilter> with <DateRangePicker>(react-dates), if less one, it can be formatted normally.
