### ISSUE TITLE
object.assign causes app failure in IE11 and Android

### ISSUE THREAD

**Issue by byrondevonwall** [airbnb/react-dates#476]
`object.assign` on line 15 of `lib/utils/getPhrasePropTypes.js` causes IE11 to error out, because `object.assign` is not a method IE11 recognizes.

Looking at this document: http://kangax.github.io/compat-table/es6/#test-Object_static_methods_Object.assign 
It looks as though the same will be true on most android browsers, though I haven't tested that yet.

Babel-polyfill: http://babeljs.io/docs/usage/polyfill/ is easy to use and fixes the issue, but I figured I'd make an issue just to point out that this component straight out of the box has the potential to break apps in (at least) IE11.

**Comment by ljharb** [comment]
You're expected to use https://npmjs.com/airbnb-browser-shims or the equivalent.

That said, we can use the object.assign package here and mitigate the issue.

**Comment by byrondevonwall** [comment]
It's definitely an easy fix, however there's nothing I could find in the docs about needing the shim package (it's not listed as a peer dependency, for instance) or a polyfill so I figured I'd mention it.
