### ISSUE TITLE
[Question] Is it possible to have predefined date ranges?

### ISSUE THREAD

**Issue by liubko** [airbnb/react-dates#481]
I wonder if it's possible to have predefined date ranges?

smth like:
![screen shot 2017-05-01 at 1 28 51 pm](https://cloud.githubusercontent.com/assets/4257937/25577883/2add8002-2e72-11e7-9975-6a819fda6ed9.png)

maybe it's possible to put them in `renderCalendarInfo` section?

**Comment by majapw** [comment]
This hasn't been implemented at all and isn't a terribly high priority for us, but has been discussed in https://github.com/airbnb/react-dates/issues/29. I'm going to close this as a duplicate in favor of that issue.

As mentioned in https://github.com/airbnb/react-dates/issues/29#issuecomment-272970641, it is probably possible to roll your own with the set-up right now (esp with the `renderCalendarInfo` prop).

**Comment by liubko** [comment]
Thanks. Sorry for the duplicate.
