### ISSUE TITLE
Regression of minimum nights hover with release 11.0.0

### ISSUE THREAD

**Issue by chris-verclytte** [airbnb/react-dates#487]
It seems there is a regression with last release on minimumNights prop. 

Previously, when using `minimumNights={x}`, hovering current date would hover the next `x` days. 
It is not working anymore with last version (on http://airbnb.io/react-dates/).

**Comment by majapw** [comment]
This is likely something to do with the v11 release. There's a few features that got lost/messed up by the rearchitecting that I'll attempt to patch today. Thank you for flagging!

**Comment by majapw** [comment]
Should be fixed in 11.0.1!
