### ISSUE TITLE
IE 11 issue - .includes() is not supported

### ISSUE THREAD

**Issue by arthurvi** [airbnb/react-dates#49]
### Bug
In IE11 I get the following error when selecting a day 
```
Object doesn't support property or method 'includes'
```

### Cause
It goes wrong [here](https://github.com/airbnb/react-dates/blob/58930108f67e7ccbd820deecef75aafcf17cb4bd/src/components/SingleDatePicker.jsx#L82)

### Proposed solution
`includes` is not supported in IE, can we replace it by `indexOf`?
http://stackoverflow.com/a/31119502

**Comment by ljharb** [comment]
We do typically assume people are using https://npmjs.com/airbnb-js-shims or the equivalent, but this is simple enough that we should use `indexOf` here.

**Comment by ljharb** [comment]
Instead I used `array-includes` so we didn't have to mess with index comparison. Will be included in the next release.

**Comment by DaveCole** [comment]
That fixed things nicely,  and also patched up a couple of unrelated bugs.  I could hug you.  Thank you, sir!
