### ISSUE TITLE
Overriding phrases

### ISSUE THREAD

**Issue by chris-pearce** [airbnb/react-dates#495]
I need to override some of the [phrases](https://github.com/airbnb/react-dates/blob/master/src/defaultPhrases.js), the ones that are specific to accomodation:

* [`focusStartDate`](https://github.com/airbnb/react-dates/blob/master/src/defaultPhrases.js#L2)
* [`chooseAvailableStartDate`](https://github.com/airbnb/react-dates/blob/master/src/defaultPhrases.js#L28)
* [`chooseAvailableEndDate`](https://github.com/airbnb/react-dates/blob/master/src/defaultPhrases.js#L31)

It seems the only way I can do this is to copy **ALL** of the phrases to my project as I cannot `import` them from the library due to them not being exported from [`index.js`](https://github.com/airbnb/react-dates/blob/master/index.js#L25-L49), then point the `phrases` prop to my local copy.

Unless I'm missing something?

**Comment by majapw** [comment]
oh fair point. I think you can do 
```
import defaultPhrases from 'react-dates/lib/defaultPhrases';
``` 
for now, but probs we should export them in the main index file.

**Comment by chris-pearce** [comment]
@majapw thanks for the quick reply, that worked for me but yeah be great to export the phrases so it's part of the library 👍 .

**Comment by ljharb** [comment]
I don't think they need to be exported in the main index file; everything that's importable (including file paths) is part of the library.

**Comment by chris-pearce** [comment]
I was able to override:

```js
import defaultPhrases from 'react-dates/lib/defaultPhrases';
```

```js
const phraseOverrides = {
    ...defaultPhrases,
    chooseAvailableEndDate: localeStrings('datepickerRangeEndDate'),
    chooseAvailableStartDate: localeStrings('datepickerRangeStartDate'),
    focusStartDate: localeStrings('datepickerRangeFocusStartDate')
};
```

```js
phrases={phraseOverrides}
```

If you wanted to close this?

**Comment by majapw** [comment]
LGTM!
