### ISSUE TITLE
Moment version

### ISSUE THREAD

**Issue by jgwconsulting** [airbnb/react-dates#497]
I was just wondering what the issue is with `moment@2.18.1` which doesn't play well with react-dates? Thanks!

**Comment by majapw** [comment]
I think it broke the tests, and we just haven't gotten around to updating things yet! We will probably do this shortly, but other work has been higher priority.

**Comment by jgwconsulting** [comment]
Thanks Maja, and thanks for all your hard work on this component - it's excellent.
