### ISSUE TITLE
Browser support for Safari?

### ISSUE THREAD

**Issue by dancingshell** [airbnb/react-dates#498]
What browsers does this module support?

In safari 10.0 `Object.values()` and `Object.entries()` are not available ( as added by #450 in v11 ). So the component is erroring out.

We could polyfill or version down, but also listing the browser requirements would be nice. 

Thank you!

**Comment by chris-pearce** [comment]
I was trying to find what the overall browser support is? 

Sorry if it's documented somewhere but I couldn't find it.

**Comment by ljharb** [comment]
@dancingshell we assume that you're using https://npmjs.com/airbnb-js-shims or the equivalent; but we can still fix this if I can locate something like https://www.npmjs.com/package/babel-plugin-transform-object-assign for `Object.values` and `Object.entries`.

**Comment by ljharb** [comment]
In the meantime, I've added 768578ec06480c7b07003bae59aada661223ae56 which handles `Object.values` (`Object.entries` seems to have been removed as of v11.0.1)

**Comment by ashwell** [comment]
@ljharb were you going to patch bump and release this to NPM? or just wait for it to go out in your next planned release?

**Comment by ljharb** [comment]
I'll give it a day or two before bumping a release; despite the fact that we've not properly documented the dependency, this is nowhere near the first version of react-dates that required a full ES shim to work.

In the meantime, anyone affected can (and should already be) shimming with https://npmjs.com/airbnb-js-shims or the equivalent.

**Comment by jabsatz** [comment]
where should the `import 'airbnb-js-shims'` be?

**Comment by ljharb** [comment]
As the first line in the first entry point to every page.

**Comment by majapw** [comment]
Should we add this implicit dependency to the README?

**Comment by ljharb** [comment]
Yes, probably.
