### ISSUE TITLE
Unable to update to 11.1.0

### ISSUE THREAD

**Issue by chris-pearce** [airbnb/react-dates#506]
I just tried `npm update` to `11.1.0` but it never works for me:

```bash
npm ERR! code ETARGET
npm ERR! notarget No compatible version found: react-dates@'>=11.1.0 <12.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget 1.0.0, 2.0.0, 2.1.0, 2.1.1, 2.2.0, 3.0.0, 3.1.0, 3.1.1, 3.2.0, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4, 3.4.0, 3.5.0, 3.6.0, 4.0.0, 4.0.1, 4.0.2, 4.1.0, 4.1.1, 4.1.2, 4.2.0, 4.3.0, 4.3.2, 4.3.3, 5.0.0, 5.1.0, 5.1.1, 5.2.0, 6.0.0, 6.0.1, 6.0.2, 6.1.0, 7.0.0, 7.0.1, 8.0.0, 8.1.0, 8.1.1, 8.2.0, 8.2.1, 9.0.0, 9.0.1, 10.0.0, 10.0.1, 10.1.0, 10.1.1, 10.1.2, 10.2.0, 11.0.0, 11.0.1
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chrisp/.npm/_logs/2017-05-11T01_11_10_287Z-debug.log
```

My `package.json`:

```json
"react-dates": "^11.1.0"
```

**Comment by majapw** [comment]
Can you try just running `npm install react-dates@11.1.0`? I def see it in my releases...

**Comment by chris-pearce** [comment]
Hmm not sure what's going wrong as every time I try (including what you suggested) it comes back with the same error as in my initial comment above. Even uninstalling then reinstalling it always defaults to `11.0.1`?

**Comment by ljharb** [comment]
@chris-pearce are you using a private registry, shrinkwrap, or yarn?

**Comment by chris-pearce** [comment]
@ljharb yes I'm using a private NPM registry, no to shrinkwrap and yarn.

**Comment by ljharb** [comment]
ok, so any chance that your private npm registry hasn't yet mirrored those releases from the public one?

**Comment by chris-pearce** [comment]
Ah yes, I'll clear the cache for the private registry, sorry should have thought about that.

**Comment by chris-pearce** [comment]
That fixed it, can close this 👍 .
