### ISSUE TITLE
Hover on a day on Firefox doesn't add classes to the day

### ISSUE THREAD

**Issue by tagoro9** [airbnb/react-dates#515]
When I hover on the calendar on firefox nothing happens. After debugging a little bit, I think there is a bug in the `isTouchDevice` function. 

`ontouchstart` is defined in firefox, but it has a `null` value.

<img width="326" alt="screen shot 2017-05-16 at 5 35 09 pm" src="https://cloud.githubusercontent.com/assets/1235917/26133710/0f534e46-3a5e-11e7-8502-098567812ae4.png">

Since the `onDayMouseEnter` and `onDayMouseLeave` will return if `this.isTouchDevice`, the hover logic doesn't get applied on Firefox.

**Comment by ljharb** [comment]
Which version of Firefox is this happening in? In my v53, it's `undefined`.

**Comment by tagoro9** [comment]
v53.0.2 (64-bit) in macOS sierra

**Comment by tagoro9** [comment]
I just realized what the problem was. Somehow I had the `dom.w3c_touch_events.enabled` property set to 1 in the browser. I didn't remember enabling it. I'm sorry about having created the issue.
