### ISSUE TITLE
visibleDays  should be recalculated after focusedInput change

### ISSUE THREAD

**Issue by Masalovych** [airbnb/react-dates#517]
Hi,
I am using DateRangePicker component. And I need to setup isOutsideRange function for each input separately. For example for startDate only available days should be monday and for endDate only sunday. To do this I am using focusedInput variable in my isOutsideRange function.

The problem that available days don't changed after focusedInput changed. 
I think condition in the file react-dates/src/components/DayPickerRangeController.jsx:201 should be changed that recalculate "newMonthState" when focusedInput changed

When can we expect this issue be fixed?

Best Regards,
Dmytro
dmasalovych@gmail.com

**Comment by timhwang21** [comment]
@Masalovych fixed in #522!
