### ISSUE TITLE
PropTypes deprecation warning

### ISSUE THREAD

**Issue by rbrtsmith** [airbnb/react-dates#518]
I was getting the warning  `Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.` when consuming `react-timelines`.

After some digging around on the stack trace I've narrowed down the error to be caused by the `react-portal` dependency.
![screen shot 2017-05-17 at 15 20 55](https://cloud.githubusercontent.com/assets/4982001/26158873/f757fd66-3b14-11e7-86b6-e9a24cd1a0b2.png)

It seems the `react-portal` maintainers have recently bumped their version to `3.1.0` in turn adding support for React `15.5` while `react-dates` is still has a dependency on `3.0.0` I can issue a PR for this if that is of any help?

**Comment by ljharb** [comment]
`react-dates` depends on `^3.0.0`, which means `v3.1.0` is also valid - a fresh `npm install` should install that for you automatically.

That said, it's fine to bump the dep.

**Comment by rbrtsmith** [comment]
@ljharb Makes sense.  I had not properly cleared my Yarn cache.

**Comment by ljharb** [comment]
Lockfiles do have the unfortunate effect of preventing valid semver auto-updates.
