### ISSUE TITLE
Phantom modifiers 

### ISSUE THREAD

**Issue by nboliver** [airbnb/react-dates#520]
Using the `DayPickerRangeController` component with `v12.0.0`, experiencing some strange behaviour with respect to modifiers being applied at random places:

![image](https://cloud.githubusercontent.com/assets/3094055/26173050/0ea6c196-3b10-11e7-8267-cd28fb7f0455.png)

In the above screenshot, you'll notice that there is a random hovered day, even though the mouse is nowhere near it, and the span is in a different month.

Also, June 26 is showing as last-in-range when it is not.

**Comment by majapw** [comment]
I think `last-in-range` is probably currenlty broken, but I thought I had dealt with the `hovered-span` bug in a previous version. Can you describe the actions that happened to get to the above state? Is this the first load? Did you select a range and clear it? did you select a range and then select a different range? A gif might be helpful!

**Comment by nboliver** [comment]
On further inspection, yes it happens when a range is selected and then a different range is selected. 

Here's a gif:
https://cl.ly/3x3O1l3t1g3b

**Comment by tagoro9** [comment]
I also came into this bug. The steps I used to reproduce:

* Select a range.
* Select the same start date again.
* Select an end date before the previous end date.
* The end date keeps the `CalendarDay--hovered-span` when it shouldn't.
