### ISSUE TITLE
Does it make sense to add a DayPickerController component?

### ISSUE THREAD

**Issue by tagoro9** [airbnb/react-dates#524]
We wanted to build a `<SingleDatePicker />` component but with a custom input component. We ended up creating a `<DayPickerController />` component with a similar purpose than the `<DayPickerRangeController />`.  Most of the logic of our component is really similar to the one inside `<SingleDatePicker/>`. The update to `0.11.0` involved changing a lot of the mentioned `<DayPickerController />` as the modifiers logic changed.

Because of all this, I was wondering if it would make sense to extract some of the logic inside the `<SingleDatePicker />` component into the mentioned `<DayPickerController />` in order to provide the same flexibility the `<DayPickerRangeController/>` provides towards building customized date range pickers.

**Comment by majapw** [comment]
Yes omg yes. This has been on my roadmap for like half a year (basically since we separated out the `DayPickerRangeController`). I have like a half-baked branch for it but haven't really ever gotten around to finish this. This would be HIGHLY appreciated.

**Comment by tagoro9** [comment]
Great! I'll try to create a PR with what we have.

**Comment by pokonski** [comment]
That would be great to have as I'm in exact situation like you @tagoro9 :+1:

**Comment by majapw** [comment]
This exists in v12.2.0!
