### ISSUE TITLE
Building Calendar

### ISSUE THREAD

**Issue by SouthDownsTechnologySolutions** [airbnb/react-dates#526]
Hi, we need your help. We are building the calendar function in our application.  We aim to build the calendar with features like Airbnb. For example:

1. Blocking or unblocking calendar dates 
2. Calendar settings
3. Instant Book
4. Responding to inquiries
5. Syncing calendars 

So, far we have tested different calendar libraries e.g. Bootstrap, jQuery etc. But we still struggle to achieve the same control. Specially selection of dates (>=1) and then create events like price setting etc. Therefore, please we need your help. We are using Google Cloud Services (Google App Engine with Python) for our Application. 

If I wind up the conversation, we want to build calendar module for our applications with similar to Airbnb Calendar functions and what path we should choose. We will wait for your reply. Kind Regards, 
Green. 

P.S. We can't use the React with Google App Engine. We tried earlier to move to React but we encountered issues.

**Comment by SouthDownsTechnologySolutions** [comment]
Today we spent time on this library: https://fullcalendar.io/
It gives us control but still struggling to repeat price ($23) on each date after we select multiple dates from calendar (for example on Airbnb).

**Comment by ljharb** [comment]
This library is for React; if you're unable to use React (which should work fine on appengine since you can run it clientside) then I'm not sure how we can help.

**Comment by SouthDownsTechnologySolutions** [comment]
Thank you.  We will try to reuse the React on App Engine.

**Comment by mmahalwy** [comment]
@ljharb close?

**Comment by sandro-pasquali** [comment]
A good vanilla calendar with those features is https://github.com/chmln/flatpickr
