### ISSUE TITLE
Cannot call method 'querySelector' of null

### ISSUE THREAD

**Issue by jherencia** [airbnb/react-dates#529]
We are using react-dates in a website and have installed RavenJS to track the errors, it appears this error quite often:

<img width="1008" alt="captura de pantalla 2017-05-23 a las 19 18 02" src="https://cloud.githubusercontent.com/assets/459373/26366786/9d37200a-3fec-11e7-877c-632be84b9158.png">

**Comment by ljharb** [comment]
In what browser do you see that?

**Comment by jherencia** [comment]
I attach the browser statistics:

[PEPECAR-1S3-browser.csv.txt](https://github.com/airbnb/react-dates/files/1023590/PEPECAR-1S3-browser.csv.txt)

**Comment by ljharb** [comment]
Hmm, I'm not sure why `findDOMNode` would return null in those browsers.

**Comment by johnryan** [comment]
@jherencia did you find a solution to this? i'm seeing the same issue.

**Comment by majapw** [comment]
So we can add a check for null in these locations, but it seems weird to me that it's not set in `componentDidMount` or that `React.findDOMNode` doesn't return anything.

**Comment by johnryan** [comment]
@majapw so not sure if this helps but what i'm seeing that's a bit weird is that when using create-react-app it works fine in development. The issue only shows up when it's compiled for production.

**Comment by ljharb** [comment]
@jherencia is `this.calendarMonthGrid` a ref that's being set in, perhaps, an inline arrow callback?

Refs can sometimes be null unless you use a constructor-bound instance method (such that the ref callback's reference is `===` every time). You'll either need to check for null, and/or, not use an inline function.

**Comment by majapw** [comment]
Hullo! I made a PR. Please checkout out #552

**Comment by johnryan** [comment]
@majapw Thanks for the PR! is there any recommended way to test this to make sure it fixes the issue? I tried installing with `"react-dates": "git@github.com:airbnb/react-dates.git#maja-add-null-check-for-calendarmonthgrid"` but it seems that the npm version is different than what's on github for some reason.

**Comment by ljharb** [comment]
Anything that's got a build process won't really work when installed from github.

**Comment by johnryan** [comment]
@ljharb Yea that's what I was afraid of, was just hoping to verify there wasn't some other similar null ref issue that will be revealed by this fix.

**Comment by majapw** [comment]
Yeah unfortunately, we'll have to do a release first I think. I'll get on that ASAP.

**Comment by majapw** [comment]
Check out v12.1.2! This is hopefully addressed there.

**Comment by johnryan** [comment]
@majapw that seems to have resolved the error, but the component still has problems visually (maybe related to not being able to find the ref?). Should I open a new issue / is there anything I can do to provide more info?

<img width="614" alt="screen shot 2017-06-09 at 3 37 57 pm" src="https://user-images.githubusercontent.com/416564/26996850-2564e742-4d2a-11e7-9aec-9ff66c18d565.png">

**Comment by majapw** [comment]
Can you open an issue and share your config?

**Comment by johnryan** [comment]
@majapw opened #553 thanks for all the help
