### ISSUE TITLE
Unknown plugin "transform-replace-object-assign" 

### ISSUE THREAD

**Issue by boyarskiy** [airbnb/react-dates#530]
Hi all,

I've Installed react-dates, ran project and get error:

```js
ERROR in ./~/react-dates/index.js
Module build failed: ReferenceError: Unknown plugin "transform-replace-object-assign" 
specified in ".../node_modules/react-dates/.babelrc" at 0, attempted to resolve relative 
to ".../node_modules/react-dates"
```
Is this is known issue?

**Comment by ljharb** [comment]
Did you figure it out?

**Comment by jpmarra** [comment]
Having this same issue, is there a fix?

**Comment by boyarskiy** [comment]
@jpmarra yeah, just install `babel-plugin-transform-replace-object-assign`

**Comment by ljharb** [comment]
This issue shouldn't come up unless you're babel-transforming node_modules - which you should never do.
