### ISSUE TITLE
Unknown plugin "transform-replace-object-assign"

### ISSUE THREAD

**Issue by jpmarra** [airbnb/react-dates#531]
Hey guys, running into an error when trying to use this module. Here is what I'm getting:
```
ERROR in ./~/react-dates/index.js
Module build failed: ReferenceError: Unknown plugin "transform-replace-object-assign" specified in "/Users/user/Programming/workspace/PlusOne/node_modules/react-dates/.bab
elrc" at 0, attempted to resolve relative to "/Users/kendrick/Programming/workspace/PlusOne/node_modules/react-dates"
```

Any ideas?

**Comment by ljharb** [comment]
(#530)

Are you babel-transforming node_modules? If so, don't - you should only be transpiling your own code.

**Comment by joshuapinter** [comment]
@ljharb I've got a react native app where I'm trying to include the `airbnb-prop-types` package adn I'm getting this error. How do I go about changing the settings to ensure node_modules isn't being transpiled?

**Comment by ljharb** [comment]
It’s a flaw in the React native packager. The best solution right now is to add a postinstall script that removes all babelrc files inside node_modules.
