### ISSUE TITLE
SingleDatePicker: Can't Set Input Width to 100% of Container

### ISSUE THREAD

**Issue by ethanresnick** [airbnb/react-dates#535]
Hi,

I'm using the SingleDatePicker component and need to have the input stretch to 100% of the width of the container my form is in (which is a fluid container, so I can't use a px/em-based value). The sass variable that appears designed for setting the input's width, `$react-dates-width-input`, doesn't seem to cover this case, because the `.DateInput` is inside a `.SingleDatePicker`, which has `display: inline-block`. Setting the variable to `100%` gives the `.DateInput` a width of `100%`, but that's not 100% of the `.SingleDatePicker`'s container, due to the `inline-block`.

**Comment by Jucesr** [comment]
Hi @ethanresnick  . Were you be able to achieve this?

**Comment by ethanresnick** [comment]
@Jucesr Yes, but only by overriding more styles than just the Sass variables support. (Once you do that, it's pretty easy.) See the thread in #474 for context on that approach.

**Comment by majapw** [comment]
The new block styling I am working on should accomplish this more easily!

**Comment by majapw** [comment]
This is now very easy in v15.3.0 by just setting the `block` prop on the SDP or the DRP :)

**Comment by kimfucious** [comment]
What if you add the showDefaultInputIcon={true}?  I get the icon and the date field stacked.  Where can that be adjusted to have the both fit on one line at full width?

**Comment by dknell** [comment]
@kimfucious I was able to fix the `showDefaultInputIcon={true}` and `block` bug by overriding the css (below is sass, so adjust accordingly):

```
.SingleDatePicker {
    .DateInput__block {
        width: 100%;
        padding-right: 42px;
    }

    .SingleDatePickerInput_calendarIcon {
        position: absolute;
        right: 0;
        padding: 0 10px;
        line-height: 50px;
    }
}
```

**Comment by prateekj-amura** [comment]
How to make calendar occupy the width same as input field?
