### ISSUE TITLE
SingleDatePicker: Can't Customize Input's font-weight

### ISSUE THREAD

**Issue by ethanresnick** [airbnb/react-dates#536]
As with #533, #534, #535, I'm trying to use the SingleDatePicker component in a form along side some other custom inputs. Those inputs set their text at a different font-weight, so I'd like to customize the font-weight of the SingleDatePicker input to match visually. There doesn't seem to be a sass variable for this, so I'm doing it with a CSS override at the moment. Would love it if there were something cleaner.

**Comment by playpauseandstop** [comment]
Same issue with new `react-dates` as well, input has predefined `fontWeight: 200` style, https://github.com/airbnb/react-dates/blob/master/src/components/DateInput.jsx#L303, and there is no obvious way for me to change it.

This results in hacking font-weight via querying `DateInput` by ID in DOM after `SingleDatePicker` wrapper component did mount.

**Comment by euvl** [comment]
`29 May 2017,  like a year ago, any updates on this one?
