### ISSUE TITLE
DayPickerRangeController CalendarDay--hovered-span class remains on previously selected date

### ISSUE THREAD

**Issue by gatzjames** [airbnb/react-dates#542]
In the DayPickerRangeController after changing the date range, the previous selected date has the className `CalendarDay--hovered-span` which leaves it coloured.
This can be reproduced in the react-storybook examples.

I would be more than happy to help in the issue with some guidance!
Thanks for the awesome work!!!

**Comment by majapw** [comment]
Hi @gatzjames! I *think* the fix is in https://github.com/airbnb/react-dates/pull/523 which has been merged but not released yet! I will do a release right now. :)

**Comment by majapw** [comment]
Should be fixed in v12.1.1!
