### ISSUE TITLE
Help request

### ISSUE THREAD

**Issue by mentrie** [airbnb/react-dates#545]
Please, is there a way of attaching values to each day of the month using react-dates? Something like this:
![calender-question](https://cloud.githubusercontent.com/assets/15085641/26752676/75537660-484d-11e7-99f2-82917f020b96.png)

**Comment by majapw** [comment]
Hi @mentrie, you can use the `renderDay` prop to customize the `CalendarDay` area. The `renderDay` prop expects a function and receives a moment object as an argument. You could do something as follows:
```
renderDay={(day) => <div>{day.format('d')}<div className="custom-class-name">7h</div></div>}
```
and then style `custom-class-name` as desired.
