### ISSUE TITLE
isOutsideRange doesnt refresh on date change

### ISSUE THREAD

**Issue by dancingshell** [airbnb/react-dates#548]
I am trying to set that calendar range  so that the end date can only be with 30 days of start date. Using `isOutsideRange` I get close, but the calendar seems to only re-draw the days (and re-call the `isOutsideRange` function) when it goes from closed to open state. 

When the calendar is open and i change the start date the range does not adjust. However if i close the picker and then re-open the range is correct.

Is there a prop I can pass to have it re-call `isOutsideRange` on every date change? Or a function on the ref I can call when focus changes? Any input (no pun intended) here would be helpful!

```js
 //...
 getOutsideDateRange( day ) {
    const
      { maximumNights } = this.props,
      { startDateValue } = this.state,
      startRange = moment();

    if ( maximumNights && startDateValue ) {
      const
        endRange = moment( startDateValue ).add( maximumNights, 'days' ),
        startDayOutside = !isInclusivelyAfterDay( day, startRange ),
        endDayOutside = isInclusivelyAfterDay( day, endRange );

      return startDayOutside || endDayOutside;
    }

   return !isInclusivelyAfterDay( day, startRange );
},
render() {
  return (
    <DateRangePicker
      isOutsideRange={ this.getOutsideDateRange }
      className={ dateClassName }
      onDatesChange={ this.onDatesChange }
      initialStartDate={ startDateValue ? moment.parseZone( startDateValue ) : null }
      initialEndDate={ endDateValue ? moment.parseZone( endDateValue ) : null }
      startDate={ startDateValue ? moment.parseZone( startDateValue ) : null }
      endDate={ endDateValue ? moment.parseZone( endDateValue ) : null }
      focusedInput={ this.state.focusedInput }
      onFocusChange={ focusedInput => this.setState({ focusedInput })}
      customInputIcon={ hideIcon ? null : customInputIcon }
    />
  );
}
```

**Comment by timhwang21** [comment]
@dancingshell #522 fixes this, I believe.

**Comment by dancingshell** [comment]
That update fixed it, thank you @timhwang21!

**Comment by veiico** [comment]
what about SingleDatePicker? Because as I can see it only fixes this issue for DateRangePicker, or am I missing something?

**Comment by timhwang21** [comment]
Yep, my PR failed to address that case, I overlooked it because we noticed the bug in our app only with the `DateRangePicker`. Fortunately someone else is on it with #550 :)

**Comment by shubhamkes** [comment]
Am facing similar issue in v16.2.1 . Is there any way to recompute isOutSideRange only on focus change?
