### ISSUE TITLE
isOutsideRange not re-evaluated in SingleDatePicker on render

### ISSUE THREAD

**Issue by jlyman** [airbnb/react-dates#549]
Due to various factors, we are needing to use two SingleDatePickers instead of a DateRangePicker in our project (e.g., allowing open-ended selections). The problem we've run into is that when changing the start date in one picker, the second date picker won't re-evaluate `isOutsideRange` when gaining focus again, meaning that if the user moved the start date earlier they still wouldn't be able to pick an earlier end date until shifting between months and forcing a re-render.

Preparing a PR to address this.

**Comment by timhwang21** [comment]
+1, we're doing the same thing with two SingleDatePickers sometimes, thanks for this!
