### ISSUE TITLE
Firefox displaying October 15th two times

### ISSUE THREAD

**Issue by wmartins** [airbnb/react-dates#55]
I was just testing this using the github pages and realized that when the calendar is opened using Firefox (48.0.2), it is displaying two times the "October 15th" day. Here is a screenshot:

![2016-09-02_14-37-24](https://cloud.githubusercontent.com/assets/1560801/18212868/d61a3524-711b-11e6-8748-4c1b377126f3.png)

I don't know if it has something to do with my timezone but I'm running this at BRT Timezone (GMT-03:00).

I'm running this using a windows machine, but I tested that in Firefox developer edition (in a Mint VM) and I can reproduce the problem.

If you need more info, just tell me! :)

**Comment by ljharb** [comment]
This is likely because in Brazil, daylight savings time hits at midnight instead of 2AM - the fix is likely to use a time on our moment objects of `2:01 AM` rather than midnight?

**Comment by wmartins** [comment]
Yep, daylight saving time will start at October 16th (http://www.timeanddate.com/time/change/brazil/brasilia). I've done some tests, I don't know if you can use `moment.utc` in function `getCalendarMonthWeeks`, because I think that solves this issue:

![2016-09-02_15-16-52](https://cloud.githubusercontent.com/assets/1560801/18213890/b9dbdd7c-7120-11e6-8cd1-ae421bb99cd5.png)

In the screenshot, you can see that `Array[8]` is the "wrong" output. You can see that when using `moment.utc`, the result is correct (`Array[7]`). What do you think about it?

**Comment by majapw** [comment]
Nooooooooo. Okay. We will fix this asap.

**Comment by wmartins** [comment]
@majapw, sure! I tested that on Chrome and everything is ok, I will try to install Safari here to see if it is a problem, but I think it is FF specific.

**Comment by wmartins** [comment]
@majapw, it also happens on Safari (`Version 9.1.2 (11601.7.7)`) and IE 11 (`Version 11.0.9600.18376`).

**Comment by majapw** [comment]
Sweet I can repro by changing my time zone. I will dig into it. :)

Also:
https://github.com/moment/moment/issues/2353
https://github.com/moment/moment/issues/1440

**Comment by majapw** [comment]
Courtesy of my coworker, @mstorus:
Mark: How many datepicker issues would you say you've been dealing with today?
Me: I don't know, a lot?
Mark: Would you say it's been... a B(r)azillion?

**Comment by wmartins** [comment]
@majapw hahahahahahaha

**Comment by felquis** [comment]
I still have this issues :) I'm using react-dates 12.6.0 and moment 2.18.1, I have a working demo in this branch https://github.com/pagarme/pilot/tree/refactor-filters/webapp/src/components/DateSelector, my computer timezone is America/Sao_Paulo.

**Comment by majapw** [comment]
What browser are you using? I set my timezone and looked at airbnb.com (which is running v12.6.0) and didn't see an issue. Can you (a) double-check airbnb.com on your setup and (b) send a screencap?

I am going to say I would be very surprised if this were still an issue...

**Comment by ljharb** [comment]
(Also, could you file a new issue?)
