### ISSUE TITLE
redux-friendly visibleMonth

### ISSUE THREAD

**Issue by mpyw** [airbnb/react-dates#556]
`date` of SingleDatePicker is already redux-friendly because:

- we can receive picked date in `onDateChange()`
- we can pass the next property as `date`

However, `visibleMonth` is not provided like that. There is only a poor initalizer `initialVisibleMonth()`.

Should we improve this?

**Comment by mpyw** [comment]
Sorry, it seems updatable...

<img width="533" alt="2017-06-12 21 03 14" src="https://user-images.githubusercontent.com/1351893/27033082-abd33ec0-4fb2-11e7-82fe-c69b8ca325d2.png">

Thanks anyway :D

**Comment by majapw** [comment]
The main thing to note is it will only update the ui when the datepicker closes and reopens! :)

**Comment by mpyw** [comment]
@majapw 

Does that mean standalone `DayPicker` can be initialized only once?
Its' pretty inconvenient...
