### ISSUE TITLE
“Minimum working DateRangePicker” does not seem to be working

### ISSUE THREAD

**Issue by fufjvnvnf** [airbnb/react-dates#561]
I used `DateRangePicker` according to the setup described in the README, as follows:
```
<div>
  <DateRangePicker
    startDate={null}
    endDate={null}
    onDatesChange={({ startDate, endDate }) => this.setState({ startDate, endDate })}
    focusedInput={null}
    onFocusChange={focusedInput => this.setState({ focusedInput })}
  />
 </div>
```
Since according to README this should compose a minimum working calendar. However the result I get are two vertically aligned "start date - end date" pairs, and the calendar does not show up when I clicked on either date. I can however type on the date. Is this the expected output for the "minimum working calendar"?

**Comment by fufjvnvnf** [comment]
Issue is resolved after using `DateRangePickerWrapper` from the provided examples.

**Comment by ReidunMarie** [comment]
Can you show how you used DateRangePickerWrapper? I may have imported it wrong as well.

**Comment by majapw** [comment]
@ReidunMarie you should still import the `DateRangePicker` from `react-dates` but if you copy the code in https://github.com/airbnb/react-dates/blob/master/examples/DateRangePickerWrapper.jsx, that should be the best setup to work off of.
