### ISSUE TITLE
Breaking change to modifiers prop on DayPicker

### ISSUE THREAD

**Issue by dburles** [airbnb/react-dates#562]
I have the following on a `DayPicker` component in order to highlight a range of dates that contain information, along with highlighting the currently selected day. However it now no longer works after #450. Is there another approach I can take to make it work? thanks.

```js
            modifiers={{
              selected: day =>
                moment(this.props.selectedDay).isSame(day, 'day'),
              'highlighted-calendar': day1 =>
                this.props.highlightedDays.some(day2 =>
                  moment(day2).isSame(day1, 'day'),
                ),
            }}
```

**Comment by majapw** [comment]
Awesome, thanks for opening this (it's easier to track this separately). 

The perf rearchitecting def does mean that the above is... not going to work anymore. Is there a reason you are not using the `SingleDatePicker` out of the box and using the `isDayHighlighted` prop instead?

The modifiers state has become... somewhat more complicated and I'd just like to understand if there are better ways to solve your usecase then to get into the nitty gritty of it.

**Comment by dburles** [comment]
I think what I really would like is for the DayPicker to support these options as props! Reason why I'm not using `SingleDatePicker` is that I require the calendar to always be visible. I'll attach a screenshot to hopefully provide some more context around the particular use-case that I have.

<img width="1088" alt="screen shot 2017-06-14 at 3 33 02 pm" src="https://user-images.githubusercontent.com/319567/27116881-e8e2bc40-5116-11e7-8ccc-a1fe3dbd5acf.png">

**Comment by majapw** [comment]
Okay great! So we have this always visible version of the range picker called the `DayPickerRangeController`... and what we really need is the same thing but for the `SingleDatePicker`. Then you could use that out of the box! 

I want to work on this and put up a PR this week. Until then I'd peg to an older version. How does that timeline work for you?

**Comment by dburles** [comment]
That would be fantastic! thanks!

**Comment by majapw** [comment]
Hiyo @dburles, v12.2.0 now contains a `DayPickerSingleDateController` component. I got slammed at work so it took quite a long while. Please check it out in the storybook!

**Comment by dburles** [comment]
Thanks @majapw I really appreciate that! I'll let you know how it goes!
