### ISSUE TITLE
DateRangePicker enableOutsideDays breaks date selection

### ISSUE THREAD

**Issue by LoicUV** [airbnb/react-dates#569]
Hello,

I'm migrating from `v4` to `v12.1.2` and I encountered a weird issue which I narrowed down to the use of `enableOutsideDays` prop. [See this demo](https://codesandbox.io/s/326jqJY9x), when the prop is present, whenever you try to select a date range, the following error occurs : `Uncaught TypeError: Cannot read property '2017-07-16' of undefined` which corresponds to [line 622 of `DayPickerRangeController.jsx`](https://github.com/airbnb/react-dates/blob/master/src/components/DayPickerRangeController.jsx#L622) : 
```javascript
const modifiers = new Set(month[iso]);
```
Am I missing something or ... ?

**Comment by RichardLindhout** [comment]
Same problem

**Comment by LoicUV** [comment]
I guess you could label this as a bug.

**Comment by majapw** [comment]
Hi @LoicUV @RichardLindhout, I *think* this should be fixed in v12.2.0
![outside-days](https://user-images.githubusercontent.com/1383861/27616646-15b2199c-5b66-11e7-90cd-43d3c1cfb22b.gif)

It was def not functioning beforehand though. I believe #575 contains the solution!
