### ISSUE TITLE
Block certain dates

### ISSUE THREAD

**Issue by vebjorni** [airbnb/react-dates#572]
Hi.

This is probably a duplicate, but i haven't seen the question before.

Is it possible to provide the SDP a list (array) of moment objects to block? And how do I do that? I don't fully understand the isDayBlocked prop. Does it iterate over all days or what? 

Thanks in advance!

**Comment by ljharb** [comment]
The prop is a function, that you provide, that takes a day and return true or false.

**Comment by vebjorni** [comment]
Can you provide a little more information about what this function does?

`isDayBlocked={day1 => datesList.some(day2 => this.isSameDay(day1, day2))}`

Does isDayBlocked iterate over all days in the calendar and check if it is the same day as one in my datesList?

**Comment by timhwang21** [comment]
@vebjorni I believe it only does so for "visible" days, which are days in currently displayed months +1 on either side. So if you're showing June and July, May and August would be checked, but not January.
