### ISSUE TITLE
Any way to restrict date in SDP ?

### ISSUE THREAD

**Issue by pufffff** [airbnb/react-dates#577]
I only want to select from June 1, 2017 to Aug 1, 2017. Anyway to do that? Thanks!

**Comment by timhwang21** [comment]
`isOutsideRange = day => day.isSameOrBefore(June 1, 2017 as moment or ISO-8609) || day.isSamOrAfter(Aug 1, 2017 as moment or ISO-8609)`

**Comment by pufffff** [comment]
thanks, dude!

**Comment by majapw** [comment]
@pufffff The story at https://github.com/airbnb/react-dates/blob/master/stories/DateRangePicker_day.js#L45-L53 might help you as well!
