### ISSUE TITLE
Multiple SDP

### ISSUE THREAD

**Issue by pufffff** [airbnb/react-dates#579]
I have this multiple dates in the modal

![screenshot from 2017-06-18 23-04-55](https://user-images.githubusercontent.com/13362819/27261692-c16972fa-547a-11e7-9888-5b977d3f94d5.png)

and when I click one of them, it will display like this.

![screenshot from 2017-06-18 23-05-31](https://user-images.githubusercontent.com/13362819/27261693-cc3a733c-547a-11e7-9fff-add08621c601.png)

any help would be appreciated, thanks!

**Comment by vebjorni** [comment]
This is probably because you use the props `date` and `focused` as the same name throughout each SDP. You will need different propnames for each SDP, like startDate/startDateFocus and endDate/endDateFocus.

**Comment by pufffff** [comment]
Thanks for the idea, this is technically my fault. I've set my focus on one key state so when it changes it will display everything that uses that focus. So, my bad. Thanks again! ;)

**Comment by majapw** [comment]
👍 @pufffff Thanks for the issue! As you noticed, you need different focused/date props for each picker! :)
