### ISSUE TITLE
Changing months doesn't clear selected dates from the DayRangePickerController when new range selected 

### ISSUE THREAD

**Issue by jvanderz22** [airbnb/react-dates#582]
Possibly a duplicate but I didn't see anything outstanding related to this.

Using the `DayRangePickerController` currently on http://airbnb.io/react-dates, I'm able to get into a state where two ranges appear to be selected at the same time. To get into this state, I first select a range in July when the calendar open up, click the right arrow twice so that August and September are the visible months, select a range in August and then arrow back to the left, and still see the July range selected

<img width="620" alt="screen shot 2017-06-19 at 3 09 45 pm" src="https://user-images.githubusercontent.com/5505870/27304052-77fc5456-5502-11e7-89f4-b3394ea74887.png">

**Comment by majapw** [comment]
This should be fixed in v12.2.0 by #575
