### ISSUE TITLE
Calendar icon is still clickable when it's disabled

### ISSUE THREAD

**Issue by bmd-bentar** [airbnb/react-dates#584]
When I set this to disabled and show the calendar icon, it is still clickable and return value. Is possible to fix this bug?

**Comment by majapw** [comment]
Oh yeah, that's def a bug! Should be a small fix. Maybe add a disable style to the icon at the same time.

**Comment by dart-wakar** [comment]
#591 
@majapw Please review the mentioned pull request

**Comment by majapw** [comment]
Fixed in v12.2.0!
