### ISSUE TITLE
Dates range not resets

### ISSUE THREAD

**Issue by geakstr** [airbnb/react-dates#589]
**Steps to reproduce:** 
1. Select start date in the first month.
2. Select end date in the second month.
3. Rewind for two months next 
4. Select start date in the first month.
5. Select end date in the second month.
6. Rewind for two months prev

**Expected behavior:** first range resets

**Actual behavior:** first range not resets

http://airbnb.io/react-dates/?selectedKind=DayPickerRangeController&selectedStory=default&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel

![range-bug](https://user-images.githubusercontent.com/1496368/27432499-81fe56fa-5761-11e7-9fb7-56573957faf5.gif)

**Comment by majapw** [comment]
Hiyo! I believe this is fixed now by #575 in v12.2.0

Thanks for the issue (and the PR)!
