### ISSUE TITLE
DayPickerRangeController has an inconsistent behavior for long range selection

### ISSUE THREAD

**Issue by thibautRe** [airbnb/react-dates#596]
## Overview
I run into a problem when selecting a long date range with the **DayPickerRangeController** component on the storybook. Here's a gif that reproduces it (notice the month of July which is sometimes unselected, and sometimes selected):

![react-dates-bug](https://user-images.githubusercontent.com/1416801/27530145-a6cda938-5a57-11e7-9d18-43a982f246ed.gif)

#### Steps to reproduce
- Select a long daterange (≥ 3 months if the widget has a `numberOfMonths` prop set to `2`)
- Go back to some months in the middle of the selection : it will appear selected or not unconsistently (from what I tried, it appears to show the right thing when you scroll the months far enough - in the gif example, I have to scroll until I see October for July to appear correctly).

I'd be happy to submit a PR

Possibly a duplicate of #582

**Comment by majapw** [comment]
Interesting! I think both this issue and $582 are all probably related to https://github.com/airbnb/react-dates/pull/575. I'll get that merged in asap.

**Comment by majapw** [comment]
I believe this is fixed in v12.2.0 by #575. :) Closing this as fixed as I can't dupe.
