### ISSUE TITLE
Getting a warning message when using `DayPickerSingleDateController`

### ISSUE THREAD

**Issue by tjoskar** [airbnb/react-dates#603]
Hi,

I'm geting a warning message from [isTouchDevice.js](https://github.com/airbnb/react-dates/blob/208186ddf4f843d20d475c152fcaa5d494216c3b/src/utils/isTouchDevice.js#L3) when using `DayPickerSingleDateController`.

`DayPickerSingleDateController` [is importing `utils/isTouchDevice`](https://github.com/airbnb/react-dates/blob/208186ddf4f843d20d475c152fcaa5d494216c3b/src/components/DayPickerSingleDateController.jsx#L11) [which is deprecated](https://github.com/airbnb/react-dates/blob/208186ddf4f843d20d475c152fcaa5d494216c3b/src/utils/isTouchDevice.js#L3). From my understanding it should just be to replace `import isTouchDevice from '../utils/isTouchDevice';` with `import isTouchDevice from 'is-touch-device';` in [DayPickerSingleDateController](https://github.com/airbnb/react-dates/blob/208186ddf4f843d20d475c152fcaa5d494216c3b/src/components/DayPickerSingleDateController.jsx#L11).

I can create a PR if that is fine?

**Comment by majapw** [comment]
@ljharb fixed this in https://github.com/airbnb/react-dates/commit/77e2135d2009994fbf2c62e3ff68ce82e5786194. I'll do a release rn

**Comment by majapw** [comment]
Fixed in v12.2.1! 🎉
