### ISSUE TITLE
[IE11] Demo page not rendering

### ISSUE THREAD

**Issue by pedroabreu** [airbnb/react-dates#610]
I've noticed that the demo page http://airbnb.io/react-dates doesn't work when accessing with IE11, it renders the menu on the left but no content is visible (no console errors as well)

![ie](https://user-images.githubusercontent.com/1194888/27768684-2038e4a0-5f11-11e7-8473-4e633ea486f7.png)

I'm raising this because I'm running into an issue on IE11 and wanted to check how is it rendered in a isolated environment (not sure if react-dates is supposed to support IE11 😬 )

**Comment by ljharb** [comment]
react-dates does; storybook might not, however.

**Comment by majapw** [comment]
The latest storybook has IE11 support so this has been addressed
