### ISSUE TITLE
NPM package needs update?

### ISSUE THREAD

**Issue by unski11ed** [airbnb/react-dates#614]
It looks like the package on NPM doesn't cotain the newest `index.js` which exports `DayPickerSingleDateController `, only `DayPickerRangeController ` can be found in there. 

I have cleared npm cache, and even downloaded the tarball on a virtual machine, and the effect was the same.

 Can you please check it out?

**Comment by ljharb** [comment]
Indeed, the latest changes aren't released yet. That's not a bug; it's perfectly normal for the master branch of a repo to contain unreleased changes for long period of time.

I'm sure we'll get a release out soon.

**Comment by unski11ed** [comment]
Well isn't that misleading if it says on NPM that the current version is 12.2.2, but the features from the change log aren't available?

**Comment by ljharb** [comment]
Everything in CHANGELOG.md is available. It's not misleading at all that unreleased changes exist on github; that's how every project always functions.

**Comment by unski11ed** [comment]
Ok... It says in the changelog for version 12.2.0 `[new] Add DayPickerSingleDateController component`. For version 12.2.2 the component is in the package tho it's not exported. I don't get why. It doesn't look like a normal practice for me at all...

**Comment by ljharb** [comment]
The presence of the file in the repo means you can deep-require it by path. Being exported in the main export isn't a requirement for something to be semver-minor.

**Comment by unski11ed** [comment]
ok, that was helpful, thanks!

**Comment by majapw** [comment]
it's also available now in v12.2.3!
