### ISSUE TITLE
Programatically closing calendar

### ISSUE THREAD

**Issue by alexcroox** [airbnb/react-dates#615]
I've used the `renderCalendarInfo` function to add some pre-defined date ranges which works great.

![ss](https://cl.ly/lQzB/Screen%20Shot%202017-07-04%20at%2022.04.59.png)

However I would like to close the calendar after clicking one of the buttons, am I able to do this?

**Comment by vebjorni** [comment]
When clicking on one of the buttons I assume that you are setting `startDate` and `endDate`, so you can maybe pass a function to the prop `onDateChange` and in that function you set the `focusedInput` to false?

**Comment by alexcroox** [comment]
Ah yes changing `focusedInput` to false makes sense, thank you. I'll try that later today

**Comment by MaxiSantos** [comment]
hey @alexcroox can you provide the methods you used for the clickHandler on each button on the footer? I'm looking at the API but I didn't see the renderCalendarInfo [https://www.diycode.cc/projects/airbnb/react-dates](https://www.diycode.cc/projects/airbnb/react-dates)

**Comment by spiewak** [comment]
@MaxiSantos 
Simple example:

    @autobind
    onClickTodayButton() {
        this.onDateChange(moment());
        this.onFocusChange({focused: false});
    }

    @autobind
    renderCalendarFooter() {
        return (
            <div className="date-picker-footer">
                <button className="today-button" type="button" onClick={this.onClickTodayButton}>TODAY</button>
            </div>
        );
    }

    render() {
        return (
            <div className="date-picker-wrapper">
                <SingleDatePicker
                    ...
                    renderCalendarInfo={this.renderCalendarFooter}
                />
            </div>
        );
    }

Preview:
<img width="317" alt="screen shot 2018-10-29 at 11 37 16" src="https://user-images.githubusercontent.com/4601555/47644696-24336180-db6f-11e8-9eab-562142e68c3a.png">
