### ISSUE TITLE
DayPickerRangeController: Unexpected behavior

### ISSUE THREAD

**Issue by mikkelwf** [airbnb/react-dates#619]
I've build my own datepicker based upon `DayPickerRangeController` and the example code in `DayPickerSingleDateControllerWrapper.jsx`

This is the code for the Actual `DayPickerRangeController`

```
    const isDayBlocked = (day) => day.isBefore(moment().subtract(1, 'days'))

    const numberOfMonths = mobileOnly ? 1 : 2

    return (
      <DayPickerRangeController
        startDate={startDate}
        endDate={endDate}
        focusedInput={focusedInput}
        isDayBlocked={isDayBlocked}
        onDatesChange={this.handleDatesChange}
        onFocusChange={this.handleFocusChange}
        minimumNights={1}
        daySize={this.getDaySize()}
        numberOfMonths={numberOfMonths}
        enableOutsideDays={false}
        navPrev={<PrevBtn />}
        navNext={<NextBtn />}
        hideKeyboardShortcutsPanel
        renderDay={(day) => <div><span>{day.format('D')}</span></div>}
        initialVisibleMonth={() => this.state.initialMonth} />
```

The `this.state.initialMonth` is set in the constructor based on the startDate: `initialMonth: props.startDate ? props.startDate : moment()`

The datepicker does the following unexpected actions
* The initial visible month is not aligned with the value from props `initialVisibleMonth`. August shows august, september shows august, oktober shows august..
* Selected dates disappear. When selecting a range in october (when october shows in the right column), navigating to the next month (rendering october in the left column) resolves in the selection disappering. ranges from november and forward does not show at all. 
* When the former errors first occurs, updating of modifiers when changing month becomes very slow (i've blocked dates before today, in the example its dates until 6. july 2017), and the blocked styles for months before that date is first applied after 0.5-1 sec after navigation

I've attached a gif showcasing the problem:

![react-dates-bug](https://user-images.githubusercontent.com/1061520/27916422-48cc234a-6269-11e7-9946-5ce4f4da006b.gif)

And the video version of it: https://ufile.io/jsrhc

I've tried to remove a lot of the props, nothing helped. I'm really confused and frustrated with this issue, and hope somebody can hint me towards if my code has an issue or the datepicker has a bug

**Comment by mikkelwf** [comment]
I think i has something to do with the modifiers not updating properly..
I've looked at #570 because i wanted to block dates 28 days after the selected start-date, but gave up because of that issue.

**Comment by majapw** [comment]
Hmmm, I'm really sorry you're dealing with this. Can you share what version you're using and I'll try to dig into the root cause.

**Comment by mikkelwf** [comment]
Hey.. thanks, i really appreciate it... :)

I'm using 12.2.4 right now, but i've been using 12.2.2 and 12.2.3 with the same error.

**Comment by mikkelwf** [comment]
any update on this..?

**Comment by timhwang21** [comment]
Hey @mikkelwf ! My PR on this is still WIP because it will have a perf impact for all users, while addressing the issue for the subset of users who use the picker in this way, and was waiting for input on whether the tradeoff was worth pursuing. I can clean up the issue and add tests so it's at least in an acceptable state.

**Comment by mikkelwf** [comment]
@timhwang21 i think you should proceed with your PR. 
As i see it, a lot of functionality is broken right now, or at least not working as expected, so it's better to actually make it work.
Regarding performance, i already think the datepicker has some issues already. I've experienced some perf issues, especially on mobile. So if the choice is slow + not working vs a little bit slower, i would go for the latter.. :)

**Comment by timhwang21** [comment]
Hey, yes, I intend to, I've just been extremely busy 😰 sorry!

**Comment by mikkelwf** [comment]
@timhwang21 No worries :)

**Comment by mikkelwf** [comment]
@majapw whats the status on this..?

**Comment by mikkelwf** [comment]
@majapw im gonna close this. We gave up on react-dates and build our own.. :/

**Comment by ljharb** [comment]
@mikkelwf another alternative is making a pull request to fix this one.

**Comment by majapw** [comment]
I also think the later versions of react-dates have addressed a lot of these issues as well:
> The initial visible month is not aligned with the value from props initialVisibleMonth. August shows august, september shows august, oktober shows august..
This one may still be finicky. We haven't done a lot of work on this prop --- `initialVisibleMonth` was really meant to be the *first* load and not subsequent opening/closings. The month/year change that's in the pipeline will probably help address some of those concerns. 

> Selected dates disappear. When selecting a range in october (when october shows in the right column), navigating to the next month (rendering october in the left column) resolves in the selection disappering. ranges from november and forward does not show at all.
I believe this has been addressed. 

> When the former errors first occurs, updating of modifiers when changing month becomes very slow (i've blocked dates before today, in the example its dates until 6. july 2017), and the blocked styles for months before that date is first applied after 0.5-1 sec after navigation
I think this has also been addressed in later versions. In addition, there's a lot of tweaks to the isDayBlocked and other prop modifiers functions that usually lead to better performance. 

I think it's fine to keep this issue closed and we'll continue iterating. Thanks for the feedback!
