### ISSUE TITLE
Auto Hide when selecting end Date is not good at all.

### ISSUE THREAD

**Issue by nsisodiya** [airbnb/react-dates#62]
When We select end date, Calendar autohide. this is not a Good user experience. 
when User click, on start and end Date, he expect too duration basically visually. Seeing shaded portion after clicking on end date is a mental `reconfirmation` by user. When He click first date, popup stay as it is. So he expect same behaviour when he click end date too. Once he mentally confirm that he selected correct duration, he will click outside and then you can hide the popup.

**Comment by majapw** [comment]
This is something we are working on with our designers. We may be moving towards a model where users have to close the picker and focus on the next element themselves. However, this may only be targeted at keyboard users. I will update as this progress continues.

**Comment by majapw** [comment]
We've actually added a prop to prevent this behavior here - https://github.com/airbnb/react-dates/pull/157 so this should soon be possible to avoid if necessary!

**Comment by majapw** [comment]
This is fixed now. You can use the `keepOpenOnDateSelect` prop to prevent this behavior.
