### ISSUE TITLE
Focus on second field, when the first one is choosen.

### ISSUE THREAD

**Issue by dssorokin** [airbnb/react-dates#626]
Hello, guys. This datepicker is really amazing, and it solves almost all my problems. Thank you for that.

However, i ran into problem with DateRangePricker, now i'll write full description of the case:
1)Choose first date
2)Then try to choose the second date that is less  than the first one.
3)DateRangePicker automaticaly enters into first input choseen date, but at the same time css class DateInput__display-text--focused is still on second input.

**Comment by timhwang21** [comment]
I think this is intended. When selecting such a date, the start date is updated, and the users next click will select the end date. Thus the end date remains focused. 

What do you think the intended behavior should be? Thanks!

**Comment by dssorokin** [comment]
Sorry, you are absolutely right. I am closing the issue.
