### ISSUE TITLE
Start and End Date click behaviour could be enhanced

### ISSUE THREAD

**Issue by nsisodiya** [airbnb/react-dates#63]
Currently In DatePicker the order of start and end date is fixed.
I mean, first you `have to` select Start Date and then End Date.
There is an alternate behaviour too. Just click on 2 Dates and automatically one will become startDate and Other will become endDate.
You can view this behaviour at my old project - 
http://nsisodiya.github.io/x-daterange/
Please adopt, if you like it.

**Comment by majapw** [comment]
I think that unfortunately this doesn't make as much sense given that we have definite inputs with set focus states. If we were to have a wrapper on the DayPicker component with no input fields, this behavior would make sense but as is... I don't see us moving towards this. Thanks for the suggestion though! If you would like to PR a wrapper for the DayPicker component with this behavior, we'd def consider it.
