### ISSUE TITLE
Implement verticalHeightFactor prop

### ISSUE THREAD

**Issue by vemv** [airbnb/react-dates#632]
From DatePicker.jsx source:

```javascript
    // this is a kind of made-up value that generally looks good. we'll
    // probably want to let the user set this explicitly.
    const verticalHeight = 1.75 * calendarMonthWidth;
```

I guess that the user-configurable value should be the 1.75 - setting `verticalHeight` directly seems more error-bound.

Could you please implement this prop?

Cheers - Victor

**Comment by ljharb** [comment]
Seems reasonable.

**Comment by vemv** [comment]
This one was fixed by https://github.com/airbnb/react-dates/pull/773
