### ISSUE TITLE
Anyone knows how we can keep both the input and calendar visible ?

### ISSUE THREAD

**Issue by dtalaba** [airbnb/react-dates#663]
Simillar with #193 .

Now we should use DayPickerRangeController for eg, if we want to keep the calendar visible all the time, but how can we show the inputs also ?

**Comment by majapw** [comment]
Hi @dtalaba, sorry for the delay in response! If you want it always visible but absolutely positioned, I'd just make sure that `focusedInput` is never set to null ie your `onFocusChange` method would look like:
```
onFocusChange({ focusedInput }) {
  if (focusedInput) {
    this.setState({ focusedInput });
  } else {
    this.setState({ focusedInput: START_DATE });
  }
}
```
If you want it to be inline, you will in fact have to use DayPickerRangeController and DateRangePickerInputController and then wire up the interaction between the two yourself.

**Comment by evonsdesigns** [comment]
@majapw Thanks for this solution. The only change I had to make was to not destructure `focusedInput` from the input parameter.
