### ISSUE TITLE
Outside days doesn't work

### ISSUE THREAD

**Issue by intpp** [airbnb/react-dates#67]
In your example too.

[Live demo](http://airbnb.io/react-dates/?selectedKind=DateRangePicker&selectedStory=with%20outside%20days%20enabled&full=0&down=1&left=1&panelRight=0)

**Comment by majapw** [comment]
What do you mean by "doesn't work"? I both see and am able to interact with the outside days - 
<img width="338" alt="screen shot 2016-09-07 at 10 59 43 am" src="https://cloud.githubusercontent.com/assets/1383861/18322976/4165ac10-74ea-11e6-9a41-d8bb4a1124ce.png">

**Comment by intpp** [comment]
I can't select past dates. Is it previous option "allowPastDate"?

(https://api.monosnap.com/rpc/file/download?id=UG1f4mArS99D3bVERKht9Ho3kH2H5k)

**Comment by majapw** [comment]
Ah, yes. `outside days` in this context describes days from the previous and next month that are by default not shown. What you are looking for in this context is `isOutsideRange`.

From the README:
```
