### ISSUE TITLE
focusedInput in onFocusChange is undefined

### ISSUE THREAD

**Issue by stphnlngdncoding** [airbnb/react-dates#671]
Hey guys! I'm trying to use DateRangePicker and I have passed in the following props:
```
<DateRangePicker
  onDatesChange={this.onDatesChange}
  onFocusChange={this.onFocusChange}
  startDate={startDate}
  focusedInput={focusedInput}
   endDate={endDate}
 />
```
and the onChange functions are defined as follows: 
```
  onDatesChange({ startDate, endDate }) {
    this.setState({ startDate, endDate });
  }
  onFocusChange({ focusedInput }) {
    console.log('on focus change', focusedInput);
    this.setState({ focusedInput });
  }
```
and my initial state looks like: 
```
    let focusedInput = null;

    this.state = {
      focusedInput,
      startDate: null,
      endDate: null,
    }
```

I expected the day picker to show when I selected the input that says 'start date' but nothing shows up.  My date-picker is on an absolutely positioned div with a z-index of 2.  When I log the focusedInput in the onFocusChange handler, it prints `undefined.`  Can you guys see what I'm missing here?

**Comment by stphnlngdncoding** [comment]
The form works appropriately when I pass in the state and the focus onChange handler explicitly.

**Comment by majapw** [comment]
It's possible that in your setup
```
  onDatesChange={this.onDatesChange}
  onFocusChange={this.onFocusChange}
```
If you're not binding those methods in the constructor, the `this` wouldn't be the correct one which would break things. :) Thanks for updating once you figured out a solution!
