### ISSUE TITLE
Pass current month into onNextMonthClick and onPrevMonthClick

### ISSUE THREAD

**Issue by jseminck** [airbnb/react-dates#679]
Would it be possible to pass the current month into `onNextMonthClick` and `onPrevMonthClick` ?

Use case:

We want to show only 3 months, and allow selection only of the last 4 months. We do not want users to navigate to months outside of the 4-month range. E.g. they cannot go to the future and they cannot go back more than once.

The currentMonth parameter passed from these functions could be used to determine whether or not we should render a `nextNav` or `prevNav`.

**Comment by majapw** [comment]
Hi @jseminck I think we actually do as of v12.4.0! :) https://github.com/airbnb/react-dates/blob/master/CHANGELOG.md#1240

**Comment by jseminck** [comment]
Oh whoops. I'm still running on an older version. Thanks for the quick reply! 🎉
