### ISSUE TITLE
Option to not re-open the date picker when the clear dates button is clicked.

### ISSUE THREAD

**Issue by jamhall** [airbnb/react-dates#68]
Currently when clicking on the clear button to clear the dates, the dates are cleared and the date picker is re-opened. It would be nice to allow an option for when the close button is clicked, the picker is not re-opened. The property could be called 'reopenPickerOnClear'.

Thank you for a great component!

**Comment by majapw** [comment]
Yeah I think this is a good idea, and something we've actually talked about for certain implementations on the site. This is fairly low on my priority list, but we'd definitely be super happy to take a PR!

**Comment by agupta93** [comment]
@majapw we can close this issue i guess
