### ISSUE TITLE
Config the date

### ISSUE THREAD

**Issue by LucasDvp** [airbnb/react-dates#687]
If there's any config files can re-loading the date's label like [fliggy](http://www.fliggy.com/) 
show the festival days and holidays?

**Comment by majapw** [comment]
Hi @LucasDvp, you can use the `renderDay` prop to conditionally render different content. It takes in a moment object and expects a div as output. For instance, you could do:
```
renderDay((day) => {
  if (day === some holiday) return <span>Holiday!</span>

  return day;
}
```

**Comment by LucasDvp** [comment]
@majapw ok, so I need to write my own festival rendering functions. but if there has a re-loading function would be better~~~ 👍

**Comment by majapw** [comment]
What do you mean by a reloading function?

**Comment by LucasDvp** [comment]
It's like If I request a festival API(like Chinese Festival API), it will return me a JSON like this: 

```json
{
    "holiday": "National Holiday",
  	"dates": ['2017-10-01', '2017-10-02', '2017-10-03', '2017-10-04', '2017-10-05', '2017-10-06', '2017-10-07'],
  	...
}
```

So if users can just offering **specific json format or even support the online API integration(different country)** which  would be so cool.

**Comment by majapw** [comment]
I guess the whole react-dates thing is that we want it to be highly
configurable so that you can build out this kind of functionality by
combining react-dates with some other api easily, but we're unlikely to
build in support for a specific integration ourselves. :) The renderDay
method is still likely what you are looking for.

**Comment by LucasDvp** [comment]
@majapw OK, I will made a small plugin based on react-dates, thank you so much~~~
