### ISSUE TITLE
Hardcoded color code in styling definitions

### ISSUE THREAD

**Issue by dnepro** [airbnb/react-dates#688]
The style definition for `.DayPickerKeyboardShortcuts__show-*` uses a color with the hex-code `#008489`-hardcoded instead of an actual variable.

It would be very nice, if you could utilize a actual exposed variable :)

**Comment by majapw** [comment]
Good catch! Perhaps we can call this `$react-dates-color-primary-dark`.

**Comment by majapw** [comment]
This is addressed in v12.6.0
