### ISSUE TITLE
Large bundle size

### ISSUE THREAD

**Issue by bpicolo** [airbnb/react-dates#691]
According to webpack-bundle-size-analyzer, react-dates is  my single biggest dep by a fair margin.

```
react-dates: 393.43 KB (20.8%)
mobx: 138.93 KB (7.33%)
moment: 136.72 KB (7.22%)
```

Any recommendations for reducing it's impact on bundle size?

**Comment by bpicolo** [comment]
Though this is technically unminified, perhaps I can figure out it's prod bundle contribution.

**Comment by ljharb** [comment]
So import it by path instead of from the main entry point, and you'll only get the parts you need?

**Comment by ljharb** [comment]
I'd suggest instead `import DateRangePicker from 'react-dates/lib/components/DateRangePicker'`

**Comment by aplaskota** [comment]
@ljharb so what's the difference between your suggestion and @bpicolo `import` usage?
In index.js I see variables like this
`var DateRangePicker = require('./lib/components/DateRangePicker').default;` and the same variable is exported from this file so if I import the component in that way `import {DateRangePicker} from react-dates` then webpack resolver should take the component from path which you suggest. correct?

**Comment by ljharb** [comment]
It very well might; but instead of relying on webpack to do that treeshaking for you, I'm suggesting you do it manually (always, with every package, in every case).

**Comment by aplaskota** [comment]
What I know about treeshaking and webpack 2 is that webpack only matches unused code but it doesn't remove it. To do that you need more configuration for example you need to set up UglifyJSPlugin which supports dead code removal. 
I don't see such plugin in your webpack configuration so maybe it's worth to consider it?

**Comment by bpicolo** [comment]
My build is running uglify as well, yeah.

**Comment by ljharb** [comment]
react-dates' webpack configuration is solely for its storybook; it does not apply whatsoever to its published code.

**Comment by aplaskota** [comment]
That's my result after adding treeshaking to webpack
Before treeshaking
![beforethreeshaking](https://user-images.githubusercontent.com/2686022/29795063-f710137a-8c4a-11e7-8867-184241079944.png)
Aafter treeshaking
![afterthreeshaking](https://user-images.githubusercontent.com/2686022/29795075-fc1ef782-8c4a-11e7-9055-2fa979154146.png)

Downside: 
Build process is slower around 1600ms then previously.

**Comment by ljharb** [comment]
Again, I'm suggesting you not lazily rely on treeshaking, and instead, manually deep-import the exact things you need from packages.

**Comment by aplaskota** [comment]
Ok, if I don't do that then I will retrive 31.6 kB by manually deep-import instead of 13.7 kB. On production it matters.
But on the other hand could you explain why I shouldn't rely on treeshaking? Is it something wrong with it. My case is smaller module/component. What are yours?

**Comment by ljharb** [comment]
Treeshaking is fine if it works; I'm not saying to turn it off - I'm saying that it's not an excuse to "import the world" and just naively hope that it will "shake out" all the things you're not using. JS isn't a language where that's a reliable or easy thing to determine.

**Comment by bpicolo** [comment]
@ljharb  fwiw, looks like your suggestion does shave ~40kB off the top. Still a bit higher than I'd hope for a date picking widget, but in a decent state for now : )

**Comment by ljharb** [comment]
Sounds like this is resolved :-)
