### ISSUE TITLE
Disable preNav and nextPav

### ISSUE THREAD

**Issue by vget98** [airbnb/react-dates#692]
Hi is it possible to disabled the prevNav and nextNav buttons when reaching the end of allowed dates? For example isOutsideRange disables days after September, is it possible for when a user reaches September to disable nextNav so they can't scroll past it?

**Comment by jseminck** [comment]
I recently solved this issue by using:

1/ Use `onNextMonthClick` and `onPrevMonthClick` to keep track of the current month.
2/ Use the current month to decide whether or not to render a `navNext` or `navPrev`

**Comment by vget98** [comment]
Do you not render the navNext or navPrev? I just wanted to disable the nav buttons so make it so it is not clickable but still there.

**Comment by jseminck** [comment]
You can create custom buttons and put `disabled` on them when they shouldn't be clickable. I chose not to render them at all.

 I'm not sure if you can do it with the buttons that come with the library.

**Comment by vget98** [comment]
Ahh ok thats pretty much all I needed, thank you for the help

**Comment by laurenz-glueck** [comment]
@jseminck I tried the following: 
```
navPrev={
	<button className={'MyCustomButton'} hidden={true}>
		'Prev'
	</button>
}
navNext={
	<button className={'MyCustomButton'}>
		'Next'
	</button>
}
```
But I'm unable to set the hole button (only the inside), so I can't disable or hide it:
![bildschirmfoto 2017-08-31 um 16 24 14](https://user-images.githubusercontent.com/2734232/29928280-de68605a-8e68-11e7-8386-0c49d4e723db.png)

**Comment by nosecoolie** [comment]
In case anyone want to disable preNav and nextNav, here is my work arround

You can use onPrevMonthClick & onNextMonthClick these two props.
And pass a function like this.
```js
checkMonthAvailability = month => {
  ...
  const prevBtn = document.getElementsByClassName('DayPickerNavigation_button')[0]
  const nextBtn = document.getElementsByClassName('DayPickerNavigation_button')[1]
  // Use the prevBtn.style.display = 'none' or 'block' to controll the navBtn
}
```

**Comment by mlg87** [comment]
i feel like this should be reopened bc not rendering or rendering a completely different component when the desired outcome is a disabled button feels like a hacky workaround. it would be great to be able to pass down the click handler or prevent propagation when desired

**Comment by elinskytap** [comment]
@mlg87 Is it something you are looking for?
https://github.com/airbnb/react-dates/pull/1311

**Comment by mlg87** [comment]
@elinskytap that is exactly what im looking for. now for it to get merged/released

**Comment by elinskytap** [comment]
yes, I am looking forward to the PR #1311 being merged & released!

**Comment by meghnaraju** [comment]
Hey i had an urgent question. I am trying to click a button when using date picker.. but instead of the on click of the button, the focus out of the input text box gets triggered and my click is not getting triggered.  Any help would be very much appreciated.

**Comment by DBjelovuk** [comment]
The solution in that PR doesn't work for SingleDatePicker.

**Comment by gokulrk-vuram** [comment]
Hi guys,
I found a solution to hide/unhide next button on the calendar.

 <SingleDatePicker
   navNext={this.state.isCalendarNextButtonDisabled ? <div hidden="true">Next</div> : ''}
   onNextMonthClick={this.onNextMonthClick}
   ...
/>
 onNextMonthClick = (month) => {
    if (month.month() === 5) {
      this.setState({
        isCalendarNextButtonDisabled: true,
      });
    }
  };
//If the month reaches Jun then the next button will be hidden.

**Comment by gokulramkul** [comment]
Hi guys,
I found a solution to hide/unhide next button on the calendar.

 <SingleDatePicker
   navNext={this.state.isCalendarNextButtonDisabled ? <div hidden="true">Next</div> : ''}
   onNextMonthClick={this.onNextMonthClick}
   ...
/>
 onNextMonthClick = (month) => {
    if (month.month() === 5) {
      this.setState({
        isCalendarNextButtonDisabled: true,
      });
    }
  };
//If the month reaches Jun then the next button will be hidden.

**Comment by bdrazen** [comment]
@gokulramkul Is the callback provided the next month? I don't see that in the source code.

**Comment by laila-bouziani** [comment]
import { DayPicker } from "react-day-picker";
import "react-day-picker/lib/style.css";

const App = () => {
  return (
    <div>
      <DayPicker navbar={false} />
    </div>
  );
};

export default App;
