### ISSUE TITLE
unknown props found: minimumNights

### ISSUE THREAD

**Issue by gtgalone** [airbnb/react-dates#693]
Warning: Failed prop type: DayPicker: unknown props found: minimumNights

SingleDatePicker has no props minimumNights, but DayPickerSingleDateController has props minimumNights.

I think that you forgot to add minumumNights  in DayPickerSingleDateController.

Thank you :)

**Comment by ljharb** [comment]
Where are you getting this warning exactly?

**Comment by ljharb** [comment]
The `minimumNights` prop wrongly existed on `DayPickerSingleDateController`; #686 has removed it.
