### ISSUE TITLE
IE 11 Tab Issues

### ISSUE THREAD

**Issue by humphries40** [airbnb/react-dates#696]
I've noticed that in IE 11 if you have selected a date, then click on the input box again and try and use tab or shift-tab nothing occurs. You're just trapped with the calendar input open.  

 I was going to attempt this on the storybook, but it seems that is broken. Supposedly storybook has been updated to fix this issue [here](https://github.com/storybooks/storybook/issues/1352),  So you may need to update your storybook package to the latest release to allow IE users to use the storybook.

**Comment by majapw** [comment]
Oh good call! We'll do the update asap.

**Comment by humphries40** [comment]
Sweet then I can check if the issue is happening there as well, or just in our solution.

**Comment by majapw** [comment]
Hi @humphries40, I updated storybook so hopefully we should be able to test in IE now.

**Comment by humphries40** [comment]
Alright, testing around in IE I couldn't replicate the issue that we're seeing in our application. I'll close this bug.

**Comment by sjain-mi9** [comment]
@majapw, I have a similar issue with tabbing on IE. I have 2 datepickers and it tabs out perfectly on chrome, but fails on IE. I need to switch from one datepicker to another one using tab. On the storybook, it takes 2 tabs to focus on the other datepicker.
