### ISSUE TITLE
Next month days are not highlighted on vertical scrollable version

### ISSUE THREAD

**Issue by Daniellt1** [airbnb/react-dates#710]
GIF from Airbnb website: [https://gfycat.com/gifs/detail/InsidiousIllfatedKob](https://gfycat.com/gifs/detail/InsidiousIllfatedKob)

The same behaviour has been noticed locally using 12.6.0 version.

**Comment by majapw** [comment]
This is a duplicate of https://github.com/airbnb/react-dates/issues/705! But yes, I need to fix this.
