### ISSUE TITLE
Re-render calendar from parent component without any interaction in Calendar

### ISSUE THREAD

**Issue by pradok** [airbnb/react-dates#711]
Hi

I have a parent component that makes an api call to get new disabled days and pass on as props to re-render the calendar, in the mean time I have initial disabled days to show. The new props from parent component doesn't seem to re-render the calendar for new disabled days, in this case isDayBlocked is not called unless I press next month or previous months.

Any help on this.

**Comment by majapw** [comment]
Hi @pradok,

The props modifiers will only get recomputed if the method signature itself changes (https://github.com/airbnb/react-dates/blob/master/src/components/DayPickerRangeController.jsx#L202-L205). I would recommend passing in a totally new function once the api call returns to achieve correct behavior.

**Comment by pradok** [comment]
Hey @majapw 
Awesome! Thanks for the insight.
Works well.
