### ISSUE TITLE
Can we show only specific dates 

### ISSUE THREAD

**Issue by zeegeek** [airbnb/react-dates#714]
For time being i was using blocking the past dates and showing all future dates with some days blocked.

Is there a way to block all dates and show only specific dates?

**Comment by chukitow** [comment]
@zeegeek you mean something like this? http://airbnb.io/react-dates/?selectedKind=DayPickerSingleDateController&selectedStory=with%20some%20blocked%20dates&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel

**Comment by CharlyManotas** [comment]
I have an array of dates, and I just want to have those dates available, everything else does not

**Comment by ljharb** [comment]
@CharlyManotas you could define your `isOutsideRange` function to only return `true` when the date is in that array.

**Comment by CharlyManotas** [comment]
thank you!

**Comment by mathishuettl** [comment]
Hello,

I also just want to display specific dates, but it won't work...

```
<SingleDatePicker isOutsideRange={ this.filterDates } />

// this only disabled my dates
filterDates(e) {
    let availableDates = [...this.state.availableDates];
    return availableDates.some( day => isSameDay(day, e) );
  }

//  this disables all dates (even my dates)
filterDates(e) {
    let availableDates = [...this.state.availableDates];
    return availableDates.some( day => !isSameDay(day, e) );
  }

```
