### ISSUE TITLE
some problems with "isDayHighlighted"

### ISSUE THREAD

**Issue by weswithley** [airbnb/react-dates#725]
Hi, There, 

I'm trying to combine the `isSame (  moment.js method )` & `isDayHighlighted `,
but some weird things happend.

1. when i use "Array" into isSame, it's works fine : 
( the format of Array must be [YYYY, MM, DD] ) 
`isDayHighlighted : day =>  day.isSame( [2017, 8, 30], 'day' )`

2. when i use "String" into isSame, but it's not working :
( the format of String must be 'YYYY-MM-DD' ) 
`isDayHighlighted : day =>  day.isSame( '2017-8-30' , 'day' )`

either way is return true,
but the "String" way isn't working.
Does anyone knows why?

PS : isSame docs :  [http://momentjs.com/docs/#/query/is-same/](url)

Thanks for help. ^^

**Comment by majapw** [comment]
These seems like more of a moment question than a react-dates question, so I'm going to close this issue. 

Um, in general, I'd recommend using the exported `isSameDay` method from this repo as its a bit more performant.

**Comment by stahlmanDesign** [comment]
In this example will highlight today ( `moment()` = now ):
`isDayHighlighted={ day => day.isSame( moment(), 'd' ) }`
