### ISSUE TITLE
Manual input bugs 

### ISSUE THREAD

**Issue by mariepw** [airbnb/react-dates#734]
Entering date manually has some strange behaviour when `displayFormat` is custom.
In `Storybook` I tried to enter `Nov 27` but DayPicker is closing and DateInput is loosing focus just after `2`.. If I click again to add `7`, (even if cursor is not displayed, double click to select complete string, then right key to go through the end of the date...) it will fallback to default display.. 

![manualinputbug_speed](https://user-images.githubusercontent.com/8375629/30955822-4d635348-a435-11e7-9fca-5fd20d803375.gif)

So I am still thinking of an input mask, maybe it could help this strange behaviour...

**Comment by majapw** [comment]
I can't seem to reproduce this anymore given the change to the inputs.

It still loses focus with the custom date when you type `Dec 2`, but when you select the input again and add a 7, it works as expected (selecting Dec 27). I'm going to close this. :)
