### ISSUE TITLE
Keyboard shorcuts triangle button renders as square in Chrome 63 Canary 

### ISSUE THREAD

**Issue by cvializ** [airbnb/react-dates#737]
<img width="359" alt="screen shot 2017-09-29 at 2 55 06 pm" src="https://user-images.githubusercontent.com/2363700/31037555-6bc176de-a526-11e7-93fe-26d7cb5d9728.png">
<img width="888" alt="screen shot 2017-09-29 at 2 55 19 pm" src="https://user-images.githubusercontent.com/2363700/31037556-6bc28024-a526-11e7-85c1-04c9a4deb939.png">

Adding `border-radius: 0;` to the element fixes the bug.

**Comment by majapw** [comment]
Welp! Happy to accept a PR.
