### ISSUE TITLE
[object Object] in _datepicker.css

### ISSUE THREAD

**Issue by jkhedani** [airbnb/react-dates#754]
Noticed that there are two instances of css declarations that are set to`[object Object]` in _datepicker.css (lines 3105, 3058) preventing Webpack from building. Runs when commented out but just posting here to identify the issue.

**Comment by majapw** [comment]
What version are you using?

**Comment by phmietti** [comment]
Same issue here - just tried to upgrade to 13.0.2 from 12.6.0

**Comment by majapw** [comment]
@jkhedani can you clarify what css declaration are being set to `[object Object]`. I have a working demo of 13.0.2 here - https://github.com/majapw/react-dates-demo/blob/master/src/App.js, and it seems to work okay.

**Comment by jkhedani** [comment]
@majapw Sorry for the late reply! I'm using 13.0.2. When compiling my build using Webpack and a vanilla install of react-dates, I get the following error:

![screen shot 2017-10-09 at 10 30 05 pm](https://user-images.githubusercontent.com/1855878/31376701-814ee536-ad41-11e7-8071-5653baadd5b7.png)

Naturally, once the offending lines are commented out, the CSS compiles as intended. As previously mentioned, the offending lines are on lines 3105, 3058.

![screen shot 2017-10-09 at 10 28 16 pm](https://user-images.githubusercontent.com/1855878/31376620-42944598-ad41-11e7-8c59-e27ed378c822.png)

Looks like you removed one instance at 3058 but there is another at 3105.
