### ISSUE TITLE
type error when set date null and focused false of SingleDatePicker props

### ISSUE THREAD

**Issue by XiaominnHoo** [airbnb/react-dates#77]
### Error in console: 
React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `SingleDatePickerWrapper`.

### code is: 
```javascript
 import React from 'react';
import SingleDatePicker from 'react-dates';

class SingleDatePickerWrapper extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      focused: false,
      date: null,
    };

    this.onDateChange = this.onDateChange.bind(this);
    this.onFocusChange = this.onFocusChange.bind(this);
  }

  onDateChange(date) {
    this.setState({ date });
  }

  onFocusChange({ focused }) {
    this.setState({ focused });
  }

  render() {
    const { focused, date } = this.state;

    return (
        <SingleDatePicker
            {...this.props}
            id="date_input"
            date={date}
            focused={focused}
            onDateChange={this.onDateChange}
            onFocusChange={this.onFocusChange}
        />
    );
  }
}

export default SingleDatePickerWrapper;
```
Newer to React and have no idea why this happened

**Comment by majapw** [comment]
If you change the line `import SingleDatePicker from 'react-dates';` to `import { SingleDatePicker } from 'react-dates';`, your code should work. :) 

`react-dates` exports an object of various components and methods right now so you have to destructure it.

**Comment by XiaominnHoo** [comment]
@majapw thank you very much
