### ISSUE TITLE
Invalid CSS in released styles.css

### ISSUE THREAD

**Issue by MonsieurV** [airbnb/react-dates#772]
Hello!

There seems to be an issue during the generation of `react-dates/css/styles.css` with `react-dates@13.0.3`

In the release https://registry.npmjs.org/react-dates/-/react-dates-13.0.3.tgz, we have the following lines:

`css/styles.css`
```
.CalendarMonth_table {
  border-collapse: collapse;
  border-spacing: 0px;
  caption: [object Object]
}
```
(lines `400` and `1247`)

**Comment by MonsieurV** [comment]
Full fine: https://gist.github.com/MonsieurV/b23403275b7ed6d71c68254398ae956d

The issues are:
* there https://gist.github.com/MonsieurV/b23403275b7ed6d71c68254398ae956d#file-style-css-L403
* and here https://gist.github.com/MonsieurV/b23403275b7ed6d71c68254398ae956d#file-style-css-L1250

**Comment by majapw** [comment]
@MonsieurV that's fair (and we should kill that file from the npm package to prevent confusion), but in our README (https://github.com/airbnb/react-dates#webpack) we ask that you import `lib/css/_datepicker.css`, which does not have this issue. I will kill styles.css from the next built version, but I think it is just a relic of the old breakage that has been addressed in https://github.com/airbnb/react-dates/pull/757.

**Comment by MonsieurV** [comment]
Ah thanks!

Yes, that was me that was using (very) old instructions.
Works fine `lib/css/_datepicker.css`. The doc is clear! (should have really read it)

Sorry for the noise & keep-up the good work :)
