### ISSUE TITLE
Localize aria-label for CalendarDay button

### ISSUE THREAD

**Issue by koba04** [airbnb/react-dates#778]
Currently, the aria-label format for CalendarDay button is fixed like "Saturday, October 14, 2017".

https://github.com/airbnb/react-dates/blob/master/src/components/CalendarDay.jsx#L104

Is there any way to customize the format?
I guess I can do that by reparsing the text and format using moment but it seems not to be a proper approach.

Thanks!

**Comment by koba04** [comment]
What do you think about adding `dayAriaLabelFormat` prop?

**Comment by ljharb** [comment]
That seems reasonable. Are there any other label props in any other components that might need similar treatment? We should add it everywhere all at once if so.

**Comment by koba04** [comment]
@ljharb I don't have the issue in any other components now.
