### ISSUE TITLE
IE11: Object doesn't support property or method 'is' (when text field clicked)

### ISSUE THREAD

**Issue by DaveCole** [airbnb/react-dates#779]
In the latest IE11 on Windows, with most of the common MDN polyfills installed, when you click on the text field containing the date range to open the date picker, this error appears in IE11:

Warning: Failed prop type: Object doesn't support property or method 'is'
in Unknown
(the stack trace keeps going back to Unknowns)

The only noticeable behavior difference is that the blue styling for the selected date range and greyed out areas for unselectable dates is not shown.  

Without the polyfills, react-dates doesn't work at all.

**Comment by geryit** [comment]
core-js can hep you: `require('core-js/fn/object/is');`
https://github.com/zloirock/core-js

**Comment by ljharb** [comment]
@geryit indeed, but https://npmjs.com/airbnb-browser-shims is a better choice.

**Comment by DaveCole** [comment]
Props thank you for the education!

**Comment by ljharb** [comment]
Have you loaded the shims before any other code runs?
