### ISSUE TITLE
Style selected end date

### ISSUE THREAD

**Issue by stonerworx** [airbnb/react-dates#786]
Hi!
I've noticed that the selected start date and the selected end date share the same css class names. We have the case that we need to set a different styling to the end date. Is it possible to set a different class name for the selected end date?

Or any other ideas how to select the selected end date with css?

We're already doing things like this:
```
/*
selected end date
*/
.CalendarDay__selected,
.CalendarDay__selected:hover,
td.CalendarDay__selected + td.CalendarDay__selected {
  ...
}

/*
selected start date
*/
.CalendarDay__selected:first-of-type,
:not(.CalendarDay__selected_span) + .CalendarDay__selected {
  ...
}
```
But it feels super hacky.

Thanks!

**Comment by tagoro9** [comment]
I just run into this issue while updating to the latest version. I believe this is a bug. `CalendarDay--selected-start` and `CalendarDay--selected-end` class names used to be added to the calendar day. 

I'm gonna try to work on a fix.

**Comment by stonerworx** [comment]
awesome, thank you!
