### ISSUE TITLE
Selecting Initial Date on SingleDatePicker Component Mount

### ISSUE THREAD

**Issue by merrilj** [airbnb/react-dates#793]
Hey!

I'm using your react-dates module for an app I'm developing and absolutely love it! However, I'm trying to select an initial date on component mount, where today for instance is initially selected. I looked through Storybook and tried using the 'initialDate' property on the SingleDatePicker component, but it gets grumpy about it. Any advice?

Thanks,
Merril

**Comment by majapw** [comment]
Hi @merrilj, sorry we never responded to this... but can you share how you addressed your issue?

**Comment by merrilj** [comment]
Hello @majapw, thanks for reaching out! I set the initial value of the `date` property to a `new Date()` object and formatted it accordingly -- worked like a charm. Keep up the great work :)

**Comment by reidbarber** [comment]
If the above solution doesn't work for anyone who comes across this issue, I had better luck using a moment object instead of a date object. See:

```javascript
var moment = require('moment');

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {selectedDate: moment()};
  }
. . .
```

**Comment by majapw** [comment]
In general, since using `react-dates` involves bringing in moment, I def recommend using a moment object if at all possible.

Thanks for sharing your solution @reidbarber!
