### ISSUE TITLE
I want to enable past and present dates.

### ISSUE THREAD

**Issue by Subramanian8** [airbnb/react-dates#801]
I want to enable past and present dates to choose.

**Comment by erin-doyle** [comment]
This is possible.  What is the question or problem you're having?

**Comment by Subramanian8** [comment]
@erin-doyle thanks for your reply. my question is how to do that?

i found solution for this.

isOutsideRange={(day) => {
           return !day.isSameOrBefore());
}}

**Comment by Parthchokshi** [comment]
`isOutsideRange = {() => false}`
To enable every date

**Comment by tuanluu-agilityio** [comment]
Thank you for saving my time @Parthchokshi
```
isOutsideRange = {() => false}
```
To enable every date
