### ISSUE TITLE
How to iterate through all the rendered dates on the DRP

### ISSUE THREAD

**Issue by RahulReddy75** [airbnb/react-dates#814]
Hi,
I am using the isDayBlocked prop to disable weekends on the calendar. But how do I iterate through all the rendered dates on the DRP?

**Comment by majapw** [comment]
Why do you need to iterate through all the rendered dates?

**Comment by RahulReddy75** [comment]
To check if the day is a weekend or not. and based on that block it.

**Comment by majapw** [comment]
@RahulReddy75 the `isDayBlocked` method take a function which receives a day (in moment object form) as an argument. So to block weekends you would do something like
```
isDayBlocked((day) => day.day() === 6 || day.day() === 0)
```

The documentation on this is not super clear (whoops) and should probably be improved. But yeah! that woudl do it.

**Comment by RahulReddy75** [comment]
oh ok i get it. I was trying to do it through the getDay() function. 
Anyway thanks this solves the issue.
