### ISSUE TITLE
Enable dates only from Jan1st 2017 to current date

### ISSUE THREAD

**Issue by kishoreyarram** [airbnb/react-dates#817]
- Is there any way to enable only dates from Jan 1st 2017 till current date and disable previous to jan 1st and future dates
- Future dates I am disabling using ```isOutsideRange={day => !isInclusivelyBeforeDay(day, moment())}```
- I need suggestions only to disable date before Jan 1st

**Comment by majapw** [comment]
You can use an or operator in your `isOutsideRange`
```
isOutsideRange={day =>  isAfterDay(day, moment()) || isBeforeDay(day, moment('2017-01-01'))};
```

**Comment by kishoreyarram** [comment]
Thank you @majapw For the real quick response. Its working...!!
