### ISSUE TITLE
react-dates doesn't work in IE9

### ISSUE THREAD

**Issue by corohsnk** [airbnb/react-dates#820]
Hello Guys, I imported react-dates in my project and I tested in IE9 and broke webapp.

I imported in file.js

```
import 'airbnb-js-shims';
import 'react-dates/initialize';
import { DateRangePicker } from 'react-dates';
and import css...
```

I inserted like get started instruct 

```
<DateRangePicker
  startDate={this.state.startDate} // momentPropTypes.momentObj or null,
  endDate={this.state.endDate} // momentPropTypes.momentObj or null,
  onDatesChange={({ startDate, endDate }) => this.setState({ startDate, endDate })} // PropTypes.func.isRequired,
  focusedInput={this.state.focusedInput} // PropTypes.oneOf([START_DATE, END_DATE]) or null,
  onFocusChange={focusedInput => this.setState({ focusedInput })} // PropTypes.func.isRequired,
/>
```
and in IE9 when I click to select date broken webapp and print exception in console 

> 
> Line: 44499
> Error: Unable to get value of the property 'isDayBlocked': object is null or undefined

Any idea on how to fix it?

**Comment by majapw** [comment]
Woah! That is a surprise. I will dig into that today. That seems major.

**Comment by ljharb** [comment]
@corohsnk could you provide line 44499 in your bundle?

**Comment by corohsnk** [comment]
Attach error in line 44499

![selection_019](https://user-images.githubusercontent.com/18468813/32291503-64f1de44-bf24-11e7-9e9b-3a94a21fb58c.png)

**Comment by ljharb** [comment]
What version of React are you using?

**Comment by corohsnk** [comment]
is 16.0.0

**Comment by corohsnk** [comment]
I created project blank with React ^15.5.4, added react-dates ^15.0.0 and I got the same error again.

**Comment by ljharb** [comment]
That error is indicating that `this.props` is undefined; any chance you could use a debugger, and figure out what the value of `this` is there?

**Comment by majapw** [comment]
Is there a possibility the arrow functions in the constructor are not being transpiled correctly?

**Comment by ljharb** [comment]
No - https://unpkg.com/react-dates@15.0.0/lib/components/DateRangePicker.js shows that it's correct.

Are you sure you're not babel-transpiling node_modules (something you should never do)?

**Comment by ljharb** [comment]
Regardless, if it wasn't being transpiled correctly, it'd be failing on most engines, not just on IE 9 :-(

**Comment by corohsnk** [comment]
Sorry for the delay, well...

> That error is indicating that this.props is undefined; any chance you could use a debugger, and figure out what the value of this is there?

For me, this is 
`context: undefined
props: undefined
refs: {}
updater: {isMounted: ƒ, enqueueForceUpdate: ƒ, enqueueReplaceState: ƒ, enqueueSetState: ƒ}
isMounted: (...)
replaceState: (...)
__proto__: ReactComponent`

**Comment by ljharb** [comment]
`props` should just never be `undefined`, rather an empty object - this feels like it might be a React bug.

**Comment by ljharb** [comment]
Can you share the entire component code that's rendering the DateRangePicker?

**Comment by corohsnk** [comment]
Hello @ljharb, 

```
import React, { Component } from 'react';
import './historico.css'
import 'moment/locale/pt-br';
import * as moment from 'moment';
import 'airbnb-js-shims';
import 'react-dates/initialize';
import { DateRangePicker } from 'react-dates';
import 'react-dates/lib/css/_datepicker.css';

moment.locale('pt-br');

class Calendar extends Component {
  constructor() {
    super()
    this.state = {
      startDate: null,
      endDate: null,
      focusedInput: null
    }
  }
  render() {
    return (
      <div className="historico-calendar-container">
        <div className="container">
          <div className="row">
            <span>Resultados dos exames de:</span>
            <DateRangePicker
              startDate={this.state.startDate} // momentPropTypes.momentObj or null,
              endDate={this.state.endDate} // momentPropTypes.momentObj or null,
              onDatesChange={({ startDate, endDate }) => this.setState({ startDate, endDate })} // PropTypes.func.isRequired,
              focusedInput={this.state.focusedInput} // PropTypes.oneOf([START_DATE, END_DATE]) or null,
              onFocusChange={focusedInput => this.setState({ focusedInput })} // PropTypes.func.isRequired,
              startDatePlaceholderText="De"
              endDatePlaceholderText="Até"
              isOutsideRange={() => false}
            />
          </div>
        </div>
      </div>
    )
  }
}

export default Calendar;
```

**Comment by corohsnk** [comment]
> Can you share the entire component code that's rendering the DateRangePicker?

**Comment by ljharb** [comment]
Why `import * as moment`? That’s incorrect; moment is a CJS package and as such, only has a default export.

Separately, the airbnb-js-shims import needs to happen first, before any other code in your application runs, especially react.

**Comment by corohsnk** [comment]
Hello @ljharb, I removed import * as moment and moment.locale('pt-br');

I up 'airbnb-js-shims'; to first import;

but I see error yet

`Error: Unable to get value of the property 'isDayBlocked': object is null or undefined`

**Comment by ljharb** [comment]
Ok, another thing - the shims have to be the first thing imported *in your entire application*, not just in this component. Meaning, before any other JavaScript has executed on the page.

**Comment by corohsnk** [comment]
Hmmm, so I need import shims in all components/pages or index.js?

**Comment by ljharb** [comment]
As the first line of javascript that runs on every webpage on your site; where that means it needs to go depends on your specific setup.

**Comment by corohsnk** [comment]
Ok, thanks, Are you able to use the component in IE?

**Comment by ljharb** [comment]
Yes.

**Comment by corohsnk** [comment]
Hoooow?, even with a blank project, I can not

**Comment by khsily** [comment]
@corohsnk That is because of "this.props.isDayBlocked" in constructor.
I don't know why but lower versions of ie do not support using this.props in constructor so simply changing "this.props.isDayBlocked" to "props.isDayBlocked" will fix the problem.

**Comment by ljharb** [comment]
(#233)
