### ISSUE TITLE
Babel dependencies properly included for development

### ISSUE THREAD

**Issue by JuanCaicedo** [airbnb/react-dates#827]
I'm seeing some errors within my webpack build (coming from babel) when trying to get started with this component. They seem to require that I install the babel plugins used by react-date's own [.babelrc](https://github.com/airbnb/react-dates/blob/master/.babelrc#L14). 

To verify, I ran `$ npm install babel-plugin-inline-react-svg babel-preset-airbnb babel-plugin-transform-replace-object-assign`. 

I _think_ the problem comes from the fact that when you run `$ npm install react-dates`, it only installs production dependencies, but these babel plugins are inside [devDependencies](https://github.com/airbnb/react-dates/blob/master/package.json#L63). Since react-dates will be handled inside of my own webpack build (in development), I think that means that I will need react-date's dev dependencies. 

I'm not sure what it's like to manage a library that is used within a webpack build, yet has it's own webpack build and dependencies. I think maybe it would be nice to be able to just get a dist copy that has already been built, so that it's agnostic to the build system.

Let me know if I can provide any more information to help with this!

**Comment by ljharb** [comment]
This issue is caused if you are (incorrectly) transpiling `node_modules`. If you don't configure your babel to do this, you won't run into it.

**Comment by JuanCaicedo** [comment]
Thanks for the quick response. Perhaps I'm understanding how babel is configured, but as far as I can tell, I'm not doing anything with `node_modules`
```
// .babelrc
{
  "plugins": [
    [
      "module-resolver", {
        "root": ["."],
        "alias": {
          "styles": "./styles"
        },
        "cwd": "babelrc"
    }],
    [
      "wrap-in-js",
      {
        "extensions": ["css$", "scss$"]
      }
    ],
    ["transform-define", "./env-config.js"]
  ],
  "presets": [
    "next/babel"
  ],
  "ignore": []
}
```

Perhaps it has to do with [the preset I'm using](https://github.com/kMeillet/babel-preset-next-react/blob/master/index.js)?

**Comment by ljharb** [comment]
Nothing in that seems like it'd transpile node_modules.

What are the errors you're seeing?

`react-dates`, installed from npm, should be using the pre-transpiled code in `lib` - babel plugins are only required for *developers* of react-dates, not users of it.

**Comment by JuanCaicedo** [comment]
They're along the lines of
```
error  in ./node_modules/react-dates/lib/css/_datepicker.css

Module build failed: ReferenceError: Unknown plugin "inline-react-svg" specified in "<project-root>/node_modules/react-dates/.babelrc.env.development"
```

**Comment by JuanCaicedo** [comment]
Also I'm confused about how importing a css file could cause this error

**Comment by ljharb** [comment]
aha! looks like `wrap-in-js` is transpiling that css; and it's reading the `.babelrc` inside `react-dates`.

That's a bug in that plugin; it should be setting `--no-babelrc` when it transforms CSS files.

**Comment by JuanCaicedo** [comment]
I added this issue so I can close the one here https://github.com/davibe/babel-plugin-wrap-in-js/issues/2, but I'm still having trouble 😬

**Comment by mihirsoni** [comment]
@ljharb  I am also facing similar issue.

.babelrc 

```
{
  "env": {
    "production": {
      "presets": ["es2015", "react"]
    },
    "development": {
      "presets": ["es2015", "react"]
    },
    "test": {
      "presets": ["es2015", "react"]
    }
  }
}
```


Error log

```js
ERROR in ./node_modules/react-dates/initialize.js
Module build failed: ReferenceError: Unknown plugin "inline-react-svg" specified in "react-dates-integ/node_modules/react-dates/.babelrc.env.development" at 0, attempted to resolve relative to "react-dates-integ/node_modules/react-dates"
    at react-dates-integ/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (react-dates-integ/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (react-dates-integ/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (react-dates-integ/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (react-dates-integ/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (react-dates-integ/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (react-dates-integ/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (react-dates-integ/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (react-dates-integ/node_modules/babel-loader/lib/index.js:175:20)
 @ ./src/index.js 15:0-33
```
