### ISSUE TITLE
Pass modifiers to renderDay to allow flexible CalendarDay display and styling?

### ISSUE THREAD

**Issue by ericls** [airbnb/react-dates#828]
First of all, thanks for such a great library.

I'm trying to change how days are rendered based on the select/hover state of the calendar.
I'm aware that you can combine onMouseEnter, startDate, endDate, etc to achieve this, but it would be nice to have all those information passed to renderDay directly from modifiers.

**Comment by majapw** [comment]
Yes! I actually have a local branch that does this but haven't had a chance
to merge it in. I'd love to accept a PR for this.

**Comment by Rickkorsten** [comment]
@majapw @ljharb @schleyfox Is there someone who can show me an example how to use modifiers with the calendar?

thx

**Comment by majapw** [comment]
@Rickkorsten I'm not sure that that is related to this issue (which I'm going to close since we merged in the feature). Can you open a new issue with more details on what exactly you're trying to do?

Thanks!
