### ISSUE TITLE
`DayPickerRangeController` leaves ghost values when using a keyboard

### ISSUE THREAD

**Issue by backwardok** [airbnb/react-dates#831]
http://airbnb.io/react-dates/?selectedKind=DayPickerRangeController&selectedStory=default&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel

Steps to reproduce:
1. Tab into calendar with keyboard
2. Select a date with the keyboard via space or enter. Notice that there's a green highlighted date right after the date chosen
3. Select an end date
4. Select a new date not in the existing range to select a new range

The date right after the start date is highlighted differently than the highlight for selected dates within the range. That highlight also doesn't go away when selecting a new range. This leaves highlighted dates on the calendar.

![image](https://user-images.githubusercontent.com/6530351/32582321-05dfe6d8-c4a3-11e7-9641-5daa10b98c48.png)

![ghostdateskeyboard](https://user-images.githubusercontent.com/6530351/32582386-5f357c0c-c4a3-11e7-9fde-c82f4e753ca7.gif)

**Comment by majapw** [comment]
Ah, yeah, I think this was probably due to the withStyles change being somewhat incomplete. In the DRP, we get a refresh due to the calendar being closed and reopened so it's not an issue there. 

Actually, just kidding... gh-pages seems kind of out of date. :/ It's not showing the aphrodite classes.

**Comment by majapw** [comment]
Okay, now that I went on that segway. This appears to be true, even in the latest version. It looks like we are not cleaning up the hovered-span class which is... weird.
