### ISSUE TITLE
Reduce transition duration

### ISSUE THREAD

**Issue by M-Willett** [airbnb/react-dates#834]
First of all, awesome job on this! Very nice and flexible. 

Our users feel that the transition duration is too slow. The component waits for the end of the transition before being able to skip ahead without delay. I had a quick search through the list of issues but surprisingly no one has reported this.

I've tried setting a `transition-duration: .1s !important` property which creates a weird card-shuffling effect. I then tried `transition: none !important` to remove completely but since the pagination relies on the `transitionEnd` it breaks the pagination. (I've found and tried `transformValue`  as a string but this didn't change anything afaik.)

Is there/could there be a default prop for setting this?

**Comment by majapw** [comment]
I think that's probably a good idea! I would support this added prop.

**Comment by majapw** [comment]
Released in 15.3.0! :)
