### ISSUE TITLE
Inputs cannot be labeled

### ISSUE THREAD

**Issue by Jesus-Gonzalez** [airbnb/react-dates#835]
Hello.

Is there some way I can label the inputs in the `DateRangePicker`? I do not have the flexibility to add a custom label to the inputs.

If you like, I can open a PR myself to get this done.

Thanks,
Jesús

**Comment by timhwang21** [comment]
@Jesus-Gonzalez we have had a similar issue. One alternative option for you is to assemble your own `DatePicker` using the exported components. For example, instead of importing `DateRangePicker`, import `DayPickerRangeController` and build your own inputs.

**Comment by Jesus-Gonzalez** [comment]
@timhwang21 thanks, I will try this :slightly_smiling_face:

**Comment by majapw** [comment]
I actually kind of thing it would be a great idea to add a visible label to the inputs (and maybe add an option to hide them and have an invisible but accessible label as well).

We should def be encouraging the positive a11y practice of visible labels! Placeholders do not count as labels... no matter how much we want them to. :P

**Comment by jyotsana-khaparde** [comment]
Hello, 
I was using **DateRangePicker** and i wanted to show labels for the start date and end date for example -> 
![image](https://user-images.githubusercontent.com/58733142/162171478-ab818c6b-db0a-4844-9f87-a5a585343cff.png)

which props can be used for it? 
for placeholder i have used **startDatePlaceholderText, endDatePlaceholderText** props which is working.
for labels i have tried **startDateTitleText, endDateTitleText also startDateAriaLabel, endDateAriaLabel**  props but it's not working.

Does anyone have an idea how to achieve this? any help will be appreciated :-)
Thanks!!
