### ISSUE TITLE
No CSS with React 16 & react-dates v15

### ISSUE THREAD

**Issue by Drecula** [airbnb/react-dates#836]
I've read #45 et al., and have imported both initialize
and _datepicker.css, but DateRangePicker is not showing
styles.

I also tried copying the css directly into where I'm using
the datepicker and verified that I've no other class named
DateRangePicker.

Please let me know if there's anything else I can do to help
with the diagnosis or fix.

Thanks!!!

page level:
`
import 'react-dates/initialize';
`

at page or component level:
`
import 'react-dates/lib/css/_datepicker.css';
`

**Comment by majapw** [comment]
Are you getting any errors? Do your components have classnames? Does the datepicker.css look like you would expect?

**Comment by Drecula** [comment]
Thanks for the speedy response!!!

I am not getting any errors.

It is several layers deep in my view hierarchy, and containing
components do indeed have classnames.

I'm not sure what you mean by "Does the datepicker.css look like you would expect?". I am
just trying to get the component to render with the default styles.

**Comment by Drecula** [comment]
OK, it was a webpack config problem...there was no css loader in the config.

**Comment by LucasAndrad** [comment]
Hi @Drecula, could you please explain how did you solve? I think I have the same problem here. Thank you
