### ISSUE TITLE
displayFormat seems to run the value returned by a function through moment

### ISSUE THREAD

**Issue by derwaldgeist** [airbnb/react-dates#837]
If I provide a function to `displayFormat`, the return value isn't being used as it is. Instead, it seems to be additionally interpreted by moment. If, for instance, the value includes an "l" (small L), this letter is replaced by the complete date. Why is this so? I would prefer the function value to be displayed as is.

If this is not how it is intended to work, a "renderDisplay" function or something like this would be great.

**Comment by majapw** [comment]
So moment is our formatter of choice so your return value needs to conform
to its standards. If you have an l (or L) in that output, those letters are
special in moment. Anything hardcoded in should be surrounded by brackets,
like so `MMDD [this text won't be run through the formatter]`.

Does that answer your question?

**Comment by derwaldgeist** [comment]
Ah, I did not know about the bracket syntax. Great, thanks.
