### ISSUE TITLE
ACTION LOGGER appears doesn't work in demo

### ISSUE THREAD

**Issue by wzup** [airbnb/react-dates#84]
There is an "ACTION LOGGER" section on demo page http://airbnb.io/react-dates/. Is I understand it should log operations show them to us . But it doesn't

![react storybook - google chrome 2016-09-14 14 44 27](https://cloud.githubusercontent.com/assets/3880497/18502473/f7f0486a-7a89-11e6-943f-b58f779237f5.png)

**Comment by majapw** [comment]
The `Action Logger` is actually a feature of storybook and would require some hooks in the various stories (https://github.com/airbnb/react-dates/tree/master/stories) themselves to trigger on things like date change and focus change. 

So its totally working; there just, uh, aren't any actions to speak of. :) If you think it makes sense to add some, please feel free to PR in, but I don't think this is inherently an issue.
