### ISSUE TITLE
Getting - cannot read property 'create' of undefined - React 16 

### ISSUE THREAD

**Issue by firaskrichi** [airbnb/react-dates#845]
<img width="816" alt="screen shot 2017-11-16 at 8 54 22 am" src="https://user-images.githubusercontent.com/9126737/32909846-ca5177bc-caab-11e7-8643-e56067121772.png">

**Comment by ljharb** [comment]
What version of react-dates are you using? What does `npm ls react-with-styles` say? If you run `npm update`, does it fix it?

**Comment by firaskrichi** [comment]
Here are my packages: 

<img width="372" alt="screen shot 2017-11-16 at 12 57 55 pm" src="https://user-images.githubusercontent.com/9126737/32920678-4df9b9cc-cace-11e7-91f7-541012ee3419.png">

And here is what I see when I run `npm ls react-with-styles`

<img width="286" alt="screen shot 2017-11-16 at 1 01 51 pm" src="https://user-images.githubusercontent.com/9126737/32920705-6910d2ae-cace-11e7-8ff1-f4e60ea478af.png">

**Comment by firaskrichi** [comment]
`npm update ` doesn't help :/

**Comment by firaskrichi** [comment]
@ljharb any ideas what's wrong I've tried a few things but without luck

**Comment by EstebanBorai** [comment]
Same issue here!
Im getting:
`Uncaught TypeError: Cannot read property 'create' of undefined
    at Object.createLTR [as create] (main.js:112557)
    at WithStyles.maybeCreateStyles (main.js:9133)
    at WithStyles.componentWillMount (main.js:9119)
    at callComponentWillMount (main.js:61652)
    at mountClassInstance (main.js:61708)
    at updateClassComponent (main.js:63164)
    at beginWork (main.js:63548)
    at performUnitOfWork (main.js:65539)
    at slowWorkLoopThatChecksForFailedWork (main.js:65625)
    at workLoop (main.js:65593)`

``-- react-dates@15.1.0
  `-- react-with-styles@2.3.0`

**Comment by firaskrichi** [comment]
was able to fix the issue by reverting to react-dates 12.2.4

**Comment by ljharb** [comment]
That's pretty far back; and it shouldn't be needed.

The implication is that `ThemedStyleSheet` is undefined.

Perhaps you haven't done `import 'react-dates/initialize';` at the beginning of your application, which is noted in the readme? @firaskrichi @EstebanBorai does this fix your issue?

**Comment by EstebanBorai** [comment]
It worked for me thanks!

**Comment by majapw** [comment]
It seems like this has been resolved!

**Comment by tiberiumihai** [comment]
I defined basepath in my environment files and used it for translations like this:
```
...
useFactory: (http: HttpClient) => new TranslateHttpLoader(http, environment.basepath + 'assets/i18n/', '.json'),
...
```
I change it to:
```
const BASE_PATH = environment.basepath;

...
useFactory: (http: HttpClient) => new TranslateHttpLoader(http, BASE_HREF + 'assets/i18n/', '.json'),
...
```
and is working fine now.

**Comment by bilal68** [comment]
import 'react-dates/initialize';
fixed the solution for me

**Comment by Josemboa** [comment]
import 'react-dates/initialize'; 
fixed the problem for me too.

**Comment by SevenInterval** [comment]
@firaskrichi maybe you didn't create sql side in your project.

**Comment by rsgilbert** [comment]
import 'react-dates/initialize'
