### ISSUE TITLE
Option to disable animation

### ISSUE THREAD

**Issue by wachunga** [airbnb/react-dates#849]
It appears there is no way to disable the transitions/animation when navigating through months. I would like to use this library but the animation doesn't jive with my company's style guide.

I've tried overriding `transition-duration` etc but the navigation breaks after navigating back a month or two (using SingleDatePicker). The [inline styles in CalendarMonthGrid](https://github.com/airbnb/react-dates/blob/master/src/components/CalendarMonthGrid.jsx#L255) are also difficult to work with.

Could eg `animated` be a prop? Perhaps I've overlooked a simpler solution?

**Comment by ljharb** [comment]
A prop to disable animations/transitions makes sense to me.

**Comment by majapw** [comment]
This seems like a good idea to me too! I think it's been floated before.
Happy to accept a PR.

**Comment by majapw** [comment]
Released in 15.3.0! :)
