### ISSUE TITLE
How do I highlight "today" on the calendar? v12.6.0 upgrading to v15.1.0

### ISSUE THREAD

**Issue by uvtzxpm** [airbnb/react-dates#859]
Using an old version (v12.6.0), this CSS worked:

```
.CalendarDay--today {
	box-shadow: inset 0 0 2px 1px rgba(0,0,255,1);
	font-weight: bold;
}
```

To give this effect:

![image](https://user-images.githubusercontent.com/24996578/33333872-0a036c04-d460-11e7-82f1-11ff529596f1.png)

How can I do the same thing using a recent version?

I have searched and looked at the v13+ changes, but the answer does not seem obvious. Thanks!

**Comment by majapw** [comment]
Hmmm, it looks like this feature got removed by accident. Will add back!

**Comment by erin-doyle** [comment]
This may have happened during the conversion to using `withStyles`.  Previously there was this:

```javascript
const className = cx('CalendarDay', {
    'CalendarDay--outside': isOutsideDay,
}, Array.from(modifiers, mod => `CalendarDay--${mod}`));
```

And within `modifiers` is "today", so it would have set the class `CalendarDay--today`.

**Comment by majapw** [comment]
Put up a PR for a quick fix! :)

**Comment by uvtzxpm** [comment]
@majapw Thanks for the fast fix. It works for me (class changed to `.CalendarDay__today`).

Do you think there will be a release containing this sometime this week?

**Comment by majapw** [comment]
Yup! Working on a release right now :)

**Comment by majapw** [comment]
v15.2.0 is out! :D
