### ISSUE TITLE
Set date range

### ISSUE THREAD

**Issue by mnsr** [airbnb/react-dates#86]
Is it possible to set the usable date range? (e.g. jan 01, 2017 -> dec 31, 2017)

Lets say i want the DateRangePicker to start from jan 01, 2017 and anything before that should not be selectable. Therefore the calendar opens up by default at jan 01, 2017, rather than today.

I see there is a property called `isOutsideRange`, but i'm not sure how that works.

**Comment by ljharb** [comment]
@mnsr the prop takes a function that receives a moment object, and returns true or false. `isOutsideRange: date => date.year() !== 2017` should prevent any date not in 2017 from being selected, for example.

I think #47 / #70 is what you're waiting for for "what month does it open up to initially".

**Comment by majapw** [comment]
https://github.com/airbnb/react-dates/pull/70 has been merged in, so you should be able to set the initial month on open now.
