### ISSUE TITLE
_datepicker.css empty, no styles

### ISSUE THREAD

**Issue by littleninja** [airbnb/react-dates#864]
It seems there might be a breaking change in the latest release 15.2.0. The datepicker stylesheet (`react-dates/lib/css/_datepicker.css`) is an empty file. Our workaround is to pin our project to version 15.1.0.

Steps:

1. Create an empty directory `test`
2. Change into `test` directory
3. Install latest version of react-dates `npm install react-dates`
4. Open stylesheet in text editor: `node_modules/react-dates/lib/css/_datepicker.css`

Expected: ~700 lines of styles
Actual: empty file

Versions:

react-dates: 15.1.0 (working) and 15.2.0 (broken)

node: 7.2.1
npm: 4.0.5
react: ^16.0.0
react-dom: ^16.0.0
react-addons-shallow-compare: ^15.6.2
moment: ^2.18.1
webpack: 3.5.1
style-loader: 0.18.2
css-loader: 0.28.4

**Comment by majapw** [comment]
Ah you are totally right. I believe this is due to the react-with-styles change. :O let me fix this real quick. Sorry for the breakage!

**Comment by majapw** [comment]
... Okay I actually have no idea what happened because I basically just ran the publish script again and we're back. :/ 

Sorry for the breakage again and v15.2.1 should contain the patch!

https://unpkg.com/react-dates@15.2.1/lib/css/_datepicker.css
