### ISSUE TITLE
DayPickerRangeController highlight selection does not remove when using keyboard

### ISSUE THREAD

**Issue by allanpope** [airbnb/react-dates#872]
Using a keyboard to navigate the calendar and making a selection works. When you make another selection using the keyboard, the original date range highlight remains.

I am using `DayPickerRangeController` component and using CSS stylesheets and classes(not react-with-styles) and Chrome.

In the screenshot below the dates 15-19th are from the previous selection and still have the `.CalendarDay__hovered_span` class. Also cant replicate this on the "react-with-styles" version.

<img width="1095" alt="bug" src="https://user-images.githubusercontent.com/2561365/33410635-5332fafe-d5d5-11e7-8b75-bdf73f2c9a72.png">

**Comment by majapw** [comment]
@allanpope can you share what version of react-dates you're using? We had recently addressed a similar issue so I'm wondering if it's related.

**Comment by allanpope** [comment]
@majapw Yeah you are right. I was using version `15.1.0`, upgrading to `15.2.1` fixes it. 
Sorry should of checked the see if there was a newer version. Thanks for your help.

**Comment by majapw** [comment]
Glad to see that we fixed it! :)
