### ISSUE TITLE
CalendarDay - onKeyDown is not a function

### ISSUE THREAD

**Issue by passi246** [airbnb/react-dates#899]
Preconditions: 
 - Using v16
 - Using SingleDatePicker Component
 - Entering the CalendarDay by pressing the down key

Pressing a key results in CalendarDay onKeyDown is not a function
<img width="562" alt="bildschirmfoto 2017-12-13 um 12 47 26" src="https://user-images.githubusercontent.com/6725613/33937556-401bd0c4-e004-11e7-9398-5f6e2e73a819.png">

**Comment by ljharb** [comment]
Thanks, this is definitely a [bug](https://github.com/airbnb/react-dates/blob/master/src/components/CalendarDay.jsx#L164)

**Comment by majapw** [comment]
oh no! will fix asap!
