### ISSUE TITLE
DayPickerRangeController position top

### ISSUE THREAD

**Issue by sag1v** [airbnb/react-dates#900]
Hi, is there a feature that i'm missing regarding the position of `DayPickerRangeController`?
For example if i placing the Input on the bottom of the page (fixed position),  the `DayPickerRangeController` won't show as it will render below the input. 
I think we should have a `position` prop with the shape of `bottom || top`.
Or maybe even better, if react dates could calculate the position by it self and decide if it should be rendered above or below the input.

**Comment by sag1v** [comment]
Any thoughts about this? 😮

**Comment by majapw** [comment]
Do you mean when using the DateRangePicker? I think there is already a prop
for this. It is called openDirection.

**Comment by sag1v** [comment]
@majapw Yup, [you are right](https://github.com/airbnb/react-dates/blob/master/src/components/DateRangePicker.jsx#L365)!
And yeah i meant `DateRangePicker`, i had a typo.
I guess I've missed it. sorry. :)
