### ISSUE TITLE
openDirection="up" has fang in the wrong location

### ISSUE THREAD

**Issue by singingwolfboy** [airbnb/react-dates#904]
This can be easily seen on the [official Storybook story for this case](http://airbnb.io/react-dates/?selectedKind=DRP%20-%20Calendar%20Props&selectedStory=open%20up):

![misplaced-fang](https://user-images.githubusercontent.com/132355/34110401-d955d5ae-e406-11e7-8325-3a5953f77271.png)

Notice how the top of the fang is aligned to the _input_, when it should be aligned to the _calendar_.

**Comment by majapw** [comment]
Whoops! This is probably due to my recent refactoring. I can't get to a fix
until after the 25th, but the error is in the logic for fang placement in
the DateInput component. We'd accept a PR with the patch!

**Comment by mhluska** [comment]
This tripped me up for a while. As a temporary fix, I'm passing `verticalSpacing={0}` to hide the caret.

**Comment by majapw** [comment]
https://github.com/airbnb/react-dates/pull/925 should fix this!

**Comment by singingwolfboy** [comment]
This appears to be fixed!
