### ISSUE TITLE
Unexpected token ] in JSON

### ISSUE THREAD

**Issue by Olian04** [airbnb/react-dates#907]
I've followed the installation instructions but I'm getting an error: 

```
.../node_modules/react-dates/index.js: Unexpected token ] in JSON at position 364 while
parsing near '...ect.assign"],    ],  },    "produ...' in .../node_modules/react-dates/index.js

    at module.exports (.../node_modules/parse-json/index.js:26:19)
    at Object.load (.../node_modules/parcel-bundler/src/utils/config.js:40:12)
    at <anonymous>

```
The error is thrown when i try and use the `DateRangePicker` component:
```jsx
<div>
    <DateRangePicker 
         startDate={this.props.state.startDate} 
         endDate={this.props.state.endDate}
         onDatesChange={d => {
              console.log(d);
         }}
         focusedInput={this.state.focusedInput}
         onFocusChange={focusedInput => this.setState({ focusedInput })}
    />
</div>
```

__Versions:__
npm: 5.5.1
react-vis: 1.8.0
react: 16.2.0
parcel-bundler: 1.2.0

**Comment by ljharb** [comment]
This seems like it might be an issue with parcel; I'm not sure why it'd be running into any JSON. In this case, it looks like it's picking up the `.babelrc` file and trying to require it?

**Comment by Olian04** [comment]
@ljharb hmm, alright. I'll open an issue over there aswell then.
