### ISSUE TITLE
Border-radius

### ISSUE THREAD

**Issue by matheusalxds** [airbnb/react-dates#912]
How could I set border-radius?

**Comment by matheusalxds** [comment]
Any suggestion?

**Comment by ljharb** [comment]
On what, exactly?

**Comment by matheusalxds** [comment]
At all, but I dit it!

**Comment by barrylachapelle** [comment]
Wow. Maybe dropping the css in as an answer would have helped.

**Comment by matheusalxds** [comment]
Of course!! I've created a file to control my css and added this class there:

`.DateRangePickerInput {
  border-radius: 5px;
  border: 0px;
  overflow: hidden;
  ...
}`
