### ISSUE TITLE
Allow selecting same date in DateRangePickerWrapper 

### ISSUE THREAD

**Issue by evonsdesigns** [airbnb/react-dates#914]
I have an inline calendar where the date range can span a single day.

Is it possible to allow the end date to be selected as the same day as the start date with the Calendar view of DateRangePickerWrapper? In Storybook, nothing happens when selecting the same day. I can do it programmatically via a preset, but that makes for bad UX.

**Comment by majapw** [comment]
Yup! Just pass in minimumNights={0}.

**Comment by evonsdesigns** [comment]
That works! Thanks!

**Comment by experts-web2** [comment]
bundle of thanks @majapw,
