### ISSUE TITLE
Open SingleDatePicker at the current selected date

### ISSUE THREAD

**Issue by sir-marc** [airbnb/react-dates#92]
Is there a possibility to open the SingleDatePicker at the position of the current selected date?
Because if the current value is 10 years back, it opens today, and going back is a pain in the ass because of the also missing "changeYear" functionality.

**Comment by devourment77** [comment]
I ran into this today with the range date picker.  If I preset dates in the future (say 3 months out), when the user clicks the input, the months displayed are the current months.  Note that the correct inputs are selected in the calendar, just have click the arrows a few times to get to the correct months.

**Comment by majapw** [comment]
I think that this should be fixed by https://github.com/airbnb/react-dates/pull/70 and setting the `initialVisibleMonth` prop
