### ISSUE TITLE
Unexpected result when selecting the same day by DRP

### ISSUE THREAD

**Issue by seraphimrose** [airbnb/react-dates#923]
Version: `16.0.1`

I've cloned the repo and done `npm run storybook`.

I passed in the prop `minimumNights={0}` to the `DateRangePicker` component in `examples/DateRangePickerWrapper.jsx` to allow the start and end date to be the same, then I modified the `onDatesChange` method as below so that when the user selects, the start date is always `00:00:00.000`, and the end date is always `23:59:59.999`.

```jsx
onDatesChange({ startDate, endDate }) {
  this.setState({
    startDate: startDate && startDate.startOf('day'),
    endDate: endDate && endDate.endOf('day'),
  })
}
```
It turns out that it only works when selecting different dates for start and end, i.e., selecting 27/12 and 28/12 would give me `27/12 00:00:00` and `28/12 23:59:59`.  If the start and end dates are the same, however, they'd both become the end date.  For example, if I put 27/12 for both, they'll both become `27/12 23:59:59`.

**Comment by michaelfaust** [comment]
the same problem zzzZZZ

**Comment by michaelfaust** [comment]
Anyone could solve this problem? I also met this problem and it really confuse the user...

**Comment by majapw** [comment]
@michaelfaust @seraphimrose `moment` objects are not immutable and when you call `startDate.startOf('day')` and `endDate.endOf('day')`, you are actually changing the value of the original moment object. I wonder if you cloned the `startDate` and `endDate` if that would help things, e.g.:
```
onDatesChange({ startDate, endDate }) {
  this.setState({
    startDate: startDate && startDate.clone().startOf('day'),
    endDate: endDate && endDate.clone().endOf('day'),
  })
}
```

Do you still see the same problem if you don't change the time at all?

**Comment by seraphimrose** [comment]
@majapw Thank you very much for your response! It works. That's my mistake.
