### ISSUE TITLE
Set different formats for Start Date and End Date for DateRangePicker

### ISSUE THREAD

**Issue by nikoootine** [airbnb/react-dates#930]
I have a use case where the Date Input should look like this: 
![image](https://user-images.githubusercontent.com/15661253/34446044-fbe282f0-ec8c-11e7-9443-96baf1acfaec.png)

The way I see it is maybe we can add props like startDateFormat and endDateFormat for the DateRangePicker

**Comment by ljharb** [comment]
What would your use case look like when the dates are December 23rd, through January 2nd?

**Comment by nikoootine** [comment]
The dates would be displayed as "Dec 10, 2017 - January 2, 2018" as they spread out into different years.

**Comment by ljharb** [comment]
So you're suggesting that you (the consumer) would be responsible for changing the startDateFormat/endDateFormat as needed?

**Comment by nikoootine** [comment]
Precisely, this would allow us to further customize the date picker inputs.  I can make the pull request if needed

**Comment by ljharb** [comment]
Great! Let's see what @majapw and @erin-doyle think first.

**Comment by erin-doyle** [comment]
Hmm, I'm not sure.  It seems to me that if the library consumer wants to really customize the input then maybe it's the right scenario for using the [DayPickerRangeController](https://github.com/airbnb/react-dates#daypickerrangecontroller) instead and implementing the input yourself.

**Comment by majapw** [comment]
I am kind of with @erin-doyle on this one. This is similar to what happens on airbnb.com/s/ right now and in that case, we use a single button instead of two inputs and pair that with the `DayPickerRangeController`, esp since this formatting doesn't seem very keyboard editable.

**Comment by nikoootine** [comment]
Thanks for the thoughts. I will try just implementing the input myself. Appreciate the feedbacks

**Comment by erin-doyle** [comment]
I'm going to go ahead and close this then.  Thanks @nikoootine for the question!

**Comment by rodolph66** [comment]
I know this is closed, but I have one simple query and relates to this post...
The DateRangePicker displays the initial startDate and endDate in the format MM/DD/YYYY, however, were I come from the standard recognized date format is DD/MM/YYYY, which is just a matter of exchanging the month and day location. is there a why to do that?
The locale on my device is set to such format, but using moment.locale() seems to have no effect on these properties in particular.

**Comment by miodragdz** [comment]
Hello,

Does this above worked? My component is:
<DateRangePicker
              startDate={this.props.filters.startDate}
              endDate={this.props.filters.endDate}
              onDatesChange={this.onDatesChange}
              focusedInput={this.state.calendarFocused}
              onFocusChange={this.onFocusChange}
              showClearDates={true}
              numberOfMonths={1}
              isOutsideRange={() => false}
 /> 
and I am not sure how to implement this.
Thanks in advance and BR.

**Comment by huvber** [comment]
Hello I also see that the `displayFormat` can accept a function so I thought would be a way to have a custom formatter but I saw the code and in the end it has to return a moment format. I actually not understanding the purpose of having a function if we can already send the format as a string. Wouldn't be better to use this function to replace the format of moment?
