### ISSUE TITLE
[a11y] Tabbing away from date picker results in keyboard trap in Safari, Edge/IE

### ISSUE THREAD

**Issue by backwardok** [airbnb/react-dates#937]
For both the [DateRangePicker](http://airbnb.io/react-dates/?selectedKind=DateRangePicker%20%28DRP%29&selectedStory=default&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel) and the [SingleDatePicker](http://airbnb.io/react-dates/?selectedKind=SingleDatePicker%20%28SDP%29&selectedStory=default&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel), if you tab to the date picker and then try to tab to the next thing after it, tab focus is reset to the top of the page and you're stuck in a keyboard trap.

Steps to reproduce:
1. Open one of the examples ([DateRangePicker](http://airbnb.io/react-dates/?selectedKind=DateRangePicker%20%28DRP%29&selectedStory=default&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel) or [SingleDatePicker](http://airbnb.io/react-dates/?selectedKind=SingleDatePicker%20%28SDP%29&selectedStory=default&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel)) using Safari or Edge
2. Tab to the date picker (note you'll go past the README link and the wrapper source link)
3. Tab out of the date picker

What's expected:
Next tab goes to Show Info button

What happens:
Next tab goes back to README link

Note that this works fine in Chrome, FF

Tested on Safari, Edge, IE11, Chrome (in Windows and Mac), FF (in Windows and Mac), Opera (in Windows)

**Comment by rokborf** [comment]
FYI

This bug is caused by different browsers approaches to managing blur DOM method:

* Edge, Safari and IE after blur() reset tab order to start
* Chrome and Firefox - keep tab order, just unfocus an element

Demo: https://jsfiddle.net/Lebcjfeb/

Here blur method is used: https://github.com/airbnb/react-dates/blob/7dfe618bb5a6b6947799686114a00e70fe42a779/src/components/DateInput.jsx#L114

**Comment by backwardok** [comment]
This issue was fixed a while back
