### ISSUE TITLE
Visually hidden previous/next months get read by screen readers

### ISSUE THREAD

**Issue by backwardok** [airbnb/react-dates#939]
Steps to repro:
1. Open a date picker in Storybook (ex. http://airbnb.io/react-dates/?selectedKind=SingleDatePicker%20%28SDP%29&selectedStory=default&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel)
2. Turn on VoiceOver (or your screen reader of choice)
3. Navigate to the date picker input
4. Use arrow navigation (ctrl + opt + arrow in VoiceOver) to move to calendar and access dates

What's expected:
First date reached is the first date that is visible

What happens:
First date reached is the first date of the month before the visible month (so if this month is January, and that's the visible month, it goes to December).

Similarly, if you're on the last visible date, navigating beyond takes you to the next month (that's supposed to be invisible).

This could probably be solved by just setting `visibility:hidden` on the hidden months and then removing that styling when they're going to move over. Alternatively, you could use `aria-hidden` on the dates, but it's preferred to not use ARIA unless you have to.

**Comment by majapw** [comment]
> This could probably be solved by just setting visibility:hidden on the hidden months and then removing that styling when they're going to move over. Alternatively, you could use aria-hidden on the dates, but it's preferred to not use ARIA unless you have to.

@backwardok can you explain why the discrepancy between the focused date and what's read is happening? I'm concerned that even if we apply `visibility: hidden` to the invisible months there will still be a problem in the following scenario:
![screen shot 2018-01-03 at 2 07 40 pm](https://user-images.githubusercontent.com/1383861/34542007-7975994a-f08f-11e7-8861-5f5af806f642.png)

where react-dates focused on the first available day if it exists. let me test that real quick.

**Comment by majapw** [comment]
Okay, never mind, that does seem to work. Is it strange that our focus handling and the voiceover focus handling get out of sync?

**Comment by backwardok** [comment]
If someone is navigating by traditional keyboard methods (tabbing around), then the focus would be on the "appropriate" date, though you'd still run into the situation where going to hidden dates would be possible. If you're navigating by screen reader browsing methods (going from node to node), then focus would end up on the inappropriate date. 

VO "focus" doesn't always match up to browser focus if the element you're on isn't something that can be focused by the browser (like a text node). What's perhaps somewhat interesting is that a keyboard user can trigger loading the previous month by using the arrow keys, but a screen reader user can't (arrow keys events don't get triggered in the browser because the screen reader uses arrow keys for its own navigation).

**Comment by erin-doyle** [comment]
I'm curious what browser you're using in combination with VoiceOver.  I did run into some issues with the VoiceOver focus not aligning with the browser focus when using in Chrome recently but found that Safari's focus was lining up with VoiceOver just fine.  It's my understanding that the usage numbers of VoiceOver with Chrome is pretty low compared with Safari (and maybe because it is flukey and unreliable for those that really depend on things working properly).  But if there is a way we can code these things to work consistently across all browsers and screen reader combos then let's definitely try to figure that out!

**Comment by backwardok** [comment]
I've been testing with Safari - the only times when focus won't match up is if you're VO focused on something that isn't focusable (like text). Doesn't seem to impact using the calendar in any meaningful way though (aka I didn't notice any issues with focus being somewhere I didn't expect it to be)

**Comment by erin-doyle** [comment]
Ah ok, I bet I've missed this because I admittedly have not been testing using the VoiceOver commands but mostly tabbing along with the keyboard shortcuts. :woman_facepalming:
