### ISSUE TITLE
SingleDatePicker Doesnt accept onDayMouseEnter param

### ISSUE THREAD

**Issue by smoakey** [airbnb/react-dates#94]
The SingleDatePicker component doesnt accept onDayMouseEnter param to pass along to the DayPicker component it creates.

```
onDayMouseEnter(day, modifiers, e) {
    this.setState({
      hoverDate: day,
    });
    this.props.onDayMouseEnter(day, modifiers, e);
}
```

instead of the current:

```
onDayMouseEnter(day) {
    this.setState({
      hoverDate: day,
    });
}
```

**Comment by ljharb** [comment]
What use case would you hope to achieve with such a prop?

**Comment by smoakey** [comment]
I need to be able to style specific dates differently. I also need to display a tooltip when hovering over those specific dates to display a user a message specific to those dates.

I was able to accomplish this by allowing modifiers to be passed into the SingleDatePicker as well as onDayMouseEnter and onDayMouseLeave callbacks.

I am mostly just curious why the SingleDayPicker and DateRangePicker don't just allow all props of DayPicker to be passed through since both create an instance of DayPicker internally. Is there a reason you chose not to do that?

**Comment by kane-thornwyrd** [comment]
Is there any update on this topic ?

**Comment by ljharb** [comment]
There are 15 open PRs; that's nowhere close to being a big queue.

A PR would certainly help continue the discussion.

As for why the DayPicker props aren't all allowed, perhaps @majapw can weigh in.

**Comment by smoakey** [comment]
@majapw What was the reasoning for not exposing those props?

**Comment by majapw** [comment]
@smoakey the goal of the callbacks as described in https://github.com/airbnb/react-dates/issues/94#issuecomment-249207698 is already supported by using the `renderDay` prop for custom behavior (like adding a tooltip or having something else happen on mouse interactions). I think exposing the specific day props ends up being messier than just encouraging consumers to use `renderDay` (especially since it now passes back the list of modifiers applied to that day).

**Comment by majapw** [comment]
If you want direct access to those callbacks, I kind expect it's because you want a different set-up for selection (like picking weeks at a time or something) and in that case, you probs just wanna use the DayPicker directly and set up your own wrappers.

**Comment by smoakey** [comment]
@majapw Ah thanks for the explanation! It also looks like a lot has changed since I submitted this on v3.0.0 :)

**Comment by majapw** [comment]
🙃 definitely! I appreciate you opening the issue though originally! I think it def motivated the creation of that prop.
