### ISSUE TITLE
SingleDatePicker now showing a weird top margin even withPortal is true

### ISSUE THREAD

**Issue by senseluo** [airbnb/react-dates#947]
Here is what it looks like now (Pretty sure it should be fine several weeks ago):

![snip20180109_2](https://user-images.githubusercontent.com/128367/34702262-c23a247e-f527-11e7-8f4a-c1f1d27a061b.png)

I noticed in source file[ src/components/SingleDatePicker.jsx](https://github.com/airbnb/react-dates/blob/master/src/components/SingleDatePicker.jsx)

```javascript
    const inputHeight = getInputHeight(reactDates, small);

    return (
      <div // eslint-disable-line jsx-a11y/no-static-element-interactions
        ref={this.setDayPickerContainerRef}
        {...css(
          styles.SingleDatePicker_picker,
          anchorDirection === ANCHOR_LEFT && styles.SingleDatePicker_picker__directionLeft,
          anchorDirection === ANCHOR_RIGHT && styles.SingleDatePicker_picker__directionRight,
          openDirection === OPEN_DOWN && styles.SingleDatePicker_picker__openDown,
          openDirection === OPEN_UP && styles.SingleDatePicker_picker__openUp,
          openDirection === OPEN_DOWN && {
            top: inputHeight + verticalSpacing,
          },
          openDirection === OPEN_UP && {
            bottom: inputHeight + verticalSpacing,
          },
```

I tried to set verticalSpacing to 0, but still not working.

So I am guessing it was led by `getInputHeight` function since it should check `withPortal` prop since `withPortal` to true means showing up a fullscreen modal view.

I haven't pull request before so just posting here hope someone can make a fix.

Thanks a lot!

**Comment by raphaelbeckmann** [comment]
Same here! Super annoying bug.
I'm wondering if Airbnb is testing their code before commiting?

**Comment by majapw** [comment]
I think it's not terribly productive to snarkily accuse us of not testing our code. We work fairly hard at maintaining this repo and bugs like this can always slip through the cracks.

I am also somewhat confused because the portal examples in the storybook don't seem to have the same problem as your screenshot @senseluo . Can you share what props you're passing into the SDP and any other styles you're applying so we can add an appropriate example?

**Comment by imprashast** [comment]
Same here. Fixed it temporarily with a custom css:

`
.SingleDatePicker_picker__fullScreenPortal {
    background-color: #fff;
    top: 0px !important;
    z-index: 999;
  }
`

Hope it helps 😄

**Comment by raphaelbeckmann** [comment]
This is my fix:

```
.SingleDatePicker_picker__portal {
	top: 0 !important;
}
```
