### ISSUE TITLE
Error in module exports?

### ISSUE THREAD

**Issue by thj-dk** [airbnb/react-dates#95]
Looking at [index.js](https://github.com/airbnb/react-dates/blob/master/index.js); all the exports points to some lib folder. Looks like it should be the src folder, or am I missing something? Using the npm package here.

**Comment by majapw** [comment]
Hiyo! It points to the `lib` folder which is the built/babelified version of all of the datepicker components. This folder is git ignored, but is not npm ignored and therefore is included in the published `react-dates` npm package. :)

This is why you should be able to easily to `import { DateRangePicker } from 'react-dates';` once you npm install the package.

**Comment by thj-dk** [comment]
Oh, obviously. My mistake - I had moment 2.15 installed hence react-dates wasn't build on install.

**Comment by majapw** [comment]
Oh yeah! I think moment fixed their 2.15 issue so we can probs upgrade as
well and prevent this issue in the future. :)

**Comment by ljharb** [comment]
@majapw done in d11e4911612779e09637d5c67c60a24e87e9c6b4, just waiting on a release
