### ISSUE TITLE
DateRangePicker - Picker disappearing from the dom

### ISSUE THREAD

**Issue by davidvenin** [airbnb/react-dates#963]
Hi, 

I'm using DateRangePicker and according to the doc, I'm unable to find a way to avoid the calendar to disappear when inputs are not focused.
I tried to work with the onClose fn but not working.

I saw that the Calendar is removed from the dom, I don't want that...

Any idea or some props I didn't see ?

[Edit] For now, I forced the props/state `isDateRangePickerInputFocused` to `true` in the `component/DateRangePicker`.

**Comment by majapw** [comment]
@davidvenin Removing the picker from the DOM is intentional behavior (for performance reasons). If you want the picker to always be open, you could have your `onFocusChange` method look like:
```
(focusedInput) => {
  this.setState({ focusedInput: focusedInput || START_DATE });
}
```

Maybe if you gave more context on your usecase, it might make sense to make it a feature. :)
