### ISSUE TITLE
Is this support for react native ?

### ISSUE THREAD

**Issue by hrmshandy** [airbnb/react-dates#969]
Is this support for react native ? because I got this error
![screen shot 2018-01-23 at 14 24 42](https://user-images.githubusercontent.com/8230690/35262898-2e6ea472-0049-11e8-964f-3f5a126b22db.png)

and can you provide me some guide to implement on react native ?

Thanks.

**Comment by lavokad** [comment]
This is a `js` lib, it has to work without any issues in react native. Post some of your code, that throws that error.

**Comment by ljharb** [comment]
No, this is a React web component.
